// External snapshot, committed: which other systems expose a function of each head's name,
// asked of the kernels by scripts/collect-coverage.ts (wolframscript, SymPy, mpmath). A head
// absent here has none. scripts/collect-provenance.ts folds it into the built provenance data.
//
//   vp node packages/reference/scripts/collect-coverage.ts

export const coverage: Readonly<Record<string, readonly string[]>> = {
  AGM: ["mpmath"],
  Abs: ["wolfram", "sympy"],
  AbsoluteTiming: ["wolfram"],
  Abundance: ["sympy"],
  Accumulate: ["wolfram"],
  Add: ["sympy"],
  AdjacencyGraph: ["wolfram"],
  AdjacencyMatrix: ["wolfram"],
  AiryAi: ["wolfram", "sympy", "mpmath"],
  AiryAiPrime: ["wolfram", "sympy"],
  AiryBi: ["wolfram", "sympy", "mpmath"],
  AiryBiPrime: ["wolfram", "sympy"],
  All: ["wolfram"],
  AlternatingGroup: ["wolfram"],
  And: ["wolfram", "sympy"],
  Animator: ["wolfram"],
  AppellF1: ["wolfram", "sympy", "mpmath"],
  Append: ["wolfram"],
  AppendTo: ["wolfram"],
  Apply: ["wolfram"],
  Around: ["wolfram"],
  Array: ["wolfram", "sympy"],
  ArrayPlot: ["wolfram"],
  Arrow: ["wolfram"],
  Association: ["wolfram"],
  AssociationThread: ["wolfram"],
  Assuming: ["wolfram", "sympy"],
  Attributes: ["wolfram"],
  BarChart: ["wolfram"],
  BarChart3D: ["wolfram"],
  BarnesG: ["wolfram", "mpmath"],
  BellY: ["wolfram"],
  BernoulliB: ["wolfram"],
  BesselI: ["wolfram", "sympy", "mpmath"],
  BesselJ: ["wolfram", "sympy", "mpmath"],
  BesselJZero: ["wolfram", "mpmath"],
  BesselK: ["wolfram", "sympy", "mpmath"],
  BesselY: ["wolfram", "sympy", "mpmath"],
  Beta: ["wolfram", "sympy", "mpmath"],
  BetaRegularized: ["wolfram"],
  Binomial: ["wolfram", "sympy", "mpmath"],
  BinomialDistribution: ["wolfram"],
  BooleanConvert: ["wolfram"],
  Bottom: ["wolfram"],
  BoxWhiskerChart: ["wolfram"],
  C: ["wolfram"],
  CDF: ["wolfram"],
  CaputoD: ["wolfram"],
  CarlsonRC: ["wolfram"],
  CarlsonRD: ["wolfram"],
  CarlsonRF: ["wolfram"],
  CarlsonRG: ["wolfram"],
  CarlsonRJ: ["wolfram"],
  CarmichaelLambda: ["wolfram"],
  Cases: ["wolfram"],
  CatalanNumber: ["wolfram"],
  Catch: ["wolfram"],
  Ceil: ["mpmath"],
  Cell: ["wolfram"],
  CellularAutomaton: ["wolfram"],
  CenteredInterval: ["wolfram"],
  CharacterRange: ["wolfram"],
  ChebyshevT: ["wolfram", "sympy"],
  ChebyshevU: ["wolfram", "sympy"],
  Checkbox: ["wolfram"],
  ChineseRemainder: ["wolfram"],
  Chop: ["wolfram", "mpmath"],
  Circle: ["wolfram", "sympy"],
  CircleTimes: ["wolfram"],
  CirculantGraph: ["wolfram"],
  CliffordAlgebra: ["wolfram"],
  ClosenessCentrality: ["wolfram"],
  ColorSlider: ["wolfram"],
  Column: ["wolfram"],
  Commonest: ["wolfram"],
  CompleteGraph: ["wolfram"],
  CompleteKaryTree: ["wolfram"],
  Complex: ["wolfram"],
  ComplexExpand: ["wolfram"],
  ComplexPlot: ["wolfram"],
  ComplexPlot3D: ["wolfram"],
  Compose: ["wolfram", "sympy"],
  Conjugate: ["wolfram", "sympy"],
  ConnectedComponents: ["wolfram"],
  Contains: ["sympy"],
  Content: ["sympy"],
  ContinuedFraction: ["wolfram", "sympy"],
  ContinuedFractionK: ["wolfram"],
  ContourPlot: ["wolfram"],
  Convergents: ["wolfram"],
  Coproduct: ["wolfram"],
  Cos: ["wolfram", "sympy", "mpmath"],
  Cosh: ["wolfram", "sympy", "mpmath"],
  Cot: ["wolfram", "sympy", "mpmath"],
  Coth: ["wolfram", "sympy", "mpmath"],
  Count: ["wolfram"],
  Covariance: ["wolfram"],
  Csc: ["wolfram", "sympy", "mpmath"],
  Csch: ["wolfram", "sympy", "mpmath"],
  CubeRoot: ["wolfram"],
  CycleGraph: ["wolfram"],
  Cycles: ["wolfram"],
  CyclicGroup: ["wolfram"],
  D: ["wolfram"],
  DSolveValue: ["wolfram"],
  DedekindEta: ["wolfram"],
  DeleteCases: ["wolfram"],
  Dendrogram: ["wolfram"],
  Denominator: ["wolfram"],
  DensityPlot: ["wolfram"],
  Derivative: ["wolfram", "sympy"],
  Determinant: ["sympy"],
  DiagonalMatrix: ["wolfram", "sympy"],
  DifferenceDelta: ["wolfram", "sympy"],
  DifferenceRoot: ["wolfram"],
  DifferenceRootReduce: ["wolfram"],
  DifferentialRoot: ["wolfram"],
  DifferentialRootReduce: ["wolfram"],
  Digamma: ["sympy", "mpmath"],
  DigitCount: ["wolfram"],
  DigitSum: ["wolfram"],
  DihedralGroup: ["wolfram"],
  DiracDelta: ["wolfram", "sympy"],
  DirectedEdge: ["wolfram"],
  DirichletBeta: ["wolfram"],
  DirichletCharacter: ["wolfram"],
  DirichletEta: ["wolfram", "sympy"],
  DirichletL: ["wolfram"],
  DiscreteDelta: ["wolfram"],
  DiscretePlot: ["wolfram"],
  DiscreteRatio: ["wolfram"],
  DiscreteShift: ["wolfram"],
  Disk: ["wolfram"],
  DisplayForm: ["wolfram"],
  Divide: ["wolfram"],
  DivisorCount: ["sympy"],
  DivisorSigma: ["wolfram", "sympy"],
  DivisorSum: ["wolfram"],
  Divisors: ["wolfram", "sympy"],
  Do: ["wolfram"],
  Dot: ["wolfram"],
  Drop: ["wolfram"],
  Dynamic: ["wolfram"],
  DynamicModule: ["wolfram"],
  Echo: ["wolfram"],
  EdgeCount: ["wolfram"],
  EdgeList: ["wolfram"],
  EgyptianFraction: ["sympy"],
  EigenvectorCentrality: ["wolfram"],
  Element: ["wolfram"],
  EllipticE: ["wolfram", "sympy"],
  EllipticF: ["wolfram", "sympy"],
  EllipticK: ["wolfram", "sympy"],
  EllipticPi: ["wolfram", "sympy"],
  EllipticTheta: ["wolfram"],
  EllipticThetaPrime: ["wolfram"],
  Equal: ["wolfram"],
  Erf: ["wolfram", "sympy", "mpmath"],
  ErfInv: ["sympy", "mpmath"],
  Erfc: ["wolfram", "sympy", "mpmath"],
  ErrorBox: ["wolfram"],
  EulerE: ["wolfram"],
  EulerGamma: ["wolfram"],
  Exp: ["wolfram", "sympy", "mpmath"],
  ExpIntegralE: ["wolfram"],
  ExpIntegralEi: ["wolfram"],
  ExpToTrig: ["wolfram"],
  Expand: ["wolfram", "sympy"],
  ExponentialGeneratingFunction: ["wolfram"],
  ExtendedGCD: ["wolfram"],
  Extract: ["wolfram"],
  FactorInteger: ["wolfram"],
  Factorial: ["wolfram", "sympy", "mpmath"],
  Factorial2: ["wolfram", "sympy"],
  FactorialPower: ["wolfram"],
  FallingFactorial: ["sympy"],
  FareySequence: ["wolfram"],
  Fibonacci: ["wolfram", "sympy", "mpmath"],
  FindInstance: ["wolfram"],
  FindSequenceFunction: ["wolfram"],
  FindShortestPath: ["wolfram"],
  First: ["wolfram"],
  FirstPosition: ["wolfram"],
  FixedPoint: ["wolfram"],
  FixedPointList: ["wolfram"],
  Flatten: ["wolfram", "sympy"],
  Floor: ["wolfram", "sympy", "mpmath"],
  Fold: ["wolfram"],
  FoldList: ["wolfram"],
  Fourier: ["wolfram", "mpmath"],
  FourierCoefficient: ["wolfram"],
  FourierSeries: ["wolfram", "sympy"],
  FourierTransform: ["wolfram", "sympy"],
  FractionBox: ["wolfram"],
  FractionalPart: ["wolfram"],
  FrameBox: ["wolfram"],
  FreeQ: ["wolfram"],
  FrobeniusNumber: ["wolfram"],
  FrobeniusSolve: ["wolfram"],
  FromCharacterCode: ["wolfram"],
  FromContinuedFraction: ["wolfram"],
  FromDigits: ["wolfram"],
  FullSimplify: ["wolfram"],
  Function: ["wolfram", "sympy"],
  FunctionAnalytic: ["wolfram"],
  FunctionContinuous: ["wolfram"],
  FunctionConvexity: ["wolfram"],
  FunctionDiscontinuities: ["wolfram"],
  FunctionDomain: ["wolfram"],
  FunctionExpand: ["wolfram"],
  FunctionInjective: ["wolfram"],
  FunctionMeromorphic: ["wolfram"],
  FunctionMonotonicity: ["wolfram"],
  FunctionPeriod: ["wolfram"],
  FunctionRange: ["wolfram"],
  FunctionSign: ["wolfram"],
  FunctionSingularities: ["wolfram"],
  FunctionSurjective: ["wolfram"],
  GCD: ["wolfram", "sympy"],
  Gamma: ["wolfram", "sympy", "mpmath"],
  GammaRegularized: ["wolfram"],
  Gather: ["wolfram"],
  GatherBy: ["wolfram"],
  GaussianIntegers: ["wolfram"],
  GeneratingFunction: ["wolfram"],
  GeometricMean: ["wolfram"],
  GoldenRatio: ["wolfram"],
  Graph: ["wolfram"],
  GraphCenter: ["wolfram"],
  GraphDiameter: ["wolfram"],
  GraphDistance: ["wolfram"],
  GraphDistanceMatrix: ["wolfram"],
  GraphPeriphery: ["wolfram"],
  GraphPlot: ["wolfram"],
  GraphRadius: ["wolfram"],
  GrassmannAlgebra: ["wolfram"],
  Greater: ["wolfram"],
  GreaterEqual: ["wolfram"],
  Grid: ["wolfram"],
  GridBox: ["wolfram"],
  GridGraph: ["wolfram"],
  GroupElements: ["wolfram"],
  GroupGenerators: ["wolfram"],
  GroupOrder: ["wolfram"],
  Gudermannian: ["wolfram"],
  HankelMatrix: ["wolfram"],
  HankelTransform: ["wolfram", "sympy"],
  HararyGraph: ["wolfram"],
  HarmonicMean: ["wolfram"],
  HarmonicNumber: ["wolfram"],
  HeavisideLambda: ["wolfram"],
  HeavisidePi: ["wolfram"],
  HeavisideTheta: ["wolfram"],
  HermiteDecomposition: ["wolfram"],
  HilbertMatrix: ["wolfram"],
  Histogram: ["wolfram"],
  HurwitzZeta: ["wolfram"],
  HypercubeGraph: ["wolfram"],
  Hyperfactorial: ["wolfram"],
  Hypergeometric0F1: ["wolfram"],
  Hypergeometric0F1Regularized: ["wolfram"],
  Hypergeometric1F1: ["wolfram"],
  Hypergeometric1F1Regularized: ["wolfram"],
  Hypergeometric2F1: ["wolfram"],
  Hypergeometric2F1Regularized: ["wolfram"],
  HypergeometricPFQ: ["wolfram"],
  HypergeometricU: ["wolfram"],
  Image: ["wolfram"],
  ImageSize: ["wolfram"],
  IncidenceMatrix: ["wolfram"],
  Inequality: ["wolfram"],
  InputField: ["wolfram"],
  IntegerDigits: ["wolfram"],
  IntegerExponent: ["wolfram"],
  IntegerLength: ["wolfram"],
  IntegerPart: ["wolfram"],
  IntegerPartitions: ["wolfram"],
  IntegerReverse: ["wolfram"],
  IntegerString: ["wolfram"],
  Integrate: ["wolfram", "sympy"],
  InterpretationBox: ["wolfram"],
  Intersection: ["wolfram", "sympy"],
  Interval: ["wolfram", "sympy"],
  IntervalSlider: ["wolfram"],
  InverseBetaRegularized: ["wolfram"],
  InverseErfc: ["wolfram"],
  InverseFourier: ["wolfram"],
  InverseFourierTransform: ["wolfram", "sympy"],
  InverseGammaRegularized: ["wolfram"],
  InverseLaplaceTransform: ["wolfram", "sympy"],
  InverseMellinTransform: ["wolfram", "sympy"],
  InversePermutation: ["wolfram"],
  IsPerfect: ["sympy"],
  IsPrime: ["sympy"],
  JacobiAmplitude: ["wolfram"],
  JacobiCD: ["wolfram"],
  JacobiCN: ["wolfram"],
  JacobiCS: ["wolfram"],
  JacobiDC: ["wolfram"],
  JacobiDN: ["wolfram"],
  JacobiDS: ["wolfram"],
  JacobiNC: ["wolfram"],
  JacobiND: ["wolfram"],
  JacobiNS: ["wolfram"],
  JacobiSC: ["wolfram"],
  JacobiSD: ["wolfram"],
  JacobiSN: ["wolfram"],
  JacobiSymbol: ["wolfram", "sympy"],
  JacobiZN: ["wolfram"],
  Join: ["wolfram"],
  KaryTree: ["wolfram"],
  Key: ["wolfram"],
  Khinchin: ["wolfram", "mpmath"],
  KleinInvariantJ: ["wolfram"],
  KroneckerSymbol: ["wolfram", "sympy"],
  LCM: ["wolfram", "sympy"],
  Labeled: ["wolfram"],
  LambertW: ["wolfram", "sympy", "mpmath"],
  LaplaceTransform: ["wolfram", "sympy"],
  Last: ["wolfram"],
  LayeredGraphPlot: ["wolfram"],
  LegendreSymbol: ["sympy"],
  Length: ["wolfram"],
  LerchPhi: ["wolfram", "sympy", "mpmath"],
  Less: ["wolfram"],
  LessEqual: ["wolfram"],
  LetterNumber: ["wolfram"],
  Level: ["wolfram"],
  Line: ["wolfram", "sympy"],
  LineGraph: ["wolfram"],
  LinearRecurrence: ["wolfram"],
  LiouvilleLambda: ["wolfram"],
  List: ["wolfram"],
  ListLinePlot: ["wolfram"],
  ListPicker: ["wolfram"],
  ListPlot: ["wolfram"],
  ListPlot3D: ["wolfram"],
  Ln: ["sympy", "mpmath"],
  Locator: ["wolfram"],
  Log: ["wolfram", "sympy", "mpmath"],
  Log10: ["wolfram", "mpmath"],
  Log2: ["wolfram"],
  LogBarnesG: ["wolfram"],
  LogGamma: ["wolfram", "sympy", "mpmath"],
  LogIntegral: ["wolfram"],
  LogicalExpand: ["wolfram"],
  LucasL: ["wolfram"],
  MakeBoxes: ["wolfram"],
  MangoldtLambda: ["wolfram"],
  Manipulate: ["wolfram"],
  MapAt: ["wolfram"],
  MapIndexed: ["wolfram"],
  MapThread: ["wolfram"],
  MatchQ: ["wolfram"],
  MatrixExp: ["wolfram"],
  MatrixFunction: ["wolfram"],
  MatrixPower: ["wolfram"],
  MatrixRank: ["wolfram"],
  Max: ["wolfram", "sympy"],
  MaxValue: ["wolfram"],
  Maximize: ["wolfram"],
  Mean: ["wolfram"],
  Median: ["wolfram"],
  MeijerG: ["wolfram", "sympy", "mpmath"],
  MeijerGReduce: ["wolfram"],
  MellinTransform: ["wolfram", "sympy"],
  MemoryConstrained: ["wolfram"],
  MersennePrimeExponent: ["wolfram", "sympy"],
  Midpoint: ["wolfram"],
  Min: ["wolfram", "sympy"],
  MinValue: ["wolfram"],
  Minimize: ["wolfram"],
  MixedRadix: ["wolfram"],
  Mod: ["wolfram", "sympy"],
  Mode: ["wolfram"],
  ModularInverse: ["wolfram"],
  ModularLambda: ["wolfram"],
  Module: ["wolfram"],
  MoebiusMu: ["wolfram"],
  Most: ["wolfram"],
  MovingMap: ["wolfram"],
  Multinomial: ["wolfram"],
  MultiplicativeOrder: ["wolfram"],
  N: ["wolfram", "sympy"],
  NMaximize: ["wolfram"],
  NMinimize: ["wolfram"],
  NSum: ["wolfram", "mpmath"],
  Nand: ["wolfram", "sympy"],
  NeighborhoodGraph: ["wolfram"],
  Nest: ["wolfram"],
  NestList: ["wolfram"],
  NestWhile: ["wolfram"],
  NestWhileList: ["wolfram"],
  NextPrime: ["wolfram", "sympy"],
  NonCommutativeMultiply: ["wolfram"],
  NoneTrue: ["wolfram"],
  Nor: ["wolfram", "sympy"],
  NorlundB: ["wolfram"],
  Norm: ["wolfram", "mpmath"],
  NormalDistribution: ["wolfram"],
  Normalize: ["wolfram"],
  Not: ["wolfram", "sympy"],
  Notebook: ["wolfram"],
  NumberExpand: ["wolfram"],
  NumberQ: ["wolfram"],
  Numerator: ["wolfram"],
  Ones: ["sympy", "mpmath"],
  Or: ["wolfram", "sympy"],
  Ordering: ["wolfram"],
  Outer: ["wolfram"],
  OverBar: ["wolfram"],
  OverscriptBox: ["wolfram"],
  PDF: ["wolfram"],
  PadLeft: ["wolfram"],
  PadRight: ["wolfram"],
  Panel: ["wolfram"],
  Partition: ["wolfram", "sympy"],
  PartitionsQ: ["wolfram"],
  PascalBinomial: ["wolfram"],
  PathGraph: ["wolfram"],
  PerfectNumber: ["wolfram"],
  PermutationCycles: ["wolfram"],
  PermutationGroup: ["wolfram"],
  PermutationList: ["wolfram"],
  PermutationReplace: ["wolfram"],
  Permutations: ["wolfram"],
  Permute: ["wolfram"],
  PetersenGraph: ["wolfram"],
  Pi: ["wolfram", "mpmath"],
  Pick: ["wolfram"],
  PieChart: ["wolfram"],
  Piecewise: ["wolfram", "sympy"],
  PiecewiseExpand: ["wolfram"],
  Plot: ["wolfram", "sympy", "mpmath"],
  Plot3D: ["wolfram"],
  PlusMinus: ["wolfram"],
  Pochhammer: ["wolfram"],
  Point: ["wolfram", "sympy"],
  PoissonDistribution: ["wolfram"],
  PolarPlot: ["wolfram"],
  PolyGamma: ["wolfram", "sympy", "mpmath"],
  PolyLog: ["wolfram", "sympy", "mpmath"],
  PopupMenu: ["wolfram"],
  Position: ["wolfram"],
  Power: ["wolfram", "mpmath"],
  PowerExpand: ["wolfram"],
  PowerMod: ["wolfram"],
  PowerModList: ["wolfram"],
  PowerSet: ["sympy"],
  PowersRepresentations: ["wolfram"],
  Precision: ["wolfram"],
  Prepend: ["wolfram"],
  Prime: ["wolfram", "sympy"],
  PrimeNu: ["wolfram", "sympy"],
  PrimeOmega: ["wolfram", "sympy"],
  PrimePi: ["wolfram", "sympy", "mpmath"],
  PrimeZetaP: ["wolfram"],
  Primes: ["wolfram"],
  PrimitiveRootList: ["wolfram"],
  Product: ["wolfram", "sympy"],
  QBinomial: ["wolfram"],
  QFactorial: ["wolfram"],
  QPochhammer: ["wolfram"],
  Quotient: ["wolfram"],
  RadicalBox: ["wolfram"],
  RadioButtonBar: ["wolfram"],
  RamanujanTau: ["wolfram"],
  Ramp: ["wolfram"],
  Random: ["wolfram"],
  RandomComplex: ["wolfram"],
  RandomGraph: ["wolfram"],
  RandomInteger: ["wolfram"],
  Range: ["wolfram", "sympy"],
  Rasterize: ["wolfram"],
  Rational: ["wolfram", "sympy"],
  Rationalize: ["wolfram"],
  RawBoxes: ["wolfram"],
  ReIm: ["wolfram"],
  Real: ["wolfram"],
  RealAbs: ["wolfram"],
  RealDigits: ["wolfram"],
  RealSign: ["wolfram"],
  Reap: ["wolfram"],
  Rectangle: ["wolfram"],
  RecurrenceTable: ["wolfram"],
  Refine: ["wolfram", "sympy"],
  Replace: ["wolfram"],
  ReplacePart: ["wolfram"],
  Rescale: ["wolfram"],
  Rest: ["wolfram"],
  RiemannSiegelTheta: ["wolfram"],
  RiemannSiegelZ: ["wolfram"],
  Riffle: ["wolfram"],
  RisingFactorial: ["sympy"],
  RomanNumeral: ["wolfram"],
  Root: ["wolfram", "sympy", "mpmath"],
  Round: ["wolfram"],
  Row: ["wolfram"],
  RowBox: ["wolfram"],
  Rule: ["wolfram"],
  SawtoothWave: ["wolfram"],
  Scan: ["wolfram"],
  Sec: ["wolfram", "sympy", "mpmath"],
  Sech: ["wolfram", "sympy", "mpmath"],
  SeedRandom: ["wolfram"],
  SeriesCoefficient: ["wolfram"],
  SetAttributes: ["wolfram"],
  SetterBar: ["wolfram"],
  Shape: ["sympy"],
  Sign: ["wolfram", "sympy", "mpmath"],
  Simplex: ["wolfram"],
  Simplify: ["wolfram", "sympy"],
  Sin: ["wolfram", "sympy", "mpmath"],
  Sinh: ["wolfram", "sympy", "mpmath"],
  Slider: ["wolfram"],
  Slider2D: ["wolfram"],
  Sort: ["wolfram"],
  SortBy: ["wolfram"],
  Sow: ["wolfram"],
  Span: ["wolfram"],
  SparseArray: ["wolfram"],
  Split: ["wolfram"],
  SplitBy: ["wolfram"],
  Sqrt: ["wolfram", "sympy", "mpmath"],
  SqrtBox: ["wolfram"],
  Square: ["wolfram"],
  SquareWave: ["wolfram"],
  SquaresR: ["wolfram"],
  StandardDeviation: ["wolfram"],
  StarGraph: ["wolfram"],
  StieltjesGamma: ["wolfram"],
  StirlingS1: ["wolfram"],
  StreamPlot: ["wolfram"],
  StringLength: ["wolfram"],
  StringTake: ["wolfram"],
  StyleBox: ["wolfram"],
  Subfactorial: ["wolfram", "sympy"],
  Subgraph: ["wolfram"],
  SubscriptBox: ["wolfram"],
  Subsets: ["wolfram", "sympy"],
  SubsuperscriptBox: ["wolfram"],
  Subtract: ["wolfram"],
  Sum: ["wolfram", "sympy"],
  SuperscriptBox: ["wolfram"],
  Surd: ["wolfram"],
  Switch: ["wolfram"],
  SymmetricGroup: ["wolfram"],
  TagBox: ["wolfram"],
  Take: ["wolfram", "sympy"],
  Tan: ["wolfram", "sympy", "mpmath"],
  Tanh: ["wolfram", "sympy", "mpmath"],
  TestResultObject: ["wolfram"],
  Text: ["wolfram"],
  TextBox: ["wolfram"],
  Thread: ["wolfram"],
  Through: ["wolfram"],
  Throw: ["wolfram"],
  TimeConstrained: ["wolfram"],
  ToBoxes: ["wolfram"],
  ToCharacterCode: ["wolfram"],
  ToString: ["wolfram"],
  Toggler: ["wolfram"],
  TogglerBar: ["wolfram"],
  Totient: ["sympy"],
  Trace: ["wolfram", "sympy"],
  Transpose: ["wolfram", "sympy"],
  TreeGraph: ["wolfram"],
  TriangleWave: ["wolfram"],
  TrigFactor: ["wolfram"],
  TrigToExp: ["wolfram"],
  Trigamma: ["sympy"],
  Tuple: ["sympy"],
  Tuples: ["wolfram"],
  TuranGraph: ["wolfram"],
  UnderoverscriptBox: ["wolfram"],
  UnderscriptBox: ["wolfram"],
  UndirectedEdge: ["wolfram"],
  UniformDistribution: ["wolfram"],
  Union: ["wolfram", "sympy"],
  Unique: ["wolfram"],
  UnitBox: ["wolfram"],
  UnitStep: ["wolfram"],
  UnitTriangle: ["wolfram", "mpmath"],
  UpTo: ["wolfram"],
  Variance: ["wolfram"],
  VectorPlot: ["wolfram"],
  Vee: ["wolfram"],
  VerificationTest: ["wolfram"],
  VertexCount: ["wolfram"],
  VertexDegree: ["wolfram"],
  VertexEccentricity: ["wolfram"],
  VertexInDegree: ["wolfram"],
  VertexIndex: ["wolfram"],
  VertexList: ["wolfram"],
  VertexOutDegree: ["wolfram"],
  VerticalSlider: ["wolfram"],
  WeightedAdjacencyMatrix: ["wolfram"],
  WheelGraph: ["wolfram"],
  While: ["wolfram"],
  With: ["wolfram"],
  Word: ["wolfram"],
  Zeros: ["sympy", "mpmath"],
  Zeta: ["wolfram", "sympy", "mpmath"],
};
