// GENERATED by scripts/fetch-dlmf.ts — do not edit by hand.
//
// Every notation in the DLMF's index (dlmf.nist.gov/not/), with the function it names and
// where the handbook defines it. Regenerate with:
//
//   vp node packages/reference/scripts/fetch-dlmf.ts

/** One notation: the handbook's name for it, its LaTeX, and the defining location. */
export interface DlmfNotation {
  readonly name: string;
  /** The notation as the DLMF writes it, with \NVar{…} marking the variables. */
  readonly notation: string;
  /** Section and anchor, as the site addresses it: `5.2#E1`, `24.2#i`. */
  readonly ref: string;
}

export const dlmf: readonly DlmfNotation[] = [
  {
    name: "for every",
    notation: "\\forall",
    ref: "front/introduction#common.t1.r12",
  },
  {
    name: "Glaisher’s constant",
    notation: "A",
    ref: "5.17#E6",
  },
  {
    name: "kth zero of Airy Ai",
    notation: "a_{\\NVar{k}}",
    ref: "9.2#i",
  },
  {
    name: "kth zero of Airy Ai′",
    notation: "a^{\\prime}_{\\NVar{k}}",
    ref: "9.2#i",
  },
  {
    name: "q-Euler number",
    notation: "A_{\\NVar{m},\\NVar{s}}\\left(\\NVar{q}\\right)",
    ref: "17.3#E8",
  },
  {
    name: "q-Stirling number",
    notation: "a_{\\NVar{m},\\NVar{s}}\\left(\\NVar{q}\\right)",
    ref: "17.3#E9",
  },
  {
    name: "eigenvalues of Mathieu equation",
    notation: "a_{\\NVar{n}}\\left(\\NVar{q}\\right)",
    ref: "28.2#v.p1",
  },
  {
    name: "generalized Airy function",
    notation: "A_{\\NVar{n}}\\left(\\NVar{z}\\right)",
    ref: "9.13#i.p2",
  },
  {
    name: "Bessel function of matrix argument (first kind)",
    notation: "A_{\\NVar{\\nu}}\\left(\\NVar{\\mathbf{T}}\\right)",
    ref: "35.5#i",
  },
  {
    name: "Anger–Weber function",
    notation: "\\mathbf{A}_{\\NVar{\\nu}}\\left(\\NVar{z}\\right)",
    ref: "11.10#E4",
  },
  {
    name: "eigenvalues of Lamé’s equation",
    notation: "a^{\\NVar{n}}_{\\NVar{\\nu}}\\left(\\NVar{k^{2}}\\right)",
    ref: "29.3#i.p1",
  },
  {
    name: "generalized Airy function",
    notation: "A_{\\NVar{k}}\\left(\\NVar{z},\\NVar{p}\\right)",
    ref: "9.13#ii.p1",
  },
  {
    name: "Airy function",
    notation: "\\operatorname{Ai}\\left(\\NVar{z}\\right)",
    ref: "9.2#i",
  },
  {
    name: "fine structure constant",
    notation: "\\alpha",
    ref: "18.39#Px10",
  },
  {
    name: "Jacobi’s amplitude function",
    notation: "\\operatorname{am}\\left(\\NVar{x},\\NVar{k}\\right)",
    ref: "22.16#E1",
  },
  {
    name: "inverse Jacobian elliptic function",
    notation: "\\operatorname{arccd}\\left(\\NVar{x},\\NVar{k}\\right)",
    ref: "22.15#i.p1",
  },
  {
    name: "inverse Jacobian elliptic function",
    notation: "\\operatorname{arccn}\\left(\\NVar{x},\\NVar{k}\\right)",
    ref: "22.15#i.p1",
  },
  {
    name: "general arccosine function",
    notation: "\\operatorname{Arccos}\\NVar{z}",
    ref: "4.23#E2",
  },
  {
    name: "arccosine function",
    notation: "\\operatorname{arccos}\\NVar{z}",
    ref: "4.23#ii.p1",
  },
  {
    name: "general inverse hyperbolic cosine function",
    notation: "\\operatorname{Arccosh}\\NVar{z}",
    ref: "4.37#E2",
  },
  {
    name: "inverse hyperbolic cosine function",
    notation: "\\operatorname{arccosh}\\NVar{z}",
    ref: "4.37#ii.p1",
  },
  {
    name: "general arccotangent function",
    notation: "\\operatorname{Arccot}\\NVar{z}",
    ref: "4.23#E6",
  },
  {
    name: "arccotangent function",
    notation: "\\operatorname{arccot}\\NVar{z}",
    ref: "4.23#E9",
  },
  {
    name: "general inverse hyperbolic cotangent function",
    notation: "\\operatorname{Arccoth}\\NVar{z}",
    ref: "4.37#E6",
  },
  {
    name: "inverse hyperbolic cotangent function",
    notation: "\\operatorname{arccoth}\\NVar{z}",
    ref: "4.37#E9",
  },
  {
    name: "inverse Jacobian elliptic function",
    notation: "\\operatorname{arccs}\\left(\\NVar{x},\\NVar{k}\\right)",
    ref: "22.15#i.p1",
  },
  {
    name: "general arccosecant function",
    notation: "\\operatorname{Arccsc}\\NVar{z}",
    ref: "4.23#E4",
  },
  {
    name: "arccosecant function",
    notation: "\\operatorname{arccsc}\\NVar{z}",
    ref: "4.23#E7",
  },
  {
    name: "general inverse hyperbolic cosecant function",
    notation: "\\operatorname{Arccsch}\\NVar{z}",
    ref: "4.37#E4",
  },
  {
    name: "inverse hyperbolic cosecant function",
    notation: "\\operatorname{arccsch}\\NVar{z}",
    ref: "4.37#E7",
  },
  {
    name: "inverse Jacobian elliptic function",
    notation: "\\operatorname{arcdc}\\left(\\NVar{x},\\NVar{k}\\right)",
    ref: "22.15#i.p1",
  },
  {
    name: "inverse Jacobian elliptic function",
    notation: "\\operatorname{arcdn}\\left(\\NVar{x},\\NVar{k}\\right)",
    ref: "22.15#i.p1",
  },
  {
    name: "inverse Jacobian elliptic function",
    notation: "\\operatorname{arcds}\\left(\\NVar{x},\\NVar{k}\\right)",
    ref: "22.15#i.p1",
  },
  {
    name: "inverse Jacobian elliptic function",
    notation: "\\operatorname{arcnc}\\left(\\NVar{x},\\NVar{k}\\right)",
    ref: "22.15#i.p1",
  },
  {
    name: "inverse Jacobian elliptic function",
    notation: "\\operatorname{arcnd}\\left(\\NVar{x},\\NVar{k}\\right)",
    ref: "22.15#i.p1",
  },
  {
    name: "inverse Jacobian elliptic function",
    notation: "\\operatorname{arcns}\\left(\\NVar{x},\\NVar{k}\\right)",
    ref: "22.15#i.p1",
  },
  {
    name: "inverse Jacobian elliptic function",
    notation: "\\operatorname{arcsc}\\left(\\NVar{x},\\NVar{k}\\right)",
    ref: "22.15#i.p1",
  },
  {
    name: "inverse Jacobian elliptic function",
    notation: "\\operatorname{arcsd}\\left(\\NVar{x},\\NVar{k}\\right)",
    ref: "22.15#i.p1",
  },
  {
    name: "general arcsecant function",
    notation: "\\operatorname{Arcsec}\\NVar{z}",
    ref: "4.23#E5",
  },
  {
    name: "arcsecant function",
    notation: "\\operatorname{arcsec}\\NVar{z}",
    ref: "4.23#E8",
  },
  {
    name: "general inverse hyperbolic secant function",
    notation: "\\operatorname{Arcsech}\\NVar{z}",
    ref: "4.37#E5",
  },
  {
    name: "inverse hyperbolic secant function",
    notation: "\\operatorname{arcsech}\\NVar{z}",
    ref: "4.37#E8",
  },
  {
    name: "general arcsine function",
    notation: "\\operatorname{Arcsin}\\NVar{z}",
    ref: "4.23#E1",
  },
  {
    name: "arcsine function",
    notation: "\\operatorname{arcsin}\\NVar{z}",
    ref: "4.23#ii.p1",
  },
  {
    name: "general inverse hyperbolic sine function",
    notation: "\\operatorname{Arcsinh}\\NVar{z}",
    ref: "4.37#E1",
  },
  {
    name: "inverse hyperbolic sine function",
    notation: "\\operatorname{arcsinh}\\NVar{z}",
    ref: "4.37#ii.p1",
  },
  {
    name: "inverse Jacobian elliptic function",
    notation: "\\operatorname{arcsn}\\left(\\NVar{x},\\NVar{k}\\right)",
    ref: "22.15#i.p1",
  },
  {
    name: "general arctangent function",
    notation: "\\operatorname{Arctan}\\NVar{z}",
    ref: "4.23#E3",
  },
  {
    name: "arctangent function",
    notation: "\\operatorname{arctan}\\NVar{z}",
    ref: "4.23#ii.p1",
  },
  {
    name: "general inverse hyperbolic tangent function",
    notation: "\\operatorname{Arctanh}\\NVar{z}",
    ref: "4.37#E3",
  },
  {
    name: "inverse hyperbolic tangent function",
    notation: "\\operatorname{arctanh}\\NVar{z}",
    ref: "4.37#ii.p1",
  },
  {
    name: "kth zero of Airy Bi",
    notation: "b_{\\NVar{k}}",
    ref: "9.2#i",
  },
  {
    name: "kth zero of Airy Bi′",
    notation: "b^{\\prime}_{\\NVar{k}}",
    ref: "9.2#i",
  },
  {
    name: "Bernoulli numbers",
    notation: "B_{\\NVar{n}}",
    ref: "24.2#i",
  },
  {
    name: "generalized Bernoulli numbers",
    notation: "B^{(\\NVar{\\ell})}_{\\NVar{n}}",
    ref: "24.16#Px1.p1",
  },
  {
    name: "Nörlund polynomials",
    notation: "B^{(\\NVar{x})}_{\\NVar{n}}",
    ref: "24.16#Px4",
  },
  {
    name: "Bell number",
    notation: "B\\left(\\NVar{n}\\right)",
    ref: "26.7#i",
  },
  {
    name: "eigenvalues of Mathieu equation",
    notation: "b_{\\NVar{n}}\\left(\\NVar{q}\\right)",
    ref: "28.2#v.p1",
  },
  {
    name: "Bernoulli polynomials",
    notation: "B_{\\NVar{n}}\\left(\\NVar{x}\\right)",
    ref: "24.2#i",
  },
  {
    name: "generalized Airy function",
    notation: "B_{\\NVar{n}}\\left(\\NVar{z}\\right)",
    ref: "9.13#i.p2",
  },
  {
    name: "Bessel function of matrix argument (second kind)",
    notation: "B_{\\NVar{\\nu}}\\left(\\NVar{\\mathbf{T}}\\right)",
    ref: "35.5#E3",
  },
  {
    name: "generalized Bernoulli polynomials",
    notation: "B^{(\\NVar{\\ell})}_{\\NVar{n}}\\left(\\NVar{x}\\right)",
    ref: "24.16#Px1.p1",
  },
  {
    name: "periodic Bernoulli functions",
    notation: "\\widetilde{B}_{\\NVar{n}}\\left(\\NVar{x}\\right)",
    ref: "24.2#iii",
  },
  {
    name: "eigenvalues of Lamé’s equation",
    notation: "b^{\\NVar{n}}_{\\NVar{\\nu}}\\left(\\NVar{k^{2}}\\right)",
    ref: "29.3#i.p1",
  },
  {
    name: "beta function",
    notation: "\\mathrm{B}\\left(\\NVar{a},\\NVar{b}\\right)",
    ref: "5.12#E1",
  },
  {
    name: "generalized Airy function",
    notation: "B_{\\NVar{k}}\\left(\\NVar{z},\\NVar{p}\\right)",
    ref: "9.13#ii.p1",
  },
  {
    name: "multivariate beta function",
    notation: "\\mathrm{B}_{\\NVar{m}}\\left(\\NVar{a},\\NVar{b}\\right)",
    ref: "35.3#E3",
  },
  {
    name: "q-beta function",
    notation: "\\mathrm{B}_{\\NVar{q}}\\left(\\NVar{a},\\NVar{b}\\right)",
    ref: "5.18#E11",
  },
  {
    name: "incomplete beta function",
    notation: "\\mathrm{B}_{\\NVar{x}}\\left(\\NVar{a},\\NVar{b}\\right)",
    ref: "8.17#E1",
  },
  {
    name: "Kelvin function",
    notation: "\\operatorname{bei}_{\\NVar{\\nu}}\\left(\\NVar{x}\\right)",
    ref: "10.61#E1",
  },
  {
    name: "Kelvin function",
    notation: "\\operatorname{ber}_{\\NVar{\\nu}}\\left(\\NVar{x}\\right)",
    ref: "10.61#E1",
  },
  {
    name: "kth complex zero of Airy Bi",
    notation: "\\beta_{\\NVar{k}}",
    ref: "9.2#i",
  },
  {
    name: "kth complex zero of Airy Bi′",
    notation: "\\beta^{\\prime}_{\\NVar{k}}",
    ref: "9.2#i",
  },
  {
    name: "q-Bernoulli polynomial",
    notation: "\\beta_{\\NVar{n}}\\left(\\NVar{x},\\NVar{q}\\right)",
    ref: "17.3#E7",
  },
  {
    name: "Airy function",
    notation: "\\operatorname{Bi}\\left(\\NVar{z}\\right)",
    ref: "9.2#i",
  },
  {
    name: "complex plane",
    notation: "\\mathbb{C}",
    ref: "front/introduction#common.t1.r1",
  },
  {
    name: "is contained in",
    notation: "\\subset",
    ref: "front/introduction#common.t2.r2",
  },
  {
    name: "is, or is contained in",
    notation: "\\subseteq",
    ref: "front/introduction#common.t2.r3",
  },
  {
    name: "continuous on an interval I or (a,b)",
    notation: "C(\\NVar{I})",
    ref: "front/introduction#common.t1.r29",
  },
  {
    name: "Catalan number",
    notation: "C\\left(\\NVar{n}\\right)",
    ref: "26.5#E1",
  },
  {
    name: "number of compositions of n",
    notation: "c\\left(\\NVar{n}\\right)",
    ref: "26.11#p1",
  },
  {
    name: "Fresnel integral",
    notation: "C\\left(\\NVar{z}\\right)",
    ref: "7.2#E7",
  },
  {
    name: "alternative notation for the Fresnel integral",
    notation: "C_{1}(\\NVar{z})=C\\left(\\sqrt{2/\\pi}z\\right)",
    ref: "7.1#p4",
  },
  {
    name: "alternative notation for the Fresnel integral",
    notation: "C_{2}(\\NVar{z})=C\\left(\\sqrt{2z/\\pi}\\right)",
    ref: "7.1#p4",
  },
  {
    name: "Ramanujan’s sum",
    notation: "c_{\\NVar{k}}\\left(\\NVar{n}\\right)",
    ref: "27.10#E4",
  },
  {
    name: "normalizing constant for Coulomb radial functions",
    notation: "C_{\\NVar{\\ell}}\\left(\\NVar{\\eta}\\right)",
    ref: "33.2#E5",
  },
  {
    name: "number of compositions of n into exactly m parts",
    notation: "c_{\\NVar{m}}\\left(\\NVar{n}\\right)",
    ref: "26.11#p1",
  },
  {
    name: "dilated Chebyshev polynomial",
    notation: "C_{\\NVar{n}}\\left(\\NVar{x}\\right)",
    ref: "18.1#E3",
  },
  {
    name: "cylinder function",
    notation: "\\mathscr{C}_{\\NVar{\\nu}}\\left(\\NVar{z}\\right)",
    ref: "10.2#Px5.p1",
  },
  {
    name: "continuously differentiable n times on an interval I or (a,b)",
    notation: "C^{\\NVar{n}}(\\NVar{I})",
    ref: "front/introduction#common.t1.r29",
  },
  {
    name: "infinitely differentiable on an interval I or (a,b)",
    notation: "C^{\\infty}(\\NVar{I})",
    ref: "front/introduction#common.t1.r29",
  },
  {
    name: "Gegenbauer function",
    notation: "C^{(\\NVar{\\lambda})}_{\\NVar{\\alpha}}\\left(\\NVar{z}\\right)",
    ref: "15.9#E15",
  },
  {
    name: "ultraspherical (or Gegenbauer) polynomial",
    notation: "C^{(\\NVar{\\lambda})}_{\\NVar{n}}\\left(\\NVar{x}\\right)",
    ref: "18.3#T1.t1.r3",
  },
  {
    name: "restricted number of compositions of n",
    notation: "c\\left(\\NVar{\\mathrm{condition}},\\NVar{n}\\right)",
    ref: "26.11#p1",
  },
  {
    name: "Charlier polynomial",
    notation: "C_{\\NVar{n}}\\left(\\NVar{x};\\NVar{a}\\right)",
    ref: "18.19#T1.t1.r5",
  },
  {
    name: "Ince polynomials",
    notation: "C_{\\NVar{n}}^{\\NVar{m}}(\\NVar{z},\\NVar{\\xi})",
    ref: "28.31#ii.p4",
  },
  {
    name: "irregular Coulomb function",
    notation: "c\\left(\\NVar{\\epsilon},\\NVar{\\ell};\\NVar{r}\\right)",
    ref: "33.14#E9",
  },
  {
    name: "cardinal function",
    notation: "C(\\NVar{f},\\NVar{h})(\\NVar{x})",
    ref: "3.3#E43",
  },
  {
    name: "continuous q-ultraspherical polynomial",
    notation: "C_{\\NVar{n}}\\left(\\NVar{x};\\NVar{\\beta}\\,|\\,\\NVar{q}\\right)",
    ref: "18.28#E13",
  },
  {
    name: "Jacobian elliptic function",
    notation: "\\operatorname{cd}\\left(\\NVar{z},\\NVar{k}\\right)",
    ref: "22.2#E8",
  },
  {
    name: "Lamé polynomial",
    notation: "\\mathit{cdE}^{\\NVar{m}}_{2\\NVar{n}+2}\\left(\\NVar{z},\\NVar{k^{2}}\\right)",
    ref: "29.12#E7",
  },
  {
    name: "Mathieu function",
    notation: "\\operatorname{ce}_{\\NVar{n}}\\left(\\NVar{z},\\NVar{q}\\right)",
    ref: "28.2#vi.p1",
  },
  {
    name: "modified Mathieu function",
    notation: "\\operatorname{Ce}_{\\NVar{\\nu}}\\left(\\NVar{z},\\NVar{q}\\right)",
    ref: "28.20#E3",
  },
  {
    name: "Lamé polynomial",
    notation: "\\mathit{cE}^{\\NVar{m}}_{2\\NVar{n}+1}\\left(\\NVar{z},\\NVar{k^{2}}\\right)",
    ref: "29.12#E3",
  },
  {
    name: "Mathieu function of noninteger order",
    notation: "\\operatorname{ce}_{\\NVar{\\nu}}\\left(\\NVar{z},\\NVar{q}\\right)",
    ref: "28.12#E12",
  },
  {
    name: "Bulirsch’s complete elliptic integral",
    notation: "\\operatorname{cel}\\left(\\NVar{k_{c}},\\NVar{p},\\NVar{a},\\NVar{b}\\right)",
    ref: "19.2#E11",
  },
  {
    name: "Dirichlet character",
    notation: "\\chi\\left(\\NVar{n}\\right)",
    ref: "27.8#p1",
  },
  {
    name: "ratio of gamma functions",
    notation: "\\chi(\\NVar{x})",
    ref: "9.7#i.p1",
  },
  {
    name: "hyperbolic cosine integral",
    notation: "\\operatorname{Chi}\\left(\\NVar{z}\\right)",
    ref: "6.2#E16",
  },
  {
    name: "cosine integral",
    notation: "\\operatorname{Ci}\\left(\\NVar{z}\\right)",
    ref: "6.2#E11",
  },
  {
    name: "generalized cosine integral",
    notation: "\\operatorname{Ci}\\left(\\NVar{a},\\NVar{z}\\right)",
    ref: "8.21#E2",
  },
  {
    name: "generalized cosine integral",
    notation: "\\operatorname{ci}\\left(\\NVar{a},\\NVar{z}\\right)",
    ref: "8.21#E1",
  },
  {
    name: "cosine integral",
    notation: "\\operatorname{Cin}\\left(\\NVar{z}\\right)",
    ref: "6.2#E12",
  },
  {
    name: "Jacobian elliptic function",
    notation: "\\operatorname{cn}\\left(\\NVar{z},\\NVar{k}\\right)",
    ref: "22.2#E5",
  },
  {
    name: "alternative notation",
    notation:
      "\\mathrm{cn}(\\NVar{z}\\mathpunct{|}\\NVar{m})=\\operatorname{cn}\\left(z,\\sqrt{m}\\right)",
    ref: "22.1#p5",
  },
  {
    name: "cosine function",
    notation: "\\cos\\NVar{z}",
    ref: "4.14#E2",
  },
  {
    name: "q-cosine function",
    notation: "\\operatorname{Cos}_{\\NVar{q}}\\left(\\NVar{x}\\right)",
    ref: "17.3#E6",
  },
  {
    name: "q-cosine function",
    notation: "\\operatorname{cos}_{\\NVar{q}}\\left(\\NVar{x}\\right)",
    ref: "17.3#E5",
  },
  {
    name: "hyperbolic cosine function",
    notation: "\\cosh\\NVar{z}",
    ref: "4.28#E2",
  },
  {
    name: "cotangent function",
    notation: "\\cot\\NVar{z}",
    ref: "4.14#E7",
  },
  {
    name: "hyperbolic cotangent function",
    notation: "\\coth\\NVar{z}",
    ref: "4.28#E7",
  },
  {
    name: "Jacobian elliptic function",
    notation: "\\operatorname{cs}\\left(\\NVar{z},\\NVar{k}\\right)",
    ref: "22.2#E9",
  },
  {
    name: "cosecant function",
    notation: "\\csc\\NVar{z}",
    ref: "4.14#E5",
  },
  {
    name: "hyperbolic cosecant function",
    notation: "\\operatorname{csch}\\NVar{z}",
    ref: "4.28#E5",
  },
  {
    name: "of vector-valued function",
    notation: "\\operatorname{curl}",
    ref: "1.6#E22",
  },
  {
    name: "q-differential operator",
    notation: "\\mathcal{D}_{\\NVar{q}}",
    ref: "17.2#E41",
  },
  {
    name: "fractional derivative",
    notation: "D^{\\NVar{\\alpha}}",
    ref: "1.15#E51",
  },
  {
    name: "complete elliptic integral of Legendre’s type",
    notation: "D\\left(\\NVar{k}\\right)",
    ref: "19.2#E8",
  },
  {
    name: "divisor function",
    notation: "d\\left(\\NVar{n}\\right)",
    ref: "27.2#E9",
  },
  {
    name: "derangement number",
    notation: "d(\\NVar{n})",
    ref: "26.13#p7",
  },
  {
    name: "q-differential of x",
    notation: "\\,{\\mathrm{d}}_{\\NVar{q}}\\NVar{x}",
    ref: "17.2#v",
  },
  {
    name: "partial differential of x",
    notation: "\\,\\partial\\NVar{x}",
    ref: "1.5#E3",
  },
  {
    name: "divisor function",
    notation: "d_{\\NVar{k}}\\left(\\NVar{n}\\right)",
    ref: "27.2#i.p4",
  },
  {
    name: "discriminant function",
    notation: "\\operatorname{Disc}\\left(\\NVar{x}\\right)",
    ref: "18.2#E20",
  },
  {
    name: "parabolic cylinder function",
    notation: "D_{\\NVar{\\nu}}\\left(\\NVar{z}\\right)",
    ref: "12.1#p3",
  },
  {
    name: "Delannoy number",
    notation: "D(\\NVar{m},\\NVar{n})",
    ref: "26.6#E1",
  },
  {
    name: "incomplete elliptic integral of Legendre’s type",
    notation: "D\\left(\\NVar{\\phi},\\NVar{k}\\right)",
    ref: "19.2#E6",
  },
  {
    name: "cross-products of modified Mathieu functions and their derivatives",
    notation: "\\operatorname{D}_{\\NVar{j}}\\left(\\NVar{\\nu},\\NVar{\\mu},\\NVar{z}\\right)",
    ref: "28.28#E24",
  },
  {
    name: "alternative notation",
    notation:
      "\\mathfrak{D}_{\\NVar{lm}}(\\NVar{\\theta},\\NVar{\\phi})\\propto Y_{{l},{m}}\\left(%\n\\theta,\\phi\\right)",
    ref: "14.30#i.p2",
  },
  {
    name: "Jacobian elliptic function",
    notation: "\\operatorname{dc}\\left(\\NVar{z},\\NVar{k}\\right)",
    ref: "22.2#E8",
  },
  {
    name: "cross-products of radial Mathieu functions and their derivatives",
    notation: "\\operatorname{Dc}_{\\NVar{j}}\\left(\\NVar{n},\\NVar{m},\\NVar{z}\\right)",
    ref: "28.28#E39",
  },
  {
    name: "derivative of f with respect to x",
    notation: "\\frac{\\mathrm{d}\\NVar{f}}{\\mathrm{d}\\NVar{x}}",
    ref: "1.4#E4",
  },
  {
    name: "partial derivative of f with respect to x",
    notation: "\\frac{\\partial\\NVar{f}}{\\partial\\NVar{x}}",
    ref: "1.5#E3",
  },
  {
    name: "Jacobian",
    notation: "\\frac{\\partial(\\NVar{f,g})}{\\partial(\\NVar{x,y})}",
    ref: "1.5#E38",
  },
  {
    name: "Lamé polynomial",
    notation: "\\mathit{dE}^{\\NVar{m}}_{2\\NVar{n}+1}\\left(\\NVar{z},\\NVar{k^{2}}\\right)",
    ref: "29.12#E4",
  },
  {
    name: "forward difference operator",
    notation: "\\Delta",
    ref: "3.6#i.p1",
  },
  {
    name: "Kronecker delta",
    notation: "\\delta_{\\NVar{j},\\NVar{k}}",
    ref: "front/introduction#common.t1.r4",
  },
  {
    name: "central difference",
    notation: "\\delta_{\\NVar{x}}",
    ref: "18.1#EGx3",
  },
  {
    name: "forward difference",
    notation: "\\Delta_{\\NVar{x}}",
    ref: "18.1#EGx1",
  },
  {
    name: "discriminant function",
    notation: "\\Delta\\left(\\NVar{\\tau}\\right)",
    ref: "27.14#E16",
  },
  {
    name: "Dirac delta distribution",
    notation: "\\delta_{x}",
    ref: "1.16#iii",
  },
  {
    name: "Dirac delta (or Dirac delta function)",
    notation: "\\delta\\left(\\NVar{x-a}\\right)",
    ref: "1.17#i.p1",
  },
  {
    name: "Dirac delta sequence",
    notation: "\\delta_{n}\\left(\\NVar{x}\\right)",
    ref: "1.17#i.p1",
  },
  {
    name: "determinant",
    notation: "\\det",
    ref: "1.2#Px11.p1",
  },
  {
    name: "divergence of vector-valued function",
    notation: "\\operatorname{div}",
    ref: "1.6#E21",
  },
  {
    name: "Jacobian elliptic function",
    notation: "\\operatorname{dn}\\left(\\NVar{z},\\NVar{k}\\right)",
    ref: "22.2#E6",
  },
  {
    name: "alternative notation",
    notation:
      "\\mathrm{dn}(\\NVar{z}\\mathpunct{|}\\NVar{m})=\\operatorname{dn}\\left(z,\\sqrt{m}\\right)",
    ref: "22.1#p5",
  },
  {
    name: "Jacobian elliptic function",
    notation: "\\operatorname{ds}\\left(\\NVar{z},\\NVar{k}\\right)",
    ref: "22.2#E7",
  },
  {
    name: "cross-products of radial Mathieu functions and their derivatives",
    notation: "\\operatorname{Ds}_{\\NVar{j}}\\left(\\NVar{n},\\NVar{m},\\NVar{z}\\right)",
    ref: "28.28#E35",
  },
  {
    name: "cross-products of radial Mathieu functions and their derivatives",
    notation: "\\operatorname{Dsc}_{\\NVar{j}}\\left(\\NVar{n},\\NVar{m},\\NVar{z}\\right)",
    ref: "28.28#E40",
  },
  {
    name: "equals by definition",
    notation: "\\equiv",
    ref: "front/introduction#common.t1.r9",
  },
  {
    name: "elementary charge",
    notation: "e",
    ref: "18.39#Px5",
  },
  {
    name: "base of natural logarithm",
    notation: "\\mathrm{e}",
    ref: "4.2#E11",
  },
  {
    name: "element of",
    notation: "\\in",
    ref: "front/introduction#common.t1.r10",
  },
  {
    name: "not an element of",
    notation: "\\notin",
    ref: "front/introduction#common.t1.r11",
  },
  {
    name: "Euler numbers",
    notation: "E_{\\NVar{n}}",
    ref: "24.2#ii",
  },
  {
    name: "generalized Euler numbers",
    notation: "E^{(\\NVar{\\ell})}_{\\NVar{n}}",
    ref: "24.16#Px1.p1",
  },
  {
    name: "Legendre’s complete elliptic integral of the second kind",
    notation: "E\\left(\\NVar{k}\\right)",
    ref: "19.2#E8",
  },
  {
    name: "Dedekind’s eta function (or Dedekind modular function)",
    notation: "\\eta\\left(\\NVar{\\tau}\\right)",
    ref: "27.14#E12",
  },
  {
    name: "exponential integral",
    notation: "E_{1}\\left(\\NVar{z}\\right)",
    ref: "6.2#E1",
  },
  {
    name: "Legendre’s complementary complete elliptic integral of the second kind",
    notation: "{E^{\\prime}}\\left(\\NVar{k}\\right)",
    ref: "19.2#E8_2",
  },
  {
    name: "Mittag-Leffler function",
    notation: "E_{\\NVar{a},\\NVar{b}}\\left(\\NVar{z}\\right)",
    ref: "10.46#E3",
  },
  {
    name: "Euler polynomials",
    notation: "E_{\\NVar{n}}\\left(\\NVar{x}\\right)",
    ref: "24.2#ii",
  },
  {
    name: "Weber function",
    notation: "\\mathbf{E}_{\\NVar{\\nu}}\\left(\\NVar{z}\\right)",
    ref: "11.10#E2",
  },
  {
    name: "generalized exponential integral",
    notation: "E_{\\NVar{p}}\\left(\\NVar{z}\\right)",
    ref: "8.19#E1",
  },
  {
    name: "q-exponential function",
    notation: "E_{\\NVar{q}}\\left(\\NVar{x}\\right)",
    ref: "17.3#E2",
  },
  {
    name: "q-exponential function",
    notation: "e_{\\NVar{q}}\\left(\\NVar{x}\\right)",
    ref: "17.3#E1",
  },
  {
    name: "elementary symmetric function",
    notation: "E_{\\NVar{s}}(\\NVar{\\mathbf{z}})",
    ref: "19.19#E4",
  },
  {
    name: "generalized Euler polynomials",
    notation: "E^{(\\NVar{\\ell})}_{\\NVar{n}}\\left(\\NVar{x}\\right)",
    ref: "24.16#Px1.p1",
  },
  {
    name: "periodic Euler functions",
    notation: "\\widetilde{E}_{\\NVar{n}}\\left(\\NVar{x}\\right)",
    ref: "24.2#iii",
  },
  {
    name: "Legendre’s incomplete elliptic integral of the second kind",
    notation: "E\\left(\\NVar{\\phi},\\NVar{k}\\right)",
    ref: "19.2#E5",
  },
  {
    name: "Weierstrass lattice roots",
    notation: "e_{\\NVar{j}}",
    ref: "23.3#i",
  },
  {
    name: "Lamé function",
    notation: "\\mathit{Ec}^{\\NVar{m}}_{\\NVar{\\nu}}\\left(\\NVar{z},\\NVar{k^{2}}\\right)",
    ref: "29.3#iv.p1",
  },
  {
    name: "exponential integral",
    notation: "\\operatorname{Ei}\\left(\\NVar{x}\\right)",
    ref: "6.2#i.p3",
  },
  {
    name: "complementary exponential integral",
    notation: "\\operatorname{Ein}\\left(\\NVar{z}\\right)",
    ref: "6.2#E3",
  },
  {
    name: "Bulirsch’s incomplete elliptic integral of the first kind",
    notation: "\\operatorname{el1}\\left(\\NVar{x},\\NVar{k_{c}}\\right)",
    ref: "19.2#E11_5",
  },
  {
    name: "Bulirsch’s incomplete elliptic integral of the second kind",
    notation: "\\operatorname{el2}\\left(\\NVar{x},\\NVar{k_{c}},\\NVar{a},\\NVar{b}\\right)",
    ref: "19.2#E12",
  },
  {
    name: "Bulirsch’s incomplete elliptic integral of the third kind",
    notation: "\\operatorname{el3}\\left(\\NVar{x},\\NVar{k_{c}},\\NVar{p}\\right)",
    ref: "19.2#E16",
  },
  {
    name: "envelope of Airy function Ai(x)",
    notation: "\\operatorname{envAi}\\left(\\NVar{x}\\right)",
    ref: "9.2#i",
  },
  {
    name: "envelope of Airy function Bi(x)",
    notation: "\\operatorname{envBi}\\left(\\NVar{x}\\right)",
    ref: "9.2#i",
  },
  {
    name: "envelope of Bessel function Jν(x)",
    notation: "\\operatorname{env}\\mskip-2.0muJ_{\\NVar{\\nu}}\\left(\\NVar{x}\\right)",
    ref: "10.2#E2",
  },
  {
    name: "envelope of Bessel function Yν(x)",
    notation: "\\operatorname{env}\\mskip-2.0muY_{\\NVar{\\nu}}\\left(\\NVar{x}\\right)",
    ref: "10.2#E3",
  },
  {
    name: "envelope of parabolic cylinder function U(c,x)",
    notation: "\\mathrm{env}\\mskip-1.0muU\\left(\\NVar{c},\\NVar{x}\\right)",
    ref: "12.2#i.p1",
  },
  {
    name: "envelope of parabolic cylinder function U¯(c,x)",
    notation: "\\mathrm{env}\\mskip-1.0mu\\overline{U}\\left(\\NVar{c},\\NVar{x}\\right)",
    ref: "12.2#vi.p1",
  },
  {
    name: "Levi-Civita symbol",
    notation: "\\epsilon_{\\NVar{j}\\NVar{k}\\NVar{\\ell}}",
    ref: "1.6#E14",
  },
  {
    name: "Jacobi’s epsilon function",
    notation: "\\mathcal{E}\\left(\\NVar{x},\\NVar{k}\\right)",
    ref: "22.16#E14",
  },
  {
    name: "modular equivalence",
    notation: "\\equiv",
    ref: "front/introduction#common.t2.r10",
  },
  {
    name: "alternative notation for the error function",
    notation: "\\operatorname{Erf}\\NVar{z}=\\tfrac{1}{2}\\sqrt{\\pi}\\operatorname{erf}z",
    ref: "7.1#p4",
  },
  {
    name: "error function",
    notation: "\\operatorname{erf}\\NVar{z}",
    ref: "7.2#E1",
  },
  {
    name: "complementary error function",
    notation: "\\operatorname{erfc}\\NVar{z}",
    ref: "7.2#E2",
  },
  {
    name: "alternative notation for Dawson’s integral",
    notation: "\\operatorname{Erfi}\\NVar{z}=e^{z^{2}}F\\left(z\\right)",
    ref: "7.1#p4",
  },
  {
    name: "Lamé function",
    notation: "\\mathit{Es}^{\\NVar{m}}_{\\NVar{\\nu}}\\left(\\NVar{z},\\NVar{k^{2}}\\right)",
    ref: "29.3#iv.p1",
  },
  {
    name: "exponential of trace",
    notation: "\\operatorname{etr}\\left(\\NVar{\\mathbf{A}}\\right)",
    ref: "1.2#E77",
  },
  {
    name: "exponential function",
    notation: "\\exp\\NVar{z}",
    ref: "4.2#E19",
  },
  {
    name: "Lauricella’s multivariate hypergeometric function",
    notation: "F_{D}",
    ref: "19.15#p1",
  },
  {
    name: "Fibonacci number",
    notation: "F_{\\NVar{n}}",
    ref: "26.11#p4",
  },
  {
    name: "Euler’s reciprocal function",
    notation: "\\mathit{f}\\left(\\NVar{x}\\right)",
    ref: "27.14#E2",
  },
  {
    name: "auxiliary function for Fresnel integrals",
    notation: "\\mathrm{f}\\left(\\NVar{z}\\right)",
    ref: "7.2#E10",
  },
  {
    name: "auxiliary function for sine and cosine integrals",
    notation: "\\mathrm{f}\\left(\\NVar{z}\\right)",
    ref: "6.2#E17",
  },
  {
    name: "Dawson’s integral",
    notation: "F\\left(\\NVar{z}\\right)",
    ref: "7.2#E5",
  },
  {
    name: "Fresnel integral",
    notation: "\\mathcal{F}\\left(\\NVar{z}\\right)",
    ref: "7.2#E6",
  },
  {
    name: "joining factor for radial Mathieu functions",
    notation: "f_{\\mathit{e},\\NVar{m}}(\\NVar{h})",
    ref: "28.22#EGx2",
  },
  {
    name: "joining factor for radial Mathieu functions",
    notation: "f_{\\mathit{o},\\NVar{m}}(\\NVar{h})",
    ref: "28.22#EGx2",
  },
  {
    name: "terminant function",
    notation: "F_{\\NVar{p}}\\left(\\NVar{z}\\right)",
    ref: "2.11#E11",
  },
  {
    name: "Fermi–Dirac integral",
    notation: "F_{\\NVar{s}}(\\NVar{x})",
    ref: "25.12#E14",
  },
  {
    name: "Fourier transform",
    notation: "\\mathscr{F}\\left(\\NVar{f}\\right)\\left(\\NVar{s}\\right)",
    ref: "1.14#E1",
  },
  {
    name: "Fourier cosine transform",
    notation: "\\mathscr{F}_{\\mkern-3.0muc}\\left(\\NVar{f}\\right)\\left(\\NVar{s}\\right)",
    ref: "1.14#E9",
  },
  {
    name: "Fourier sine transform",
    notation: "\\mathscr{F}_{\\mkern-2.0mus}\\left(\\NVar{f}\\right)\\left(\\NVar{s}\\right)",
    ref: "1.14#E10",
  },
  {
    name: "Fourier transform of a tempered distribution",
    notation: "\\mathscr{F}\\left(\\NVar{u}\\right)",
    ref: "1.16#E35",
  },
  {
    name: "Legendre’s incomplete elliptic integral of the first kind",
    notation: "F\\left(\\NVar{\\phi},\\NVar{k}\\right)",
    ref: "19.2#E4",
  },
  {
    name: "regular Coulomb radial function",
    notation: "F_{\\NVar{\\ell}}\\left(\\NVar{\\eta},\\NVar{\\rho}\\right)",
    ref: "33.2#E3",
  },
  {
    name: "periodic zeta function",
    notation: "F\\left(\\NVar{x},\\NVar{s}\\right)",
    ref: "25.13#E1",
  },
  {
    name: "=F12(a,b",
    notation: "F\\left(\\NVar{a},\\NVar{b};\\NVar{c};\\NVar{z}\\right)",
    ref: "16.2",
  },
  {
    name: "=𝐅12(a,b",
    notation: "\\mathbf{F}\\left(\\NVar{a},\\NVar{b};\\NVar{c};\\NVar{z}\\right)",
    ref: "16.2#E5",
  },
  {
    name: "regular Coulomb function",
    notation: "f\\left(\\NVar{\\epsilon},\\NVar{\\ell};\\NVar{r}\\right)",
    ref: "33.14#E4",
  },
  {
    name: "=M(a,b,z) notation for the Kummer confluent hypergeometric function",
    notation: "{{}_{1}F_{1}}\\left(\\NVar{a};\\NVar{b};\\NVar{z}\\right)",
    ref: "13.2#E2",
  },
  {
    name: "confluent hypergeometric function of matrix argument (first kind)",
    notation: "{{}_{1}F_{1}}\\left(\\NVar{a};\\NVar{b};\\NVar{\\mathbf{T}}\\right)",
    ref: "35.6#i",
  },
  {
    name: "=F(a,b",
    notation: "{{}_{2}F_{1}}\\left(\\NVar{a},\\NVar{b};\\NVar{c};\\NVar{z}\\right)",
    ref: "15.2#E1",
  },
  {
    name: "Gaussian hypergeometric function of matrix argument",
    notation: "{{}_{2}F_{1}}\\left(\\NVar{a},\\NVar{b};\\NVar{c};\\NVar{\\mathbf{T}}\\right)",
    ref: "35.7#E1",
  },
  {
    name: "Olver’s hypergeometric function",
    notation: "{{}_{2}{\\mathbf{F}}_{1}}\\left(\\NVar{a},\\NVar{b};\\NVar{c};\\NVar{z}\\right)",
    ref: "15.2#E2",
  },
  {
    name: "alternatively Fqp(𝐚",
    notation:
      "{{}_{\\NVar{p}}F_{\\NVar{q}}}\\left(\\NVar{a_{1},\\dots,a_{p}};\\NVar{b_{1},\\dots,b_%\n{q}};\\NVar{z}\\right)",
    ref: "16.2",
  },
  {
    name: "scaled (or Olver’s) generalized hypergeometric function",
    notation:
      "{{}_{\\NVar{p}}{\\mathbf{F}}_{\\NVar{q}}}\\left(\\NVar{\\mathbf{a}};\\NVar{\\mathbf{b}%\n};\\NVar{z}\\right)",
    ref: "16.2#E5",
  },
  {
    name: "generalized hypergeometric function of matrix argument",
    notation:
      "{{}_{\\NVar{p}}F_{\\NVar{q}}}\\left(\\NVar{a_{1},\\dots,a_{p}};\\NVar{b_{1},\\dots,b_%\n{q}};\\NVar{\\mathbf{T}}\\right)",
    ref: "35.8#E1",
  },
  {
    name: "alternative notation for specialization of ϕ12",
    notation: "F(\\NVar{a},\\NVar{b};\\NVar{t}:\\NVar{q})",
    ref: "17.4#E1",
  },
  {
    name: "first Appell function",
    notation:
      "{F_{1}}\\left(\\NVar{\\alpha};\\NVar{\\beta},\\NVar{\\beta^{\\prime}};\\NVar{\\gamma};%\n\\NVar{x},\\NVar{y}\\right)",
    ref: "16.13#E1",
  },
  {
    name: "second Appell function",
    notation:
      "{F_{2}}\\left(\\NVar{\\alpha};\\NVar{\\beta},\\NVar{\\beta^{\\prime}};\\NVar{\\gamma},%\n\\NVar{\\gamma^{\\prime}};\\NVar{x},\\NVar{y}\\right)",
    ref: "16.13#E2",
  },
  {
    name: "third Appell function",
    notation:
      "{F_{3}}\\left(\\NVar{\\alpha},\\NVar{\\alpha^{\\prime}};\\NVar{\\beta},\\NVar{\\beta^{%\n\\prime}};\\NVar{\\gamma};\\NVar{x},\\NVar{y}\\right)",
    ref: "16.13#E3",
  },
  {
    name: "fourth Appell function",
    notation:
      "{F_{4}}\\left(\\NVar{\\alpha},\\NVar{\\beta};\\NVar{\\gamma},\\NVar{\\gamma^{\\prime}};%\n\\NVar{x},\\NVar{y}\\right)",
    ref: "16.13#E4",
  },
  {
    name: "modified Mathieu function",
    notation: "\\operatorname{Fe}_{\\NVar{n}}\\left(\\NVar{z},\\NVar{q}\\right)",
    ref: "28.20#E6",
  },
  {
    name: "second solution, Mathieu’s equation",
    notation: "\\operatorname{fe}_{\\NVar{n}}\\left(\\NVar{z},\\NVar{q}\\right)",
    ref: "28.5#E1",
  },
  {
    name: "Genocchi numbers",
    notation: "G_{\\NVar{n}}",
    ref: "24.15#i",
  },
  {
    name: "Waring’s function",
    notation: "G\\left(\\NVar{k}\\right)",
    ref: "27.13#iii.p1",
  },
  {
    name: "Waring’s function",
    notation: "g\\left(\\NVar{k}\\right)",
    ref: "27.13#iii.p1",
  },
  {
    name: "auxiliary function for Fresnel integrals",
    notation: "\\mathrm{g}\\left(\\NVar{z}\\right)",
    ref: "7.2#E11",
  },
  {
    name: "auxiliary function for sine and cosine integrals",
    notation: "\\mathrm{g}\\left(\\NVar{z}\\right)",
    ref: "6.2#E18",
  },
  {
    name: "Barnes’ G-function (or double gamma function)",
    notation: "G\\left(\\NVar{z}\\right)",
    ref: "5.17#E1",
  },
  {
    name: "Goodwin–Staton integral",
    notation: "G\\left(\\NVar{z}\\right)",
    ref: "7.2#E12",
  },
  {
    name: "joining factor for radial Mathieu functions",
    notation: "g_{\\mathit{e},\\NVar{m}}(\\NVar{h})",
    ref: "28.22#EGx2",
  },
  {
    name: "joining factor for radial Mathieu functions",
    notation: "g_{\\mathit{o},\\NVar{m}}(\\NVar{h})",
    ref: "28.22#EGx2",
  },
  {
    name: "rescaled terminant function",
    notation: "G_{\\NVar{p}}\\left(\\NVar{z}\\right)",
    ref: "9.7#E22",
  },
  {
    name: "Bose–Einstein integral",
    notation: "G_{\\NVar{s}}(\\NVar{x})",
    ref: "25.12#E15",
  },
  {
    name: "Gauss sum",
    notation: "G\\left(\\NVar{n},\\NVar{\\chi}\\right)",
    ref: "27.10#E9",
  },
  {
    name: "scaled gamma function",
    notation: "\\Gamma^{*}\\left(\\NVar{z}\\right)",
    ref: "5.11#E3",
  },
  {
    name: "Weierstrass lattice invariants g2, g3",
    notation: "g_{\\NVar{j}}",
    ref: "23.3#EGx1",
  },
  {
    name: "irregular Coulomb radial function",
    notation: "G_{\\NVar{\\ell}}\\left(\\NVar{\\eta},\\NVar{\\rho}\\right)",
    ref: "33.2#E11",
  },
  {
    name: "shifted Jacobi polynomial",
    notation: "G_{\\NVar{n}}\\left(\\NVar{p},\\NVar{q},\\NVar{x}\\right)",
    ref: "18.1#E2",
  },
  {
    name: "Meijer G-function",
    notation:
      "{G^{\\NVar{m},\\NVar{n}}_{\\NVar{p},\\NVar{q}}}\\left(\\NVar{z};{\\NVar{a_{1},\\dots,a%\n_{p}}\\atop\\NVar{b_{1},\\dots,b_{q}}}\\right)",
    ref: "16.17#E1",
  },
  {
    name: "Euler’s constant",
    notation: "\\gamma",
    ref: "5.2#E3",
  },
  {
    name: "Stieltjes constants",
    notation: "\\gamma_{\\NVar{n}}",
    ref: "25.2#E5",
  },
  {
    name: "gamma function",
    notation: "\\Gamma\\left(\\NVar{z}\\right)",
    ref: "5.2#E1",
  },
  {
    name: "multivariate gamma function",
    notation: "\\Gamma_{\\NVar{m}}\\left(\\NVar{a}\\right)",
    ref: "35.3#i",
  },
  {
    name: "q-gamma function",
    notation: "\\Gamma_{\\NVar{q}}\\left(\\NVar{z}\\right)",
    ref: "5.18#E4",
  },
  {
    name: "incomplete gamma function",
    notation: "\\Gamma\\left(\\NVar{a},\\NVar{z}\\right)",
    ref: "8.2#E2",
  },
  {
    name: "incomplete gamma function",
    notation: "\\gamma^{*}\\left(\\NVar{a},\\NVar{z}\\right)",
    ref: "8.2#E6",
  },
  {
    name: "Gudermannian function",
    notation: "\\operatorname{gd}\\NVar{x}",
    ref: "4.23#E39",
  },
  {
    name: "inverse Gudermannian function",
    notation: "{\\operatorname{gd}^{-1}}\\left(\\NVar{x}\\right)",
    ref: "4.23#E41",
  },
  {
    name: "modified Mathieu function",
    notation: "\\operatorname{Ge}_{\\NVar{n}}\\left(\\NVar{z},\\NVar{q}\\right)",
    ref: "28.20#E7",
  },
  {
    name: "second solution, Mathieu’s equation",
    notation: "\\operatorname{ge}_{\\NVar{n}}\\left(\\NVar{z},\\NVar{q}\\right)",
    ref: "28.5#E2",
  },
  {
    name: "Scorer function (inhomogeneous Airy function)",
    notation: "\\operatorname{Gi}\\left(\\NVar{z}\\right)",
    ref: "9.12#E4",
  },
  {
    name: "gradient of differentiable scalar function",
    notation: "\\operatorname{grad}",
    ref: "1.6#E20",
  },
  {
    name: "harmonic number",
    notation: "H_{\\NVar{n}}",
    ref: "25.11#E33",
  },
  {
    name: "Euler sums",
    notation: "H\\left(\\NVar{s}\\right)",
    ref: "25.16#ii.p1",
  },
  {
    name: "Heaviside function",
    notation: "H\\left(\\NVar{x}\\right)",
    ref: "1.16#E13",
  },
  {
    name: "Hermite polynomial",
    notation: "\\mathit{He}_{\\NVar{n}}\\left(\\NVar{x}\\right)",
    ref: "18.3#T1.t1.r14",
  },
  {
    name: "Struve function",
    notation: "\\mathbf{H}_{\\NVar{\\nu}}\\left(\\NVar{z}\\right)",
    ref: "11.2#E1",
  },
  {
    name: "spherical Bessel function of the third kind",
    notation: "{\\mathsf{h}^{(1)}_{\\NVar{n}}}\\left(\\NVar{z}\\right)",
    ref: "10.47#E5",
  },
  {
    name: "spherical Bessel function of the third kind",
    notation: "{\\mathsf{h}^{(2)}_{\\NVar{n}}}\\left(\\NVar{z}\\right)",
    ref: "10.47#E6",
  },
  {
    name: "Bessel function of the third kind (or Hankel function)",
    notation: "{H^{(1)}_{\\NVar{\\nu}}}\\left(\\NVar{z}\\right)",
    ref: "10.2#E5",
  },
  {
    name: "Bessel function of the third kind (or Hankel function)",
    notation: "{H^{(2)}_{\\NVar{\\nu}}}\\left(\\NVar{z}\\right)",
    ref: "10.2#E6",
  },
  {
    name: "line-broadening function",
    notation: "H\\left(\\NVar{a},\\NVar{u}\\right)",
    ref: "7.19#E4",
  },
  {
    name: "Hilbert transform",
    notation: "\\mathcal{H}\\left(\\NVar{f}\\right)\\left(\\NVar{x}\\right)",
    ref: "1.14#v.p1",
  },
  {
    name: "generalized Euler sums",
    notation: "H\\left(\\NVar{s},\\NVar{z}\\right)",
    ref: "25.16#ii.p7",
  },
  {
    name: "Jacobi’s notation",
    notation: "\\mathrm{H}(\\NVar{z}|\\NVar{\\tau})=\\theta_{1}\\left(u\\middle|\\tau\\right)",
    ref: "20.1#Px1.p1",
  },
  {
    name: "Jacobi’s notation",
    notation: "\\mathrm{H}_{1}(\\NVar{z}|\\NVar{\\tau})=\\theta_{2}\\left(u\\middle|\\tau\\right)",
    ref: "20.1#Px1.p1",
  },
  {
    name: "exceptional Hermite polynomial",
    notation: "\\hat{H}_{\\NVar{n}}\\left(\\NVar{x}\\right)",
    ref: "18.36#Px2.p1",
  },
  {
    name: "continuous q-Hermite polynomial",
    notation: "H_{\\NVar{n}}\\left(\\NVar{x}\\,|\\,\\NVar{q}\\right)",
    ref: "18.28#E16",
  },
  {
    name: "discrete q-Hermite I polynomial",
    notation: "h_{\\NVar{n}}\\left(\\NVar{x};\\NVar{q}\\right)",
    ref: "18.27#E21",
  },
  {
    name: "discrete q-Hermite II polynomial",
    notation: "\\tilde{h}_{\\NVar{n}}\\left(\\NVar{x};\\NVar{q}\\right)",
    ref: "18.27#E23",
  },
  {
    name: "irregular Coulomb radial functions",
    notation: "{H^{\\NVar{\\pm}}_{\\NVar{\\ell}}}\\left(\\NVar{\\eta},\\NVar{\\rho}\\right)",
    ref: "33.2#E7",
  },
  {
    name: "irregular Coulomb function",
    notation: "h\\left(\\NVar{\\epsilon},\\NVar{\\ell};\\NVar{r}\\right)",
    ref: "33.14#E7",
  },
  {
    name: "bilateral hypergeometric function",
    notation:
      "{{}_{\\NVar{p}}H_{\\NVar{q}}}\\left({\\NVar{a_{1},\\dots,a_{p}}\\atop\\NVar{b_{1},%\n\\dots,b_{q}}};\\NVar{z}\\right)",
    ref: "16.4#E16",
  },
  {
    name: "paraboloidal wave function",
    notation: "\\mathit{hc}_{\\NVar{p}}^{\\NVar{m}}(\\NVar{z},\\NVar{\\xi})",
    ref: "28.31#iii.p1",
  },
  {
    name: "Heun functions",
    notation:
      "(\\NVar{s_{1}},\\NVar{s_{2}})\\mathit{Hf}_{\\NVar{m}}\\left(\\NVar{a},\\NVar{q_{m}};%\n\\NVar{\\alpha},\\NVar{\\beta},\\NVar{\\gamma},\\NVar{\\delta};\\NVar{z}\\right)",
    ref: "31.4#p1",
  },
  {
    name: "path-multiplicative solutions of Heun’s equation",
    notation:
      "(\\NVar{s_{1}},\\NVar{s_{2}})\\mathit{Hf}_{\\NVar{m}}^{\\NVar{\\nu}}\\left(\\NVar{a},%\n\\NVar{q_{m}};\\NVar{\\alpha},\\NVar{\\beta},\\NVar{\\gamma},\\NVar{\\delta};\\NVar{z}\\right)",
    ref: "31.6#p1",
  },
  {
    name: "probability function",
    notation: "\\mathit{Hh}_{\\NVar{n}}\\left(\\NVar{z}\\right)",
    ref: "7.18#E12",
  },
  {
    name: "Scorer function (inhomogeneous Airy function)",
    notation: "\\operatorname{Hi}\\left(\\NVar{z}\\right)",
    ref: "9.12#E5",
  },
  {
    name: "Heun functions",
    notation:
      "\\mathit{H\\!\\ell}\\left(\\NVar{a},\\NVar{q};\\NVar{\\alpha},\\NVar{\\beta},\\NVar{%\n\\gamma},\\NVar{\\delta};\\NVar{z}\\right)",
    ref: "31.3#E1",
  },
  {
    name: "Heun polynomials",
    notation:
      "\\mathit{Hp}_{\\NVar{n},\\NVar{m}}\\left(\\NVar{a},\\NVar{q_{n,m}};\\NVar{-n},\\NVar{%\n\\beta},\\NVar{\\gamma},\\NVar{\\delta};\\NVar{z}\\right)",
    ref: "31.5#E2",
  },
  {
    name: "paraboloidal wave function",
    notation: "\\mathit{hs}_{\\NVar{p}}^{\\NVar{m}}(\\NVar{z},\\NVar{\\xi})",
    ref: "28.31#iii.p1",
  },
  {
    name: "identity matrix",
    notation: "\\mathbf{I}",
    ref: "1.2#E53",
  },
  {
    name: "imaginary part",
    notation: "\\Im",
    ref: "1.9#E2",
  },
  {
    name: "imaginary unit",
    notation: "\\mathrm{i}",
    ref: "1.9#E1",
  },
  {
    name: "fractional integral",
    notation: "I^{\\NVar{\\alpha}}",
    ref: "1.15#E47",
  },
  {
    name: "general elliptic integral",
    notation: "I(\\NVar{\\mathbf{m}})",
    ref: "19.29#ii.p1",
  },
  {
    name: "modified Bessel function of the first kind of imaginary order",
    notation: "\\widetilde{I}_{\\NVar{\\nu}}\\left(\\NVar{x}\\right)",
    ref: "10.45#E2",
  },
  {
    name: "modified Bessel function of the first kind",
    notation: "I_{\\NVar{\\nu}}\\left(\\NVar{z}\\right)",
    ref: "10.25#E2",
  },
  {
    name: "modified spherical Bessel function",
    notation: "{\\mathsf{i}^{(1)}_{\\NVar{n}}}\\left(\\NVar{z}\\right)",
    ref: "10.47#E7",
  },
  {
    name: "modified spherical Bessel function",
    notation: "{\\mathsf{i}^{(2)}_{\\NVar{n}}}\\left(\\NVar{z}\\right)",
    ref: "10.47#E8",
  },
  {
    name: "incomplete beta function",
    notation: "I_{\\NVar{x}}\\left(\\NVar{a},\\NVar{b}\\right)",
    ref: "8.17#E2",
  },
  {
    name: "idem function",
    notation:
      "\\operatorname{idem}\\left(\\NVar{\\chi_{1}};\\NVar{\\chi_{2},\\dots,\\chi_{n}}\\right)",
    ref: "17.1#p3",
  },
  {
    name: "modified Mathieu function",
    notation: "\\operatorname{Ie}_{\\NVar{n}}\\left(\\NVar{z},\\NVar{h}\\right)",
    ref: "28.20#E17",
  },
  {
    name: "repeated integrals of the complementary error function",
    notation: "\\mathop{\\mathrm{i}^{\\NVar{n}}\\mathrm{erfc}}\\left(\\NVar{z}\\right)",
    ref: "7.18#E2",
  },
  {
    name: "greatest lower bound (infimum)",
    notation: "\\inf",
    ref: "front/introduction#common.t1.r25",
  },
  {
    name: "inversion number",
    notation: "\\mathrm{inv}",
    ref: "26.14#i.p1",
  },
  {
    name: "inverse error function",
    notation: "\\operatorname{inverf}\\NVar{x}",
    ref: "7.17#E1",
  },
  {
    name: "inverse complementary error function",
    notation: "\\operatorname{inverfc}\\NVar{x}",
    ref: "7.17#E1",
  },
  {
    name: "modified Mathieu function",
    notation: "\\operatorname{Io}_{\\NVar{n}}\\left(\\NVar{z},\\NVar{h}\\right)",
    ref: "28.20#E18",
  },
  {
    name: "zeros of the Bessel function Jν(x)",
    notation: "j_{\\NVar{\\nu},\\NVar{m}}",
    ref: "10.2#E2",
  },
  {
    name: "zeros of the Bessel function derivative Jν′(x)",
    notation: "{j^{\\prime}_{\\NVar{\\nu},\\NVar{m}}}",
    ref: "10.2#E2",
  },
  {
    name: "Klein’s complete invariant",
    notation: "J\\left(\\NVar{\\tau}\\right)",
    ref: "23.15#E7",
  },
  {
    name: "Jordan’s function",
    notation: "J_{\\NVar{k}}\\left(\\NVar{n}\\right)",
    ref: "27.2#E11",
  },
  {
    name: "spherical Bessel function of the first kind",
    notation: "\\mathsf{j}_{\\NVar{n}}\\left(\\NVar{z}\\right)",
    ref: "10.47#E3",
  },
  {
    name: "Bessel function of imaginary order",
    notation: "\\widetilde{J}_{\\NVar{\\nu}}\\left(\\NVar{x}\\right)",
    ref: "10.24#Ex1",
  },
  {
    name: "Anger function",
    notation: "\\mathbf{J}_{\\NVar{\\nu}}\\left(\\NVar{z}\\right)",
    ref: "11.10#E1",
  },
  {
    name: "Bessel function of the first kind",
    notation: "J_{\\NVar{\\nu}}\\left(\\NVar{z}\\right)",
    ref: "10.2#E2",
  },
  {
    name: "Legendre’s complete elliptic integral of the first kind",
    notation: "K\\left(\\NVar{k}\\right)",
    ref: "19.2#E8",
  },
  {
    name: "Legendre’s complementary complete elliptic integral of the first kind",
    notation: "{K^{\\prime}}\\left(\\NVar{k}\\right)",
    ref: "19.2#E8_1",
  },
  {
    name: "modified spherical Bessel function",
    notation: "\\mathsf{k}_{\\NVar{n}}\\left(\\NVar{z}\\right)",
    ref: "10.47#E9",
  },
  {
    name: "modified Bessel function fo the second kind of imaginary order",
    notation: "\\widetilde{K}_{\\NVar{\\nu}}\\left(\\NVar{x}\\right)",
    ref: "10.45#E2",
  },
  {
    name: "modified Bessel function of the second kind",
    notation: "K_{\\NVar{\\nu}}\\left(\\NVar{z}\\right)",
    ref: "10.25#E3",
  },
  {
    name: "Struve function",
    notation: "\\mathbf{K}_{\\NVar{\\nu}}\\left(\\NVar{z}\\right)",
    ref: "11.2#E5",
  },
  {
    name: "Krawtchouk polynomial",
    notation: "K_{\\NVar{n}}\\left(\\NVar{x};\\NVar{p},\\NVar{N}\\right)",
    ref: "18.19#T1.t1.r3",
  },
  {
    name: "condition number",
    notation: "\\kappa(\\NVar{\\lambda})",
    ref: "3.2#v.p1",
  },
  {
    name: "modified Mathieu function",
    notation: "\\operatorname{Ke}_{\\NVar{n}}\\left(\\NVar{z},\\NVar{h}\\right)",
    ref: "28.20#E19",
  },
  {
    name: "Kelvin function",
    notation: "\\operatorname{kei}_{\\NVar{\\nu}}\\left(\\NVar{x}\\right)",
    ref: "10.61#E2",
  },
  {
    name: "Kelvin function",
    notation: "\\operatorname{ker}_{\\NVar{\\nu}}\\left(\\NVar{x}\\right)",
    ref: "10.61#E2",
  },
  {
    name: "Bickley function",
    notation: "\\operatorname{Ki}_{\\NVar{\\alpha}}\\left(\\NVar{x}\\right)",
    ref: "10.43#E11",
  },
  {
    name: "modified Mathieu function",
    notation: "\\operatorname{Ko}_{\\NVar{n}}\\left(\\NVar{z},\\NVar{h}\\right)",
    ref: "28.20#E20",
  },
  {
    name: "lattice in ℂ",
    notation: "\\mathbb{L}",
    ref: "front/introduction#common.t1.r1",
  },
  {
    name: "Lebesgue constant",
    notation: "L_{\\NVar{n}}",
    ref: "1.8#E8",
  },
  {
    name: "Lebesgue–Stieltjes measurable, square integrable, complex-valued functions",
    notation: "L^{2}\\left(\\NVar{X},\\NVar{\\,\\mathrm{d}x}\\right)",
    ref: "1.18#ii.p1",
  },
  {
    name: "Laguerre polynomial",
    notation: "L_{\\NVar{n}}\\left(\\NVar{x}\\right)=L^{(0)}_{n}\\left(x\\right)",
    ref: "18.1#I1.ix7.p1",
  },
  {
    name: "Laguerre function of matrix argument",
    notation: "L^{(\\NVar{\\gamma})}_{\\NVar{\\nu}}\\left(\\NVar{\\mathbf{T}}\\right)",
    ref: "35.6#E3",
  },
  {
    name: "modified Struve function",
    notation: "\\mathbf{L}_{\\NVar{\\nu}}\\left(\\NVar{z}\\right)",
    ref: "11.2#E2",
  },
  {
    name: "Laguerre (or generalized Laguerre) polynomial",
    notation: "L^{(\\NVar{\\alpha})}_{\\NVar{n}}\\left(\\NVar{x}\\right)",
    ref: "18.3#T1.t1.r12",
  },
  {
    name: "Laplace transform",
    notation: "\\mathscr{L}\\left(\\NVar{f}\\right)\\left(\\NVar{s}\\right)",
    ref: "1.14#E17",
  },
  {
    name: "Dirichlet L-function",
    notation: "L\\left(\\NVar{s},\\NVar{\\chi}\\right)",
    ref: "25.15#E1",
  },
  {
    name: "exceptional Laguerre polynomial",
    notation: "\\hat{L}^{(\\NVar{k})}_{\\NVar{n}}\\left(\\NVar{x}\\right)",
    ref: "18.36#E4",
  },
  {
    name: "q-Laguerre polynomial",
    notation: "L^{(\\NVar{\\alpha})}_{\\NVar{n}}\\left(\\NVar{x};\\NVar{q}\\right)",
    ref: "18.27#E15",
  },
  {
    name: "Liouville’s function",
    notation: "\\lambda\\left(\\NVar{n}\\right)",
    ref: "27.2#E13",
  },
  {
    name: "Mangoldt’s function",
    notation: "\\Lambda\\left(\\NVar{n}\\right)",
    ref: "27.2#E14",
  },
  {
    name: "alternative notation for eigenvalues of the spheroidal differential equation",
    notation:
      "\\lambda_{\\NVar{mn}}(\\NVar{\\gamma})=\\lambda^{m}_{n}\\left(\\gamma^{2}\\right)+%\n\\gamma^{2}",
    ref: "30.1#Px1.p1",
  },
  {
    name: "eigenvalues of Mathieu equation",
    notation: "\\lambda_{\\NVar{\\nu+2n}}\\left(\\NVar{q}\\right)",
    ref: "28.12#i.p2",
  },
  {
    name: "eigenvalues of the spheroidal differential equation",
    notation: "\\lambda^{\\NVar{m}}_{\\NVar{n}}\\left(\\NVar{\\gamma^{2}}\\right)",
    ref: "30.3#i.p1",
  },
  {
    name: "elliptic modular function",
    notation: "\\lambda\\left(\\NVar{\\tau}\\right)",
    ref: "23.15#E6",
  },
  {
    name: "logarithmic integral",
    notation: "\\operatorname{li}\\left(\\NVar{x}\\right)",
    ref: "6.2#E8",
  },
  {
    name: "dilogarithm",
    notation: "\\operatorname{Li}_{2}\\left(\\NVar{z}\\right)",
    ref: "25.12#E1",
  },
  {
    name: "polylogarithm",
    notation: "\\operatorname{Li}_{\\NVar{s}}\\left(\\NVar{z}\\right)",
    ref: "25.12#E10",
  },
  {
    name: "least limit point",
    notation: "\\liminf",
    ref: "front/introduction#common.t2.r4",
  },
  {
    name: "general logarithm function",
    notation: "\\operatorname{Ln}\\NVar{z}",
    ref: "4.2#E1",
  },
  {
    name: "principal branch of logarithm function",
    notation: "\\ln\\NVar{z}",
    ref: "4.2#E2",
  },
  {
    name: "common logarithm",
    notation: "\\operatorname{log}_{10}\\NVar{z}",
    ref: "4.2#ii.p2",
  },
  {
    name: "logarithm to general base",
    notation: "\\operatorname{log}_{\\NVar{a}}\\NVar{z}",
    ref: "4.2#EGx1",
  },
  {
    name: "mass of electron",
    notation: "m_{e}",
    ref: "18.39#Px5",
  },
  {
    name: "Motzkin number",
    notation: "M(\\NVar{n})",
    ref: "26.6#E2",
  },
  {
    name: "Mills’ ratio",
    notation: "\\mathsf{M}\\left(\\NVar{x}\\right)",
    ref: "7.8#E1",
  },
  {
    name: "Airy modulus function",
    notation: "M\\left(\\NVar{z}\\right)",
    ref: "9.8#E3",
  },
  {
    name: "Whittaker confluent hypergeometric function",
    notation: "M_{\\NVar{\\kappa},\\NVar{\\mu}}\\left(\\NVar{z}\\right)",
    ref: "13.14#E2",
  },
  {
    name: "modulus of Bessel functions",
    notation: "M_{\\NVar{\\nu}}\\left(\\NVar{x}\\right)",
    ref: "10.18#E1",
  },
  {
    name: "modified Struve function",
    notation: "\\mathbf{M}_{\\NVar{\\nu}}\\left(\\NVar{z}\\right)",
    ref: "11.2#E6",
  },
  {
    name: "arithmetic-geometric mean",
    notation: "M\\left(\\NVar{a},\\NVar{g}\\right)",
    ref: "19.8#i.p1",
  },
  {
    name: "Mellin transform",
    notation: "\\mathscr{M}\\left(\\NVar{f}\\right)\\left(\\NVar{s}\\right)",
    ref: "1.14#E32",
  },
  {
    name: "envelope of Coulomb functions",
    notation: "M_{\\NVar{\\ell}}\\left(\\NVar{\\eta},\\NVar{\\rho}\\right)",
    ref: "33.3#E1",
  },
  {
    name: "modified Mathieu function",
    notation: "{\\operatorname{M}^{(\\NVar{j})}_{\\NVar{\\nu}}}\\left(\\NVar{z},\\NVar{h}\\right)",
    ref: "28.20#iii.p1",
  },
  {
    name: "=F11(a",
    notation: "M\\left(\\NVar{a},\\NVar{b},\\NVar{z}\\right)",
    ref: "16.2",
  },
  {
    name: "Olver’s confluent hypergeometric function",
    notation: "{\\mathbf{M}}\\left(\\NVar{a},\\NVar{b},\\NVar{z}\\right)",
    ref: "13.2#E3",
  },
  {
    name: "Meixner polynomial",
    notation: "M_{\\NVar{n}}\\left(\\NVar{x};\\NVar{\\beta},\\NVar{c}\\right)",
    ref: "18.19#T1.t1.r4",
  },
  {
    name: "major index",
    notation: "\\mathrm{maj}",
    ref: "26.14#i.p2",
  },
  {
    name: "radial Mathieu function",
    notation: "{\\operatorname{Mc}^{(\\NVar{j})}_{\\NVar{n}}}\\left(\\NVar{z},\\NVar{h}\\right)",
    ref: "28.20#E15",
  },
  {
    name: "Mathieu function",
    notation: "\\operatorname{me}_{\\NVar{n}}\\left(\\NVar{z},\\NVar{q}\\right)",
    ref: "28.12#ii.p2",
  },
  {
    name: "Mathieu function of noninteger order",
    notation: "\\operatorname{me}_{\\NVar{\\nu}}\\left(\\NVar{z},\\NVar{q}\\right)",
    ref: "28.12#ii.p1",
  },
  {
    name: "modified Mathieu function",
    notation: "\\operatorname{Me}_{\\NVar{\\nu}}\\left(\\NVar{z},\\NVar{q}\\right)",
    ref: "28.20#E5",
  },
  {
    name: "modulo",
    notation: "\\mod",
    ref: "front/introduction#common.t2.r10",
  },
  {
    name: "radial Mathieu function",
    notation: "{\\operatorname{Ms}^{(\\NVar{j})}_{\\NVar{n}}}\\left(\\NVar{z},\\NVar{h}\\right)",
    ref: "28.20#E16",
  },
  {
    name: "Möbius function",
    notation: "\\mu\\left(\\NVar{n}\\right)",
    ref: "27.2#E12",
  },
  {
    name: "intersection",
    notation: "\\cap",
    ref: "front/introduction#common.t1.r27",
  },
  {
    name: "set of all positive integers",
    notation: "\\mathbb{N}",
    ref: "front/introduction#common.t2.r11",
  },
  {
    name: "winding number",
    notation: "\\mathcal{N}",
    ref: "1.9#E32",
  },
  {
    name: "Airy modulus function",
    notation: "N\\left(\\NVar{z}\\right)",
    ref: "9.8#E7",
  },
  {
    name: "modulus of derivatives of Bessel functions",
    notation: "N_{\\NVar{\\nu}}\\left(\\NVar{x}\\right)",
    ref: "10.18#E2",
  },
  {
    name: "common alternative notation",
    notation: "N_{\\NVar{\\nu}}(\\NVar{z})=Y_{\\nu}\\left(z\\right)",
    ref: "10.1#p4",
  },
  {
    name: "Narayana number",
    notation: "N(\\NVar{n},\\NVar{k})",
    ref: "26.6#E3",
  },
  {
    name: "backward difference",
    notation: "\\nabla_{\\NVar{x}}",
    ref: "18.1#EGx2",
  },
  {
    name: "Jacobian elliptic function",
    notation: "\\operatorname{nc}\\left(\\NVar{z},\\NVar{k}\\right)",
    ref: "22.2#E5",
  },
  {
    name: "Jacobian elliptic function",
    notation: "\\operatorname{nd}\\left(\\NVar{z},\\NVar{k}\\right)",
    ref: "22.2#E6",
  },
  {
    name: "Jacobian elliptic function",
    notation: "\\operatorname{ns}\\left(\\NVar{z},\\NVar{k}\\right)",
    ref: "22.2#E4",
  },
  {
    name: "number of distinct primes dividing a number",
    notation: "\\nu\\left(\\NVar{n}\\right)",
    ref: "27.2#i.p1",
  },
  {
    name: "order not exceeding",
    notation: "O\\left(\\NVar{x}\\right)",
    ref: "2.1#E3",
  },
  {
    name: "order less than",
    notation: "o\\left(\\NVar{x}\\right)",
    ref: "2.1#E2",
  },
  {
    name: "Neumann’s polynomial",
    notation: "O_{\\NVar{n}}\\left(\\NVar{x}\\right)",
    ref: "10.23#E12",
  },
  {
    name: "Wright ω-function",
    notation: "\\omega\\left(\\NVar{z}\\right)",
    ref: "4.13#p4",
  },
  {
    name: "Painlevé transcendents",
    notation: "\\mbox{P}_{\\mbox{\\scriptsize I}}",
    ref: "32.2#i.p3",
  },
  {
    name: "total number of partitions of n into at most k parts",
    notation: "p_{\\NVar{k}}\\left(\\NVar{n}\\right)",
    ref: "26.9#i.p1",
  },
  {
    name: "alternative notation for the complementary error function",
    notation: "P(\\NVar{z})=\\tfrac{1}{2}\\operatorname{erfc}\\left(-z/\\sqrt{2}\\right)",
    ref: "7.1#p4",
  },
  {
    name: "number of partitions of n into at most k parts",
    notation: "p_{\\NVar{k}}\\left(\\NVar{n}\\right)",
    ref: "26.9#i.p1",
  },
  {
    name: "Legendre polynomial",
    notation: "P_{\\NVar{n}}\\left(\\NVar{x}\\right)",
    ref: "18.3#T1.t1.r10",
  },
  {
    name: "shifted Legendre polynomial",
    notation: "P^{*}_{\\NVar{n}}\\left(\\NVar{x}\\right)",
    ref: "18.3#T1.t1.r11",
  },
  {
    name: "Ferrers function of the first kind",
    notation:
      "\\mathsf{P}_{\\NVar{\\nu}}\\left(\\NVar{x}\\right)=\\mathsf{P}^{0}_{\\nu}\\left(x\\right)",
    ref: "14.2#ii.p2",
  },
  {
    name: "Legendre function of the first kind",
    notation: "P_{\\NVar{\\nu}}\\left(\\NVar{z}\\right)=P^{0}_{\\nu}\\left(z\\right)",
    ref: "14.2#ii.p2",
  },
  {
    name: "conical function",
    notation: "\\mathsf{P}^{-\\NVar{\\mu}}_{\\NVar{-\\frac{1}{2}+i\\tau}}\\left(\\NVar{x}\\right)",
    ref: "14.20#i.p1",
  },
  {
    name: "Jacobi polynomial",
    notation: "P^{(\\NVar{\\alpha},\\NVar{\\beta})}_{\\NVar{n}}\\left(\\NVar{x}\\right)",
    ref: "18.3#T1.t1.r2",
  },
  {
    name: "Jacobi function of matrix argument",
    notation:
      "P^{(\\NVar{\\gamma},\\NVar{\\delta})}_{\\NVar{\\nu}}\\left(\\NVar{\\mathbf{T}}\\right)",
    ref: "35.7#E2",
  },
  {
    name: "Ferrers function of the first kind",
    notation: "\\mathsf{P}^{\\NVar{\\mu}}_{\\NVar{\\nu}}\\left(\\NVar{x}\\right)",
    ref: "14.3#E1",
  },
  {
    name: "associated Legendre function of the first kind",
    notation: "P^{\\NVar{\\mu}}_{\\NVar{\\nu}}\\left(\\NVar{z}\\right)",
    ref: "14.21#i.p1",
  },
  {
    name: "normalized incomplete gamma function",
    notation: "P\\left(\\NVar{a},\\NVar{z}\\right)",
    ref: "8.2#E4",
  },
  {
    name: "restricted number of partitions of n",
    notation: "p\\left(\\NVar{\\mathrm{condition}},\\NVar{n}\\right)",
    ref: "26.10#i",
  },
  {
    name: "Weierstrass ℘-function",
    notation: "\\wp\\left(\\NVar{z}\\right)",
    ref: "23.2#E4",
  },
  {
    name: "number of partitions of n into at most k parts, each less than or equal to m",
    notation: "p_{\\NVar{k}}\\left(\\leq\\NVar{m},\\NVar{n}\\right)",
    ref: "26.9#i",
  },
  {
    name: "number of partitions of n into at most k distinct parts",
    notation: "p_{\\NVar{k}}\\left(\\NVar{\\mathcal{D}},\\NVar{n}\\right)",
    ref: "26.10#i",
  },
  {
    name: "associated Hermite polynomial",
    notation: "H_{\\NVar{n}}\\left(\\NVar{x};\\NVar{c}\\right)",
    ref: "18.30#iv.p1",
  },
  {
    name: "associated Legendre polynomial",
    notation: "P_{\\NVar{n}}\\left(\\NVar{x};\\NVar{c}\\right)",
    ref: "18.30#E6",
  },
  {
    name: "associated Meixner–Pollaczek polynomial",
    notation:
      "{\\mathscr{P}}^{\\NVar{\\lambda}}_{\\NVar{n}}\\left(\\NVar{x};\\NVar{\\phi},\\NVar{c}\\right)",
    ref: "18.30#v.p1",
  },
  {
    name: "Meixner–Pollaczek polynomial",
    notation: "P^{(\\NVar{\\lambda})}_{\\NVar{n}}\\left(\\NVar{x};\\NVar{\\phi}\\right)",
    ref: "18.19#Px3.p1",
  },
  {
    name: "triangle polynomial",
    notation:
      "P^{\\NVar{\\alpha},\\NVar{\\beta},\\NVar{\\gamma}}_{\\NVar{m},\\NVar{n}}\\left(\\NVar{x}%\n,\\NVar{y}\\right)",
    ref: "18.37#E7",
  },
  {
    name: "associated Jacobi polynomial",
    notation: "P^{(\\NVar{\\alpha},\\NVar{\\beta})}_{\\NVar{n}}\\left(\\NVar{x};\\NVar{c}\\right)",
    ref: "18.30#E4",
  },
  {
    name: "Weierstrass ℘-function",
    notation: "\\wp\\left(\\NVar{z};\\NVar{g_{2}},\\NVar{g_{3}}\\right)",
    ref: "23.3#E8",
  },
  {
    name: "Pollaczek polynomial",
    notation: "P^{(\\NVar{\\lambda})}_{\\NVar{n}}\\left(\\NVar{x};\\NVar{a},\\NVar{b}\\right)",
    ref: "18.35#E4",
  },
  {
    name: "little q-Jacobi polynomial",
    notation: "p_{\\NVar{n}}\\left(\\NVar{x};\\NVar{a},\\NVar{b};\\NVar{q}\\right)",
    ref: "18.27#E13",
  },
  {
    name: "big q-Jacobi polynomial",
    notation:
      "P^{(\\NVar{\\alpha},\\NVar{\\beta})}_{\\NVar{n}}\\left(\\NVar{x};\\NVar{c},\\NVar{d};%\n\\NVar{q}\\right)",
    ref: "18.27#E6",
  },
  {
    name: "continuous Hahn polynomial",
    notation:
      "p_{\\NVar{n}}\\left(\\NVar{x};\\NVar{a},\\NVar{b},\\NVar{\\overline{a}},\\NVar{%\n\\overline{b}}\\right)",
    ref: "18.19#Px2.p1",
  },
  {
    name: "big q-Jacobi polynomial",
    notation: "P_{\\NVar{n}}\\left(\\NVar{x};\\NVar{a},\\NVar{b},\\NVar{c};\\NVar{q}\\right)",
    ref: "18.27#E5",
  },
  {
    name: "Askey–Wilson polynomial",
    notation:
      "p_{\\NVar{n}}\\left(\\NVar{x};\\NVar{a},\\NVar{b},\\NVar{c},\\NVar{d}\\,|\\,\\NVar{q}\\right)",
    ref: "18.28#E1",
  },
  {
    name: "Riemann’s P-symbol for solutions of the generalized hypergeometric differential equation",
    notation:
      "P\\NVar{\\begin{Bmatrix}\\alpha&\\beta&\\gamma&\\\\\na_{1}&b_{1}&c_{1}&z\\\\\na_{2}&b_{2}&c_{2}&\\end{Bmatrix}}",
    ref: "15.11#E3",
  },
  {
    name: "phase",
    notation: "\\operatorname{ph}",
    ref: "1.9#E7",
  },
  {
    name: "Euler’s totient",
    notation: "\\phi\\left(\\NVar{n}\\right)",
    ref: "27.2#E7",
  },
  {
    name: "Airy phase function",
    notation: "\\phi\\left(\\NVar{z}\\right)",
    ref: "9.8#E8",
  },
  {
    name: "alternative notation for the complementary error function",
    notation: "\\Phi(\\NVar{z})=\\tfrac{1}{2}\\operatorname{erfc}\\left(-z/\\sqrt{2}\\right)",
    ref: "7.1#p4",
  },
  {
    name: "sum of powers of integers relatively prime to a number",
    notation: "\\phi_{\\NVar{k}}\\left(\\NVar{n}\\right)",
    ref: "27.2#E6",
  },
  {
    name: "phase of derivatives of Bessel functions",
    notation: "\\phi_{\\NVar{\\nu}}\\left(\\NVar{x}\\right)",
    ref: "10.18#E3",
  },
  {
    name: "Jacobi function",
    notation: "\\phi^{(\\NVar{\\alpha},\\NVar{\\beta})}_{\\NVar{\\lambda}}\\left(\\NVar{t}\\right)",
    ref: "15.9#E11",
  },
  {
    name: "combined theta function",
    notation: "\\varphi_{\\NVar{n},\\NVar{m}}\\left(\\NVar{z},\\NVar{q}\\right)",
    ref: "20.11#v.p2",
  },
  {
    name: "cuspoid catastrophe of codimension K",
    notation: "\\Phi_{\\NVar{K}}\\left(\\NVar{t};\\NVar{\\mathbf{x}}\\right)",
    ref: "36.2#E1",
  },
  {
    name: "generalized Bessel function",
    notation: "\\phi\\left(\\NVar{\\rho},\\NVar{\\beta};\\NVar{z}\\right)",
    ref: "10.46#E1",
  },
  {
    name: "Lerch’s transcendent",
    notation: "\\Phi\\left(\\NVar{z},\\NVar{s},\\NVar{a}\\right)",
    ref: "25.14#E1",
  },
  {
    name: "elliptic umbilic catastrophe",
    notation: "\\Phi^{(\\mathrm{E})}\\left(\\NVar{s},\\NVar{t};\\NVar{\\mathbf{x}}\\right)",
    ref: "36.2#E2",
  },
  {
    name: "hyperbolic umbilic catastrophe",
    notation: "\\Phi^{(\\mathrm{H})}\\left(\\NVar{s},\\NVar{t};\\NVar{\\mathbf{x}}\\right)",
    ref: "36.2#E3",
  },
  {
    name: "elliptic umbilic catastrophe for U=E or K",
    notation: "\\Phi^{(\\mathrm{U})}\\left(\\NVar{s},\\NVar{t};\\NVar{\\mathbf{x}}\\right)",
    ref: "36.2#Px2",
  },
  {
    name: "first q-Appell function",
    notation:
      "\\Phi^{(1)}\\left(\\NVar{a};\\NVar{b},\\NVar{b^{\\prime}};\\NVar{c};\\NVar{q};\\NVar{x}%\n,\\NVar{y}\\right)",
    ref: "17.4#E5",
  },
  {
    name: "second q-Appell function",
    notation:
      "\\Phi^{(2)}\\left(\\NVar{a};\\NVar{b},\\NVar{b^{\\prime}};\\NVar{c},\\NVar{c^{\\prime}}%\n;\\NVar{q};\\NVar{x},\\NVar{y}\\right)",
    ref: "17.4#E6",
  },
  {
    name: "third q-Appell function",
    notation:
      "\\Phi^{(3)}\\left(\\NVar{a},\\NVar{a^{\\prime}};\\NVar{b},\\NVar{b^{\\prime}};\\NVar{c}%\n;\\NVar{q};\\NVar{x},\\NVar{y}\\right)",
    ref: "17.4#E7",
  },
  {
    name: "fourth q-Appell function",
    notation:
      "\\Phi^{(4)}\\left(\\NVar{a},\\NVar{b};\\NVar{c},\\NVar{c^{\\prime}};\\NVar{q};\\NVar{x}%\n,\\NVar{y}\\right)",
    ref: "17.4#E8",
  },
  {
    name: "basic hypergeometric (or q-hypergeometric) function",
    notation:
      "{{}_{\\NVar{r+1}}\\phi_{\\NVar{s}}}\\left(\\NVar{a_{0},\\dots,a_{r}};\\NVar{b_{1},%\n\\dots,b_{s}};\\NVar{q},\\NVar{z}\\right)",
    ref: "17.4#E1",
  },
  {
    name: "the ratio of the circumference of a circle to its diameter",
    notation: "\\pi",
    ref: "3.12#E1",
  },
  {
    name: "set of plane partitions",
    notation: "\\pi",
    ref: "26.12#i.p1",
  },
  {
    name: "number of primes not exceeding a number",
    notation: "\\pi\\left(\\NVar{x}\\right)",
    ref: "27.2#E2",
  },
  {
    name: "notation used by Gauss",
    notation: "\\Pi(\\NVar{z-1})=\\Gamma\\left(z\\right)",
    ref: "5.1#p4",
  },
  {
    name: "Legendre’s complete elliptic integral of the third kind",
    notation: "\\Pi\\left(\\NVar{\\alpha}^{2},\\NVar{k}\\right)",
    ref: "19.2#E8",
  },
  {
    name: "Legendre’s incomplete elliptic integral of the third kind",
    notation: "\\Pi\\left(\\NVar{\\phi},\\NVar{\\alpha}^{2},\\NVar{k}\\right)",
    ref: "19.2#E7",
  },
  {
    name: "number of plane partitions of n",
    notation: "\\operatorname{pp}\\left(\\NVar{n}\\right)",
    ref: "26.12#i.p4",
  },
  {
    name: "generic Jacobian elliptic function",
    notation: "\\operatorname{pq}\\left(\\NVar{z},\\NVar{k}\\right)",
    ref: "22.2#E10",
  },
  {
    name: "spheroidal wave function of the first kind",
    notation: "\\mathsf{Ps}^{\\NVar{m}}_{\\NVar{n}}\\left(\\NVar{x},\\NVar{\\gamma^{2}}\\right)",
    ref: "30.4#i",
  },
  {
    name: "spheroidal wave function of complex argument",
    notation: "\\mathit{Ps}^{\\NVar{m}}_{\\NVar{n}}\\left(\\NVar{z},\\NVar{\\gamma^{2}}\\right)",
    ref: "30.6#p1",
  },
  {
    name: "Chebyshev ψ-function",
    notation: "\\psi\\left(\\NVar{x}\\right)",
    ref: "25.16#E1",
  },
  {
    name: "psi (or digamma) function",
    notation: "\\psi\\left(\\NVar{z}\\right)",
    ref: "5.2#E2",
  },
  {
    name: "canonical integral function",
    notation: "\\Psi_{\\NVar{K}}\\left(\\NVar{\\mathbf{x}}\\right)",
    ref: "36.2#E4",
  },
  {
    name: "Pearcey integral",
    notation: "\\Psi_{2}\\left(\\NVar{\\mathbf{x}}\\right)",
    ref: "36.2#E14",
  },
  {
    name: "elliptic umbilic canonical integral function",
    notation: "\\Psi^{(\\mathrm{E})}\\left(\\NVar{\\mathbf{x}}\\right)",
    ref: "36.2#E5",
  },
  {
    name: "hyperbolic umbilic canonical integral function",
    notation: "\\Psi^{(\\mathrm{H})}\\left(\\NVar{\\mathbf{x}}\\right)",
    ref: "36.2#E5",
  },
  {
    name: "polygamma functions",
    notation: "\\psi^{(\\NVar{n})}\\left(\\NVar{z}\\right)",
    ref: "5.15",
  },
  {
    name: "umbilic canonical integral function",
    notation: "\\Psi^{(\\mathrm{U})}\\left(\\NVar{\\mathbf{x}}\\right)",
    ref: "36.2#E5",
  },
  {
    name: "diffraction catastrophe",
    notation: "\\Psi_{\\NVar{K}}(\\NVar{\\mathbf{x}};k)",
    ref: "36.2#E10",
  },
  {
    name: "elliptic umbilic canonical integral function",
    notation: "\\Psi^{(\\mathrm{E})}(\\NVar{\\mathbf{x}};\\NVar{k})",
    ref: "36.2#E11",
  },
  {
    name: "hyperbolic umbilic canonical integral function",
    notation: "\\Psi^{(\\mathrm{H})}(\\NVar{\\mathbf{x}};\\NVar{k})",
    ref: "36.2#E11",
  },
  {
    name: "umbilic canonical integral function",
    notation: "\\Psi^{(\\mathrm{U})}(\\NVar{\\mathbf{x}};\\NVar{k})",
    ref: "36.2#E11",
  },
  {
    name: "confluent hypergeometric function of matrix argument (second kind)",
    notation: "\\Psi\\left(\\NVar{a};\\NVar{b};\\NVar{\\mathbf{T}}\\right)",
    ref: "35.6#E2",
  },
  {
    name: "bilateral basic hypergeometric (or bilateral q-hypergeometric) function",
    notation:
      "{{}_{\\NVar{r}}\\psi_{\\NVar{s}}}\\left(\\NVar{a_{1},\\dots,a_{r}};\\NVar{b_{1},\\dots%\n,b_{s}};\\NVar{q},\\NVar{z}\\right)",
    ref: "17.4#E3",
  },
  {
    name: "set of all rational numbers",
    notation: "\\mathbb{Q}",
    ref: "front/introduction#common.t2.r13",
  },
  {
    name: "alternative notation for the complementary error function",
    notation: "Q(\\NVar{z})=\\tfrac{1}{2}\\operatorname{erfc}\\left(z/\\sqrt{2}\\right)",
    ref: "7.1#p4",
  },
  {
    name: "Ferrers function of the second kind",
    notation:
      "\\mathsf{Q}_{\\NVar{\\nu}}\\left(\\NVar{x}\\right)=\\mathsf{Q}^{0}_{\\nu}\\left(x\\right)",
    ref: "14.2#ii.p2",
  },
  {
    name: "Olver’s associated Legendre function",
    notation:
      "\\boldsymbol{Q}_{\\NVar{\\nu}}\\left(\\NVar{z}\\right)=\\boldsymbol{Q}^{0}_{\\nu}\\left%\n(z\\right)",
    ref: "14.2#ii.p2",
  },
  {
    name: "conical function",
    notation:
      "\\widehat{\\mathsf{Q}}^{-\\NVar{\\mu}}_{\\NVar{-\\frac{1}{2}+i\\tau}}\\left(\\NVar{x}\\right)",
    ref: "14.20#E2",
  },
  {
    name: "Ferrers function of the second kind",
    notation: "\\mathsf{Q}^{\\NVar{\\mu}}_{\\NVar{\\nu}}\\left(\\NVar{x}\\right)",
    ref: "14.3#E2",
  },
  {
    name: "associated Legendre function of the second kind",
    notation: "Q^{\\NVar{\\mu}}_{\\NVar{\\nu}}\\left(\\NVar{z}\\right)",
    ref: "14.21#i.p1",
  },
  {
    name: "Olver’s associated Legendre function",
    notation: "\\boldsymbol{Q}^{\\NVar{\\mu}}_{\\NVar{\\nu}}\\left(\\NVar{z}\\right)",
    ref: "14.21#i.p1",
  },
  {
    name: "normalized incomplete gamma function",
    notation: "Q\\left(\\NVar{a},\\NVar{z}\\right)",
    ref: "8.2#E4",
  },
  {
    name: "Pollaczek polynomial",
    notation:
      "{Q}^{{(\\NVar{\\lambda})}}_{\\NVar{n}}\\left(\\NVar{x};\\NVar{a},\\NVar{b},\\NVar{c}\\right)",
    ref: "18.35#E2_2",
  },
  {
    name: "q−1-Al-Salam–Chihara polynomial",
    notation: "Q_{\\NVar{n}}\\left(\\NVar{x};\\NVar{a},\\NVar{b}\\,|\\,\\NVar{q}^{-1}\\right)",
    ref: "18.28#E9",
  },
  {
    name: "Hahn polynomial",
    notation: "Q_{\\NVar{n}}\\left(\\NVar{x};\\NVar{\\alpha},\\NVar{\\beta},\\NVar{N}\\right)",
    ref: "18.19#T1.t1.r2",
  },
  {
    name: "q-Hahn polynomial",
    notation:
      "Q_{\\NVar{n}}\\left(\\NVar{x};\\NVar{\\alpha},\\NVar{\\beta},\\NVar{N};\\NVar{q}\\right)",
    ref: "18.27#E3",
  },
  {
    name: "spheroidal wave function of the second kind",
    notation: "\\mathsf{Qs}^{\\NVar{m}}_{\\NVar{n}}\\left(\\NVar{x},\\NVar{\\gamma^{2}}\\right)",
    ref: "30.5",
  },
  {
    name: "spheroidal wave function of complex argument",
    notation: "\\mathit{Qs}^{\\NVar{m}}_{\\NVar{n}}\\left(\\NVar{z},\\NVar{\\gamma^{2}}\\right)",
    ref: "30.6#p1",
  },
  {
    name: "real line",
    notation: "\\mathbb{R}",
    ref: "front/introduction#common.t2.r14",
  },
  {
    name: "real part",
    notation: "\\Re",
    ref: "1.9#E2",
  },
  {
    name: "Schröder number",
    notation: "r(\\NVar{n})",
    ref: "26.6#E4",
  },
  {
    name: "number of squares",
    notation: "r_{\\NVar{k}}\\left(\\NVar{n}\\right)",
    ref: "27.13#iv.p1",
  },
  {
    name: "disk polynomial",
    notation: "R^{(\\NVar{\\alpha})}_{\\NVar{m},\\NVar{n}}\\left(\\NVar{z}\\right)",
    ref: "18.37#E1",
  },
  {
    name: "outer turning point for Coulomb functions",
    notation: "r_{\\operatorname{tp}}\\left(\\NVar{\\epsilon},\\NVar{\\ell}\\right)",
    ref: "33.14#E3",
  },
  {
    name: "outer turning point for Coulomb radial functions",
    notation: "\\rho_{\\operatorname{tp}}\\left(\\NVar{\\eta},\\NVar{\\ell}\\right)",
    ref: "33.2#E2",
  },
  {
    name: "multivariate hypergeometric function",
    notation:
      "R_{\\NVar{-a}}\\left(\\NVar{b_{1}},\\dots,\\NVar{b_{n}};\\NVar{z_{1}},\\dots,\\NVar{z_%\n{n}}\\right)",
    ref: "19.16#E9",
  },
  {
    name: "alternative notation for the radial spheroidal wave function",
    notation:
      "R_{\\NVar{mn}}^{(\\NVar{j})}(\\NVar{\\gamma},\\NVar{z})=S^{m(j)}_{n}\\left(z,\\gamma\\right)",
    ref: "30.1#Px1.p1",
  },
  {
    name: "alternative notation",
    notation:
      "R(\\NVar{a};\\NVar{\\mathbf{b}};\\NVar{\\mathbf{z}})=R_{-a}\\left(\\mathbf{b};\\mathbf%\n{z}\\right)",
    ref: "19.16#ii.p1",
  },
  {
    name: "dual Hahn polynomial",
    notation: "R_{\\NVar{n}}\\left(\\NVar{x};\\NVar{\\gamma},\\NVar{\\delta},\\NVar{N}\\right)",
    ref: "18.25#T1.t1.r5",
  },
  {
    name: "Racah polynomial",
    notation:
      "R_{\\NVar{n}}\\left(\\NVar{x};\\NVar{\\alpha},\\NVar{\\beta},\\NVar{\\gamma},\\NVar{%\n\\delta}\\right)",
    ref: "18.25#T1.t1.r4",
  },
  {
    name: "q-Racah polynomial",
    notation:
      "R_{\\NVar{n}}\\left(\\NVar{x};\\NVar{\\alpha},\\NVar{\\beta},\\NVar{\\gamma},\\NVar{%\n\\delta}\\,|\\,\\NVar{q}\\right)",
    ref: "18.28#E19",
  },
  {
    name: "Carlson’s combination of inverse circular and inverse hyperbolic functions",
    notation: "R_{C}\\left(\\NVar{x},\\NVar{y}\\right)",
    ref: "19.2#E17",
  },
  {
    name: "elliptic integral symmetric in only two variables",
    notation: "R_{D}\\left(\\NVar{x},\\NVar{y},\\NVar{z}\\right)",
    ref: "19.16#E5",
  },
  {
    name: "residue",
    notation: "\\Residue",
    ref: "1.10#iii.p5",
  },
  {
    name: "symmetric elliptic integral of first kind",
    notation: "R_{F}\\left(\\NVar{x},\\NVar{y},\\NVar{z}\\right)",
    ref: "19.16#E1",
  },
  {
    name: "symmetric elliptic integral of second kind",
    notation: "R_{G}\\left(\\NVar{x},\\NVar{y},\\NVar{z}\\right)",
    ref: "19.16#E2_5",
  },
  {
    name: "symmetric elliptic integral of third kind",
    notation: "R_{J}\\left(\\NVar{x},\\NVar{y},\\NVar{z},\\NVar{p}\\right)",
    ref: "19.16#E2",
  },
  {
    name: "set of permutations of {1,2,…,n}",
    notation: "\\mathfrak{S}_{\\NVar{n}}",
    ref: "26.13#p1",
  },
  {
    name: "Fresnel integral",
    notation: "S\\left(\\NVar{z}\\right)",
    ref: "7.2#E8",
  },
  {
    name: "alternative notation for the Fresnel integral",
    notation: "S_{1}(\\NVar{z})=S\\left(\\sqrt{2/\\pi}z\\right)",
    ref: "7.1#p4",
  },
  {
    name: "alternative notation for the Fresnel integral",
    notation: "S_{2}(\\NVar{z})=S\\left(\\sqrt{2z/\\pi}\\right)",
    ref: "7.1#p4",
  },
  {
    name: "Lommel function",
    notation: "S_{{\\NVar{\\mu}},{\\NVar{\\nu}}}\\left(\\NVar{z}\\right)",
    ref: "11.9#E5",
  },
  {
    name: "Lommel function",
    notation: "s_{{\\NVar{\\mu}},{\\NVar{\\nu}}}\\left(\\NVar{z}\\right)",
    ref: "11.9#E3",
  },
  {
    name: "dilated Chebyshev polynomial",
    notation: "S_{\\NVar{n}}\\left(\\NVar{x}\\right)",
    ref: "18.1#E3",
  },
  {
    name: "Stieltjes transform",
    notation: "\\mathcal{S}\\left(\\NVar{f}\\right)\\left(\\NVar{s}\\right)",
    ref: "1.14#E47",
  },
  {
    name: "Stirling number of the first kind",
    notation: "s\\left(\\NVar{n},\\NVar{k}\\right)",
    ref: "26.8#i.p1",
  },
  {
    name: "Stirling number of the second kind",
    notation: "S\\left(\\NVar{n},\\NVar{k}\\right)",
    ref: "26.8#i.p3",
  },
  {
    name: "radial spheroidal wave function",
    notation: "S^{\\NVar{m}(\\NVar{j})}_{\\NVar{n}}\\left(\\NVar{z},\\NVar{\\gamma}\\right)",
    ref: "30.11#E3",
  },
  {
    name: "alternative notation for the spheroidal wave function of the first kind",
    notation:
      "S^{(1)}_{\\NVar{mn}}(\\NVar{\\gamma},\\NVar{x})\\propto\\mathsf{Ps}^{m}_{n}\\left(x,%\n\\gamma^{2}\\right)",
    ref: "30.1#Px1.p1",
  },
  {
    name: "alternative notation for the spheroidal wave function of the second kind",
    notation:
      "S^{(2)}_{\\NVar{mn}}(\\NVar{\\gamma},\\NVar{x})\\propto\\mathsf{Qs}^{m}_{n}\\left(x,%\n\\gamma^{2}\\right)",
    ref: "30.1#Px1.p1",
  },
  {
    name: "Ince polynomials",
    notation: "S_{\\NVar{n}}^{\\NVar{m}}(\\NVar{z},\\NVar{\\xi})",
    ref: "28.31#ii.p4",
  },
  {
    name: "Stieltjes–Wigert polynomial",
    notation: "S_{\\NVar{n}}\\left(\\NVar{x};\\NVar{q}\\right)",
    ref: "18.27#E18",
  },
  {
    name: "regular Coulomb function",
    notation: "s\\left(\\NVar{\\epsilon},\\NVar{\\ell};\\NVar{r}\\right)",
    ref: "33.14#E9",
  },
  {
    name: "Sinc function",
    notation: "S(\\NVar{k},\\NVar{h})(\\NVar{x})",
    ref: "3.3#vi.p2",
  },
  {
    name: "continuous dual Hahn polynomial",
    notation: "S_{\\NVar{n}}\\left(\\NVar{x};\\NVar{a},\\NVar{b},\\NVar{c}\\right)",
    ref: "18.25#T1.t1.r3",
  },
  {
    name: "Jacobian elliptic function",
    notation: "\\operatorname{sc}\\left(\\NVar{z},\\NVar{k}\\right)",
    ref: "22.2#E9",
  },
  {
    name: "Lamé polynomial",
    notation: "\\mathit{scdE}^{\\NVar{m}}_{2\\NVar{n}+3}\\left(\\NVar{z},\\NVar{k^{2}}\\right)",
    ref: "29.12#E8",
  },
  {
    name: "Lamé polynomial",
    notation: "\\mathit{scE}^{\\NVar{m}}_{2\\NVar{n}+2}\\left(\\NVar{z},\\NVar{k^{2}}\\right)",
    ref: "29.12#E5",
  },
  {
    name: "Jacobian elliptic function",
    notation: "\\operatorname{sd}\\left(\\NVar{z},\\NVar{k}\\right)",
    ref: "22.2#E7",
  },
  {
    name: "Lamé polynomial",
    notation: "\\mathit{sdE}^{\\NVar{m}}_{2\\NVar{n}+2}\\left(\\NVar{z},\\NVar{k^{2}}\\right)",
    ref: "29.12#E6",
  },
  {
    name: "Mathieu function",
    notation: "\\operatorname{se}_{\\NVar{n}}\\left(\\NVar{z},\\NVar{q}\\right)",
    ref: "28.2#vi.p1",
  },
  {
    name: "Mathieu function of noninteger order",
    notation: "\\operatorname{se}_{\\NVar{\\nu}}\\left(\\NVar{z},\\NVar{q}\\right)",
    ref: "28.12#E13",
  },
  {
    name: "modified Mathieu function",
    notation: "\\operatorname{Se}_{\\NVar{\\nu}}\\left(\\NVar{z},\\NVar{q}\\right)",
    ref: "28.20#E4",
  },
  {
    name: "Lamé polynomial",
    notation: "\\mathit{sE}^{\\NVar{m}}_{2\\NVar{n}+1}\\left(\\NVar{z},\\NVar{k^{2}}\\right)",
    ref: "29.12#E2",
  },
  {
    name: "secant function",
    notation: "\\sec\\NVar{z}",
    ref: "4.14#E6",
  },
  {
    name: "hyperbolic secant function",
    notation: "\\operatorname{sech}\\NVar{z}",
    ref: "4.28#E6",
  },
  {
    name: "hyperbolic sine integral",
    notation: "\\operatorname{Shi}\\left(\\NVar{z}\\right)",
    ref: "6.2#E15",
  },
  {
    name: "sine integral",
    notation: "\\operatorname{Si}\\left(\\NVar{z}\\right)",
    ref: "6.2#E9",
  },
  {
    name: "sine integral",
    notation: "\\operatorname{si}\\left(\\NVar{z}\\right)",
    ref: "6.2#E10",
  },
  {
    name: "generalized sine integral",
    notation: "\\operatorname{Si}\\left(\\NVar{a},\\NVar{z}\\right)",
    ref: "8.21#E2",
  },
  {
    name: "generalized sine integral",
    notation: "\\operatorname{si}\\left(\\NVar{a},\\NVar{z}\\right)",
    ref: "8.21#E1",
  },
  {
    name: "sum of powers of divisors of a number",
    notation: "\\sigma_{\\NVar{\\alpha}}\\left(\\NVar{n}\\right)",
    ref: "27.2#E10",
  },
  {
    name: "Coulomb phase shift",
    notation: "{\\sigma_{\\NVar{\\ell}}}\\left(\\NVar{\\eta}\\right)",
    ref: "33.2#E10",
  },
  {
    name: "Rayleigh function",
    notation: "\\sigma_{\\NVar{n}}\\left(\\NVar{\\nu}\\right)",
    ref: "10.21#E55",
  },
  {
    name: "Weierstrass sigma function",
    notation: "\\sigma\\left(\\NVar{z}\\right)",
    ref: "23.2#E6",
  },
  {
    name: "Weierstrass sigma function",
    notation: "\\sigma\\left(\\NVar{z};\\NVar{g_{2}},\\NVar{g_{3}}\\right)",
    ref: "23.3#i.p3",
  },
  {
    name: "sign of",
    notation: "\\operatorname{sign}\\NVar{x}",
    ref: "front/introduction#common.t2.r18",
  },
  {
    name: "sine function",
    notation: "\\sin\\NVar{z}",
    ref: "4.14#E1",
  },
  {
    name: "q-sine function",
    notation: "\\operatorname{Sin}_{\\NVar{q}}\\left(\\NVar{x}\\right)",
    ref: "17.3#E4",
  },
  {
    name: "q-sine function",
    notation: "\\operatorname{sin}_{\\NVar{q}}\\left(\\NVar{x}\\right)",
    ref: "17.3#E3",
  },
  {
    name: "hyperbolic sine function",
    notation: "\\sinh\\NVar{z}",
    ref: "4.28#E1",
  },
  {
    name: "Jacobian elliptic function",
    notation: "\\operatorname{sn}\\left(\\NVar{z},\\NVar{k}\\right)",
    ref: "22.2#E4",
  },
  {
    name: "alternative notation",
    notation:
      "\\mathrm{sn}(\\NVar{z}\\mathpunct{|}\\NVar{m})=\\operatorname{sn}\\left(z,\\sqrt{m}\\right)",
    ref: "22.1#p5",
  },
  {
    name: "least upper bound (supremum)",
    notation: "\\sup",
    ref: "front/introduction#common.t1.r26",
  },
  {
    name: "tangent numbers",
    notation: "T_{\\NVar{n}}",
    ref: "24.15#ii",
  },
  {
    name: "Tree T-function",
    notation: "T\\left(\\NVar{z}\\right)",
    ref: "4.13#p4",
  },
  {
    name: "shifted Chebyshev polynomial of the first kind",
    notation: "T^{*}_{\\NVar{n}}\\left(\\NVar{x}\\right)",
    ref: "18.3#T1.t1.r8",
  },
  {
    name: "tangent function",
    notation: "\\tan\\NVar{z}",
    ref: "4.14#E4",
  },
  {
    name: "hyperbolic tangent function",
    notation: "\\tanh\\NVar{z}",
    ref: "4.28#E4",
  },
  {
    name: "Ramanujan’s tau function",
    notation: "\\tau\\left(\\NVar{n}\\right)",
    ref: "27.14#E18",
  },
  {
    name: "alternative notation",
    notation: "\\vartheta\\left(\\NVar{x}\\right)=\\theta_{3}\\left(0,x\\right)",
    ref: "27.13#E4",
  },
  {
    name: "Airy phase function",
    notation: "\\theta\\left(\\NVar{z}\\right)",
    ref: "9.8#E4",
  },
  {
    name: "phase of Bessel functions",
    notation: "\\theta_{\\NVar{\\nu}}\\left(\\NVar{x}\\right)",
    ref: "10.18#E3",
  },
  {
    name: "Riemann theta function",
    notation: "\\theta\\left(\\NVar{\\mathbf{z}}\\middle|\\NVar{\\boldsymbol{{\\Omega}}}\\right)",
    ref: "21.2#E1",
  },
  {
    name: "Jacobi’s notation",
    notation: "\\Theta(\\NVar{z}|\\NVar{\\tau})=\\theta_{4}\\left(u\\middle|\\tau\\right)",
    ref: "20.1#Px1.p1",
  },
  {
    name: "Jacobi’s notation",
    notation: "\\Theta_{1}(\\NVar{z}|\\NVar{\\tau})=\\theta_{3}\\left(u\\middle|\\tau\\right)",
    ref: "20.1#Px1.p1",
  },
  {
    name: "scaled Riemann theta function",
    notation:
      "\\hat{\\theta}\\left(\\NVar{\\mathbf{z}}\\middle|\\NVar{\\boldsymbol{{\\Omega}}}\\right)",
    ref: "21.2#E2",
  },
  {
    name: "theta function",
    notation: "\\theta_{\\NVar{j}}\\left(\\NVar{z},\\NVar{q}\\right)",
    ref: "20.2#i",
  },
  {
    name: "theta function",
    notation: "\\theta_{\\NVar{j}}\\left(\\NVar{z}\\middle|\\NVar{\\tau}\\right)",
    ref: "20.2#i",
  },
  {
    name: "phase of Coulomb functions",
    notation: "{\\theta_{\\NVar{\\ell}}}\\left(\\NVar{\\eta},\\NVar{\\rho}\\right)",
    ref: "33.2#E9",
  },
  {
    name: "Riemann theta function with characteristics",
    notation:
      "\\theta\\genfrac{[}{]}{0.0pt}{}{\\NVar{\\boldsymbol{{\\alpha}}}}{\\NVar{\\boldsymbol{%\n{\\beta}}}}\\left(\\NVar{\\mathbf{z}}\\middle|\\NVar{\\boldsymbol{{\\Omega}}}\\right)",
    ref: "21.2#E5",
  },
  {
    name: "trace of matrix",
    notation: "\\operatorname{tr}\\NVar{\\mathbf{A}}",
    ref: "1.2#E62",
  },
  {
    name: "union",
    notation: "\\cup",
    ref: "front/introduction#common.t1.r28",
  },
  {
    name: "generalized Airy function",
    notation: "U_{\\NVar{m}}(\\NVar{t})",
    ref: "9.13#i.p6",
  },
  {
    name: "shifted Chebyshev polynomial of the second kind",
    notation: "U^{*}_{\\NVar{n}}\\left(\\NVar{x}\\right)",
    ref: "18.3#T1.t1.r9",
  },
  {
    name: "parabolic cylinder function",
    notation: "\\overline{U}\\left(\\NVar{a},\\NVar{x}\\right)",
    ref: "12.2#vi.p1",
  },
  {
    name: "Voigt function",
    notation: "\\mathsf{U}\\left(\\NVar{x},\\NVar{t}\\right)",
    ref: "7.19#E1",
  },
  {
    name: "Kummer confluent hypergeometric function",
    notation: "U\\left(\\NVar{a},\\NVar{b},\\NVar{z}\\right)",
    ref: "13.2#E6",
  },
  {
    name: "Lamé polynomial",
    notation: "\\mathit{uE}^{\\NVar{m}}_{2\\NVar{n}}\\left(\\NVar{z},\\NVar{k^{2}}\\right)",
    ref: "29.12#E1",
  },
  {
    name: "total variation",
    notation: "\\mathcal{V}\\left(\\NVar{f}\\right)",
    ref: "1.4#E33",
  },
  {
    name: "total variation",
    notation: "\\mathcal{V}_{\\NVar{a,b}}\\left(\\NVar{f}\\right)",
    ref: "1.4#E33",
  },
  {
    name: "generalized Airy function",
    notation: "V_{\\NVar{m}}(\\NVar{t})",
    ref: "9.13#i.p6",
  },
  {
    name: "generalized Airy function",
    notation: "\\overline{V}_{\\NVar{m}}(\\NVar{t})",
    ref: "9.13#i.p6",
  },
  {
    name: "Chebyshev polynomial of the third kind",
    notation: "V_{\\NVar{n}}\\left(\\NVar{x}\\right)",
    ref: "18.3#T1.t1.r6",
  },
  {
    name: "parabolic cylinder function",
    notation: "V\\left(\\NVar{a},\\NVar{z}\\right)",
    ref: "12.2#i.p1",
  },
  {
    name: "Voigt function",
    notation: "\\mathsf{V}\\left(\\NVar{x},\\NVar{t}\\right)",
    ref: "7.19#E2",
  },
  {
    name: "Wronskian",
    notation: "\\mathscr{W}",
    ref: "1.13#Px2.p1",
  },
  {
    name: "Faddeeva (or Faddeyeva) function",
    notation: "w\\left(\\NVar{z}\\right)",
    ref: "7.2#E3",
  },
  {
    name: "Lambert W-function",
    notation: "W\\left(\\NVar{z}\\right)",
    ref: "4.13#E1",
  },
  {
    name: "Whittaker confluent hypergeometric function",
    notation: "W_{\\NVar{\\kappa},\\NVar{\\mu}}\\left(\\NVar{z}\\right)",
    ref: "13.14#E3",
  },
  {
    name: "nonprincipal branch of Lambert W-function",
    notation: "\\operatorname{Wm}\\left(\\NVar{x}\\right)",
    ref: "4.13#E1",
  },
  {
    name: "Chebyshev polynomial of the fourth kind",
    notation: "W_{\\NVar{n}}\\left(\\NVar{x}\\right)",
    ref: "18.3#T1.t1.r7",
  },
  {
    name: "principal branch of Lambert W-function",
    notation: "\\operatorname{Wp}\\left(\\NVar{x}\\right)",
    ref: "4.13#E1",
  },
  {
    name: "parabolic cylinder function",
    notation: "W\\left(\\NVar{a},\\NVar{x}\\right)",
    ref: "12.14#i.p1",
  },
  {
    name: "basic solution, Hill’s equation",
    notation: "w_{\\mbox{\\tiny I}}(\\NVar{z},\\NVar{\\lambda})",
    ref: "28.29#EGx1",
  },
  {
    name: "basic solution, Hill’s equation",
    notation: "w_{\\mbox{\\tiny II}}(\\NVar{z},\\NVar{\\lambda})",
    ref: "28.29#EGx1",
  },
  {
    name: "basic solution, Mathieu’s equation",
    notation: "w_{\\mbox{\\tiny I}}(\\NVar{z};\\NVar{a},\\NVar{q})",
    ref: "28.2#ii.p2",
  },
  {
    name: "basic solution, Mathieu’s equation",
    notation: "w_{\\mbox{\\tiny II}}(\\NVar{z};\\NVar{a},\\NVar{q})",
    ref: "28.2#ii.p2",
  },
  {
    name: "Wilson polynomial",
    notation: "W_{\\NVar{n}}\\left(\\NVar{x};\\NVar{a},\\NVar{b},\\NVar{c},\\NVar{d}\\right)",
    ref: "18.25#T1.t1.r2",
  },
  {
    name: "Riemann’s ξ-function",
    notation: "\\xi\\left(\\NVar{s}\\right)",
    ref: "25.4#E4",
  },
  {
    name: "zeros of the Bessel function Yν(x)",
    notation: "y_{\\NVar{\\nu},\\NVar{m}}",
    ref: "10.2#E3",
  },
  {
    name: "zeros of the Bessel function derivative Yν′(x)",
    notation: "{y^{\\prime}_{\\NVar{\\nu},\\NVar{m}}}",
    ref: "10.2#E3",
  },
  {
    name: "other notation",
    notation: "y_{\\NVar{n}}(\\NVar{x})=y_{n}\\left(x;2\\right)",
    ref: "18.34#E2",
  },
  {
    name: "spherical Bessel function of the second kind",
    notation: "\\mathsf{y}_{\\NVar{n}}\\left(\\NVar{z}\\right)",
    ref: "10.47#E4",
  },
  {
    name: "Bessel function of imaginary order",
    notation: "\\widetilde{Y}_{\\NVar{\\nu}}\\left(\\NVar{x}\\right)",
    ref: "10.24#Ex2",
  },
  {
    name: "Bessel function of the second kind",
    notation: "Y_{\\NVar{\\nu}}\\left(\\NVar{z}\\right)",
    ref: "10.2#E3",
  },
  {
    name: "spherical harmonic",
    notation: "Y_{{\\NVar{l}},{\\NVar{m}}}\\left(\\NVar{\\theta},\\NVar{\\phi}\\right)",
    ref: "14.30#E1",
  },
  {
    name: "Bessel polynomial",
    notation: "y_{\\NVar{n}}\\left(\\NVar{x};\\NVar{a}\\right)",
    ref: "18.34#E1",
  },
  {
    name: "surface harmonic of the first kind",
    notation: "Y_{\\NVar{l}}^{\\NVar{m}}\\left(\\NVar{\\theta},\\NVar{\\phi}\\right)",
    ref: "14.30#E2",
  },
  {
    name: "other notation",
    notation: "y_{\\NVar{n}}(\\NVar{x};\\NVar{a},\\NVar{b})=y_{n}\\left(2x/b;a\\right)",
    ref: "18.34#E3",
  },
  {
    name: "set of all integers",
    notation: "\\mathbb{Z}",
    ref: "front/introduction#common.t2.r20",
  },
  {
    name: "power function",
    notation: "{\\NVar{z}}^{\\NVar{a}}",
    ref: "4.2#E26",
  },
  {
    name: "zonal polynomial",
    notation: "Z_{\\NVar{\\kappa}}\\left(\\NVar{\\mathbf{T}}\\right)",
    ref: "35.4#i.p3",
  },
  {
    name: "modified cylinder function",
    notation: "\\mathscr{Z}_{\\NVar{\\nu}}\\left(\\NVar{z}\\right)",
    ref: "10.25#Px2.p1",
  },
  {
    name: "Jacobi’s zeta function",
    notation: "\\mathrm{Z}\\left(\\NVar{x}|\\NVar{k}\\right)",
    ref: "22.16#E32",
  },
  {
    name: "Riemann zeta function",
    notation: "\\zeta\\left(\\NVar{s}\\right)",
    ref: "25.2#E1",
  },
  {
    name: "incomplete Riemann zeta function",
    notation: "\\zeta_{\\NVar{x}}(\\NVar{s})",
    ref: "8.22#E2",
  },
  {
    name: "Hurwitz zeta function",
    notation: "\\zeta\\left(\\NVar{s},\\NVar{a}\\right)",
    ref: "25.11#E1",
  },
  {
    name: "Weierstrass zeta function",
    notation: "\\zeta\\left(\\NVar{z}\\right)",
    ref: "23.2#E5",
  },
  {
    name: "Weierstrass zeta function",
    notation: "\\zeta\\left(\\NVar{z};\\NVar{g_{2}},\\NVar{g_{3}}\\right)",
    ref: "23.3#i.p3",
  },
];
