// The modular group PSL(2,Z), and the words that name its elements.
//
// PSL(2,Z) is the quotient of SL(2,Z) by ±I. As an abstract group it is the free product
// Z/2 * Z/3, generated by
//
//     S = [ 0 −1 ]   of order 2,     U = ST = [ 0 −1 ]   of order 3,
//         [ 1  0 ]                            [ 1  1 ]
//
// and that free-product structure is why everything here is a WORD. Three different
// alphabets show up, and they are the same object seen three ways:
//
//   S, T      the geometric generators — T is the translation z ↦ z+1, S the inversion
//             z ↦ −1/z. Every element is an alternating product of S and powers of T,
//             and the exponents are exactly a continued fraction.
//   L, R      the two parabolic generators L = [[1,0],[1,1]] and R = [[1,1],[0,1]].
//             A matrix with non-negative entries is a UNIQUE positive word in L and R,
//             which is also its path down the Stern–Brocot tree.
//   necklace  a hyperbolic conjugacy class is an LR word up to CYCLIC rotation, because
//             conjugating by the first letter rotates the word. So the classes are
//             binary necklaces — and the primitive ones are Lyndon words' necklaces.
//
// The last line is the payoff. A hyperbolic conjugacy class is a closed geodesic on the
// modular surface, i.e. a periodic orbit of the modular (geodesic) flow, i.e. a MODULAR
// KNOT in the complement of the trefoil. Counting closed geodesics of a given length is
// therefore a necklace-counting problem, which is combinatorics this catalogue already
// knows how to do.

/** A 2×2 integer matrix [a, b, c, d], read as [[a, b], [c, d]]. */
export type Matrix = readonly [number, number, number, number];

export const IDENTITY: Matrix = [1, 0, 0, 1];
/** S: z ↦ −1/z, of order 2 in PSL(2,Z). */
export const S: Matrix = [0, -1, 1, 0];
/** T: z ↦ z + 1. */
export const T: Matrix = [1, 1, 0, 1];
/** U = ST, of order 3 in PSL(2,Z) — the other free factor. */
export const U: Matrix = [0, -1, 1, 1];
/** R = T, named for its role as a Stern–Brocot step. */
export const R: Matrix = [1, 1, 0, 1];
/** L, the transpose of R. */
export const L: Matrix = [1, 0, 1, 1];

const isInt = (x: number): boolean => Number.isSafeInteger(x);

export const determinant = ([a, b, c, d]: Matrix): number => a * d - b * c;
export const trace = ([a, , , d]: Matrix): number => a + d;

export const multiply = (m: Matrix, n: Matrix): Matrix => [
  m[0] * n[0] + m[1] * n[2],
  m[0] * n[1] + m[1] * n[3],
  m[2] * n[0] + m[3] * n[2],
  m[2] * n[1] + m[3] * n[3],
];

/** The inverse, which for determinant 1 needs no division. */
export const invert = ([a, b, c, d]: Matrix): Matrix | undefined =>
  a * d - b * c === 1 ? [d, -b, -c, a] : undefined;

export const isModular = (m: Matrix): boolean => m.every(isInt) && determinant(m) === 1;

/** Equality in PSL(2,Z), where M and −M are the same element. */
export const samePSL = (m: Matrix, n: Matrix): boolean =>
  m.every((x, i) => x === n[i]) || m.every((x, i) => x === -(n[i] as number));

export const power = (m: Matrix, k: number): Matrix | undefined => {
  if (!isInt(k)) return undefined;
  if (k < 0) {
    const i = invert(m);
    return i === undefined ? undefined : power(i, -k);
  }
  let out = IDENTITY;
  for (let i = 0; i < k; i++) out = multiply(out, m);
  return out;
};

/**
 * The three kinds of element, by |trace|. Elliptic ones are rotations and have finite
 * order; parabolic ones fix one point on the boundary; hyperbolic ones fix two, and
 * translate along the geodesic between them — those are the ones with closed geodesics.
 */
export type Kind = "identity" | "elliptic" | "parabolic" | "hyperbolic";

export function classify(m: Matrix): Kind | undefined {
  if (!isModular(m)) return undefined;
  if (samePSL(m, IDENTITY)) return "identity";
  const t = Math.abs(trace(m));
  return t < 2 ? "elliptic" : t === 2 ? "parabolic" : "hyperbolic";
}

// ── words in L and R ────────────────────────────────────────────────────────────

/** A word in the letters L and R, most significant (leftmost) factor first. */
export type Word = string;

export const wordToMatrix = (word: Word): Matrix | undefined => {
  let out = IDENTITY;
  for (const letter of word) {
    if (letter === "L") out = multiply(out, L);
    else if (letter === "R") out = multiply(out, R);
    else return undefined;
  }
  return out;
};

/**
 * The unique positive LR word of a matrix with non-negative entries.
 *
 * Peeling is deterministic, and the reason is worth stating: R⁻¹M subtracts row 2 from
 * row 1, L⁻¹M subtracts row 1 from row 2, so R can be peeled when (a ≥ c and b ≥ d) and
 * L when (c ≥ a and d ≥ b). Both cannot hold at once — that would force a = c and b = d,
 * hence determinant 0 — so there is never a choice to make, and no search. It is the
 * matrix form of the subtractive Euclidean algorithm, which is also why the word read off
 * is the path down the Stern–Brocot tree.
 */
export function positiveWord(m: Matrix): Word | undefined {
  if (!isModular(m) || m.some((x) => x < 0)) return undefined;
  let [a, b, c, d] = m;
  const letters: string[] = [];
  // Each peel strictly decreases a + b + c + d, which starts finite and stays ≥ 2, so the
  // loop terminates; the cap is belt and braces against a caller-supplied bad matrix.
  for (let guard = 0; guard < 100_000; guard++) {
    if (a === 1 && b === 0 && c === 0 && d === 1) return letters.join("");
    if (a >= c && b >= d) {
      a -= c;
      b -= d;
      letters.push("R");
    } else if (c >= a && d >= b) {
      c -= a;
      d -= b;
      letters.push("L");
    } else return undefined;
  }
  return undefined;
}

// ── words in S and T ────────────────────────────────────────────────────────────

/**
 * An S/T factorisation, as the exponents of the alternating product
 * T^{e₀} S T^{e₁} S … S T^{eₙ}. The exponents are the continued fraction of the matrix,
 * up to sign — which is the bridge between the group and the numeral system.
 */
export interface STWord {
  readonly exponents: readonly number[];
}

/** Rebuild the matrix from its S/T exponents. */
export function stWordToMatrix(word: STWord): Matrix | undefined {
  if (!word.exponents.every(isInt) || word.exponents.length === 0) return undefined;
  let out: Matrix | undefined = power(T, word.exponents[0]!);
  for (const e of word.exponents.slice(1)) {
    const step = power(T, e);
    if (out === undefined || step === undefined) return undefined;
    out = multiply(multiply(out, S), step);
  }
  return out;
}

/**
 * Factor a matrix as T^{e₀} S T^{e₁} S … by the Euclidean algorithm on the left column:
 * S swaps the rows (with a sign) and T^e shears, so repeatedly reducing a mod c is
 * exactly the continued fraction of a/c. The result is equal in PSL(2,Z) — the sign that
 * S⁻¹ = −S introduces is precisely the ±I being quotiented out.
 */
export function stWord(m: Matrix): STWord | undefined {
  if (!isModular(m)) return undefined;
  let [a, b, c, d] = m;
  const exponents: number[] = [];
  for (let guard = 0; guard < 100_000; guard++) {
    if (c === 0) {
      // [[a, b], [0, d]] with ad = 1, so it is ±T^{ab}.
      exponents.push(a === d ? b * a : -b * a);
      return { exponents };
    }
    const e = Math.floor(a / c);
    exponents.push(e);
    // Left-multiply by S⁻¹T^{−e}, i.e. strip T^e S off the front.
    [a, b, c, d] = [c, d, -(a - e * c), -(b - e * d)];
  }
  return undefined;
}

// ── continued fractions and the Stern–Brocot tree ───────────────────────────────

/**
 * The regular continued fraction [a₀; a₁, a₂, …] of p/q, for q > 0. The last partial
 * quotient is never 1 (except for the single-term expansion of an integer), which is the
 * choice that makes the expansion unique.
 */
export function continuedFraction(p: number, q: number): number[] | undefined {
  if (!isInt(p) || !isInt(q) || q <= 0) return undefined;
  const out: number[] = [];
  let [x, y] = [p, q];
  for (let guard = 0; guard < 10_000 && y !== 0; guard++) {
    const e = Math.floor(x / y);
    out.push(e);
    [x, y] = [y, x - e * y];
  }
  if (y !== 0) return undefined;
  // Normalise the trailing 1: […, k, 1] and […, k+1] are the same number.
  if (out.length > 1 && out[out.length - 1] === 1) {
    out.pop();
    out[out.length - 1] = (out[out.length - 1] as number) + 1;
  }
  return out;
}

/** The rational a continued fraction denotes, as a reduced [numerator, denominator]. */
export function fromContinuedFraction(
  quotients: readonly number[],
): readonly [number, number] | undefined {
  if (quotients.length === 0 || !quotients.every(isInt)) return undefined;
  if (quotients.slice(1).some((a) => a <= 0)) return undefined;
  let [numerator, denominator] = [1, 0];
  for (const a of [...quotients].reverse()) {
    [numerator, denominator] = [a * numerator + denominator, numerator];
  }
  return denominator < 0 ? [-numerator, -denominator] : [numerator, denominator];
}

/**
 * The Stern–Brocot path of a positive rational: the sequence of left and right turns that
 * reaches p/q from 1/1. It is the same word as `positiveWord` of the matrix built from
 * the convergents, and its letter counts are the continued fraction — the tree, the
 * numeral system and the group are one object.
 */
export function sternBrocotPath(p: number, q: number): Word | undefined {
  if (!isInt(p) || !isInt(q) || p <= 0 || q <= 0) return undefined;
  const letters: string[] = [];
  let [x, y] = [p, q];
  for (let guard = 0; guard < 100_000; guard++) {
    if (x === y) return x === 1 ? letters.join("") : undefined; // only 1/1 reduces to x = y
    if (x > y) {
      const steps = Math.floor((x - 1) / y);
      letters.push("R".repeat(steps));
      x -= steps * y;
    } else {
      const steps = Math.floor((y - 1) / x);
      letters.push("L".repeat(steps));
      y -= steps * x;
    }
  }
  return undefined;
}

/** The positive rational at the end of a Stern–Brocot path. */
export function fromSternBrocotPath(path: Word): readonly [number, number] | undefined {
  const m = wordToMatrix(path);
  if (m === undefined) return undefined;
  // The path matrix sends 1/1 to the rational it names.
  const [a, b, c, d] = m;
  return [a + b, c + d];
}

/** Whether p/q and r/s are Farey neighbours — the determinant test, |ps − qr| = 1. */
export const areFareyNeighbours = (p: number, q: number, r: number, s: number): boolean =>
  [p, q, r, s].every(isInt) && Math.abs(p * s - q * r) === 1;

/** The Farey sequence of order n: every reduced p/q in [0,1] with q ≤ n, in order. */
export function fareySequence(n: number): (readonly [number, number])[] | undefined {
  if (!isInt(n) || n < 1 || n > 2000) return undefined;
  // The classic next-term recurrence, which needs no sorting and no gcd.
  const out: (readonly [number, number])[] = [[0, 1]];
  let [a, b, c, d] = [0, 1, 1, n];
  while (c <= n) {
    out.push([c, d]);
    const k = Math.floor((n + b) / d);
    [a, b, c, d] = [c, d, k * c - a, k * d - b];
  }
  return out;
}

// ── conjugacy classes: necklaces of L and R ─────────────────────────────────────

/** The lexicographically least rotation — the canonical name of a necklace. */
export function leastRotation(word: Word): Word {
  let best = word;
  for (let i = 1; i < word.length; i++) {
    const rotation = word.slice(i) + word.slice(0, i);
    if (rotation < best) best = rotation;
  }
  return best;
}

/** Whether a word is aperiodic — not a proper power of a shorter word. */
export function isPrimitiveWord(word: Word): boolean {
  const n = word.length;
  if (n === 0) return false;
  for (let period = 1; period < n; period++) {
    if (n % period !== 0) continue;
    const block = word.slice(0, period);
    if (block.repeat(n / period) === word) return false;
  }
  return true;
}

/**
 * The conjugacy class of a positive word, named by its least rotation.
 *
 * Conjugating by the first letter rotates the word: (xw)ʷ conjugated by x⁻¹ is wx. So
 * conjugacy classes of positive words ARE necklaces, and this is their canonical name.
 */
export const conjugacyClassName = (word: Word): Word | undefined =>
  /^[LR]*$/.test(word) && word.length > 0 ? leastRotation(word) : undefined;

/**
 * Every hyperbolic conjugacy class whose LR word has a given length — i.e. every closed
 * geodesic of that combinatorial length, as a necklace. A word of all L or all R is
 * parabolic, not hyperbolic, so those two are excluded.
 */
export function hyperbolicClasses(length: number, primitiveOnly = false): Word[] | undefined {
  if (!isInt(length) || length < 1 || length > 24) return undefined;
  const seen = new Set<Word>();
  for (let mask = 0; mask < 2 ** length; mask++) {
    let word = "";
    for (let i = 0; i < length; i++) word += (mask >> i) & 1 ? "R" : "L";
    if (!word.includes("L") || !word.includes("R")) continue; // parabolic
    if (primitiveOnly && !isPrimitiveWord(word)) continue;
    seen.add(leastRotation(word));
  }
  return [...seen].sort();
}
