// Emit `.control` + `<extension>--<version>.sql` packaging artifacts for `CREATE EXTENSION` (#322, under #122;
// wiki Core-And-Packs §7): the pack dependency graph IS Postgres's extension dependency graph, 1:1. One
// `enumeratio.control` for core, plus one `enumeratio_<pack>.control` per EXTRACTED pack with
// `requires = 'enumeratio[, enumeratio_<dep>, …]'` derived straight from the pack's own manifest (never
// hardcoded here) — and CROSS-CHECKED against `PACK_DEPS` (pack-map.ts) before anything is written, so the two
// sources of truth can't silently drift.
//
// Reuses the exact machinery the real loader (node.ts/buildCore, applyPackSegments) uses to load core+packs into
// a session — `orderPacks` + `segmentByPack` — so "what CREATE EXTENSION would apply" and "what the in-process
// loader applies" are provably the same ordering, not a second reimplementation of it.
//
// THIS IS A PACKAGING ARTIFACT, not a supported install path: the docs still disclaim `CREATE EXTENSION` (see
// docs/develop/index.md, docs/develop/api.md, docs/develop/packages/data/index.md) — this script only proves the
// artifacts assemble correctly; it doesn't wire up a documented `CREATE EXTENSION` flow. Output is gitignored
// (under dist/, per the root .gitignore) and NOT part of the default gate — run it explicitly via
// `pnpm --filter @enumeratio/data build:control`.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { loadCoreAndPacks } from './node.ts'
import { orderPacks, segmentByPack, type PackSegment } from './sqlsrc-order.ts'
import { PACK_DEPS, type PackName } from './pack-map.ts'

const here = dirname(fileURLToPath(import.meta.url))
const outDir = join(here, 'dist', 'control')
mkdirSync(outDir, { recursive: true })

const pkg = JSON.parse(readFileSync(join(here, 'package.json'), 'utf8')) as { version: string }
const version = pkg.version

/** `<pack>` → the Postgres extension name. Postgres extension names travel through bare identifiers and the
 *  `--<version>.sql` filename convention, so hyphenated pack names (`trees-graphs`) become underscored
 *  (`enumeratio_trees_graphs`) — 'core' is the bare `enumeratio` extension itself, never `enumeratio_core`. */
function extName(pack: string): string {
  return pack === 'core' ? 'enumeratio' : `enumeratio_${pack.replace(/-/g, '_')}`
}

const bannerJoin = (files: { name: string; content: string }[]): string =>
  files.map(f => `-- ═══ ${f.name}.sql ═══\n${f.content}`).join('\n')

const { core, packs } = loadCoreAndPacks()
const ordered = orderPacks(core, packs)
const segments: PackSegment[] = segmentByPack(ordered, core, packs)

// ── (3) requires cross-check: every pack's own `-- requires-pack:` manifest header must match PACK_DEPS exactly,
// both directions — pack-map.ts is the OTHER source of truth for the graph (pack-lint.mts/pack-additivity.mts
// read it too), and a mismatch here means one of them drifted. Fail loudly before writing anything.
for (const pack of packs) {
  const declared = [...new Set(pack.requiresPack)].sort()
  const expected = [...new Set(PACK_DEPS[pack.name as PackName] ?? [])].sort()
  if (JSON.stringify(declared) !== JSON.stringify(expected)) {
    throw new Error(
      `pack "${pack.name}": manifest "-- requires-pack: ${declared.join(', ')}" != ` +
      `PACK_DEPS["${pack.name}"] = [${expected.join(', ')}] — fix whichever one drifted before packaging`,
    )
  }
}

// ── core: enumeratio.control + enumeratio--<version>.sql ────────────────────────────────────────────────────
// segmentByPack always emits core's segment first (orderPacks pushes core's own ordered files before any pack's —
// see sqlsrc-order.ts); core is never GUC-bracketed by the loader (applyPackSegments only brackets non-core
// segments) and already finalizes itself at the tail of its own load (meta-collections.stats.sql ends with
// `SELECT base_pack_finalize('core');`) — so core's assembled script is JUST its ordered files, byte-identical
// to the loader's own core segment, nothing appended.
const coreSeg = segments[0]
if (coreSeg.pack !== 'core') throw new Error(`segmentByPack: expected segment 0 to be 'core', got "${coreSeg.pack}"`)
const coreSql = bannerJoin(coreSeg.files) + '\n'

writeFileSync(join(outDir, 'enumeratio.control'), [
  `# enumeratio — generated by build-control.mts, do not edit by hand`,
  `comment = 'enumeratio: a data-driven library of combinatorial collections'`,
  `default_version = '${version}'`,
  `relocatable = false`,
  `schema = public`,
  '',
].join('\n'))
writeFileSync(join(outDir, `enumeratio--${version}.sql`), coreSql)

// ── each extracted pack: enumeratio_<pack>.control + enumeratio_<pack>--<version>.sql ───────────────────────
// Per applyPackSegments (sqlsrc-order.ts): bracket the pack's own ordered files with `set_config('enumeratio.pack',
// …)`, finalize, then reset to 'core' — this is exactly what a single `CREATE EXTENSION enumeratio_<pack>` needs
// to run standalone in a session where 'enumeratio' (and any required sibling pack extensions) are already
// installed: the DEFAULT-stamped `pack` columns and the pack guard trigger (bootstrap.sql) both read this GUC.
const packByName = new Map(packs.map(p => [p.name, p]))
const packFiles: string[] = []
for (const seg of segments.slice(1)) {
  const pack = packByName.get(seg.pack)
  if (!pack) throw new Error(`segmentByPack produced a segment for unknown pack "${seg.pack}"`)
  const requires = [...new Set(['core', ...pack.requiresPack])].map(extName)
  const ext = extName(pack.name)
  const q = (s: string) => s.replace(/'/g, "''")

  const sql = [
    `SELECT set_config('enumeratio.pack', '${q(pack.name)}', false);`,
    bannerJoin(seg.files),
    `SELECT base_pack_finalize('${q(pack.name)}');`,
    `SELECT set_config('enumeratio.pack', 'core', false);`,
    '',
  ].join('\n')

  writeFileSync(join(outDir, `${ext}.control`), [
    `# ${ext} — generated by build-control.mts, do not edit by hand`,
    `comment = 'enumeratio pack: ${pack.name}'`,
    `default_version = '${version}'`,
    `relocatable = false`,
    `schema = public`,
    `requires = '${requires.join(', ')}'`,
    '',
  ].join('\n'))
  writeFileSync(join(outDir, `${ext}--${version}.sql`), sql)
  packFiles.push(ext)
}

console.log(`build-control: wrote enumeratio.control + enumeratio--${version}.sql, and ${packFiles.length} pack extension(s) under ${outDir}`)
console.log(`  packs: ${packFiles.join(', ')}`)
