// The build-time CATALOG SNAPSHOT — the Expr vocabulary, frozen at build and shipped in the package tarball, so a
// consumer can answer "can this engine evaluate this expression?" SYNCHRONOUSLY, without a database round-trip
// (#278 D2). It is not a cache of the catalog; it is the small slice an engine's `can()` walks: functions and
// their implementations, the engines and what each is granted, and just enough about collections for a grant's
// scope to resolve. Reprs, carriers and the operation algebras are DELIBERATELY absent: nothing routes on them
// yet, and an unused section is bundle weight a browser consumer pays for. Add them when a consumer needs them.
//
// It is a RELEASE ARTIFACT, not a repo file: `catalog-snapshot.json` is generated by build-catalog-snapshot.mts,
// gitignored exactly like enumeratio-core.pgdata, and listed in the package's `files` so it ships when published.
// Everything here is therefore split so nothing DEPENDS on the artifact existing: `buildCatalogSnapshot(pg)` is
// pure and callable in-process (which is how the tests get one), and `loadCatalogSnapshot()` returns null when the
// file is absent. A missing or stale snapshot means an engine that needs it simply declines — never a wrong answer.
/** Anything that can answer SQL — a PGlite, a pooled Postgres client, or the client's own `runSql`. Taking the
 *  query function rather than a database means a test can build a snapshot off the connection it ALREADY has,
 *  which is what keeps every test independent of whether the release artifact was ever generated. */
export type SnapshotSource = <T>(sql: string) => Promise<T[]>

export type Representation = 'numeric' | 'bigint' | 'float64' | 'i64' | 'text'

/** A pg type reduced to what a JavaScript value can be checked against. Domains resolve to their base type
 *  (`term_index` is an int), so the TS resolver never has to know the catalog's domain names, and the set is
 *  closed — a composite is 'composite', full stop, which is precisely the signal that a TS engine has no way to
 *  print that result and must decline. */
export type TypeKind = 'int' | 'numeric' | 'float' | 'text' | 'bool' | 'composite' | 'array' | 'other'

/** One implementation of one curated identity. `argTypes` is the axis Postgres DISPATCHES on (the overload); a
 *  second row with the same argTypes and a different `representation` is the same overload carried more or less
 *  precisely — pg cannot overload on return type, so precision is a separate axis from arity/typing. */
export type ImplRow = {
  engine: string
  implRef: string
  argTypes: string[]
  /** argTypes reduced to TypeKind, resolved at build time — what overload resolution actually matches on */
  argKinds: TypeKind[]
  returnType: string
  returnKind: TypeKind
  representation: Representation
  cost: number | null
  note: string | null
}
export type FunctionRow = { id: string; title: string | null; description: string; impls: ImplRow[] }

export type CollectionRow = {
  id: string
  carrier: string | null
  grades: string[]
  unbounded: boolean
  aliasOf: string | null
  category: string
  tags: string[]
  /** which of the realizer's optional hooks this collection actually defines (to_regprocedure, as base_realize
   *  itself asks) — what an engine would have to reimplement to claim the row half */
  hooks: { fiberCount: boolean; fiberUnrank: boolean; fiberElements: boolean; containsInFiber: boolean }
}

export type GrantRow = { engine: string; columnGroup: string; scopeKind: string; scope: string; mode: string }
export type ColumnGroupRow = { id: string; kinds: string[] }
export type EngineRow = { id: string; description: string }

/** A composite carrier's shape, for engines that must CONSTRUCT one from arguments. Only the carriers some impl
 *  row actually mentions travel — this is the Expr vocabulary, not a mirror of the type catalog. A single-field
 *  carrier is the interesting case: `permutation` is one `int[]` in pg and a bare `number[]` in TS, so an engine
 *  needs the field count to know which shape it is building. */
export type CarrierRow = { name: string; fields: { name: string; type: string; kind: TypeKind }[] }
/** A non-pg engine that can evaluate this statistic itself, so a predicate on it pushes down. pg rows are NOT
 *  stored (see buildCatalogSnapshot) — pg is foldable for everything by construction. */
export type FoldableRow = { collection: string; stat: string; engine: string }

export type CatalogSnapshot = {
  /** the sqlsrc bundle hash this was built from — compared against the live core's, and a mismatch disables it */
  hash: string
  builtAt: string
  functions: FunctionRow[]
  collections: CollectionRow[]
  carriers: CarrierRow[]
  engines: EngineRow[]
  columnGroups: ColumnGroupRow[]
  grants: GrantRow[]
  foldable: FoldableRow[]
}

type Q = SnapshotSource

/** `integer[]` → `integer`, `character varying(8)` → `character varying` — format_type's spelling reduced to the
 *  bare type name pg_type is keyed by. An array field keeps kind 'array' via the [] check in the caller. */
export const baseName = (ty: string): string => ty.replace(/\[\]$/, '').replace(/\(.*\)$/, '').trim()

/** the spellings pg_type has no row for under that exact name (SQL-standard aliases the parser expands) */
const ALIASES: Record<string, TypeKind> = { int: 'int', integer: 'int', bigint: 'int', smallint: 'int', 'double precision': 'float', real: 'float', decimal: 'numeric', boolean: 'bool' }

function typeKind(category: string, base: string): TypeKind {
  if (category === 'A') return 'array'
  if (category === 'C') return 'composite'
  if (category === 'B') return 'bool'
  if (category === 'S') return 'text'
  if (category === 'N') {
    if (/^int[248]$/.test(base)) return 'int'
    if (base === 'numeric') return 'numeric'
    if (base === 'float4' || base === 'float8') return 'float'
    return 'numeric'
  }
  return 'other'
}

/** Build the snapshot from a LIVE core. Pure: reads, returns the object, writes nothing. */
export async function buildCatalogSnapshot(source: SnapshotSource, hash: string): Promise<CatalogSnapshot> {
  const q: Q = source

  // Every type name any impl row mentions, reduced to its TypeKind. A DOMAIN resolves to its base type
  // (typbasetype), so `term_index` answers 'int' — the TS resolver matches base kinds and never has to carry the
  // catalog's domain vocabulary.
  const kinds = new Map<string, TypeKind>()
  for (const r of await q<{ name: string; category: string; base: string }>(`
    SELECT t.typname AS name, t.typcategory AS category, coalesce(b.typname, t.typname) AS base
      FROM pg_type t LEFT JOIN pg_type b ON b.oid = t.typbasetype`)) {
    kinds.set(String(r.name), typeKind(String(r.category), String(r.base)))
  }
  const kindOf = (name: string): TypeKind => kinds.get(name) ?? kinds.get(name.replace(/^pg_catalog\./, '')) ?? ALIASES[name] ?? 'other'

  const impls = await q<{ function: string } & Record<string, unknown>>(`
    SELECT function, engine, impl_ref, arg_types::text AS arg_types, return_type, representation, cost, note
      FROM base_function_impl ORDER BY function, engine, impl_ref`)
  const byFn = new Map<string, ImplRow[]>()
  for (const r of impls) {
    const argTypes = pgArray(String(r.arg_types))
    const returnType = String(r.return_type)
    const row: ImplRow = {
      engine: String(r.engine), implRef: String(r.impl_ref),
      argTypes, argKinds: argTypes.map(kindOf), returnType, returnKind: kindOf(returnType),
      representation: String(r.representation) as Representation,
      cost: r.cost == null ? null : Number(r.cost),
      note: r.note == null ? null : String(r.note),
    }
    const list = byFn.get(r.function); if (list) list.push(row); else byFn.set(r.function, [row])
  }

  const functions = (await q<{ id: string; title: string | null; description: string }>(
    `SELECT id, title, description FROM base_function ORDER BY id`))
    .map((f) => ({ ...f, impls: byFn.get(f.id) ?? [] }))

  const collections = (await q<Record<string, unknown>>(`
    SELECT c.id, c.carrier, c.grades::text AS grades, c.unbounded, c.alias_of,
           coalesce(cc.category, 'mathematical') AS category,
           coalesce((SELECT array_agg(t.tag ORDER BY t.tag) FROM base_collection_tag t WHERE t.collection = c.id), '{}')::text AS tags,
           to_regprocedure(format('fiber_count(%I)', c.id || '_fiber'))              IS NOT NULL AS h_count,
           to_regprocedure(format('fiber_unrank(%I, rank_index)', c.id || '_fiber')) IS NOT NULL AS h_unrank,
           to_regprocedure(format('fiber_elements(%I)', c.id || '_fiber'))           IS NOT NULL AS h_elements,
           to_regprocedure(format('contains_in_fiber(%I, %s)', c.id || '_fiber', coalesce(c.carrier, 'text'))) IS NOT NULL AS h_contains
      FROM base_catalog c LEFT JOIN base_collection_category cc ON cc.collection = c.id
     ORDER BY c.id`))
    .map((r): CollectionRow => ({
      id: String(r.id),
      carrier: r.carrier == null ? null : String(r.carrier),
      grades: pgArray(String(r.grades)),
      unbounded: r.unbounded === true,
      aliasOf: r.alias_of == null ? null : String(r.alias_of),
      category: String(r.category),
      tags: pgArray(String(r.tags)),
      hooks: { fiberCount: r.h_count === true, fiberUnrank: r.h_unrank === true, fiberElements: r.h_elements === true, containsInFiber: r.h_contains === true },
    }))

  // the composite types some impl row names, and their attribute layout — what an engine needs to build one
  const composites = [...new Set(impls.flatMap((r) => [...pgArray(String(r.arg_types)), String(r.return_type)]))]
    .filter((t) => kindOf(t) === 'composite')
  const carriers: CarrierRow[] = []
  for (const name of composites.sort()) {
    const fields = await q<{ attname: string; ty: string }>(`
      SELECT a.attname, format_type(a.atttypid, a.atttypmod) AS ty
        FROM pg_attribute a JOIN pg_class c ON c.oid = a.attrelid
       WHERE c.relname = '${name}' AND a.attnum > 0 AND NOT a.attisdropped
       ORDER BY a.attnum`)
    carriers.push({ name, fields: fields.map((f) => { const ty = String(f.ty); return { name: String(f.attname), type: ty, kind: ty.endsWith('[]') ? 'array' as TypeKind : kindOf(baseName(ty)) } }) })
  }

  const engines = await q<EngineRow>(`SELECT id, description FROM base_engine ORDER BY id`)
  const columnGroups = (await q<Record<string, unknown>>(`SELECT id, kinds::text AS kinds FROM base_column_group ORDER BY id`))
    .map((r): ColumnGroupRow => ({ id: String(r.id), kinds: pgArray(String(r.kinds)) }))
  const grants = (await q<Record<string, unknown>>(
    `SELECT engine, column_group, scope_kind, scope, mode FROM base_engine_grant ORDER BY engine, column_group, scope_kind, scope`))
    .map((r): GrantRow => ({ engine: String(r.engine), columnGroup: String(r.column_group), scopeKind: String(r.scope_kind), scope: String(r.scope), mode: String(r.mode) }))
  // pg is foldable for every (collection, stat) BY DEFINITION — the stat IS a pg function — so shipping its ~2500
  // rows would be 180 KiB of redundancy in a browser bundle. Only the rows that say something non-obvious travel;
  // `isFoldable` below restores the pg rule.
  const foldable = (await q<Record<string, unknown>>(
    `SELECT collection, stat_id, engine FROM base_stat_foldable WHERE engine <> 'pg' ORDER BY collection, stat_id, engine`))
    .map((r): FoldableRow => ({ collection: String(r.collection), stat: String(r.stat_id), engine: String(r.engine) }))

  return { hash, builtAt: new Date().toISOString(), functions, collections, carriers, engines, columnGroups, grants, foldable }
}

/** Postgres array literal → string[]. The snapshot casts arrays to ::text so the driver hands back one shape on
 *  every backend (pglite and node-postgres disagree about array parsing per type). */
export function pgArray(text: string): string[] {
  const inner = text.replace(/^\{|\}$/g, '')
  if (!inner) return []
  const out: string[] = []
  let cur = '', quote = false
  for (let i = 0; i < inner.length; i++) {
    const ch = inner[i]
    if (quote) { if (ch === '\\') { cur += inner[++i]; continue } if (ch === '"') { quote = false; continue } cur += ch; continue }
    if (ch === '"') { quote = true; continue }
    if (ch === ',') { out.push(cur); cur = ''; continue }
    cur += ch
  }
  out.push(cur)
  return out
}

// LOADING the artifact is deliberately NOT here. A static `import './catalog-snapshot.json'` would make the whole
// package fail to typecheck or bundle whenever the artifact has not been generated — which is the normal state of a
// source checkout, since it is gitignored. So each ENTRY loads it the way its environment can tolerate a missing
// file: node.ts reads it off disk in a try/catch, and index.ts (the Vite entry) uses import.meta.glob, which
// resolves to an empty record rather than a build error when nothing matches.

// ── grant resolution, ported from SQL ─────────────────────────────────────────────────────────────────────────────
// The SAME fold as policies.sql's policy_rows/policy_resolve, applied to engine grants: rows ordered GENERAL →
// SPECIFIC, permissive appends, restrictive subtracts at the end and always wins. Two implementations of one rule
// is a differential waiting to happen, which is exactly why selfcert-engine asserts this equals engine_grants()
// for every (engine, collection) — the same discipline as the accelerated == naive oracle.
const TIER: Record<string, number> = { collection: 0, carrier: 1, category: 2, tag: 2, all: 3 }

/** The column groups `engine` is granted at `coll`'s scope. A FROM-less expression has no collection: pass null,
 *  and only the `all`-scoped rows apply. */
/** Can `engine` evaluate this statistic itself (so a predicate on it pushes into the engine rather than filtering
 *  pg's element stream after the fact)? pg always can — the statistic IS a pg function. */
export const isFoldable = (snap: CatalogSnapshot, engine: string, coll: string, stat: string): boolean =>
  engine === 'pg' || snap.foldable.some((f) => f.engine === engine && f.collection === coll && f.stat === stat)

export function grantsFor(snap: CatalogSnapshot, engine: string, coll: string | null): string[] {
  const c = coll == null ? null : snap.collections.find((x) => x.id === coll)
  const applies = (g: GrantRow): boolean => {
    switch (g.scopeKind) {
      case 'all': return true
      case 'collection': return c != null && g.scope === c.id
      case 'carrier': return c != null && g.scope === c.carrier
      case 'category': return c != null && g.scope === c.category
      case 'tag': return c != null && c.tags.includes(g.scope)
      default: return false
    }
  }
  const rows = snap.grants.filter((g) => g.engine === engine && applies(g))
    .sort((a, b) => TIER[b.scopeKind] - TIER[a.scopeKind])   // general first, as policy_rows orders them
  const acc: string[] = []
  const revoked: string[] = []
  for (const g of rows) {
    if (g.mode === 'restrictive') revoked.push(g.columnGroup)
    else if (!acc.includes(g.columnGroup)) acc.push(g.columnGroup)
  }
  return acc.filter((x) => !revoked.includes(x))
}
