// Generates `packs-entry/<pack>.ts` for every pack in EXTRACTED_PACKS (pack-map.ts) — the real files
// `"./packs/*": "./packs-entry/*.ts"` (package.json) resolves `@enumeratio/data/packs/<p>` to (#321, wiki §7).
// A tiny, deterministic codemod in the same spirit as pack-migrate.mts: idempotent, `--check` reports drift
// without writing, and it's the acceptance test for "is packs-entry/ in sync with EXTRACTED_PACKS". Regenerate
// (`pnpm --filter @enumeratio/data gen-pack-entries`) whenever a pack lands or leaves EXTRACTED_PACKS — nothing in
// packs-entry/ should ever be hand-edited.
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { extractedPacks } from './pack-map.ts'

const here = dirname(fileURLToPath(import.meta.url))
const outDir = join(here, 'packs-entry')

function contentFor(pack: string): string {
  return [
    `// AUTO-GENERATED by gen-pack-entries.mts — do not hand-edit.`,
    `// Subpath: @enumeratio/data/packs/${pack} (#321, wiki Core-And-Packs §7). Regenerate`,
    `// (\`pnpm --filter @enumeratio/data gen-pack-entries\`) whenever EXTRACTED_PACKS (pack-map.ts) changes.`,
    `import { packEntry } from '../pack-entry.ts'`,
    ``,
    `export const { name, requiresPack, files, manifest, fragment } = packEntry('${pack}')`,
    ``,
  ].join('\n')
}

const wanted = new Map(extractedPacks().map(p => [`${p}.ts`, contentFor(p)]))
const checkOnly = process.argv.includes('--check')

const existing = existsSync(outDir)
  ? Object.fromEntries(readdirSync(outDir).filter(f => f.endsWith('.ts')).map(f => [f, readFileSync(join(outDir, f), 'utf8')]))
  : {}

const stale = Object.keys(existing).filter(f => !wanted.has(f))
const missingOrDrifted = [...wanted.entries()].filter(([f, content]) => existing[f] !== content).map(([f]) => f)

if (checkOnly) {
  if (stale.length === 0 && missingOrDrifted.length === 0) {
    console.log(`gen-pack-entries --check: packs-entry/ matches EXTRACTED_PACKS (${wanted.size} pack(s)) — clean`)
    process.exit(0)
  }
  for (const f of stale) console.error(`gen-pack-entries --check: stale (no longer in EXTRACTED_PACKS): packs-entry/${f}`)
  for (const f of missingOrDrifted) console.error(`gen-pack-entries --check: missing/out of date: packs-entry/${f}`)
  console.error(`gen-pack-entries --check: run \`pnpm --filter @enumeratio/data gen-pack-entries\` to fix`)
  process.exit(1)
}

mkdirSync(outDir, { recursive: true })
for (const f of stale) { rmSync(join(outDir, f)); console.log(`gen-pack-entries: removed stale packs-entry/${f}`) }
for (const [f, content] of wanted) {
  if (existing[f] === content) continue
  writeFileSync(join(outDir, f), content)
  console.log(`gen-pack-entries: wrote packs-entry/${f}`)
}
console.log(`gen-pack-entries: packs-entry/ now matches EXTRACTED_PACKS (${wanted.size} pack(s))`)
