// Shared payload builder for the `@enumeratio/data/packs/<p>` subpath exports (#283 phase 4, wiki §7): "that
// pack's ordered files + manifest + snapshot fragment". Node-only (fs, via node.ts) — like node.ts itself, this
// works in a plain node/tsx consumer with no bundler, in BOTH a source checkout and a published npm install (the
// package's `files` list ships `packs/`, `sqlsrc/` and `catalog-snapshot.*.json` alongside `*.ts`).
//
// Each pack gets its OWN tiny entry file (`packs-entry/<pack>.ts`, generated by gen-pack-entries.mts) that just
// calls `packEntry('<pack>')` and re-exports the result — package.json's `"./packs/*": "./packs-entry/*.ts"`
// wildcard maps the import specifier to that real file. A single shared module can't do this itself: an import
// specifier's wildcard match isn't passed into the resolved module at runtime, so "@enumeratio/data/packs/paths"
// and "@enumeratio/data/packs/tableaux" must resolve to two different files on disk, even though both just close
// over this one function with a different literal argument.
import { readFileSync } from 'node:fs'
import { catalogSnapshotFragmentPath, loadCoreAndPacks } from './node.ts'
import { orderPacks, segmentByPack, PACK_MANIFEST, type SqlFile } from './sqlsrc-order.ts'
import type { CatalogSnapshot } from './catalog-snapshot.ts'

export type PackEntry = {
  name: string
  /** This pack's declared `requires-pack` dependencies (pack-map.ts's PACK_DEPS should agree — build-control.mts
   *  cross-checks that at packaging time; this is just what the pack's own manifest says). */
  requiresPack: string[]
  /** This pack's own files, in DEPENDENCY ORDER (its manifest first, like `bootstrap` is core's) — the same
   *  order the real loader (node.ts/applyPackSegments) and build-control.mts's assembled extension SQL use, so
   *  "what this subpath exports" can never silently drift from "what loading this pack actually applies". */
  files: SqlFile[]
  /** Raw content of this pack's `_pack.sql` manifest (the `-- pack:` / `-- requires-pack:` header) — also present,
   *  unparsed, as one of `files` (basename `_pack`). */
  manifest: string
  /** This pack's catalog-snapshot fragment (`catalog-snapshot.<pack>.json`, build-catalog-snapshot.mts), or null
   *  when the release artifact hasn't been built (a source checkout before `pnpm build`) — same degrade-to-null
   *  contract as node.ts's loadCatalogSnapshotFragments. */
  fragment: CatalogSnapshot | null
}

/** Build the `@enumeratio/data/packs/<name>` subpath payload. Reuses the SAME `orderPacks`/`segmentByPack` the
 *  real loader and build-control.mts use (grouping every segment owned by `name` — a pack can legitimately
 *  produce more than one non-contiguous segment, see hash.ts's packHashes comment — rather than assuming one). */
export function packEntry(name: string): PackEntry {
  const { core, packs } = loadCoreAndPacks()
  const pack = packs.find(p => p.name === name)
  if (!pack) {
    throw new Error(`pack "${name}" not found under packs/ — check EXTRACTED_PACKS in pack-map.ts and re-run gen-pack-entries.mts`)
  }
  const ordered = orderPacks(core, packs)
  const segments = segmentByPack(ordered, core, packs)
  const files = segments.filter(s => s.pack === name).flatMap(s => s.files)
  const manifestFile = files.find(f => f.name === PACK_MANIFEST)

  let fragment: CatalogSnapshot | null = null
  try { fragment = JSON.parse(readFileSync(catalogSnapshotFragmentPath(name), 'utf8')) as CatalogSnapshot } catch {
    /* fragment never built (source checkout before `pnpm build`) — same degrade-to-null as loadCatalogSnapshotFragments */
  }

  return { name: pack.name, requiresPack: pack.requiresPack, files, manifest: manifestFile?.content ?? '', fragment }
}
