# Helpers the `oscar` emit templates call (packages/oracle/src/mappings.ts): our groups, with
# our element labels, built as Oscar permutation groups.
#
# Labels follow packages/groupalgebra/src/group.ts: Z_n is 0 … n−1 (rᵏ for the generating
# n-cycle), D_n is `k` = rᵏ and `sk` = s·rᵏ, and a direct product is `a/b`. A group is built
# once per constructor call site value, so `ClassSum(D(3), 2)` and the `D(3)` around it share
# one group algebra.

struct EnumeratioGroup
  G::PermGroup
  labels::Vector{String}
  elem::Dict{String,PermGroupElem}
  label::Dict{PermGroupElem,String}
  A::GroupAlgebra
end

const _enumeratio_groups = Dict{Any,EnumeratioGroup}()
const _enumeratio_by_algebra = IdDict{Any,EnumeratioGroup}()

function _enumeratio_labelled(key, G::PermGroup, pairs::Vector{Pair{String,PermGroupElem}})
  get!(_enumeratio_groups, key) do
    A = group_algebra(QQ, G)
    g = EnumeratioGroup(G, first.(pairs), Dict(pairs), Dict(e => l for (l, e) in pairs), A)
    _enumeratio_by_algebra[A] = g
    g
  end
end

function enumeratio_cyclic(G::PermGroup, n::Integer)
  r = n == 1 ? one(G) : gens(G)[1]
  _enumeratio_labelled((:cyclic, n), G, [string(k) => r^k for k in 0:n-1])
end

# `dihedral_group(PermGroup, 2n)` is generated by the rotation (1,…,n) and a reflection.
function enumeratio_dihedral(G::PermGroup, n::Integer)
  r, s = gens(G)
  _enumeratio_labelled((:dihedral, n), G,
    vcat([string(k) => r^k for k in 0:n-1], ["s$k" => s * r^k for k in 0:n-1]))
end

function enumeratio_direct_product(g::EnumeratioGroup, h::EnumeratioGroup)
  get(_enumeratio_groups, (:product, objectid(g), objectid(h))) do
    P = direct_product(g.G, h.G)
    into = isomorphism(PermGroup, P)
    Q = codomain(into)
    i1, i2 = canonical_injection(P, 1), canonical_injection(P, 2)
    pairs = [("$a/$b") => into(i1(g.elem[a]) * i2(h.elem[b])) for a in g.labels for b in h.labels]
    _enumeratio_labelled((:product, objectid(g), objectid(h)), Q, pairs)
  end
end

# A basis element before it knows its group: `GroupBasis("s0")` resolves against whichever
# group the enclosing head names.
struct EnumeratioBasis
  label::String
end

_enumeratio_element(g::EnumeratioGroup, x::EnumeratioBasis) = g.A(g.elem[x.label])
_enumeratio_element(g::EnumeratioGroup, x) = x

enumeratio_product(g::EnumeratioGroup, a, b) =
  _enumeratio_element(g, a) * _enumeratio_element(g, b)

# Conjugacy classes in OUR order: by each class's smallest label index, members ascending.
function enumeratio_classes(g::EnumeratioGroup)
  index = Dict(l => i for (i, l) in enumerate(g.labels))
  classes = [sort([g.label[e] for e in collect(c)], by = l -> index[l]) for c in conjugacy_classes(g.G)]
  sort(classes, by = c -> index[c[1]])
end

enumeratio_class_sum(g::EnumeratioGroup, k::Integer) =
  sum(g.A(g.elem[l]) for l in enumeratio_classes(g)[k])

function enumeratio_is_central(g::EnumeratioGroup, x)
  y = _enumeratio_element(g, x)
  all(y * g.A(e) == g.A(e) * y for e in gens(g.G))
end

# How the runner prints an algebra element: a label → coefficient map the scan compares
# against ours (oracle compare.ts, `compareCombination`).
function enumeratio_combination(x::GroupAlgebraElem)
  g = _enumeratio_by_algebra[parent(x)]
  c = coefficients(x)
  terms = ["\"GroupBasis($(l))\":$(c[parent(x).group_to_base[g.elem[l]]])" for l in g.labels
           if !iszero(c[parent(x).group_to_base[g.elem[l]]])]
  "combination:{" * join(terms, ",") * "}"
end
enumeratio_combination(x::EnumeratioBasis) = "combination:{\"GroupBasis($(x.label))\":1}"

show_oracle(x::GroupAlgebraElem) = enumeratio_combination(x)
show_oracle(x::EnumeratioBasis) = enumeratio_combination(x)
