// Native harness generator for the Python family (design/benchmarking.md §4.2): mpmath,
// SymPy and Sage share one runtime template and `preludeFor`'s preamble/printer, so a run
// gets the same answers the oracle scan already verified. Sage's own preparser only runs
// through `sage_eval` (packages/oracle/src/run.ts), and this generator runs in Node with no
// Sage on PATH to preparse against — so each Sage source is preparsed once at harness
// *startup* instead of at generation time, still outside the timed region.

import { fileURLToPath } from "node:url";
import { preludeFor } from "@enumeratio/oracle/src";
import { planned } from "../generate.ts";
import { PROTOCOL, QUIT } from "../protocol.ts";
import type { HarnessCommand } from "../run.ts";
import type { BenchSystem, Plan } from "../types.ts";

type PySystem = Extract<BenchSystem, "mpmath" | "sympy" | "sage">;
type Planned = ReturnType<typeof planned>;

const FILE: Record<PySystem, string> = {
  mpmath: "bench.py",
  sympy: "bench.py",
  sage: "bench.sage.py",
};

/** Whether each system's memo caches can be cleared before a sample (design/benchmarking.md §4.3). */
export const CACHES_MPMATH = "uncleared"; // no global cache worth clearing
export const CACHES_SYMPY = "cleared"; // sympy.core.cache.clear_cache()
export const CACHES_SAGE = "uncleared"; // sage.misc.cachefunc has no global clear

const CLEAR_BODY: Record<PySystem, string> = {
  mpmath: "pass",
  sympy: "sympy.core.cache.clear_cache()",
  sage: "pass",
};

/** The preamble assumes its caller's globals: the sympy REPL's `from sympy import *`, or
 * Sage's own `from sage.all import *`, which `sage -python` (plain Python) doesn't do for us. */
const EXTRA_IMPORTS: Record<PySystem, string> = {
  mpmath: "",
  sympy: "import sympy\n",
  sage: "from sage.all import *\n",
};

/** Precision, set per case outside the timing (§4.4). Only mpmath needs it: SymPy is exact-only
 * and Sage's mapped sources already emit the right kind of literal for `exact`/`machine`. */
const PRECISION_BODY: Record<PySystem, readonly string[]> = {
  mpmath: [
    'if precision == "machine":',
    "    mp.dps = 15",
    "elif isinstance(precision, int):",
    "    mp.dps = precision",
  ],
  sympy: ["pass"],
  sage: ["pass"],
};

const HEADER = `# Generated by @enumeratio/bench (src/generators/python.ts). Do not edit by hand; a
# mappings or catalogue change regenerates this file (design/benchmarking.md §4).
#
# Reads a case name per line on stdin, replies one line \`<<name>>{json}\` on stdout:
# \`{"value", "k", "samplesNs", "timedOut"}\`, or \`{"error"}\` for an unknown, unsupported or
# failing case.`;

const here = (path: string): string => fileURLToPath(new URL(path, import.meta.url));

function precisionLiteral(p: Plan["cases"][number]["precision"]): string {
  return typeof p === "number" ? String(p) : JSON.stringify(p);
}

/** Each source as a zero-argument callable, compiled/preparsed once, before any timing. */
function defsFor(system: PySystem, cases: Planned): string {
  if (system !== "sage") {
    const lines: string[] = [];
    for (const [i, c] of cases.entries())
      c.sources.forEach((source, j) => lines.push(`def _b${i}_${j}():`, `    return ${source}`));
    return lines.join("\n");
  }
  // Sage: the callables can't be preparsed until Sage itself runs, so they're built at
  // process startup instead, from a plain data list, still outside the timed region.
  const entries: string[] = [];
  for (const [i, c] of cases.entries())
    c.sources.forEach((source, j) =>
      entries.push(`    (${JSON.stringify(`_b${i}_${j}`)}, ${JSON.stringify(source)}),`),
    );
  return [
    "_sage_sources = [",
    ...entries,
    "]",
    "for _name, _src in _sage_sources:",
    '    globals()[_name] = sage_eval("lambda: (" + _src + ")", locals=globals())',
  ].join("\n");
}

function render(system: PySystem, plan: Plan): string {
  const prelude = preludeFor(system);
  const cases = planned(plan, system);
  const caseEntries = cases.map((c, i) => {
    const fns = c.sources.map((_, j) => `_b${i}_${j}`).join(", ");
    return `    ${JSON.stringify(c.name)}: {"precision": ${precisionLiteral(c.case.precision)}, "budget": ${c.case.budget}, "fns": [${fns}]},`;
  });
  return `${HEADER}

import json, sys, time
${EXTRA_IMPORTS[system]}
${prelude.preamble}

PROTOCOL = ${JSON.stringify(PROTOCOL, null, 4)}


def _clear():
    ${CLEAR_BODY[system]}


${defsFor(system, cases)}

CASES = {
${caseEntries.join("\n")}
}


def _measure(call, budget_ms):
    now = time.perf_counter_ns
    start = now()

    def spent():
        return (now() - start) / 1e6

    def time_k(k):
        _clear()
        t0 = now()
        for _ in range(k):
            call()
        return (now() - t0) / k

    k = 1
    single = max(time_k(1), 1)
    if single < PROTOCOL["batchBelowMs"] * 1e6:
        while single * k < PROTOCOL["minSampleMs"] * 1e6 and spent() < budget_ms:
            k *= 2
    w = 0
    while w < PROTOCOL["warmup"] and spent() < PROTOCOL["warmupMs"] and spent() < budget_ms:
        single = time_k(k)
        w += 1
    samples = []
    while len(samples) < PROTOCOL["samples"]:
        if len(samples) >= PROTOCOL["minSamples"] and spent() >= budget_ms:
            break
        samples.append(time_k(k))
        if spent() >= budget_ms * 4:
            break
    return {"k": k, "samplesNs": samples, "timedOut": len(samples) < PROTOCOL["minSamples"]}


def _value(x, precision):
    # The scan's printer goes through a double; at a digit precision print every digit.
    if isinstance(x, list):
        return "[" + ", ".join(_value(e, precision) for e in x) + "]"
    if isinstance(precision, int) and type(x).__name__ in ("mpf", "mpc"):
        return nstr(x, precision)
    return enumeratio_value(x)


def _set_precision(precision):
    ${PRECISION_BODY[system].join("\n    ")}


def run(name):
    case = CASES.get(name)
    if case is None:
        return {"error": "no case %s" % name}
    _set_precision(case["precision"])
    fns = case["fns"]
    value = _value(fns[0](), case["precision"])
    state = {"i": 0}

    def once():
        f = fns[state["i"] % len(fns)]
        state["i"] += 1
        return f()

    timed = _measure(once, case["budget"] * 1000)
    return {"value": value, **timed}


for _line in sys.stdin:
    _name = _line.strip()
    if _name == "":
        continue
    if _name == "${QUIT}":
        break
    try:
        _out = run(_name)
    except Exception as _exc:
        _out = {"error": (type(_exc).__name__ + ": " + str(_exc))[:200]}
    sys.stdout.write("<<%s>>%s\\n" % (_name, json.dumps(_out)))
    sys.stdout.flush()
`;
}

export function generateMpmath(plan: Plan): Readonly<Record<string, string>> {
  return { [FILE.mpmath]: render("mpmath", plan) };
}
export function generateSympy(plan: Plan): Readonly<Record<string, string>> {
  return { [FILE.sympy]: render("sympy", plan) };
}
export function generateSage(plan: Plan): Readonly<Record<string, string>> {
  return { [FILE.sage]: render("sage", plan) };
}

function harness(system: PySystem, command: string, args: readonly string[] = []): HarnessCommand {
  return { command, args: [...args, here(`../../generated/${system}/${FILE[system]}`)] };
}

export function harnessMpmath(): HarnessCommand {
  return harness("mpmath", "python3");
}
export function harnessSympy(): HarnessCommand {
  return harness("sympy", "python3");
}
export function harnessSage(): HarnessCommand {
  return harness("sage", "sage", ["-python"]);
}
