// Rust harness generator (design/benchmarking.md §4, packages/bench/src/generate.ts's
// contract). Writes a self-contained Cargo crate under `generated/rust/`: one `fn b_i_j() ->
// V` per source, compiled once, and a stdin/stdout loop implementing `measure()` from
// protocol.ts. Depends on `packages/oracle/rust` (the `V` adapters) by path; never edit that
// crate from here.

import { fileURLToPath } from "node:url";
import type { Generator } from "../generate.ts";
import { planned } from "../generate.ts";
import { PROTOCOL } from "../protocol.ts";
import type { HarnessCommand } from "../run.ts";
import type { Plan } from "../types.ts";

export const CACHES_RUST = "uncleared" as const;

/** Rust's literal constructors, black-boxed so LLVM can't fold or hoist a call whose inputs
 * are compile-time constants (design/benchmarking.md §4.2 asks the same of Julia's `Ref`s). */
function foldLiterals(source: string): string {
  return source
    .replace(/\bn\((-?\d+)\)/g, "n(std::hint::black_box($1))")
    .replace(/\bbig\("(-?\d+)"\)/g, 'big(std::hint::black_box("$1"))')
    .replace(/\bx\(([^()]*)\)/g, "x(std::hint::black_box($1))");
}

/** A Rust string literal for `s` (case names only; no escapes expected, but don't assume). */
function rustString(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

const MEASURE_RS = `
struct Timed {
    k: u64,
    samples_ns: Vec<f64>,
    timed_out: bool,
}

/** \`measure()\` from protocol.ts, verbatim: calibrate \`k\`, warm up, sample to the budget. */
fn measure(budget_ms: f64, call: &mut dyn FnMut()) -> Timed {
    let start = Instant::now();
    let spent = |start: Instant| start.elapsed().as_secs_f64() * 1e3;
    let time = |k: u64, call: &mut dyn FnMut()| -> f64 {
        let t0 = Instant::now();
        for _ in 0..k {
            call();
        }
        t0.elapsed().as_nanos() as f64 / k as f64
    };
    let mut k: u64 = 1;
    let mut single = time(1, call).max(1.0);
    if single < PROTOCOL_BATCH_BELOW_MS * 1e6 {
        while single * (k as f64) < PROTOCOL_MIN_SAMPLE_MS * 1e6 && spent(start) < budget_ms {
            k *= 2;
        }
    }
    let mut w = 0;
    while w < PROTOCOL_WARMUP && spent(start) < PROTOCOL_WARMUP_MS && spent(start) < budget_ms {
        single = time(k, call);
        w += 1;
    }
    let _ = single;
    let mut samples_ns: Vec<f64> = Vec::new();
    while samples_ns.len() < PROTOCOL_SAMPLES {
        if samples_ns.len() >= PROTOCOL_MIN_SAMPLES && spent(start) >= budget_ms {
            break;
        }
        samples_ns.push(time(k, call));
        if spent(start) >= budget_ms * 4.0 {
            break;
        }
    }
    let timed_out = samples_ns.len() < PROTOCOL_MIN_SAMPLES;
    Timed { k, samples_ns, timed_out }
}
`;

/** The Generator (packages/bench/src/generate.ts): the whole catalogue's rust-planned cases,
 * as one Cargo crate. */
export const generateRust: Generator = (plan: Plan) => {
  const cases = planned(plan, "rust");

  const fns: string[] = [];
  const entries: string[] = [];
  cases.forEach((c, i) => {
    const names = c.sources.map((source, j) => {
      const name = `b_${i}_${j}`;
      fns.push(`fn ${name}() -> V {\n    ${foldLiterals(source)}\n}`);
      return name;
    });
    entries.push(
      `    CaseEntry { name: ${rustString(c.name)}, budget_ms: ${(c.case.budget * 1000).toFixed(1)}, calls: &[${names.join(", ")}] },`,
    );
  });

  const mainRs = `// GENERATED by @enumeratio/bench/src/generators/rust.ts -- do not edit.
//
// One \`fn b_<case>_<source>() -> V\` per emitted source, compiled once; a stdin/stdout loop
// answers \`<<name>>{json}\` per line, implementing the protocol.ts measurement algorithm
// (\`measure\` below) against the \`enumeratio-oracle\` adapters. Caches: ${CACHES_RUST} (the
// crate's \`V\` operations keep no memo tables to clear).
#![allow(unused_parens, unused_imports, clippy::all)]

use enumeratio_oracle::*;
use std::cell::RefCell;
use std::hint::black_box;
use std::io::{self, BufRead, Write};
use std::panic::{catch_unwind, AssertUnwindSafe};
use std::time::Instant;

// PROTOCOL (packages/bench/src/protocol.ts), embedded verbatim; regenerate on any change there.
const PROTOCOL_WARMUP: u32 = ${PROTOCOL.warmup};
const PROTOCOL_WARMUP_MS: f64 = ${PROTOCOL.warmupMs}.0;
const PROTOCOL_SAMPLES: usize = ${PROTOCOL.samples};
const PROTOCOL_MIN_SAMPLES: usize = ${PROTOCOL.minSamples};
const PROTOCOL_BATCH_BELOW_MS: f64 = ${PROTOCOL.batchBelowMs}.0;
const PROTOCOL_MIN_SAMPLE_MS: f64 = ${PROTOCOL.minSampleMs}.0;
${MEASURE_RS}
struct CaseEntry {
    name: &'static str,
    budget_ms: f64,
    calls: &'static [fn() -> V],
}

${fns.join("\n\n")}

const CASES: &[CaseEntry] = &[
${entries.join("\n")}
];

fn json_string(s: &str) -> String {
    let mut out = String::from("\\"");
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\\\\""),
            '\\\\' => out.push_str("\\\\\\\\"),
            '\\n' => out.push_str("\\\\n"),
            '\\r' => out.push_str("\\\\r"),
            '\\t' => out.push_str("\\\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

// The panic hook, not the caught \`Box<dyn Any>\`, gets the message: downcasting that box after
// the fact is unreliable on some toolchains, but a hook sees the payload live, at the panic site.
thread_local! {
    static PANIC_MSG: RefCell<String> = const { RefCell::new(String::new()) };
}

fn install_panic_hook() {
    std::panic::set_hook(Box::new(|info| {
        let msg = match info.payload().downcast_ref::<&str>() {
            Some(s) => (*s).to_string(),
            None => info
                .payload()
                .downcast_ref::<String>()
                .cloned()
                .unwrap_or_else(|| info.to_string()),
        };
        PANIC_MSG.with(|c| *c.borrow_mut() = msg);
    }));
}

/** The last panic's message, as \`item()\` in lib.rs reports one: 200 chars max. */
fn panic_message() -> String {
    let msg = PANIC_MSG.with(|c| c.borrow().clone());
    let mut m = format!("panic: {}", msg.replace('\\n', " "));
    if m.len() > 200 {
        m.truncate(200);
    }
    m
}

fn run_case(entry: &CaseEntry) -> String {
    let calls = entry.calls;
    let budget_ms = entry.budget_ms;
    let outcome = catch_unwind(AssertUnwindSafe(|| {
        // The value: once, before timing, the way the oracle scan prints it (\`Show\`, lib.rs).
        let value = calls[0]().show();
        let mut next = 0usize;
        let mut call = || {
            let v = calls[next % calls.len()]();
            next += 1;
            black_box(v);
        };
        let timed = measure(budget_ms, &mut call);
        (value, timed)
    }));
    match outcome {
        Ok((value, timed)) => {
            let samples = timed
                .samples_ns
                .iter()
                .map(|v| v.to_string())
                .collect::<Vec<_>>()
                .join(",");
            format!(
                "{{\\"value\\":{},\\"k\\":{},\\"samplesNs\\":[{}],\\"timedOut\\":{}}}",
                json_string(&value),
                timed.k,
                samples,
                timed.timed_out
            )
        }
        Err(_) => format!("{{\\"error\\":{}}}", json_string(&panic_message())),
    }
}

fn main() {
    install_panic_hook();
    let stdin = io::stdin();
    let stdout = io::stdout();
    let mut out = stdout.lock();
    for line in stdin.lock().lines() {
        let name = match line {
            Ok(l) => l.trim().to_string(),
            Err(_) => break,
        };
        if name.is_empty() {
            continue;
        }
        let reply = match CASES.iter().find(|c| c.name == name) {
            Some(c) => run_case(c),
            None => format!("{{\\"error\\":{}}}", json_string(&format!("no case {name}"))),
        };
        let _ = writeln!(out, "<<{name}>>{reply}");
        let _ = out.flush();
    }
}
`;

  const cargoToml = `# GENERATED by @enumeratio/bench/src/generators/rust.ts -- do not edit.
[package]
name = "enumeratio-bench-rust"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "bench"
path = "src/main.rs"

[dependencies]
enumeratio-oracle = { path = "../../../oracle/rust" }

[profile.release]
opt-level = 3
`;

  const gitignore = `target/\n`;

  // Pinned to match packages/oracle/rust/rust-toolchain.toml: the `V` adapters and this crate
  // must build with the same compiler.
  const toolchain = `[toolchain]
channel = "1.98.1"
profile = "minimal"
`;

  return {
    "Cargo.toml": cargoToml,
    "src/main.rs": mainRs,
    ".gitignore": gitignore,
    "rust-toolchain.toml": toolchain,
  };
};

const here = (path: string): string => fileURLToPath(new URL(path, import.meta.url));
const CRATE_DIR = here("../../generated/rust");

/** `cargo build`, once, then exec the binary directly (so a SIGKILL past budget lands on the
 * harness itself, not on a `cargo run` parent). */
export function harnessRust(): HarnessCommand {
  return {
    command: "sh",
    args: ["-c", "cargo build --release --quiet && exec ./target/release/bench"],
    cwd: CRATE_DIR,
  };
}
