// The Wolfram Language harness (design/benchmarking.md §4.2). wolframscript runs its kernel
// over a link, so the kernel can't read our stdin: the harness connects back to the
// coordinator over TCP instead (`socket`). Each source is parsed once when the script loads,
// held, and released inside the timing; `ClearSystemCache[]` runs before every sample.

import { fileURLToPath } from "node:url";
import { planned } from "../generate.ts";
import { PROTOCOL, QUIT } from "../protocol.ts";
import type { HarnessCommand } from "../run.ts";
import type { Plan, Precision } from "../types.ts";

export const CACHES_WOLFRAM = "cleared";

/** A WL string literal. */
const str = (s: string): string => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;

/**
 * Mark every decimal literal with a precision: a bare backtick keeps a long decimal (as a
 * shortest round-trip double often is) at machine precision, and `` `d `` lifts an input to
 * `d` digits, since `N[f[3.5], 30]` can't raise a machine input's precision.
 */
const markDecimals = (source: string, mark: string): string =>
  source.replace(/(?<![\w`.])(\d+\.\d+(?:\*\^-?\d+)?)(?![\d`])/g, `$1\`${mark}`);

export const numeric = (source: string, precision: Precision): string =>
  precision === "exact"
    ? source
    : precision === "machine"
      ? `N[${markDecimals(source, "")}]`
      : `N[${markDecimals(source, String(precision))}, ${precision}]`;

export function generateWolfram(plan: Plan): Record<string, string> {
  const cases = planned(plan, "wolfram").map(
    (c) =>
      `  ${str(c.name)} -> <|"budget" -> ${c.case.budget}, "calls" -> {${c.sources
        .map((s) => `Hold[${numeric(s, c.case.precision)}]`)
        .join(", ")}}|>`,
  );
  const p = PROTOCOL;
  const script = `(* Generated by packages/bench/scripts/generate.ts from the catalogue; do not edit.
   wolframscript -file bench.wl <port>: connects to the coordinator on 127.0.0.1:<port>. *)

protocol = <|"warmup" -> ${p.warmup}, "warmupMs" -> ${p.warmupMs}, "samples" -> ${p.samples}, "minSamples" -> ${p.minSamples}, "batchBelowMs" -> ${p.batchBelowMs}, "minSampleMs" -> ${p.minSampleMs}|>;

cases = <|
${cases.join(",\n")}
|>;

(* ns per call over k calls, caches cleared first; calls cycle through the sampled inputs *)
next = 0;
call[calls_] := ReleaseHold[calls[[Mod[next++, Length[calls]] + 1]]];
timeK[calls_, k_] := (ClearSystemCache[]; 10.^9 First[AbsoluteTiming[Do[call[calls], {k}]]]/k);

(* measure() in packages/bench/src/protocol.ts *)
measure[calls_, budgetMs_] := Module[{start = SessionTime[], spent, k = 1, single, samples = {}, w = 0},
  spent := 1000 (SessionTime[] - start);
  single = Max[timeK[calls, 1], 1];
  If[single < 10^6 protocol["batchBelowMs"],
    While[single k < 10^6 protocol["minSampleMs"] && spent < budgetMs, k *= 2]];
  While[w < protocol["warmup"] && spent < protocol["warmupMs"] && spent < budgetMs,
    single = timeK[calls, k]; w++];
  While[Length[samples] < protocol["samples"],
    If[Length[samples] >= protocol["minSamples"] && spent >= budgetMs, Break[]];
    AppendTo[samples, timeK[calls, k]];
    If[spent >= 4 budgetMs, Break[]]];
  <|"k" -> k, "samplesNs" -> samples, "timedOut" -> Length[samples] < protocol["minSamples"]|>];

sock = SocketConnect[{"127.0.0.1", ToExpression[Last[$ScriptCommandLine]]}];
reply[name_, assoc_] := WriteString[sock, "<<", name, ">>", ExportString[assoc, "RawJSON", "Compact" -> True], "\\n"];

run[name_] := If[!KeyExistsQ[cases, name],
  reply[name, <|"error" -> "no case " <> name|>],
  Module[{c = cases[name], value},
    value = Quiet[Check[ReleaseHold[First[c["calls"]]], $Failed]];
    If[value === $Failed,
      reply[name, <|"error" -> "evaluation failed"|>],
      next = 0;
      reply[name, Join[<|"value" -> ToString[value, InputForm], "version" -> $Version|>, measure[c["calls"], 1000 c["budget"]]]]]]];

While[StringQ[line = ReadLine[sock]] && line =!= "${QUIT}", run[line]];
Close[sock];
`;
  return { "bench.wl": script };
}

export const harnessWolfram = (): HarnessCommand => ({
  command: "wolframscript",
  args: ["-file", fileURLToPath(new URL("../../generated/wolfram/bench.wl", import.meta.url))],
  socket: true,
});
