// The originally hand-authored collections, expressed as NumberKernel[] over the certified kernel library
// (./kernels*.ts). Same registration mechanism as the other families — no special-casing in library.ts.
import type { NumberKernel } from "./types.ts";
import {
  CompositionCount,
  CompositionFromMask,
  CompositionRank,
  IsCompositionOf,
  BellB,
  RgsUnrank,
  RgsRank,
  RgsToBlocks,
  BlocksToRgs,
  IsSetPartitionOf,
  StirlingS2,
  SetPartitionsIntoKBlocksUnrank,
  SetPartitionsIntoKBlocksRank,
  Fubini,
  SetCompositionUnrank,
  SetCompositionRank,
  LabelsToOrderedBlocks,
  BlocksToLabels,
} from "./kernels-combinatorics.ts";
import {
  SubsetCount,
  SubsetUnrank,
  SubsetRank,
  IsSubsetOf,
  KSubsetCount,
  KSubsetUnrank,
  KSubsetRank,
  IsKSubsetOf,
  TupleCount,
  TupleUnrank,
  TupleRank,
  IsTupleOf,
  CompositionsIntoKPartsCount,
  CompositionsIntoKPartsUnrank,
  CompositionsIntoKPartsRank,
  IsCompositionIntoKParts,
  WeakCompositionCount,
  WeakCompositionUnrank,
  WeakCompositionRank,
  IsWeakCompositionOf,
  MultisetCount,
  MultisetUnrank,
  MultisetRank,
  IsMultisetOf,
  LatticePathCount,
  LatticePathUnrank,
  LatticePathRank,
  IsLatticePathOf,
  DyckPathCount,
  DyckPathUnrank,
  DyckPathRank,
  IsDyckPath,
  LabeledTreeCount,
  LabeledTreeUnrank,
  LabeledTreeRank,
  IsLabeledTreeOf,
  MotzkinCount,
  MotzkinUnrank,
  MotzkinRank,
  IsMotzkinPath,
  FibonacciWordCount,
  FibonacciWordUnrank,
  FibonacciWordRank,
  IsFibonacciWord,
  GrayCodeSubsetUnrank,
  GrayCodeSubsetRank,
  BinaryTreeCount,
  BinaryTreeUnrank,
  BinaryTreeRank,
  IsBinaryTree,
  BinaryTreeParentArray,
  BinaryTreeOfParentArray,
  IsBinaryTreeParentArray,
  type BinTree,
  SchroederCount,
  SchroederUnrank,
  SchroederRank,
  IsSchroederPath,
  OrderedTreeCount,
  OrderedTreeUnrank,
  OrderedTreeRank,
  IsOrderedTree,
  type OrdTree,
  KAryTreeCount,
  KAryTreeUnrank,
  KAryTreeRank,
  IsKAryTree,
  type KTree,
  SurjectionCount,
  SurjectionUnrank,
  SurjectionRank,
  IsSurjectionOf,
  BinaryStringCount,
  BinaryStringUnrank,
  BinaryStringRank,
  IsBinaryString,
  PerfectMatchingCount,
  PerfectMatchingUnrank,
  PerfectMatchingRank,
  IsPerfectMatchingOf,
  RootedForestCount,
  RootedForestUnrank,
  RootedForestRank,
  IsRootedForest,
} from "./kernels-extra.ts";

// helper to cut boilerplate for the flat (number[]) shape; casts the unknown element once here,
// same pattern subsets.ts uses at each call site.
const ints = (
  head: string,
  paramCount: 1 | 2,
  count: (p: number[]) => number,
  unrank: (p: number[], r: number) => number[],
  valid: (e: number[], p: number[]) => boolean,
  rank: (e: number[], p: number[]) => number,
): NumberKernel => ({
  head,
  paramCount,
  kind: "ints",
  count,
  unrank,
  valid: (e, p) => valid(e as number[], p),
  rank: (e, p) => rank(e as number[], p),
});

// The compositions section, kept separate from `entries` below only so
// collections/src/families/index.ts can splice `partitionsCoreEntries` back in at the exact
// interior position the (now moved) "partitions" section held between them — §4 step 5,
// https://github.com/enumeratio/enumeratio/wiki/Speculative-Combinatorics-Layering-and-Plausible.
export const compositionsEntries: NumberKernel[] = [
  // ── compositions ──
  {
    ...ints(
      "IntegerCompositions",
      1,
      ([n]) => CompositionCount(n),
      ([n], r) => CompositionFromMask(n, r),
      (a, [n]) => IsCompositionOf(a, n),
      (a) => CompositionRank(a),
    ),
    carrier: "Composition",
  },
  ints(
    "CompositionsIntoKParts",
    2,
    ([n, k]) => CompositionsIntoKPartsCount(n, k),
    ([n, k], r) => CompositionsIntoKPartsUnrank(n, k, r),
    (a, [n, k]) => IsCompositionIntoKParts(a, n, k),
    (a) => CompositionsIntoKPartsRank(a),
  ),
  ints(
    "WeakCompositions",
    2,
    ([n, k]) => WeakCompositionCount(n, k),
    ([n, k], r) => WeakCompositionUnrank(n, k, r),
    (a, [n, k]) => IsWeakCompositionOf(a, n, k),
    (a) => WeakCompositionRank(a),
  ),
];

export const entries: NumberKernel[] = [
  // ── subsets / multisets / tuples / functions / binary words ──
  ints(
    "Subsets",
    1,
    ([n]) => SubsetCount(n),
    ([n], r) => SubsetUnrank(n, r),
    (a, [n]) => IsSubsetOf(a, n),
    (a) => SubsetRank(a),
  ),
  ints(
    "KSubsets",
    2,
    ([n, k]) => KSubsetCount(n, k),
    ([n, k], r) => KSubsetUnrank(n, k, r),
    (a, [n, k]) => IsKSubsetOf(a, n, k),
    (a) => KSubsetRank(a),
  ),
  ints(
    "GrayCodeSubsets",
    1,
    ([n]) => SubsetCount(n),
    ([n], r) => GrayCodeSubsetUnrank(n, r),
    (a, [n]) => IsSubsetOf(a, n),
    (a) => GrayCodeSubsetRank(a),
  ),
  ints(
    "Multisets",
    2,
    ([n, k]) => MultisetCount(n, k),
    ([n, k], r) => MultisetUnrank(n, k, r),
    (a, [n, k]) => IsMultisetOf(a, n, k),
    (a) => MultisetRank(a),
  ),
  ints(
    "Tuples",
    2,
    ([n, k]) => TupleCount(n, k),
    ([n, k], r) => TupleUnrank(n, k, r),
    (a, [n, k]) => IsTupleOf(a, n, k),
    (a, [n]) => TupleRank(a, n),
  ),
  {
    ...ints(
      "Surjections",
      2,
      ([n, k]) => SurjectionCount(n, k),
      ([n, k], r) => SurjectionUnrank(n, k, r),
      (a, [n, k]) => IsSurjectionOf(a, n, k),
      (a, [, k]) => SurjectionRank(a, k),
    ),
    carrier: "Surjection",
  },
  ints(
    "Endofunctions",
    1,
    ([n]) => n ** n,
    ([n], r) => TupleUnrank(n, n, r),
    (a, [n]) => IsTupleOf(a, n, n),
    (a, [n]) => TupleRank(a, n),
  ),
  ints(
    "BinaryStrings",
    1,
    ([n]) => BinaryStringCount(n),
    ([n], r) => BinaryStringUnrank(n, r),
    (a, [n]) => IsBinaryString(a, n),
    (a) => BinaryStringRank(a),
  ),

  // ── lattice-path words ──
  ints(
    "LatticePaths",
    2,
    ([a, b]) => LatticePathCount(a, b),
    ([a, b], r) => LatticePathUnrank(a, b, r),
    (x, [a, b]) => IsLatticePathOf(x, a, b),
    (x) => LatticePathRank(x),
  ),
  {
    ...ints(
      "DyckPaths",
      1,
      ([n]) => DyckPathCount(n),
      ([n], r) => DyckPathUnrank(n, r),
      (a, [n]) => IsDyckPath(a, n),
      (a) => DyckPathRank(a),
    ),
    carrier: "DyckPath",
  },
  ints(
    "MotzkinPaths",
    1,
    ([n]) => MotzkinCount(n),
    ([n], r) => MotzkinUnrank(n, r),
    (a, [n]) => IsMotzkinPath(a, n),
    (a) => MotzkinRank(a),
  ),
  ints(
    "SchroederPaths",
    1,
    ([n]) => SchroederCount(n),
    ([n], r) => SchroederUnrank(n, r),
    (a, [n]) => IsSchroederPath(a, n),
    (a) => SchroederRank(a),
  ),
  ints(
    "FibonacciWords",
    1,
    ([n]) => FibonacciWordCount(n),
    ([n], r) => FibonacciWordUnrank(n, r),
    (a, [n]) => IsFibonacciWord(a, n),
    (a) => FibonacciWordRank(a),
  ),

  // ── set partitions / matchings (blocks) ──
  {
    head: "SetPartitions",
    carrier: "SetPartition",
    paramCount: 1,
    kind: "blocks",
    count: ([n]) => BellB(n),
    unrank: ([n], r) => RgsToBlocks(RgsUnrank(n, r)),
    valid: (b, [n]) => IsSetPartitionOf(b as number[][], n),
    rank: (b, [n]) => RgsRank(BlocksToRgs(b as number[][], n)),
  },
  {
    head: "SetPartitionsIntoKBlocks",
    carrier: "SetPartition",
    paramCount: 2,
    kind: "blocks",
    count: ([n, k]) => StirlingS2(n, k),
    unrank: ([n, k], r) => RgsToBlocks(SetPartitionsIntoKBlocksUnrank(n, k, r)),
    valid: (b, [n, k]) => IsSetPartitionOf(b as number[][], n, k),
    rank: (b, [n, k]) => SetPartitionsIntoKBlocksRank(BlocksToRgs(b as number[][], n), k),
  },
  {
    head: "SetCompositions",
    carrier: "SetComposition",
    paramCount: 1,
    kind: "blocks",
    count: ([n]) => Fubini(n),
    unrank: ([n], r) => LabelsToOrderedBlocks(SetCompositionUnrank(n, r)),
    valid: (b, [n]) => IsSetPartitionOf(b as number[][], n),
    rank: (b, [n]) => SetCompositionRank(BlocksToLabels(b as number[][]), n),
  },
  {
    head: "PerfectMatchings",
    paramCount: 1,
    kind: "blocks",
    count: ([n]) => PerfectMatchingCount(n),
    unrank: ([n], r) => PerfectMatchingUnrank(n, r),
    valid: (b, [n]) => IsPerfectMatchingOf(b, n),
    rank: (b, [n]) => PerfectMatchingRank(b as number[][], n),
  },
  {
    head: "LabeledTrees",
    paramCount: 1,
    kind: "blocks",
    count: ([n]) => LabeledTreeCount(n),
    unrank: ([n], r) => LabeledTreeUnrank(n, r),
    valid: (e, [n]) => IsLabeledTreeOf(e as number[][], n),
    rank: (e, [n]) => LabeledTreeRank(e as number[][], n),
  },
  {
    head: "RootedForests",
    paramCount: 1,
    kind: "ints",
    count: ([n]) => RootedForestCount(n),
    unrank: ([n], r) => RootedForestUnrank(n, r),
    valid: (a, [n]) => IsRootedForest(a, n),
    rank: (a, [n]) => RootedForestRank(a as number[], n),
  },

  // ── trees with nested elements (leaf 0 / [], node = children) ──
  {
    head: "BinaryTrees",
    paramCount: 1,
    kind: "nested",
    carrier: "BinaryTree",
    count: ([n]) => BinaryTreeCount(n),
    unrank: ([n], r) => BinaryTreeUnrank(n, r),
    valid: (e, [n]) => IsBinaryTree(e, n),
    rank: (e) => BinaryTreeRank(e as BinTree),
  },
  {
    declared: {
      carrier: "BinaryTreeParentArray",
      params: [{ name: "n", role: "axis", min: 0 }],
      cost: { count: "closed", unrank: "polynomial", rank: "polynomial", valid: "polynomial" },
    },
    head: "BinaryTreeParentArrays",
    paramCount: 1,
    kind: "ints",
    carrier: "BinaryTreeParentArray",
    count: ([n]) => BinaryTreeCount(n),
    unrank: ([n], r) => BinaryTreeParentArray(BinaryTreeUnrank(n, r)),
    valid: (e, [n]) => IsBinaryTreeParentArray(e, n),
    rank: (e) => BinaryTreeRank(BinaryTreeOfParentArray(e as number[]) ?? 0),
  },
  {
    head: "KAryTrees",
    paramCount: 2,
    kind: "nested",
    count: ([n, k]) => KAryTreeCount(n, k),
    unrank: ([n, k], r) => KAryTreeUnrank(n, k, r),
    valid: (e, [n, k]) => IsKAryTree(e, n, k),
    rank: (e, [, k]) => KAryTreeRank(e as KTree, k),
  },
  {
    head: "OrderedTrees",
    paramCount: 1,
    kind: "nested",
    count: ([n]) => OrderedTreeCount(n),
    unrank: ([n], r) => OrderedTreeUnrank(n, r),
    valid: (e, [n]) => IsOrderedTree(e, n),
    rank: (e) => OrderedTreeRank(e as OrdTree),
  },
];
