// GENERATED by scripts/generate-map-laws.ts from each map's own record (reference/<Name>/
// index.md's `laws:`). Do not edit: rerun the script after changing a record's laws.
import type { Law } from "@enumeratio/structures";

export interface MapLaws {
  readonly laws?: readonly Law[];
  readonly orderIsomorphism?: { readonly from: string; readonly to: string; readonly sizeOffset?: number };
}

export const MAP_LAWS: Readonly<Record<string, MapLaws>> = {
  "BinaryTree@binary_tree_parent_array": {
    laws: [{ inverse: "BinaryTreeParentArray" }],
    orderIsomorphism: { from: "BinaryTreeParentArrays", to: "BinaryTrees" },
  },
  "BinaryTree@dyck_path": { laws: [{ inverse: "DyckPath" }] },
  "BinaryTreeParentArray@binary_tree": {
    laws: [{ inverse: "BinaryTree" }],
    orderIsomorphism: { from: "BinaryTrees", to: "BinaryTreeParentArrays" },
  },
  "Complement@permutation": { laws: ["involution"] },
  "Composition@binary_word": {
    laws: [{ inverse: "CutWord" }],
    orderIsomorphism: { from: "BinaryWords", to: "IntegerCompositions", sizeOffset: 1 },
  },
  "ConjugacyClassRepresentative@permutation": { laws: ["idempotent"] },
  "CutWord@composition": {
    laws: [{ inverse: "Composition" }],
    orderIsomorphism: { from: "IntegerCompositions", to: "BinaryWords", sizeOffset: -1 },
  },
  "CycleDecomposition@permutation": { laws: [{ inverse: "Permutation" }] },
  "CyclicShift@permutation": { laws: [{ inverse: "InverseCyclicShift" }] },
  "DyckPath@binary_tree": { laws: [{ inverse: "BinaryTree" }] },
  "Inverse@permutation": { laws: ["involution"] },
  "InverseCyclicShift@permutation": { laws: [{ inverse: "CyclicShift" }] },
  "KnuthClassRepresentative@permutation": { laws: ["idempotent"] },
  "RestrictedGrowthString@set_partition": {
    laws: [{ inverse: "SetPartition" }],
    orderIsomorphism: { from: "SetPartitions", to: "RestrictedGrowthStrings" },
  },
  "Reverse@permutation": { laws: ["involution"] },
  "ReverseComplement@permutation": { laws: ["involution"] },
  "SetComposition@surjection": { laws: [{ inverse: "Surjection" }] },
  "SetPartition@restricted_growth_string": {
    laws: [{ inverse: "RestrictedGrowthString" }],
    orderIsomorphism: { from: "RestrictedGrowthStrings", to: "SetPartitions" },
  },
  "Surjection@set_composition": { laws: [{ inverse: "SetComposition" }] },
};
