// GENERATED by packages/reference/scripts/collect-summaries.ts — do not edit by hand.
//
// What this package's `ce.declare` calls read for `description` (symbol-metadata step 6,
// design/speculative/symbol-metadata.md): each head's record `summary`, one source instead
// of two. Regenerate with:
//
//   vp node packages/reference/scripts/collect-summaries.ts

export const SUMMARIES: Readonly<Record<string, string>> = {
  IntegerMod:
    "$a \\bmod m$ as a VALUE — an element of $\\mathbb{Z}/m$ that arithmetic stays inside, after Sage's `Mod(a, m)`.",
  IntegerModRing: "The ring $\\mathbb{Z}/m$, as the finite collection of its $m$ [[IntegerMod]] classes.",
  MultiplicativeOrder: "The smallest positive k such that a^k ≡ 1 (mod n).",
  PowerMod: "Modular exponentiation: a^b mod m, computed without forming a^b directly.",
  PowerModList: "Every $x$ in $[0, m)$ with $x^r \\equiv a^s \\pmod m$ — all the values $a^{s/r}$ can take modulo $m$.",
  PrimitiveRootList: "Every primitive root of $n$ — every generator of $(\\mathbb{Z}/n)^\\times$ — ascending.",
};
