// Turn enumeratio's carrier composite definitions into `src/domain-data.ts`.
//
// The input is one line per carrier, `name|field type, field type, …`, pulled from the
// CREATE TYPE statements in an enumeratio checkout:
//
//   grep -rhoE "CREATE TYPE [a-z_]+ AS \([^)]*\)" sqlsrc packs \
//     | grep -v "_fiber AS" \
//     | sed -E 's/CREATE TYPE ([a-z_]+) AS \((.*)\)/\1|\2/' > carrier-shapes.txt
//
// Shapes are real data rather than guesses, which matters: `set_partition` is stored as a
// RESTRICTED GROWTH STRING, not as a list of blocks, and no amount of reasoning from the
// name would have produced that.
//
// Run: node scripts/extract.ts carrier-shapes.txt

import { readFileSync, writeFileSync } from "node:fs";
import { typeFor } from "../src/types.ts";
import { PLURAL_OVERRIDES } from "./plural-overrides.ts";

const pascal = (id: string): string =>
  id
    .split("_")
    .filter(Boolean)
    .map((w) => w[0]!.toUpperCase() + w.slice(1))
    .join("");

/** The domain's TYPE-SPACE name (plural), or `undefined` for the two ids whose singular
 *  constructor already layers onto an unrelated real head instead (see `types.ts`'s
 *  `Domain.plural` doc). */
const pluralFor = (id: string): string | undefined =>
  id === "continued_fraction" || id === "permutation_cycles" ? undefined : (PLURAL_OVERRIDES[id] ?? `${pascal(id)}s`);

/** A Postgres field type, as the nearest compute-engine type. */
function typeOf(pg: string): string {
  if (pg === "int[]") return "list<integer>";
  if (pg === "numeric[]") return "list<number>";
  if (pg === "text[]") return "list<string>";
  if (pg === "int") return "integer";
  if (pg === "numeric") return "number";
  if (pg === "text") return "string";
  if (pg === "boolean") return "boolean";
  // A field whose type is another carrier — the composite carriers, which are the
  // interesting ones (a standard tableau pair is two tableaux). The carrier's TYPE is its id
  // verbatim, so this is just the field type unchanged.
  return typeFor(pg);
}

/** A carrier's shape: one field is that field's type, several make a tuple. */
function shapeOf(fields: string): string {
  const types = fields
    .split(",")
    .map((field) => field.trim())
    .filter(Boolean)
    .map((field) => typeOf(field.slice(field.indexOf(" ") + 1).trim()));
  return types.length === 1 ? types[0]! : `tuple<${types.join(", ")}>`;
}

const [, , path] = process.argv;
if (!path) throw new Error("usage: extract.ts <carrier-shapes.txt>");

const domains = readFileSync(path, "utf8")
  .split("\n")
  .filter((line) => line.includes("|"))
  .map((line) => {
    const [id = "", fields = ""] = line.split("|");
    const name = pascal(id);
    const plural = pluralFor(id);
    return { name, type: typeFor(id), shape: shapeOf(fields), id, ...(plural ? { plural } : {}) };
  })
  .sort((a, b) => a.name.localeCompare(b.name));

const body = `// GENERATED by scripts/extract.ts from enumeratio's carrier composite types. Do not edit.
//
// ${domains.length} carrier domains. The shape is the carrier's actual storage, not an
// idealisation of it — SetPartition is a restricted growth string, BinaryTree a flat int
// array, and both matter to anything that reaches inside a value.

import type { Domain } from "./types.ts";

export const DOMAINS: readonly Domain[] = ${JSON.stringify(domains, null, 2)};
`;
writeFileSync(new URL("../src/domain-data.ts", import.meta.url), body);
console.log(`domain-data.ts — ${domains.length} carrier domains`);
