// Per-carrier PLURAL overrides for scripts/extract.ts — the domain's TYPE-SPACE name
// (design/domains.md §2), never the constructor. English pluralization has real irregulars
// here (matrix -> matrices, tableau -> tableaux), so every carrier gets an explicit entry
// rather than a blind pascal-case + "s".
//
// Two ids are absent on purpose: `continued_fraction` and `permutation_cycles` layer their
// SINGULAR constructor onto a real, unrelated head (compute-engine's own continued-fraction
// expansion, Wolfram's cycle-notation conversion via `@enumeratio/groupalgebra`) and have no
// plural type-space name of their own — there is no "the ContinuedFractions" to be an
// element of.
export const PLURAL_OVERRIDES: Readonly<Record<string, string>> = {
  affine_permutation: "AffinePermutations",
  alternating_sign_matrix: "AlternatingSignMatrices",
  arrangement: "Arrangements",
  ascent_sequence: "AscentSequences",
  binary_tree: "BinaryTrees",
  binary_word: "BinaryWords",
  collatz_trajectory: "CollatzTrajectories",
  colored_motzkin_path: "ColoredMotzkinPaths",
  colored_permutation: "ColoredPermutations",
  composition: "Compositions",
  core_partition: "CorePartitions",
  decorated_permutation: "DecoratedPermutations",
  delannoy_path: "DelannoyPaths",
  dissection: "Dissections",
  distribution_match_hit: "DistributionMatchHits",
  dyck_path: "DyckPaths",
  egyptian_fraction: "EgyptianFractions",
  endofunction: "Endofunctions",
  factoradic_numeral: "FactoradicNumerals",
  factorization: "Factorizations",
  find_stat_hit: "FindStatHits",
  finite_set_element: "FiniteSetElements",
  finset: "Finsets",
  fraction: "Fractions",
  fractional_number: "FractionalNumbers",
  gaussian_fractional: "GaussianFractionals",
  gaussian_integer: "GaussianIntegers",
  gaussian_rational: "GaussianRationals",
  gelfand_tsetlin_pattern: "GelfandTsetlinPatterns",
  glyph_kind: "GlyphKinds",
  goldbach_partition: "GoldbachPartitions",
  hyperbinary_word: "HyperbinaryWords",
  hypernumerary_word: "HypernumeraryWords",
  increasing_binary_tree: "IncreasingBinaryTrees",
  integer_factorization: "IntegerFactorizations",
  integer_partition: "IntegerPartitions",
  k_ary_tree: "KAryTrees",
  k_dyck_path: "KDyckPaths",
  k_motzkin_path: "KMotzkinPaths",
  labeled_graph: "LabeledGraphs",
  labeled_tree: "LabeledTrees",
  lukasiewicz_path: "LukasiewiczPaths",
  modular_residue: "ModularResidues",
  motzkin_path: "MotzkinPaths",
  multicomplex: "Multicomplexes",
  multiplicative_partition: "MultiplicativePartitions",
  multiset: "Multisets",
  non_crossing_tree: "NonCrossingTrees",
  ordered_factorization: "OrderedFactorizations",
  ordered_tree: "OrderedTrees",
  parking_function: "ParkingFunctions",
  perfect_matching: "PerfectMatchings",
  permutation: "Permutations",
  permutation_inversion: "PermutationInversions",
  phylogenetic_tree: "PhylogeneticTrees",
  plane_partition: "PlanePartitions",
  plane_tree: "PlaneTrees",
  pythagorean_triple: "PythagoreanTriples",
  rational_dyck_path: "RationalDyckPaths",
  rational_number: "RationalNumbers",
  rook_placement: "RookPlacements",
  rooted_labeled_tree: "RootedLabeledTrees",
  rooted_unlabeled_tree: "RootedUnlabeledTrees",
  schroeder_path: "SchroederPaths",
  semistandard_tableau: "SemistandardTableaux",
  set_composition: "SetCompositions",
  set_partition: "SetPartitions",
  signed_permutation: "SignedPermutations",
  signed_set_composition: "SignedSetCompositions",
  signed_subset: "SignedSubsets",
  singleton: "Singletons",
  skew_partition: "SkewPartitions",
  skew_tableau: "SkewTableaux",
  square_decomposition: "SquareDecompositions",
  standard_tableau: "StandardTableaux",
  standard_tableau_pair: "StandardTableauPairs",
  subexcedant_seq: "SubexcedantSeqs",
  surjection: "Surjections",
  ternary_gray_code: "TernaryGrayCodes",
  total_partition: "TotalPartitions",
  tournament: "Tournaments",
  unlabeled_free_tree: "UnlabeledFreeTrees",
  weak_composition: "WeakCompositions",
  word: "Words",
};
