// The Vue face of the components, generated: one `.vue` per symbol, its props the
// element's attributes (read by `components.ts` from the element source), rendering the
// element inside `<ClientOnly>`. A page then writes `<Plot value="Sin(x)" />` or
// `<Histogram data="[1,2,2,3]" />` and gets a compile-time check on the spelling -- the
// same names the engine knows, in the template language (design/components-and-symbols.md
// §2). Emitted into `theme/generated/` (gitignored) when the site config loads, and
// registered by the theme from there; nothing is written into the repo.
//
// Two kinds of wrapper come out of one reading of the sources:
//   - one per component, named for its tag (`notatio-plot-3d` -> `Plot3D`);
//   - one per family member in `symbols.ts` (`Histogram` -> `<notatio-chart type="histogram">`),
//     the family tag's props with the member's attribute fixed.

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { VISUAL_SYMBOLS } from "@enumeratio/components/symbols";
import { type AttributeDoc, collectComponents, type ComponentDoc } from "./components.ts";

const here = dirname(fileURLToPath(import.meta.url));
export const generatedDir = resolve(here, "../theme/generated");

/** `notatio-plot-3d` -> `Plot3D`, `notatio-collection-table` -> `CollectionTable`. */
export function wrapperName(tag: string): string {
  return tag
    .replace(/^notatio-/, "")
    .split("-")
    .map((part) => (/^\d/.test(part) ? part.toUpperCase() : part[0].toUpperCase() + part.slice(1)))
    .join("");
}

/** The TypeScript type a prop takes, from the element's declared property type. */
function propType(a: AttributeDoc): string {
  if (/\bboolean\b/.test(a.type)) return "boolean";
  if (/\bnumber\b/.test(a.type)) return "number";
  return "string";
}

/** Escape for a JSDoc line inside the generated file. */
const doc = (text: string): string => text.replace(/\*\//g, "*\\/").replace(/\n+/g, " ");

function wrapperSource(
  name: string,
  component: ComponentDoc,
  fixed: Readonly<Record<string, string>> = {},
): string {
  const props = component.attributes.filter((a) => !a.propertyOnly && !(a.attribute in fixed));
  const lines = props.map((a) => {
    const comment = a.description ? `    /** ${doc(a.description)} */\n` : "";
    return `${comment}    ${a.property}?: ${propType(a)};`;
  });
  const fixedLiteral = JSON.stringify(fixed);
  return `<script setup lang="ts">
// GENERATED by web/.vitepress/data/wrappers.ts from ${component.source} -- do not edit.
// \`<${name}>\` is \`<${component.tag}>\` as a Vue component: props are the element's
// attributes, typed; anything undeclared falls through as an attribute.
import { computed } from "vue";

const props = defineProps<{
${lines.join("\n")}
}>();

// Only what the page set: an absent prop must not overwrite the element's own default.
const bound = computed(() => ({
  ...${fixedLiteral},
  ...Object.fromEntries(Object.entries(props).filter(([, v]) => v !== undefined)),
}));
</script>

<template>
  <ClientOnly>
    <${component.tag} v-bind="bound"><slot /></${component.tag}>
  </ClientOnly>
</template>
`;
}

/**
 * Emit every wrapper into `generatedDir`, replacing what was there. Returns the names,
 * in the order they were written.
 */
export function emitWrappers(): string[] {
  const components = collectComponents();
  const byTag = new Map(components.map((c) => [c.tag, c]));
  const files = new Map<string, string>();

  for (const component of components) {
    files.set(wrapperName(component.tag), wrapperSource(wrapperName(component.tag), component));
  }
  // A family member is the family's wrapper with the member's attribute fixed; a symbol
  // whose tag is its own name is already covered above.
  for (const symbol of VISUAL_SYMBOLS) {
    if (files.has(symbol.head) || symbol.fixed === undefined) continue;
    const component = byTag.get(symbol.tag);
    if (component) files.set(symbol.head, wrapperSource(symbol.head, component, symbol.fixed));
  }

  mkdirSync(generatedDir, { recursive: true });
  for (const stale of readdirSync(generatedDir)) {
    if (stale.endsWith(".vue") && !files.has(stale.slice(0, -4)))
      unlinkSync(join(generatedDir, stale));
  }
  for (const [name, source] of files) {
    const path = join(generatedDir, `${name}.vue`);
    // Leave an unchanged file alone so the dev server does not reload for nothing.
    if (existsSync(path) && readFileSync(path, "utf8") === source) continue;
    writeFileSync(path, source);
  }
  return [...files.keys()];
}
