// The symbols as Vue components, generated: one `defineComponent` per element, its props
// the element's attributes (read out of the element source by `@enumeratio/notatio/reflect`),
// rendering the element with only the props the page set -- an absent prop must not
// overwrite the element's own default, and a boolean is bound only when true, since an
// attribute that is present is an attribute that is on. A page then writes
// `<Plot value="Sin(x)" />` or `<Histogram data="[1,2,2,3]" />` and gets a compile-time
// check on the spelling: the same names the engine knows, in the template language
// (design/components-and-symbols.md §2, design/vdom.md).
//
// Two kinds of component come out of one reading of the sources:
//   - one per element, named for its tag (`notatio-plot-3d` -> `Plot3D`);
//   - one per family member in `symbols.ts` (`Histogram` -> `<notatio-chart type="histogram">`),
//     the family's props with the member's attribute fixed.
//
// Emitted into `src/generated.ts` (gitignored) by the build, or by whoever loads this
// module first -- the docs site's config does, so the file exists for the theme.

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  type AttributeDoc,
  collectComponents,
  type ComponentDoc,
  propType,
  wrapperName,
} from "@enumeratio/notatio/reflect";
import { VISUAL_SYMBOLS } from "@enumeratio/notatio/symbols";

const here = dirname(fileURLToPath(import.meta.url));

/** Where the element sources are: the sibling package, in a workspace checkout. */
export const defaultSrcDir = resolve(here, "../../notatio-lit/src");

/** Where the components are written. */
export const generatedPath = resolve(here, "./generated.ts");

/** Escape for a JSDoc line inside the generated file. */
const doc = (text: string): string => text.replace(/\*\//g, "*\\/").replace(/\n+/g, " ");

const vueType = (a: AttributeDoc): string =>
  ({ boolean: "Boolean", number: "Number", string: "String" })[propType(a)];

function componentSource(
  name: string,
  component: ComponentDoc,
  fixed: Readonly<Record<string, string>> = {},
): string {
  const props = component.attributes.filter((a) => !a.propertyOnly && !(a.attribute in fixed));
  const lines = props.map((a) => {
    const comment = a.description ? `    /** ${doc(a.description)} */\n` : "";
    return `${comment}    ${a.property}: { type: ${vueType(a)}, required: false },`;
  });
  return `/** \`<${name}>\` is \`<${component.tag}>\`: props are the element's attributes, typed. */
export const ${name} = defineComponent({
  name: ${JSON.stringify(name)},
  props: {
${lines.join("\n")}
  },
  setup(props, { slots }) {
    return () => h(${JSON.stringify(component.tag)}, bound(props, ${JSON.stringify(fixed)}), slots.default?.());
  },
});
`;
}

/** The whole generated module: the components, and a table of them by name. */
export function generatedSource(srcDir: string = defaultSrcDir): string {
  const components = collectComponents(srcDir);
  const byTag = new Map(components.map((c) => [c.tag, c]));
  const sources = new Map<string, string>();
  for (const component of components) {
    const name = wrapperName(component.tag);
    sources.set(name, componentSource(name, component));
  }
  // A family member is the family's component with the member's attribute fixed; a
  // symbol whose tag is its own name is already covered above.
  for (const symbol of VISUAL_SYMBOLS) {
    if (sources.has(symbol.head) || symbol.fixed === undefined) continue;
    const component = byTag.get(symbol.tag);
    if (component) sources.set(symbol.head, componentSource(symbol.head, component, symbol.fixed));
  }
  const names = [...sources.keys()];
  return `// GENERATED by @enumeratio/notatio-vue/generate from the element sources -- do not edit.
import { defineComponent, h } from "vue";

/** Only what the page set, and a boolean only when true: the element keeps its own defaults. */
function bound(
  props: Record<string, unknown>,
  fixed: Record<string, string>,
): Record<string, unknown> {
  const out: Record<string, unknown> = { ...fixed };
  for (const [k, v] of Object.entries(props)) {
    if (v === undefined || v === null || v === false) continue;
    out[k] = v;
  }
  return out;
}

${[...sources.values()].join("\n")}
/** Every generated component by name, for a loop that registers them. */
export const components = { ${names.join(", ")} };
`;
}

/** Write the module if it changed. Returns the component names. */
export function generate(srcDir: string = defaultSrcDir, out: string = generatedPath): string[] {
  const source = generatedSource(srcDir);
  if (!existsSync(out) || readFileSync(out, "utf8") !== source) writeFileSync(out, source);
  return [...source.matchAll(/^export const (\w+) = defineComponent/gm)].map((m) => m[1]);
}

// Run directly (`node --experimental-strip-types src/generate.ts`): write and report.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const names = generate();
  console.log(`notatio-vue: ${names.length} components -> ${join("src", "generated.ts")}`);
}
