// The generic half of an area's compiled-ahead-of-time statistics (step 6b: one generator per
// area, like `generate-entries.ts`). Each area's own `scripts/compile-definitions.ts` calls
// `compiledDefinitionsFor` with its own definitions and carrier shape, and writes the result to
// its own `statistics.compiled.generated.js` — see `../../src/statistics/compiled.ts`, which
// merges every area's table back into one lookup for `compiledStatistic`.

import { ComputeEngine } from "@cortex-js/compute-engine";
import { compileTyped, definitionHash } from "@enumeratio/engine/compiled";
import type { Definition } from "./types.ts";
import { signatureOf } from "./types.ts";

export interface CompiledDefinition {
  readonly signature: string;
  readonly hash: string;
  readonly code: string;
}

/** Every compilable definition of `definitions`, over subjects of `shape` (the carrier's bare
 *  shape, e.g. `list<integer>` — definitions the compiler can't take yet are left out). */
export function compiledDefinitionsFor(definitions: readonly Definition[], shape: string): CompiledDefinition[] {
  const ce = new ComputeEngine();
  const out: CompiledDefinition[] = [];
  for (const definition of definitions) {
    const compiled = compileTyped(ce, definition.expr, { _x: shape });
    if (compiled === undefined) continue;
    out.push({ signature: signatureOf(definition), hash: definitionHash(definition.expr), code: compiled.code });
  }
  return out.toSorted((a, b) => (a.signature < b.signature ? -1 : a.signature > b.signature ? 1 : 0));
}

/** Renders `entries` as the `statistics.compiled.generated.js` module text. */
export function renderCompiled(entries: readonly CompiledDefinition[]): string {
  const body = entries
    .map(
      (e) =>
        `  ${JSON.stringify(e.signature)}: {\n    hash: ${JSON.stringify(e.hash)},\n    run: (_SYS, _) => ${e.code},\n  },`,
    )
    .join("\n");
  return `// GENERATED by scripts/compile-definitions.ts from this area's Epsil definitions, by
// compute-engine's JavaScript compiler. Do not edit: rerun the script. Each entry is used only
// while \`hash\` matches its definition; see ../../src/statistics/compiled.ts.
// compute-engine's code can bind a parameter it never reads, or spread an array it builds.
/* eslint-disable no-unused-vars, unicorn/no-useless-spread */

export const COMPILED = {
${body}
};
`;
}
