// The generic half of an area's compiled-ahead-of-time statistics (step 6b: one generator per
// area, like `generate-entries.ts`). Each area's own `scripts/compile-definitions.ts` calls
// `compiledDefinitionsFor` with its own definitions and carrier shape, and writes the result to
// its own `statistics.compiled.generated.js` — see `../../src/statistics/compiled.ts`, which
// merges every area's table back into one lookup for `compiledStatistic`.

import { ComputeEngine } from "@cortex-js/compute-engine";
import { compileTyped, definitionHash, fromJs, toJs } from "@enumeratio/engine/compiled";
import { evaluateEpsil } from "@enumeratio/structures";
import type { Definition } from "./types.ts";
import { SUBJECT, signatureOf } from "./types.ts";

export interface CompiledDefinition {
  readonly signature: string;
  readonly hash: string;
  readonly code: string;
}

/** Every compilable definition of `definitions`, over subjects of `shape` (the carrier's bare
 *  shape, e.g. `list<integer>`). Definitions the compiler can't take yet are left out, and so are
 *  those whose compiled code answers differently from the interpreter on any of
 *  `subjectsOf(carrier)`: compiled code is otherwise trusted, so a miscompile would answer
 *  wrong silently. */
export function compiledDefinitionsFor(
  definitions: readonly Definition[],
  shape: string,
  subjectsOf: (ce: ComputeEngine, carrier: string) => readonly unknown[],
): { compiled: CompiledDefinition[]; disagreed: string[] } {
  const ce = new ComputeEngine();
  const subjects = new Map<string, readonly unknown[]>();
  const compiled: CompiledDefinition[] = [];
  const disagreed: string[] = [];
  for (const definition of definitions) {
    const code = compileTyped(ce, definition.expr, { [SUBJECT]: shape });
    if (code === undefined) continue;
    if (!subjects.has(definition.on)) subjects.set(definition.on, subjectsOf(ce, definition.on));
    if (!agrees(ce, definition, code.run, subjects.get(definition.on)!)) {
      disagreed.push(signatureOf(definition));
      continue;
    }
    compiled.push({ signature: signatureOf(definition), hash: definitionHash(definition.expr), code: code.code });
  }
  return {
    compiled: compiled.toSorted((a, b) => (a.signature < b.signature ? -1 : a.signature > b.signature ? 1 : 0)),
    disagreed: disagreed.toSorted(),
  };
}

/** Whether compiled code gives the interpreter's answer wherever it answers at all (where it
 *  can't answer exactly, the interpreter does at run time anyway). */
function agrees(
  ce: ComputeEngine,
  definition: Definition,
  run: (vars: Record<string, unknown>) => unknown,
  subjects: readonly unknown[],
): boolean {
  for (const subject of subjects) {
    const value = toJs(subject);
    if (value === undefined) continue;
    let answer;
    try {
      answer = fromJs(run({ [SUBJECT]: value }));
    } catch {
      continue;
    }
    if (answer === undefined) continue;
    const expected = evaluateEpsil(ce, definition.expr, { [SUBJECT]: subject });
    if (JSON.stringify(answer) !== JSON.stringify(expected)) return false;
  }
  return true;
}

/** Renders `entries` as the `statistics.compiled.generated.js` module text. */
export function renderCompiled(entries: readonly CompiledDefinition[]): string {
  const body = entries
    .map(
      (e) =>
        `  ${JSON.stringify(e.signature)}: {\n    hash: ${JSON.stringify(e.hash)},\n    run: (_SYS, _) => ${e.code},\n  },`,
    )
    .join("\n");
  return `// GENERATED by scripts/compile-definitions.ts from this area's Epsil definitions, by
// compute-engine's JavaScript compiler. Do not edit: rerun the script. Each entry is used only
// while \`hash\` matches its definition; see ../../src/statistics/compiled.ts.
// compute-engine's code can bind a parameter it never reads, or spread an array it builds.
/* eslint-disable no-unused-vars, unicorn/no-useless-spread */

export const COMPILED = {
${body}
};
`;
}
