// GENERATED by packages/reference/scripts/collect-summaries.ts — do not edit by hand.
//
// What this package's `ce.declare` calls read for `description` (symbol-metadata step 6,
// design/speculative/symbol-metadata.md): each head's record `summary`, one source instead
// of two. Regenerate with:
//
//   vp node packages/reference/scripts/collect-summaries.ts

export const SUMMARIES: Readonly<Record<string, string>> = {
  Adele:
    "An adèle: a real number $r$ beside a profinite number $z \\in \\hat{\\mathbb{Q}}$. `Adele(q)` for rational $q$ is the principal adèle, $q$ at every place.",
  Idele:
    "An idèle: a unit of the adèle ring — a real $r$ together with $s \\in \\mathbb{Q}^\\times$ principal everywhere except at a listed finite set of primes, where distinguished units override it.",
  ProfiniteDecomposition:
    "$\\{b, a\\}$ with $m = b \\cdot a$, $b \\in GL_n(\\hat{\\mathbb{Z}})$ and $a \\in GL_n^+(\\mathbb{Q})$ upper triangular — strong approximation for a matrix over $\\hat{\\mathbb{Q}}$.",
  ProfiniteNumber:
    "A profinite number: the rational $x + m\\hat{\\mathbb{Z}}$ in $\\hat{\\mathbb{Q}} = \\hat{\\mathbb{Z}} \\otimes \\mathbb{Q}$, known modulo $m$. Modulus 0 (the default) is just the rational $x$ itself.",
  ProfinitePlot:
    "The graph of $f: \\hat{\\mathbb{Z}} \\to \\hat{\\mathbb{Z}}$ in the variable $x$, at precision $k$ (default 5) — Lenstra's picture of a profinite function, drawn as an [[ArrayPlot]].",
};
