// GENERATED by scripts/collect-stories.ts — do not edit by hand.
//
// Every component's stories (reference/<Name>.stories.yaml), keyed by component name, each
// with its source forms derived from its expr and pinned. Regenerate with:
//
//   vp node packages/components/scripts/collect-stories.ts

export type MathJSON = number | string | boolean | readonly MathJSON[] | { readonly [key: string]: unknown };

export interface StoryForm {
  readonly id: string;
  readonly label: string;
  readonly text: string;
}

export interface StoryData {
  readonly id: string;
  readonly caption: string;
  readonly category?: string;
  readonly notes?: string;
  readonly expr: MathJSON;
  readonly forms: readonly StoryForm[];
}

export const STORIES_DATA: Readonly<Record<string, readonly StoryData[]>> = {
  BarChart3D: [
    {
      id: "a-3-3-matrix",
      caption: "A 3×3 matrix",
      category: "Bars",
      expr: ["BarChart3D", ["List", ["List", 1, 2, 3], ["List", 2, 4, 3], ["List", 3, 1, 5]]],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: "<BarChart3D>\n  <List>\n    <List>1, 2, 3</List>\n    <List>2, 4, 3</List>\n    <List>3, 1, 5</List>\n  </List>\n</BarChart3D>",
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-bar-chart-3d data="[[1,2,3],[2,4,3],[3,1,5]]"></notatio-bar-chart-3d>',
        },
      ],
    },
    {
      id: "a-single-row",
      caption: "A single row",
      category: "Bars",
      notes: "A flat list is one row of bars — the 3-D counterpart of a plain BarChart.",
      expr: ["BarChart3D", ["List", 3, 1, 4, 1, 5, 9, 2, 6], ["Tuple", "Label", "'digits of π'"]],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<BarChart3D label="digits of π">\n  <List>3, 1, 4, 1, 5, 9, 2, 6</List>\n</BarChart3D>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-bar-chart-3d data="[3,1,4,1,5,9,2,6]" label="digits of π"></notatio-bar-chart-3d>',
        },
      ],
    },
    {
      id: "labelled-categories",
      caption: "Labelled categories",
      category: "Bars",
      notes: "col-labels and row-labels take comma-separated categories, drawn just outside the near floor edges.",
      expr: [
        "BarChart3D",
        ["List", ["List", 4, 2, 3], ["List", 1, 5, 2]],
        ["Tuple", "ColLabels", "'a,b,c'"],
        ["Tuple", "RowLabels", "'x,y'"],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<BarChart3D col-labels="a,b,c" row-labels="x,y">\n  <List>\n    <List>4, 2, 3</List>\n    <List>1, 5, 2</List>\n  </List>\n</BarChart3D>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-bar-chart-3d data="[[4,2,3],[1,5,2]]" col-labels="a,b,c" row-labels="x,y"></notatio-bar-chart-3d>',
        },
      ],
    },
    {
      id: "tighter-packing-steeper-view",
      caption: "Tighter packing, steeper view",
      category: "Bars",
      notes: "gap is the space between neighbouring bars as a fraction of a cell; at 0 the bars touch.",
      expr: [
        "BarChart3D",
        ["List", ["List", 1, 2, 3, 4], ["List", 2, 3, 4, 5], ["List", 3, 4, 5, 6], ["List", 4, 5, 6, 7]],
        ["Tuple", "Gap", 0.05],
        ["Tuple", "Elevation", 45],
        ["Tuple", "Azimuth", 40],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<BarChart3D gap="0.05" elevation="45" azimuth="40">\n  <List>\n    <List>1, 2, 3, 4</List>\n    <List>2, 3, 4, 5</List>\n    <List>3, 4, 5, 6</List>\n    <List>4, 5, 6, 7</List>\n  </List>\n</BarChart3D>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-bar-chart-3d data="[[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]]" gap="0.05" elevation="45" azimuth="40"></notatio-bar-chart-3d>',
        },
      ],
    },
    {
      id: "negative-values",
      caption: "Negative values",
      category: "Bars",
      notes: "When the data straddles zero, the zero plane sits inside the cube and negative bars hang beneath it.",
      expr: ["BarChart3D", ["List", ["List", -2, 1, 3], ["List", 2, -1, 1]]],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: "<BarChart3D>\n  <List>\n    <List>-2, 1, 3</List>\n    <List>2, -1, 1</List>\n  </List>\n</BarChart3D>",
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-bar-chart-3d data="[[-2,1,3],[2,-1,1]]"></notatio-bar-chart-3d>',
        },
      ],
    },
    {
      id: "a-pinned-height-scale",
      caption: "A pinned height scale",
      category: "Bars",
      notes:
        'zrange pins the height scale so several charts can be compared; axes="false" drops the projected axis box.',
      expr: [
        "BarChart3D",
        ["List", ["List", 1, 2], ["List", 2, 3]],
        ["Tuple", "ZRange", "'0,10'"],
        ["Tuple", "Axes", "'false'"],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<BarChart3D zrange="0,10" axes="false">\n  <List>\n    <List>1, 2</List>\n    <List>2, 3</List>\n  </List>\n</BarChart3D>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-bar-chart-3d data="[[1,2],[2,3]]" zrange="0,10" axes="false"></notatio-bar-chart-3d>',
        },
      ],
    },
  ],
  Chart: [
    {
      id: "listplot-index-vs-value",
      caption: "ListPlot: index vs value",
      category: "ListPlot & ListLinePlot",
      notes: "A bare number list plots as index (x) vs value (y).",
      expr: ["ListPlot", ["List", 3, 1, 4, 1, 5, 9, 2, 6]],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: "<ListPlot>\n  <List>3, 1, 4, 1, 5, 9, 2, 6</List>\n</ListPlot>",
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-chart type="list" data="[3,1,4,1,5,9,2,6]"></notatio-chart>',
        },
      ],
    },
    {
      id: "listlineplot-connected",
      caption: "ListLinePlot: connected",
      category: "ListPlot & ListLinePlot",
      expr: ["ListLinePlot", ["List", 3, 1, 4, 1, 5, 9, 2, 6]],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: "<ListLinePlot>\n  <List>3, 1, 4, 1, 5, 9, 2, 6</List>\n</ListLinePlot>",
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-chart type="listline" data="[3,1,4,1,5,9,2,6]"></notatio-chart>',
        },
      ],
    },
    {
      id: "barchart-labelled",
      caption: "Value list with category labels",
      category: "BarChart",
      expr: [
        "BarChart",
        ["List", 12, 19, 7, 15, 10],
        ["Tuple", "Labels", ["List", "'Mon'", "'Tue'", "'Wed'", "'Thu'", "'Fri'"]],
        ["Tuple", "Label", "'Daily commits'"],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<BarChart labels="[&quot;Mon&quot;, &quot;Tue&quot;, &quot;Wed&quot;, &quot;Thu&quot;, &quot;Fri&quot;]" label="Daily commits">\n  <List>12, 19, 7, 15, 10</List>\n</BarChart>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-chart type="bar" data="[12,19,7,15,10]" labels="[&quot;Mon&quot;, &quot;Tue&quot;, &quot;Wed&quot;, &quot;Thu&quot;, &quot;Fri&quot;]" label="Daily commits"></notatio-chart>',
        },
      ],
    },
    {
      id: "barchart-negative",
      caption: "Negative values dip below the baseline",
      category: "BarChart",
      expr: ["BarChart", ["List", 3, -2, 5, -1, 4]],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: "<BarChart>\n  <List>3, -2, 5, -1, 4</List>\n</BarChart>",
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-chart type="bar" data="[3,-2,5,-1,4]"></notatio-chart>',
        },
      ],
    },
    {
      id: "histogram-auto-bins",
      caption: "Auto bin count (Sturges' rule)",
      category: "Histogram",
      notes: "The bin count defaults to Sturges' rule; pass `bins` to override.",
      expr: ["Histogram", ["List", 1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7]],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: "<Histogram>\n  <List>1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7</List>\n</Histogram>",
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-chart type="histogram" data="[1,2,2,3,3,3,4,4,4,4,5,5,5,6,6,7]"></notatio-chart>',
        },
      ],
    },
    {
      id: "histogram-explicit-bins",
      caption: "Explicit bin count",
      category: "Histogram",
      expr: ["Histogram", ["List", 1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7], ["Tuple", "Bins", 4]],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<Histogram bins="4">\n  <List>1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7</List>\n</Histogram>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-chart type="histogram" data="[1,2,2,3,3,3,4,4,4,4,5,5,5,6,6,7]" bins="4"></notatio-chart>',
        },
      ],
    },
    {
      id: "piechart-proportions",
      caption: "Proportions of a value list",
      category: "PieChart",
      expr: ["PieChart", ["List", 35, 25, 20, 20], ["Tuple", "Labels", ["List", "'A'", "'B'", "'C'", "'D'"]]],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<PieChart labels="[&quot;A&quot;, &quot;B&quot;, &quot;C&quot;, &quot;D&quot;]">\n  <List>35, 25, 20, 20</List>\n</PieChart>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-chart type="pie" data="[35,25,20,20]" labels="[&quot;A&quot;, &quot;B&quot;, &quot;C&quot;, &quot;D&quot;]"></notatio-chart>',
        },
      ],
    },
    {
      id: "boxwhisker-one-per-series",
      caption: "One box per series",
      category: "BoxWhiskerChart",
      notes:
        "`data` is a list of raw value lists; each series is reduced to its five-number summary (min, Q1, median, Q3, max).",
      expr: [
        "BoxWhiskerChart",
        ["List", ["List", 2, 4, 4, 4, 5, 5, 7, 9], ["List", 1, 2, 3, 3, 3, 4, 4, 10]],
        ["Tuple", "Labels", ["List", "'A'", "'B'"]],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<BoxWhiskerChart labels="[&quot;A&quot;, &quot;B&quot;]">\n  <List>\n    <List>2, 4, 4, 4, 5, 5, 7, 9</List>\n    <List>1, 2, 3, 3, 3, 4, 4, 10</List>\n  </List>\n</BoxWhiskerChart>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-chart type="box" data="[[2,4,4,4,5,5,7,9],[1,2,3,3,3,4,4,10]]" labels="[&quot;A&quot;, &quot;B&quot;]"></notatio-chart>',
        },
      ],
    },
    {
      id: "arrayplot-matrix-heatmap",
      caption: "A matrix as a heatmap",
      category: "ArrayPlot",
      notes:
        "Each cell's value maps to a colour ramp from blue (low) to accent (high). Cells are square: the frame's height follows rows/cols, up to a square.",
      expr: [
        "ArrayPlot",
        ["List", ["List", 0, 1, 2, 3], ["List", 1, 2, 3, 4], ["List", 2, 3, 4, 5], ["List", 3, 4, 5, 6]],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: "<ArrayPlot>\n  <List>\n    <List>0, 1, 2, 3</List>\n    <List>1, 2, 3, 4</List>\n    <List>2, 3, 4, 5</List>\n    <List>3, 4, 5, 6</List>\n  </List>\n</ArrayPlot>",
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-chart type="array" data="[[0,1,2,3],[1,2,3,4],[2,3,4,5],[3,4,5,6]]"></notatio-chart>',
        },
      ],
    },
    {
      id: "arrayplot-01-two-tone",
      caption: "A 0/1 matrix is two-tone",
      category: "ArrayPlot",
      notes: "Like Wolfram's white/black: 0 is the background, 1 the foreground, so it follows the theme.",
      expr: [
        "ArrayPlot",
        [
          "List",
          ["List", 1, 0, 0, 0, 0, 0, 0, 0],
          ["List", 0, 1, 0, 0, 0, 0, 0, 0],
          ["List", 1, 0, 1, 0, 0, 0, 0, 0],
          ["List", 0, 0, 0, 1, 0, 0, 0, 0],
          ["List", 1, 1, 0, 0, 1, 0, 0, 0],
          ["List", 0, 0, 0, 0, 0, 1, 0, 0],
          ["List", 1, 0, 1, 0, 0, 0, 1, 0],
          ["List", 0, 0, 0, 0, 0, 0, 0, 1],
        ],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: "<ArrayPlot>\n  <List>\n    <List>1, 0, 0, 0, 0, 0, 0, 0</List>\n    <List>0, 1, 0, 0, 0, 0, 0, 0</List>\n    <List>1, 0, 1, 0, 0, 0, 0, 0</List>\n    <List>0, 0, 0, 1, 0, 0, 0, 0</List>\n    <List>1, 1, 0, 0, 1, 0, 0, 0</List>\n    <List>0, 0, 0, 0, 0, 1, 0, 0</List>\n    <List>1, 0, 1, 0, 0, 0, 1, 0</List>\n    <List>0, 0, 0, 0, 0, 0, 0, 1</List>\n  </List>\n</ArrayPlot>",
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-chart type="array" data="[[1,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0],[1,0,1,0,0,0,0,0],[0,0,0,1,0,0,0,0],[1,1,0,0,1,0,0,0],[0,0,0,0,0,1,0,0],[1,0,1,0,0,0,1,0],[0,0,0,0,0,0,0,1]]"></notatio-chart>',
        },
      ],
    },
    {
      id: "arrayplot-01-single-row",
      caption: "A single wide row",
      category: "ArrayPlot",
      expr: ["ArrayPlot", ["List", ["List", 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]]],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: "<ArrayPlot>\n  <List>\n    <List>0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1</List>\n  </List>\n</ArrayPlot>",
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-chart type="array" data="[[0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1]]"></notatio-chart>',
        },
      ],
    },
    {
      id: "discreteplot-stem",
      caption: "A stem plot",
      category: "DiscretePlot",
      notes: "A vertical stem from the zero baseline to each value, with a dot on top.",
      expr: ["DiscretePlot", ["List", 1, -2, 3, 4, -1, 2]],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: "<DiscretePlot>\n  <List>1, -2, 3, 4, -1, 2</List>\n</DiscretePlot>",
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-chart type="discrete" data="[1,-2,3,4,-1,2]"></notatio-chart>',
        },
      ],
    },
    {
      id: "chosen-short-list-is-bars",
      caption: "A short number list is bars",
      category: "Chosen from the data",
      notes:
        "No `type`: the shape decides -- a short number list is bars, a long one a histogram, pairs are points, a matrix is an array plot -- `chooseChartType`, which is also the rule behind the `Chart` head.",
      expr: ["Chart", ["List", 3, 1, 4, 1, 5]],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: "<Chart>\n  <List>3, 1, 4, 1, 5</List>\n</Chart>",
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-chart data="[3,1,4,1,5]"></notatio-chart>',
        },
      ],
    },
    {
      id: "chosen-long-list-is-histogram",
      caption: "A long number list is a histogram",
      category: "Chosen from the data",
      expr: ["Chart", ["List", 5, 3, 8, 1, 9, 2, 7, 4, 6, 3, 5, 8, 2, 9, 1, 4, 7, 3, 6, 5, 2, 8, 4, 1, 9]],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: "<Chart>\n  <List>5, 3, 8, 1, 9, 2, 7, 4, 6, 3, 5, 8, 2, 9, 1, 4, 7, 3, 6, 5, 2, 8, 4, 1, 9</List>\n</Chart>",
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-chart data="[5,3,8,1,9,2,7,4,6,3,5,8,2,9,1,4,7,3,6,5,2,8,4,1,9]"></notatio-chart>',
        },
      ],
    },
    {
      id: "chosen-pairs-are-points",
      caption: "Pairs are points",
      category: "Chosen from the data",
      expr: ["Chart", ["List", ["List", 0, 1], ["List", 1, 3], ["List", 2, 2], ["List", 3, 5]]],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: "<Chart>\n  <List>\n    <List>0, 1</List>\n    <List>1, 3</List>\n    <List>2, 2</List>\n    <List>3, 5</List>\n  </List>\n</Chart>",
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-chart data="[[0,1],[1,3],[2,2],[3,5]]"></notatio-chart>',
        },
      ],
    },
    {
      id: "chosen-matrix-is-array-plot",
      caption: "A matrix is an array plot",
      category: "Chosen from the data",
      expr: ["Chart", ["List", ["List", 1, 0, 2], ["List", 0, 3, 1], ["List", 2, 1, 0]]],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: "<Chart>\n  <List>\n    <List>1, 0, 2</List>\n    <List>0, 3, 1</List>\n    <List>2, 1, 0</List>\n  </List>\n</Chart>",
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-chart data="[[1,0,2],[0,3,1],[2,1,0]]"></notatio-chart>',
        },
      ],
    },
  ],
  CollectionTable: [
    {
      id: "subsets-4-with-glyph",
      caption: "Subsets(4), every subset drawn",
      category: "Basic",
      notes:
        "Sixteen rows, in the binary (Gray-free) order the kernel unranks. Sort by `Length` to group by size; filter `Length(_) == 2` for the six pairs -- the count goes exact at once, since sixteen rows scan in a millisecond. The `Sum` column is any expression over the row, not just a head.",
      expr: [
        "CollectionTable",
        ["Subsets", 4],
        ["Tuple", "Columns", "'Length, Sum'"],
        ["Tuple", "Glyph", "'subset'"],
        ["Tuple", "PageSize", 10],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<CollectionTable columns="Length, Sum" glyph="subset" page-size="10">\n  <Subsets>4</Subsets>\n</CollectionTable>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-collection-table expr="Subsets(4)" columns="Length, Sum" glyph="subset" page-size="10"></notatio-collection-table>',
        },
      ],
    },
    {
      id: "symmetric-group-5-statistics",
      caption: "SymmetricGroup(5), the classical statistics",
      category: "Basic",
      notes:
        "The 44 derangements of five, picked out of 120 by the filter, each with its `Descents` number, `MajorIndex`, `Inversions` count and `Cycles` count. Clear the filter to see all 120; sort by `Inversions` to see that it and `MajorIndex` are equidistributed but not equal; add `Peaks`, `Excedances` or `LeftToRightMaxima` as further columns.",
      expr: [
        "CollectionTable",
        ["SymmetricGroup", 5],
        ["Tuple", "Columns", "'Descents, MajorIndex, Inversions, CycleCount, FixedPoints'"],
        ["Tuple", "Glyph", "'permutation'"],
        ["Tuple", "Filter", "'FixedPoints(_) == 0'"],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<CollectionTable columns="Descents, MajorIndex, Inversions, CycleCount, FixedPoints" glyph="permutation" filter="FixedPoints(_) == 0">\n  <SymmetricGroup>5</SymmetricGroup>\n</CollectionTable>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-collection-table expr="SymmetricGroup(5)" columns="Descents, MajorIndex, Inversions, CycleCount, FixedPoints" glyph="permutation" filter="FixedPoints(_) == 0"></notatio-collection-table>',
        },
      ],
    },
    {
      id: "symmetric-group-12-paging",
      caption: "SymmetricGroup(12) -- paging without materialising",
      category: "Basic",
      notes:
        "479,001,600 permutations. The pager opens on page one million -- `At` unranks the ten rows there directly. Type a page number, or jump to the last page. Sorting here orders only the first two thousand rows (the bound is adjustable) and says so; a filter scans twenty thousand rows at a time and offers to continue.",
      expr: [
        "CollectionTable",
        ["SymmetricGroup", 12],
        ["Tuple", "Columns", "'Descents, Inversions'"],
        ["Tuple", "Glyph", "'permutation'"],
        ["Tuple", "Page", "'1000000'"],
        ["Tuple", "PageSize", 10],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<CollectionTable columns="Descents, Inversions" glyph="permutation" page="1000000" page-size="10">\n  <SymmetricGroup>12</SymmetricGroup>\n</CollectionTable>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-collection-table expr="SymmetricGroup(12)" columns="Descents, Inversions" glyph="permutation" page="1000000" page-size="10"></notatio-collection-table>',
        },
      ],
    },
    {
      id: "symmetric-group-20-beyond-2-53",
      caption: "SymmetricGroup(20)",
      category: "Beyond 2⁵³",
      notes:
        "2,432,902,008,176,640,000 rows -- past Number.MAX_SAFE_INTEGER, so the count shows as approximate and the pager stops at the last exactly-indexable page. The kernel counts and unranks in doubles; indexing past 2⁵³ would silently round, so the table refuses rather than guess. `readonly` hides the editors.",
      expr: [
        "CollectionTable",
        ["SymmetricGroup", 20],
        ["Tuple", "Columns", "'Descents, CycleCount'"],
        ["Tuple", "PageSize", 10],
        ["Tuple", "Readonly", "True"],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<CollectionTable columns="Descents, CycleCount" page-size="10" readonly="true">\n  <SymmetricGroup>20</SymmetricGroup>\n</CollectionTable>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-collection-table expr="SymmetricGroup(20)" columns="Descents, CycleCount" page-size="10" readonly="true"></notatio-collection-table>',
        },
      ],
    },
    {
      id: "integer-partitions-8-ferrers",
      caption: "IntegerPartitions(8) as Ferrers diagrams",
      category: "Other carriers",
      notes:
        "Partitions unrank in reverse-lexicographic order. The partition statistics come from @enumeratio/statistics, where each is a definition over the part list; filter `IsSelfConjugate(_) == 1` for the two self-conjugate partitions of 8, or `Length(_) == 3` for the five into three parts.",
      expr: [
        "CollectionTable",
        ["IntegerPartitions", 8],
        ["Tuple", "Columns", "'Length, LargestPart, DistinctParts, DurfeeSquare, Crank'"],
        ["Tuple", "Glyph", "'partition'"],
        ["Tuple", "PageSize", 10],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<CollectionTable columns="Length, LargestPart, DistinctParts, DurfeeSquare, Crank" glyph="partition" page-size="10">\n  <IntegerPartitions>8</IntegerPartitions>\n</CollectionTable>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-collection-table expr="IntegerPartitions(8)" columns="Length, LargestPart, DistinctParts, DurfeeSquare, Crank" glyph="partition" page-size="10"></notatio-collection-table>',
        },
      ],
    },
    {
      id: "dyck-paths-4-step-words",
      caption: "DyckPaths(4) as step words",
      category: "Other carriers",
      notes:
        "Fourteen paths (Catalan), as up/down words drawn as mountain ranges. `Height`, `Area`, `Returns` (touches of the axis) and `Hills` are Dyck-path statistics; sort by `Returns` to see the Narayana-like split, or filter `Returns(_) == 1` for the five primitive paths.",
      expr: [
        "CollectionTable",
        ["DyckPaths", 4],
        ["Tuple", "Columns", "'Height, Area, Returns, Hills'"],
        ["Tuple", "Glyph", "'dyck'"],
        ["Tuple", "PageSize", 14],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<CollectionTable columns="Height, Area, Returns, Hills" glyph="dyck" page-size="14">\n  <DyckPaths>4</DyckPaths>\n</CollectionTable>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-collection-table expr="DyckPaths(4)" columns="Height, Area, Returns, Hills" glyph="dyck" page-size="14"></notatio-collection-table>',
        },
      ],
    },
    {
      id: "set-partitions-4-blocks",
      caption: "SetPartitions(4), blocks as pills",
      category: "Other carriers",
      notes:
        "Fifteen set partitions (Bell). The element is the block list; the glyph converts it to the restricted-growth string the set-partition figure draws. `Length` counts blocks -- sort by it to walk from one block to four -- and `Max(Map(Length, _))` is the largest block.",
      expr: [
        "CollectionTable",
        ["SetPartitions", 4],
        ["Tuple", "Columns", "'Length, Max(Map(Length, _))'"],
        ["Tuple", "Glyph", "'set-partition'"],
        ["Tuple", "PageSize", 15],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<CollectionTable columns="Length, Max(Map(Length, _))" glyph="set-partition" page-size="15">\n  <SetPartitions>4</SetPartitions>\n</CollectionTable>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-collection-table expr="SetPartitions(4)" columns="Length, Max(Map(Length, _))" glyph="set-partition" page-size="15"></notatio-collection-table>',
        },
      ],
    },
  ],
  ComplexPlot3D: [
    {
      id: "rational-function",
      caption: "A rational function",
      category: "Poles and zeros",
      notes: "Two poles at ±i, clipped at the ceiling, and the hue running once round each.",
      expr: ["ComplexPlot3D", ["Divide", 1, ["Add", ["Power", "z", 2], 1]]],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<ComplexPlot3D>\n  <Divide>\n    <Integer value="1" />\n    <Add>\n      <Power>z, 2</Power>\n      <Integer value="1" />\n    </Add>\n  </Divide>\n</ComplexPlot3D>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-complex-plot-3d value="1 / (z ^ 2 + 1)"></notatio-complex-plot-3d>',
        },
      ],
    },
    {
      id: "zeros-too",
      caption: "Zeros too",
      category: "Poles and zeros",
      notes:
        "The cube roots of unity are the three dimples; the poles are the two spikes. Reading the colour wheel round a point gives its order, and the direction of the winding says which.",
      expr: [
        "ComplexPlot3D",
        ["Divide", ["Add", ["Power", "z", 3], -1], ["Add", ["Power", "z", 2], 1]],
        ["Tuple", "z", ["Complex", -2, -2], ["Complex", 2, 2]],
        ["Tuple", "Samples", 60],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<ComplexPlot3D samples="60">\n  <Divide>\n    <Add>\n      <Power>z, 3</Power>\n      <Integer value="-1" />\n    </Add>\n    <Add>\n      <Power>z, 2</Power>\n      <Integer value="1" />\n    </Add>\n  </Divide>\n  <Tuple>\n    <Symbol value="z" />\n    <Complex>-2, -2</Complex>\n    <Complex>2, 2</Complex>\n  </Tuple>\n</ComplexPlot3D>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-complex-plot-3d value="(z ^ 3 + -1) / (z ^ 2 + 1)" var="z" domain="-2,2,-2,2" samples="60"></notatio-complex-plot-3d>',
        },
      ],
    },
    {
      id: "gamma-function",
      caption: "The gamma function",
      category: "Special functions",
      notes: "Poles at 0, −1, −2, …, each a spike; to the right the surface climbs as the factorials do.",
      expr: [
        "ComplexPlot3D",
        ["Gamma", "z"],
        ["Tuple", "z", ["Complex", -4, -3], ["Complex", 4, 3]],
        ["Tuple", "Samples", 60],
        ["Tuple", "MaxHeight", 6],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<ComplexPlot3D samples="60" max-height="6">\n  <Gamma>z</Gamma>\n  <Tuple>\n    <Symbol value="z" />\n    <Complex>-4, -3</Complex>\n    <Complex>4, 3</Complex>\n  </Tuple>\n</ComplexPlot3D>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-complex-plot-3d value="Gamma(z)" var="z" domain="-4,4,-3,3" samples="60" max-height="6"></notatio-complex-plot-3d>',
        },
      ],
    },
    {
      id: "riemann-zeta",
      caption: "The Riemann zeta function",
      category: "Special functions",
      notes:
        "The pole at z = 1, and up the critical line the first non-trivial zeros at ½ + 14.13i, ½ + 21.02i, ½ + 25.01i -- the dimples every hue winds round.",
      expr: [
        "ComplexPlot3D",
        ["Zeta", "z"],
        ["Tuple", "z", -2, ["Complex", 3, 30]],
        ["Tuple", "Samples", 70],
        ["Tuple", "MaxHeight", 3],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<ComplexPlot3D samples="70" max-height="3">\n  <Zeta>z</Zeta>\n  <Tuple>\n    <Symbol value="z" />\n    <Integer value="-2" />\n    <Complex>3, 30</Complex>\n  </Tuple>\n</ComplexPlot3D>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-complex-plot-3d value="Zeta(z)" var="z" domain="-2,3,0,30" samples="70" max-height="3"></notatio-complex-plot-3d>',
        },
      ],
    },
    {
      id: "dense-rational-surface",
      caption: "A dense rational surface",
      category: "GPU evaluation",
      notes:
        "The rational function again at 160 samples a side, so the spikes come to a point and the hue is continuous across each face.",
      expr: [
        "ComplexPlot3D",
        ["Divide", ["Add", ["Power", "z", 3], -1], ["Add", ["Power", "z", 2], 1]],
        ["Tuple", "Gpu", 160],
        ["Tuple", "MaxHeight", 3],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<ComplexPlot3D gpu="160" max-height="3">\n  <Divide>\n    <Add>\n      <Power>z, 3</Power>\n      <Integer value="-1" />\n    </Add>\n    <Add>\n      <Power>z, 2</Power>\n      <Integer value="1" />\n    </Add>\n  </Divide>\n</ComplexPlot3D>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-complex-plot-3d value="(z ^ 3 + -1) / (z ^ 2 + 1)" gpu="160" max-height="3"></notatio-complex-plot-3d>',
        },
      ],
    },
    {
      id: "essential-singularity",
      caption: "An essential singularity",
      category: "GPU evaluation",
      notes:
        "Exp(1/z) near the origin: the surface climbs to the ceiling on the right and falls to the floor on the left, and between them every hue passes infinitely often.",
      expr: [
        "ComplexPlot3D",
        ["Power", "ExponentialE", ["Divide", 1, "z"]],
        ["Tuple", "z", ["Complex", -1, -1], ["Complex", 1, 1]],
        ["Tuple", "Gpu", 200],
        ["Tuple", "MaxHeight", 3],
        ["Tuple", "Elevation", 30],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<ComplexPlot3D gpu="200" max-height="3" elevation="30">\n  <Power>\n    <Symbol value="ExponentialE" />\n    <Divide>1, z</Divide>\n  </Power>\n  <Tuple>\n    <Symbol value="z" />\n    <Complex>-1, -1</Complex>\n    <Complex>1, 1</Complex>\n  </Tuple>\n</ComplexPlot3D>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-complex-plot-3d value="ExponentialE ^ (1 / z)" var="z" domain="-1,1,-1,1" gpu="200" max-height="3" elevation="30"></notatio-complex-plot-3d>',
        },
      ],
    },
    {
      id: "trigamma-function",
      caption: "The trigamma function",
      category: "GPU evaluation",
      notes:
        "PolyGamma(1, z) through the analytic kernels on the GPU: double poles at 0, −1, −2, …, so the hue winds twice round each spike.",
      expr: [
        "ComplexPlot3D",
        ["PolyGamma", 1, "z"],
        ["Tuple", "z", ["Complex", -4, -2], ["Complex", 2, 2]],
        ["Tuple", "Gpu", 160],
        ["Tuple", "MaxHeight", 5],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<ComplexPlot3D gpu="160" max-height="5">\n  <PolyGamma>1, z</PolyGamma>\n  <Tuple>\n    <Symbol value="z" />\n    <Complex>-4, -2</Complex>\n    <Complex>2, 2</Complex>\n  </Tuple>\n</ComplexPlot3D>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-complex-plot-3d value="PolyGamma(1, z)" var="z" domain="-4,2,-2,2" gpu="160" max-height="5"></notatio-complex-plot-3d>',
        },
      ],
    },
    {
      id: "through-an-expression",
      caption: "Through an expression, corner-to-corner",
      category: "As an expression",
      notes:
        "The head is the component: an evaluated `ComplexPlot3D(f, (z, a + b i, c + d i))` draws itself, the iterator's complex corners becoming the `domain` -- the same picture as the first story, written the other way.",
      expr: [
        "ComplexPlot3D",
        ["Divide", 1, ["Add", ["Power", "z", 2], 1]],
        ["Tuple", "z", ["Complex", -2, -2], ["Complex", 2, 2]],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<ComplexPlot3D>\n  <Divide>\n    <Integer value="1" />\n    <Add>\n      <Power>z, 2</Power>\n      <Integer value="1" />\n    </Add>\n  </Divide>\n  <Tuple>\n    <Symbol value="z" />\n    <Complex>-2, -2</Complex>\n    <Complex>2, 2</Complex>\n  </Tuple>\n</ComplexPlot3D>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-complex-plot-3d value="1 / (z ^ 2 + 1)" var="z" domain="-2,2,-2,2"></notatio-complex-plot-3d>',
        },
      ],
    },
  ],
  ContourPlot: [
    {
      id: "saddle",
      caption: "A saddle",
      category: "Function contours",
      notes: "The classic hyperbolic-paraboloid saddle -- contours open along both diagonals.",
      expr: [
        "ContourPlot",
        ["Add", ["Power", "x", 2], ["Negate", ["Power", "y", 2]]],
        ["Tuple", "x", -3, 3],
        ["Tuple", "y", -3, 3],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: "<ContourPlot>\n  <Add>\n    <Power>x, 2</Power>\n    <Negate>\n      <Power>y, 2</Power>\n    </Negate>\n  </Add>\n  <Tuple>x, -3, 3</Tuple>\n  <Tuple>y, -3, 3</Tuple>\n</ContourPlot>",
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-contour-plot expr="x ^ 2 + -y ^ 2" xvar="x" xrange="-3,3" yvar="y" yrange="-3,3"></notatio-contour-plot>',
        },
      ],
    },
    {
      id: "trig-field",
      caption: "A trig field",
      category: "Function contours",
      expr: [
        "ContourPlot",
        ["Add", ["Sin", "x"], ["Cos", "y"]],
        ["Tuple", "x", -6.283, 6.283],
        ["Tuple", "y", -6.283, 6.283],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: "<ContourPlot>\n  <Add>\n    <Sin>x</Sin>\n    <Cos>y</Cos>\n  </Add>\n  <Tuple>x, -6.283, 6.283</Tuple>\n  <Tuple>y, -6.283, 6.283</Tuple>\n</ContourPlot>",
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-contour-plot expr="Sin(x) + Cos(y)" xvar="x" xrange="-6.283,6.283" yvar="y" yrange="-6.283,6.283"></notatio-contour-plot>',
        },
      ],
    },
    {
      id: "concentric-circles",
      caption: "Concentric circles (radial field)",
      category: "Function contours",
      notes: "`levels` as a JSON array picks explicit contour values instead of the automatic ~8 evenly spaced ones.",
      expr: [
        "ContourPlot",
        ["Add", ["Power", "x", 2], ["Power", "y", 2]],
        ["Tuple", "x", -3, 3],
        ["Tuple", "y", -3, 3],
        ["Tuple", "Levels", ["List", 1, 2, 4, 6, 8]],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<ContourPlot levels="[1, 2, 4, 6, 8]">\n  <Add>\n    <Power>x, 2</Power>\n    <Power>y, 2</Power>\n  </Add>\n  <Tuple>x, -3, 3</Tuple>\n  <Tuple>y, -3, 3</Tuple>\n</ContourPlot>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-contour-plot expr="x ^ 2 + y ^ 2" xvar="x" xrange="-3,3" yvar="y" yrange="-3,3" levels="[1, 2, 4, 6, 8]"></notatio-contour-plot>',
        },
      ],
    },
    {
      id: "level-count",
      caption: "A level count",
      category: "Function contours",
      notes: "A bare number for `levels` sets the auto level count; `n` controls the sampling grid's resolution.",
      expr: [
        "ContourPlot",
        ["Sin", ["Multiply", "x", "y"]],
        ["Tuple", "x", -3, 3],
        ["Tuple", "y", -3, 3],
        ["Tuple", "Levels", 12],
        ["Tuple", "N", 60],
        ["Tuple", "Label", "'sin(xy)'"],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<ContourPlot levels="12" n="60" label="sin(xy)">\n  <Sin>\n    <Multiply>x, y</Multiply>\n  </Sin>\n  <Tuple>x, -3, 3</Tuple>\n  <Tuple>y, -3, 3</Tuple>\n</ContourPlot>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-contour-plot expr="Sin(x * y)" xvar="x" xrange="-3,3" yvar="y" yrange="-3,3" levels="12" n="60" label="sin(xy)"></notatio-contour-plot>',
        },
      ],
    },
    {
      id: "filled-saddle",
      caption: "Filled saddle",
      category: "Filled bands",
      notes: "`filled` shades the bands between levels with a sequential ramp instead of drawing lines.",
      expr: [
        "ContourPlot",
        ["Add", ["Power", "x", 2], ["Negate", ["Power", "y", 2]]],
        ["Tuple", "x", -3, 3],
        ["Tuple", "y", -3, 3],
        ["Tuple", "Filled", "True"],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<ContourPlot filled="true">\n  <Add>\n    <Power>x, 2</Power>\n    <Negate>\n      <Power>y, 2</Power>\n    </Negate>\n  </Add>\n  <Tuple>x, -3, 3</Tuple>\n  <Tuple>y, -3, 3</Tuple>\n</ContourPlot>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-contour-plot expr="x ^ 2 + -y ^ 2" xvar="x" xrange="-3,3" yvar="y" yrange="-3,3" filled="true"></notatio-contour-plot>',
        },
      ],
    },
    {
      id: "filled-radial-labels",
      caption: "Filled radial field with labels",
      category: "Filled bands",
      expr: [
        "ContourPlot",
        ["Add", ["Power", "x", 2], ["Power", "y", 2]],
        ["Tuple", "x", -3, 3],
        ["Tuple", "y", -3, 3],
        ["Tuple", "Filled", "True"],
        ["Tuple", "XLabel", "'x'"],
        ["Tuple", "YLabel", "'y'"],
        ["Tuple", "Label", "'x² + y²'"],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<ContourPlot filled="true" xlabel="x" ylabel="y" label="x² + y²">\n  <Add>\n    <Power>x, 2</Power>\n    <Power>y, 2</Power>\n  </Add>\n  <Tuple>x, -3, 3</Tuple>\n  <Tuple>y, -3, 3</Tuple>\n</ContourPlot>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-contour-plot expr="x ^ 2 + y ^ 2" xvar="x" xrange="-3,3" yvar="y" yrange="-3,3" filled="true" x-label="x" y-label="y" label="x² + y²"></notatio-contour-plot>',
        },
      ],
    },
    {
      id: "pre-sampled-grid",
      caption: "A pre-sampled grid",
      category: "List contours",
      notes:
        "`ListContourPlot` contours a pre-sampled grid directly -- no expression evaluation, so it's the natural fit for numerical data.",
      expr: [
        "ListContourPlot",
        ["List", ["List", 0, 1, 2, 3], ["List", 1, 2, 3, 4], ["List", 2, 3, 4, 5], ["List", 3, 4, 5, 6]],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: "<ListContourPlot>\n  <List>\n    <List>0, 1, 2, 3</List>\n    <List>1, 2, 3, 4</List>\n    <List>2, 3, 4, 5</List>\n    <List>3, 4, 5, 6</List>\n  </List>\n</ListContourPlot>",
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-contour-plot data="[[0,1,2,3],[1,2,3,4],[2,3,4,5],[3,4,5,6]]"></notatio-contour-plot>',
        },
      ],
    },
  ],
  DensityPlot: [
    {
      id: "trig-field",
      caption: "A trig field",
      category: "Function densities",
      expr: [
        "DensityPlot",
        ["Multiply", ["Sin", "x"], ["Cos", "y"]],
        ["Tuple", "x", -3.14, 3.14],
        ["Tuple", "y", -3.14, 3.14],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: "<DensityPlot>\n  <Multiply>\n    <Sin>x</Sin>\n    <Cos>y</Cos>\n  </Multiply>\n  <Tuple>x, -3.14, 3.14</Tuple>\n  <Tuple>y, -3.14, 3.14</Tuple>\n</DensityPlot>",
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-density-plot expr="Sin(x) * Cos(y)" xvar="x" xrange="-3.14,3.14" yvar="y" yrange="-3.14,3.14"></notatio-density-plot>',
        },
      ],
    },
    {
      id: "saddle-colour-bar",
      caption: "A saddle, with a colour bar",
      category: "Function densities",
      notes: "`legend` adds a colour bar labelled with the sampled extremes.",
      expr: [
        "DensityPlot",
        ["Add", ["Power", "x", 2], ["Negate", ["Power", "y", 2]]],
        ["Tuple", "x", -3, 3],
        ["Tuple", "y", -3, 3],
        ["Tuple", "Legend", "True"],
        ["Tuple", "Label", "'x² − y²'"],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<DensityPlot legend="true" label="x² − y²">\n  <Add>\n    <Power>x, 2</Power>\n    <Negate>\n      <Power>y, 2</Power>\n    </Negate>\n  </Add>\n  <Tuple>x, -3, 3</Tuple>\n  <Tuple>y, -3, 3</Tuple>\n</DensityPlot>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-density-plot expr="x ^ 2 + -y ^ 2" xvar="x" xrange="-3,3" yvar="y" yrange="-3,3" legend="true" label="x² − y²"></notatio-density-plot>',
        },
      ],
    },
    {
      id: "interference",
      caption: "Interference",
      category: "Function densities",
      notes:
        "`n` raises the sampling resolution -- the ramp is quantised by the cell grid, so a finer grid reads as a smoother image.",
      expr: [
        "DensityPlot",
        ["Sin", ["Multiply", "x", "y"]],
        ["Tuple", "x", -4, 4],
        ["Tuple", "y", -4, 4],
        ["Tuple", "N", 80],
        ["Tuple", "Legend", "True"],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<DensityPlot n="80" legend="true">\n  <Sin>\n    <Multiply>x, y</Multiply>\n  </Sin>\n  <Tuple>x, -4, 4</Tuple>\n  <Tuple>y, -4, 4</Tuple>\n</DensityPlot>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-density-plot expr="Sin(x * y)" xvar="x" xrange="-4,4" yvar="y" yrange="-4,4" n="80" legend="true"></notatio-density-plot>',
        },
      ],
    },
    {
      id: "pinned-colour-scale",
      caption: "A pinned colour scale",
      category: "Function densities",
      notes:
        "`zrange` pins the colour scale instead of using the sampled min and max, so several plots can be compared on one scale.",
      expr: [
        "DensityPlot",
        ["Add", ["Power", "x", 2], ["Power", "y", 2]],
        ["Tuple", "x", -3, 3],
        ["Tuple", "y", -3, 3],
        ["Tuple", "ZRange", "'0,30'"],
        ["Tuple", "Legend", "True"],
        ["Tuple", "XLabel", "'x'"],
        ["Tuple", "YLabel", "'y'"],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<DensityPlot zrange="0,30" legend="true" xlabel="x" ylabel="y">\n  <Add>\n    <Power>x, 2</Power>\n    <Power>y, 2</Power>\n  </Add>\n  <Tuple>x, -3, 3</Tuple>\n  <Tuple>y, -3, 3</Tuple>\n</DensityPlot>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-density-plot expr="x ^ 2 + y ^ 2" xvar="x" xrange="-3,3" yvar="y" yrange="-3,3" zrange="0,30" legend="true" x-label="x" y-label="y"></notatio-density-plot>',
        },
      ],
    },
    {
      id: "pre-sampled-grid",
      caption: "A pre-sampled grid",
      category: "List densities",
      notes:
        "`ListDensityPlot` shades a pre-sampled grid directly -- no expression evaluation. Row 0 is the smallest y, so it sits at the bottom of the frame.",
      expr: [
        "ListDensityPlot",
        ["List", ["List", 0, 1, 2, 3], ["List", 1, 2, 3, 4], ["List", 2, 3, 4, 5], ["List", 3, 4, 5, 6]],
        ["Tuple", "Legend", "True"],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<ListDensityPlot legend="true">\n  <List>\n    <List>0, 1, 2, 3</List>\n    <List>1, 2, 3, 4</List>\n    <List>2, 3, 4, 5</List>\n    <List>3, 4, 5, 6</List>\n  </List>\n</ListDensityPlot>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-density-plot data="[[0,1,2,3],[1,2,3,4],[2,3,4,5],[3,4,5,6]]" legend="true"></notatio-density-plot>',
        },
      ],
    },
  ],
  GraphPlot: [
    {
      id: "tree-rooted-tidy",
      caption: "A rooted tree, laid out tidily by depth",
      category: "TreePlot",
      notes: "Leaves take sequential x left-to-right; each internal node sits at the mean x of its children.",
      expr: [
        "TreeGraph",
        {
          dict: {
            label: "'root'",
            children: [
              "List",
              {
                dict: {
                  label: "'a'",
                  children: [
                    "List",
                    {
                      dict: {
                        label: "'a1'",
                      },
                    },
                    {
                      dict: {
                        label: "'a2'",
                      },
                    },
                  ],
                },
              },
              {
                dict: {
                  label: "'b'",
                },
              },
            ],
          },
        },
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<TreeGraph>{"dict":{"label":"\'root\'","children":["List",{"dict":{"label":"\'a\'","children":["List",{"dict":{"label":"\'a1\'"}},{"dict":{"label":"\'a2\'"}}]}},{"dict":{"label":"\'b\'"}}]}}</TreeGraph>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-graph-plot type="tree" data="{&quot;label&quot;:&quot;root&quot;,&quot;children&quot;:[{&quot;label&quot;:&quot;a&quot;,&quot;children&quot;:[{&quot;label&quot;:&quot;a1&quot;},{&quot;label&quot;:&quot;a2&quot;}]},{&quot;label&quot;:&quot;b&quot;}]}"></notatio-graph-plot>',
        },
      ],
    },
    {
      id: "graph-undirected-circular",
      caption: "Undirected graph on a deterministic circular layout",
      category: "GraphPlot",
      notes: "Node order (and so position) comes from first appearance in `edges` when `nodes` is omitted.",
      expr: [
        "GraphPlot",
        {
          dict: {
            edges: [
              "List",
              ["List", "'a'", "'b'"],
              ["List", "'b'", "'c'"],
              ["List", "'c'", "'d'"],
              ["List", "'d'", "'a'"],
              ["List", "'a'", "'c'"],
            ],
          },
        },
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<GraphPlot>{"dict":{"edges":["List",["List","\'a\'","\'b\'"],["List","\'b\'","\'c\'"],["List","\'c\'","\'d\'"],["List","\'d\'","\'a\'"],["List","\'a\'","\'c\'"]]}}</GraphPlot>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-graph-plot type="graph" data="{&quot;edges&quot;:[[&quot;a&quot;,&quot;b&quot;],[&quot;b&quot;,&quot;c&quot;],[&quot;c&quot;,&quot;d&quot;],[&quot;d&quot;,&quot;a&quot;],[&quot;a&quot;,&quot;c&quot;]]}"></notatio-graph-plot>',
        },
      ],
    },
    {
      id: "graph-directed-arrowheads",
      caption: "Directed: arrowheads on each edge",
      category: "GraphPlot",
      expr: [
        "GraphPlot",
        {
          dict: {
            edges: ["List", ["List", "'a'", "'b'"], ["List", "'b'", "'c'"], ["List", "'c'", "'a'"]],
          },
        },
        ["Tuple", "Directed", "True"],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<GraphPlot directed="true">{"dict":{"edges":["List",["List","\'a\'","\'b\'"],["List","\'b\'","\'c\'"],["List","\'c\'","\'a\'"]]}}</GraphPlot>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-graph-plot type="graph" data="{&quot;edges&quot;:[[&quot;a&quot;,&quot;b&quot;],[&quot;b&quot;,&quot;c&quot;],[&quot;c&quot;,&quot;a&quot;]]}" directed="true"></notatio-graph-plot>',
        },
      ],
    },
    {
      id: "layered-dag-top-to-bottom",
      caption: "A DAG laid out top-to-bottom by longest-path layer",
      category: "LayeredGraphPlot",
      notes:
        "Layer(v) = 1 + the longest path from any source into v; nodes within a layer keep a deterministic (first-seen) order.",
      expr: [
        "LayeredGraphPlot",
        {
          dict: {
            edges: [
              "List",
              ["List", "'a'", "'b'"],
              ["List", "'a'", "'c'"],
              ["List", "'b'", "'d'"],
              ["List", "'c'", "'d'"],
              ["List", "'d'", "'e'"],
            ],
          },
        },
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<LayeredGraphPlot>{"dict":{"edges":["List",["List","\'a\'","\'b\'"],["List","\'a\'","\'c\'"],["List","\'b\'","\'d\'"],["List","\'c\'","\'d\'"],["List","\'d\'","\'e\'"]]}}</LayeredGraphPlot>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-graph-plot type="layered" data="{&quot;edges&quot;:[[&quot;a&quot;,&quot;b&quot;],[&quot;a&quot;,&quot;c&quot;],[&quot;b&quot;,&quot;d&quot;],[&quot;c&quot;,&quot;d&quot;],[&quot;d&quot;,&quot;e&quot;]]}"></notatio-graph-plot>',
        },
      ],
    },
    {
      id: "dendrogram-merge-heights",
      caption: "A merge tree, brackets drawn at each merge height",
      category: "Dendrogram",
      notes:
        "Leaves sit along the x axis; each internal node's `height` sets where its bracket is drawn (inferred as one more than its tallest child when omitted).",
      expr: [
        "Dendrogram",
        {
          dict: {
            height: 3,
            children: [
              "List",
              {
                dict: {
                  height: 1,
                  children: [
                    "List",
                    {
                      dict: {
                        label: "'x'",
                      },
                    },
                    {
                      dict: {
                        label: "'y'",
                      },
                    },
                  ],
                },
              },
              {
                dict: {
                  height: 2,
                  children: [
                    "List",
                    {
                      dict: {
                        label: "'z'",
                      },
                    },
                    {
                      dict: {
                        label: "'w'",
                      },
                    },
                  ],
                },
              },
            ],
          },
        },
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<Dendrogram>{"dict":{"height":3,"children":["List",{"dict":{"height":1,"children":["List",{"dict":{"label":"\'x\'"}},{"dict":{"label":"\'y\'"}}]}},{"dict":{"height":2,"children":["List",{"dict":{"label":"\'z\'"}},{"dict":{"label":"\'w\'"}}]}}]}}</Dendrogram>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-graph-plot type="dendrogram" data="{&quot;height&quot;:3,&quot;children&quot;:[{&quot;height&quot;:1,&quot;children&quot;:[{&quot;label&quot;:&quot;x&quot;},{&quot;label&quot;:&quot;y&quot;}]},{&quot;height&quot;:2,&quot;children&quot;:[{&quot;label&quot;:&quot;z&quot;},{&quot;label&quot;:&quot;w&quot;}]}]}"></notatio-graph-plot>',
        },
      ],
    },
  ],
  ListPlot3D: [
    {
      id: "height-grid",
      caption: "A height grid",
      category: "Surfaces",
      notes:
        "`data[j][i]` is the height at the *i*-th x and *j*-th y sample; each cell becomes one projected quad, shaded by its mean height.",
      expr: [
        "ListPlot3D",
        ["List", ["List", 0, 1, 2, 3], ["List", 1, 3, 4, 3], ["List", 2, 4, 6, 4], ["List", 1, 2, 3, 2]],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: "<ListPlot3D>\n  <List>\n    <List>0, 1, 2, 3</List>\n    <List>1, 3, 4, 3</List>\n    <List>2, 4, 6, 4</List>\n    <List>1, 2, 3, 2</List>\n  </List>\n</ListPlot3D>",
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-list-plot-3d data="[[0,1,2,3],[1,3,4,3],[2,4,6,4],[1,2,3,2]]"></notatio-list-plot-3d>',
        },
      ],
    },
    {
      id: "ridge-different-angle",
      caption: "A ridge, from a different angle",
      category: "Surfaces",
      notes: "`azimuth` rotates about the vertical axis; `elevation` tilts the view above the floor.",
      expr: [
        "ListPlot3D",
        [
          "List",
          ["List", 0, 0, 0, 0, 0],
          ["List", 0, 1, 2, 1, 0],
          ["List", 0, 2, 5, 2, 0],
          ["List", 0, 1, 2, 1, 0],
          ["List", 0, 0, 0, 0, 0],
        ],
        ["Tuple", "Azimuth", 55],
        ["Tuple", "Elevation", 35],
        ["Tuple", "Label", "'a ridge'"],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<ListPlot3D azimuth="55" elevation="35" label="a ridge">\n  <List>\n    <List>0, 0, 0, 0, 0</List>\n    <List>0, 1, 2, 1, 0</List>\n    <List>0, 2, 5, 2, 0</List>\n    <List>0, 1, 2, 1, 0</List>\n    <List>0, 0, 0, 0, 0</List>\n  </List>\n</ListPlot3D>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-list-plot-3d data="[[0,0,0,0,0],[0,1,2,1,0],[0,2,5,2,0],[0,1,2,1,0],[0,0,0,0,0]]" azimuth="55" elevation="35" label="a ridge"></notatio-list-plot-3d>',
        },
      ],
    },
    {
      id: "wireframe",
      caption: "Wireframe",
      category: "Surfaces",
      notes: "`wireframe` draws the quad outlines unfilled -- useful when the mesh matters more than the shading.",
      expr: [
        "ListPlot3D",
        ["List", ["List", 0, 1, 2, 3], ["List", 1, 3, 4, 3], ["List", 2, 4, 6, 4], ["List", 1, 2, 3, 2]],
        ["Tuple", "Wireframe", "True"],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<ListPlot3D wireframe="true">\n  <List>\n    <List>0, 1, 2, 3</List>\n    <List>1, 3, 4, 3</List>\n    <List>2, 4, 6, 4</List>\n    <List>1, 2, 3, 2</List>\n  </List>\n</ListPlot3D>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-list-plot-3d data="[[0,1,2,3],[1,3,4,3],[2,4,6,4],[1,2,3,2]]" wireframe="true"></notatio-list-plot-3d>',
        },
      ],
    },
    {
      id: "hole-in-surface",
      caption: "A hole in the surface",
      category: "Surfaces",
      notes:
        "A missing sample (an empty string, since the schema has no `null`) is a hole: the four quads that touch it are skipped, rather than drawing a spike through zero.",
      expr: [
        "ListPlot3D",
        [
          "List",
          ["List", 0, 0, 0, 0, 0],
          ["List", 0, 1, 2, 1, 0],
          ["List", 0, 2, "''", 2, 0],
          ["List", 0, 1, 2, 1, 0],
          ["List", 0, 0, 0, 0, 0],
        ],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: "<ListPlot3D>\n  <List>\n    <List>0, 0, 0, 0, 0</List>\n    <List>0, 1, 2, 1, 0</List>\n    <List>0, 2, , 2, 0</List>\n    <List>0, 1, 2, 1, 0</List>\n    <List>0, 0, 0, 0, 0</List>\n  </List>\n</ListPlot3D>",
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-list-plot-3d data="[[0,0,0,0,0],[0,1,2,1,0],[0,2,&quot;&quot;,2,0],[0,1,2,1,0],[0,0,0,0,0]]"></notatio-list-plot-3d>',
        },
      ],
    },
    {
      id: "scatter-3d",
      caption: "A 3-D scatter",
      category: "Point clouds",
      notes:
        "Markers are drawn back-to-front, shrinking and fading with distance -- the only depth cue an orthographic view has.",
      expr: [
        "ListPlot3D",
        [
          "List",
          ["List", 0, 0, 0],
          ["List", 1, 0, 1],
          ["List", 0, 1, 1],
          ["List", 1, 1, 0],
          ["List", 0.5, 0.5, 2],
          ["List", 0.2, 0.8, 0.4],
          ["List", 0.8, 0.2, 1.6],
        ],
        ["Tuple", "Type", "'points'"],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<ListPlot3D type="points">\n  <List>\n    <List>0, 0, 0</List>\n    <List>1, 0, 1</List>\n    <List>0, 1, 1</List>\n    <List>1, 1, 0</List>\n    <List>0.5, 0.5, 2</List>\n    <List>0.2, 0.8, 0.4</List>\n    <List>0.8, 0.2, 1.6</List>\n  </List>\n</ListPlot3D>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-list-plot-3d data="[[0,0,0],[1,0,1],[0,1,1],[1,1,0],[0.5,0.5,2],[0.2,0.8,0.4],[0.8,0.2,1.6]]" type="points"></notatio-list-plot-3d>',
        },
      ],
    },
    {
      id: "scatter-no-depth-cue",
      caption: "Without depth cueing",
      category: "Point clouds",
      notes: '`depth-cue="0"` draws every marker at the same size and opacity; `size` sets the near-marker radius.',
      expr: [
        "ListPlot3D",
        [
          "List",
          ["List", 0, 0, 0],
          ["List", 1, 0, 1],
          ["List", 0, 1, 1],
          ["List", 1, 1, 0],
          ["List", 0.5, 0.5, 2],
          ["List", 0.2, 0.8, 0.4],
          ["List", 0.8, 0.2, 1.6],
        ],
        ["Tuple", "Type", "'points'"],
        ["Tuple", "DepthCue", 0],
        ["Tuple", "Size", 5],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<ListPlot3D type="points" depth-cue="0" size="5">\n  <List>\n    <List>0, 0, 0</List>\n    <List>1, 0, 1</List>\n    <List>0, 1, 1</List>\n    <List>1, 1, 0</List>\n    <List>0.5, 0.5, 2</List>\n    <List>0.2, 0.8, 0.4</List>\n    <List>0.8, 0.2, 1.6</List>\n  </List>\n</ListPlot3D>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-list-plot-3d data="[[0,0,0],[1,0,1],[0,1,1],[1,1,0],[0.5,0.5,2],[0.2,0.8,0.4],[0.8,0.2,1.6]]" type="points" depth-cue="0" size="5"></notatio-list-plot-3d>',
        },
      ],
    },
    {
      id: "scattered-triples-surfaced",
      caption: "Scattered triples, surfaced",
      category: "Point clouds",
      notes:
        "Given triples, the surface form bins them onto an *n*x*n* grid -- each cell the mean z of the points that land in it, a cell with no points a hole -- and meshes that.",
      expr: [
        "ListPlot3D",
        [
          "List",
          ["List", 0, 0, 1],
          ["List", 1, 0, 2],
          ["List", 2, 0, 1],
          ["List", 0, 1, 2],
          ["List", 1, 1, 4],
          ["List", 2, 1, 2],
          ["List", 0, 2, 1],
          ["List", 1, 2, 2],
          ["List", 2, 2, 1],
          ["List", 0.4, 0.4, 1.5],
          ["List", 1.6, 1.4, 3],
        ],
        ["Tuple", "N", 3],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<ListPlot3D n="3">\n  <List>\n    <List>0, 0, 1</List>\n    <List>1, 0, 2</List>\n    <List>2, 0, 1</List>\n    <List>0, 1, 2</List>\n    <List>1, 1, 4</List>\n    <List>2, 1, 2</List>\n    <List>0, 2, 1</List>\n    <List>1, 2, 2</List>\n    <List>2, 2, 1</List>\n    <List>0.4, 0.4, 1.5</List>\n    <List>1.6, 1.4, 3</List>\n  </List>\n</ListPlot3D>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-list-plot-3d data="[[0,0,1],[1,0,2],[2,0,1],[0,1,2],[1,1,4],[2,1,2],[0,2,1],[1,2,2],[2,2,1],[0.4,0.4,1.5],[1.6,1.4,3]]" n="3"></notatio-list-plot-3d>',
        },
      ],
    },
  ],
  PolarPlot: [
    {
      id: "cardioid",
      caption: "A cardioid",
      category: "Function curves",
      notes: "r = 1 + cos theta over the default full turn.",
      expr: ["PolarPlot", ["Add", ["Cos", "theta"], 1]],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<PolarPlot>\n  <Add>\n    <Cos>theta</Cos>\n    <Integer value="1" />\n  </Add>\n</PolarPlot>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-polar-plot expr="Cos(theta) + 1"></notatio-polar-plot>',
        },
      ],
    },
    {
      id: "four-petal-rose",
      caption: "A four-petal rose",
      category: "Function curves",
      notes:
        "`filled` shades the enclosed region under the stroked curve. The petals that fall on a negative radius sweep out the opposite quadrants.",
      expr: [
        "PolarPlot",
        ["Cos", ["Multiply", 2, "theta"]],
        ["Tuple", "Filled", "True"],
        ["Tuple", "Label", "'r = cos 2θ'"],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<PolarPlot filled="true" label="r = cos 2θ">\n  <Cos>\n    <Multiply>2, theta</Multiply>\n  </Cos>\n</PolarPlot>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-polar-plot expr="Cos(2theta)" filled="true" label="r = cos 2θ"></notatio-polar-plot>',
        },
      ],
    },
    {
      id: "archimedean-spiral",
      caption: "An Archimedean spiral",
      category: "Function curves",
      notes:
        "`trange` takes theta well past a single turn; `n` raises the angular sampling to keep the outer windings smooth.",
      expr: ["PolarPlot", "theta", ["Tuple", "theta", 0, 18.85], ["Tuple", "N", 600]],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<PolarPlot n="600">\n  <Symbol value="theta" />\n  <Tuple>theta, 0, 18.85</Tuple>\n</PolarPlot>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-polar-plot expr="theta" tvar="theta" trange="0,18.85" n="600"></notatio-polar-plot>',
        },
      ],
    },
    {
      id: "limacon-no-grid",
      caption: "A limaçon, without the grid",
      category: "Function curves",
      expr: ["PolarPlot", ["Add", ["Multiply", 2, ["Cos", "theta"]], 1], ["Tuple", "Axes", "'false'"]],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<PolarPlot axes="false">\n  <Add>\n    <Multiply>\n      <Integer value="2" />\n      <Cos>theta</Cos>\n    </Multiply>\n    <Integer value="1" />\n  </Add>\n</PolarPlot>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-polar-plot expr="2 * Cos(theta) + 1" axes="false"></notatio-polar-plot>',
        },
      ],
    },
    {
      id: "explicit-pairs",
      caption: "Explicit (θ, r) pairs",
      category: "List polar plots",
      notes: "`closed` joins the last point back to the first.",
      expr: [
        "ListPolarPlot",
        ["List", ["List", 0, 1], ["List", 1.57, 2], ["List", 3.14, 1], ["List", 4.71, 2]],
        ["Tuple", "Closed", "True"],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<ListPolarPlot closed="true">\n  <List>\n    <List>0, 1</List>\n    <List>1.57, 2</List>\n    <List>3.14, 1</List>\n    <List>4.71, 2</List>\n  </List>\n</ListPolarPlot>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-polar-plot data="[[0,1],[1.57,2],[3.14,1],[4.71,2]]" closed="true"></notatio-polar-plot>',
        },
      ],
    },
    {
      id: "bare-radii",
      caption: "Bare radii over a turn",
      category: "List polar plots",
      expr: ["ListPolarPlot", ["List", 1, 1.5, 2, 1.5, 1, 1.5, 2, 1.5, 1]],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: "<ListPolarPlot>\n  <List>1, 1.5, 2, 1.5, 1, 1.5, 2, 1.5, 1</List>\n</ListPolarPlot>",
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-polar-plot data="[1,1.5,2,1.5,1,1.5,2,1.5,1]"></notatio-polar-plot>',
        },
      ],
    },
  ],
  VectorPlot: [
    {
      id: "rigid-rotation",
      caption: "Rigid rotation",
      category: "Vector fields",
      notes: "F = (−y, x): the arrows circulate, and their length grows with the distance from the origin.",
      expr: ["VectorPlot", ["Tuple", ["Negate", "y"], "x"], ["Tuple", "x", -2, 2], ["Tuple", "y", -2, 2]],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<VectorPlot>\n  <Tuple>\n    <Negate>y</Negate>\n    <Symbol value="x" />\n  </Tuple>\n  <Tuple>x, -2, 2</Tuple>\n  <Tuple>y, -2, 2</Tuple>\n</VectorPlot>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-vector-plot u="-y" v="x" xvar="x" xrange="-2,2" yvar="y" yrange="-2,2"></notatio-vector-plot>',
        },
      ],
    },
    {
      id: "a-saddle-field",
      caption: "A saddle",
      category: "Vector fields",
      notes:
        "The same field as a comma-separated pair -- `field` and separate `u`/`v` are two spellings of the same vector.",
      expr: [
        "VectorPlot",
        ["Tuple", "x", ["Negate", "y"]],
        ["Tuple", "x", -2, 2],
        ["Tuple", "y", -2, 2],
        ["Tuple", "Label", "'(x, −y)'"],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<VectorPlot label="(x, −y)">\n  <Tuple>\n    <Symbol value="x" />\n    <Negate>y</Negate>\n  </Tuple>\n  <Tuple>x, -2, 2</Tuple>\n  <Tuple>y, -2, 2</Tuple>\n</VectorPlot>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-vector-plot u="x" v="-y" xvar="x" xrange="-2,2" yvar="y" yrange="-2,2" label="(x, −y)"></notatio-vector-plot>',
        },
      ],
    },
    {
      id: "trigonometric-field",
      caption: "A trigonometric field",
      category: "Vector fields",
      notes: "`n` sets the arrow grid's resolution.",
      expr: [
        "VectorPlot",
        ["Tuple", ["Sin", "y"], ["Cos", "x"]],
        ["Tuple", "x", -3.14, 3.14],
        ["Tuple", "y", -3.14, 3.14],
        ["Tuple", "N", 16],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<VectorPlot n="16">\n  <Tuple>\n    <Sin>y</Sin>\n    <Cos>x</Cos>\n  </Tuple>\n  <Tuple>x, -3.14, 3.14</Tuple>\n  <Tuple>y, -3.14, 3.14</Tuple>\n</VectorPlot>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-vector-plot u="Sin(y)" v="Cos(x)" xvar="x" xrange="-3.14,3.14" yvar="y" yrange="-3.14,3.14" n="16"></notatio-vector-plot>',
        },
      ],
    },
    {
      id: "rotation-as-streamlines",
      caption: "Rotation, as streamlines",
      category: "Streamlines",
      notes: "The circular orbits of F = (−y, x). Each line carries one mid-line arrowhead showing the flow direction.",
      expr: ["StreamPlot", ["Tuple", ["Negate", "y"], "x"], ["Tuple", "x", -2, 2], ["Tuple", "y", -2, 2]],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<StreamPlot>\n  <Tuple>\n    <Negate>y</Negate>\n    <Symbol value="x" />\n  </Tuple>\n  <Tuple>x, -2, 2</Tuple>\n  <Tuple>y, -2, 2</Tuple>\n</StreamPlot>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-vector-plot type="stream" u="-y" v="x" xvar="x" xrange="-2,2" yvar="y" yrange="-2,2"></notatio-vector-plot>',
        },
      ],
    },
    {
      id: "dipole-like-flow",
      caption: "A dipole-like flow",
      category: "Streamlines",
      notes:
        "`steps` caps the RK4 steps taken in each direction from a seed -- longer lines at the cost of more integration.",
      expr: [
        "StreamPlot",
        ["Tuple", ["Add", ["Power", "x", 2], ["Negate", ["Power", "y", 2]]], ["Multiply", 2, "x", "y"]],
        ["Tuple", "x", -2, 2],
        ["Tuple", "y", -2, 2],
        ["Tuple", "N", 11],
        ["Tuple", "Steps", 80],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<StreamPlot n="11" steps="80">\n  <Tuple>\n    <Add>\n      <Power>x, 2</Power>\n      <Negate>\n        <Power>y, 2</Power>\n      </Negate>\n    </Add>\n    <Multiply>2, x, y</Multiply>\n  </Tuple>\n  <Tuple>x, -2, 2</Tuple>\n  <Tuple>y, -2, 2</Tuple>\n</StreamPlot>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-vector-plot type="stream" u="x ^ 2 + -y ^ 2" v="2 * x * y" xvar="x" xrange="-2,2" yvar="y" yrange="-2,2" n="11" steps="80"></notatio-vector-plot>',
        },
      ],
    },
    {
      id: "shear-flow",
      caption: "Shear flow",
      category: "Streamlines",
      expr: [
        "StreamPlot",
        ["Tuple", "y", ["Sin", "x"]],
        ["Tuple", "x", -3.14, 3.14],
        ["Tuple", "y", -2, 2],
        ["Tuple", "N", 10],
        ["Tuple", "XLabel", "'x'"],
        ["Tuple", "YLabel", "'y'"],
      ],
      forms: [
        {
          id: "head",
          label: "<Head>",
          text: '<StreamPlot n="10" xlabel="x" ylabel="y">\n  <Tuple>\n    <Symbol value="y" />\n    <Sin>x</Sin>\n  </Tuple>\n  <Tuple>x, -3.14, 3.14</Tuple>\n  <Tuple>y, -2, 2</Tuple>\n</StreamPlot>',
        },
        {
          id: "html",
          label: "Web component",
          text: '<notatio-vector-plot type="stream" u="y" v="Sin(x)" xvar="x" xrange="-3.14,3.14" yvar="y" yrange="-2,2" n="10" x-label="x" y-label="y"></notatio-vector-plot>',
        },
      ],
    },
  ],
};
