// GENERATED by scripts/collect-stories.ts — do not edit by hand.
//
// Every component's stories (reference/<Name>.stories.yaml), keyed by component name, each
// with its markup derived from its vdom and pinned. Regenerate with:
//
//   vp node packages/components/scripts/collect-stories.ts

export interface StoryVdom {
  readonly tag: string;
  readonly attributes?: Readonly<Record<string, string>>;
  readonly children?: readonly StoryVdom[];
  readonly text?: string;
}

export interface StoryData {
  readonly id: string;
  readonly caption: string;
  readonly category?: string;
  readonly notes?: string;
  readonly vdom: StoryVdom;
  readonly markup: string;
}

export const STORIES_DATA: Readonly<Record<string, readonly StoryData[]>> = {
  BarChart3D: [
    {
      id: "a-3-3-matrix",
      caption: "A 3×3 matrix",
      category: "Bars",
      vdom: {
        tag: "notatio-bar-chart-3d",
        attributes: {
          data: "[[1,2,3],[2,4,3],[3,1,5]]",
        },
      },
      markup: '<notatio-bar-chart-3d data="[[1,2,3],[2,4,3],[3,1,5]]"></notatio-bar-chart-3d>',
    },
    {
      id: "a-single-row",
      caption: "A single row",
      category: "Bars",
      notes: "A flat list is one row of bars — the 3-D counterpart of a plain BarChart.",
      vdom: {
        tag: "notatio-bar-chart-3d",
        attributes: {
          data: "[3,1,4,1,5,9,2,6]",
          label: "digits of π",
        },
      },
      markup: '<notatio-bar-chart-3d data="[3,1,4,1,5,9,2,6]" label="digits of π"></notatio-bar-chart-3d>',
    },
    {
      id: "labelled-categories",
      caption: "Labelled categories",
      category: "Bars",
      notes: "col-labels and row-labels take comma-separated categories, drawn just outside the near floor edges.",
      vdom: {
        tag: "notatio-bar-chart-3d",
        attributes: {
          data: "[[4,2,3],[1,5,2]]",
          "col-labels": "a,b,c",
          "row-labels": "x,y",
        },
      },
      markup:
        '<notatio-bar-chart-3d data="[[4,2,3],[1,5,2]]" col-labels="a,b,c" row-labels="x,y"></notatio-bar-chart-3d>',
    },
    {
      id: "tighter-packing-steeper-view",
      caption: "Tighter packing, steeper view",
      category: "Bars",
      notes: "gap is the space between neighbouring bars as a fraction of a cell; at 0 the bars touch.",
      vdom: {
        tag: "notatio-bar-chart-3d",
        attributes: {
          data: "[[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]]",
          gap: "0.05",
          elevation: "45",
          azimuth: "40",
        },
      },
      markup:
        '<notatio-bar-chart-3d data="[[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]]" gap="0.05" elevation="45" azimuth="40"></notatio-bar-chart-3d>',
    },
    {
      id: "negative-values",
      caption: "Negative values",
      category: "Bars",
      notes: "When the data straddles zero, the zero plane sits inside the cube and negative bars hang beneath it.",
      vdom: {
        tag: "notatio-bar-chart-3d",
        attributes: {
          data: "[[-2,1,3],[2,-1,1]]",
        },
      },
      markup: '<notatio-bar-chart-3d data="[[-2,1,3],[2,-1,1]]"></notatio-bar-chart-3d>',
    },
    {
      id: "a-pinned-height-scale",
      caption: "A pinned height scale",
      category: "Bars",
      notes:
        'zrange pins the height scale so several charts can be compared; axes="false" drops the projected axis box.',
      vdom: {
        tag: "notatio-bar-chart-3d",
        attributes: {
          data: "[[1,2],[2,3]]",
          zrange: "0,10",
          axes: "false",
        },
      },
      markup: '<notatio-bar-chart-3d data="[[1,2],[2,3]]" zrange="0,10" axes="false"></notatio-bar-chart-3d>',
    },
  ],
};
