// GENERATED by scripts/collect-stories.ts — do not edit by hand.
//
// Every component's stories (reference/<Name>.stories.yaml), keyed by component name, each
// with its markup derived from its expr and pinned. Regenerate with:
//
//   vp node packages/components/scripts/collect-stories.ts

export type MathJSON = number | string | boolean | readonly MathJSON[] | { readonly [key: string]: unknown };

export interface StoryData {
  readonly id: string;
  readonly caption: string;
  readonly category?: string;
  readonly notes?: string;
  readonly expr: MathJSON;
  readonly markup: string;
}

export const STORIES_DATA: Readonly<Record<string, readonly StoryData[]>> = {
  BarChart3D: [
    {
      id: "a-3-3-matrix",
      caption: "A 3×3 matrix",
      category: "Bars",
      expr: ["BarChart3D", ["List", ["List", 1, 2, 3], ["List", 2, 4, 3], ["List", 3, 1, 5]]],
      markup:
        "<BarChart3D>\n  <List>\n    <List>1, 2, 3</List>\n    <List>2, 4, 3</List>\n    <List>3, 1, 5</List>\n  </List>\n</BarChart3D>",
    },
    {
      id: "a-single-row",
      caption: "A single row",
      category: "Bars",
      notes: "A flat list is one row of bars — the 3-D counterpart of a plain BarChart.",
      expr: ["BarChart3D", ["List", 3, 1, 4, 1, 5, 9, 2, 6], ["Tuple", "Label", "'digits of π'"]],
      markup: '<BarChart3D label="digits of π">\n  <List>3, 1, 4, 1, 5, 9, 2, 6</List>\n</BarChart3D>',
    },
    {
      id: "labelled-categories",
      caption: "Labelled categories",
      category: "Bars",
      notes: "col-labels and row-labels take comma-separated categories, drawn just outside the near floor edges.",
      expr: [
        "BarChart3D",
        ["List", ["List", 4, 2, 3], ["List", 1, 5, 2]],
        ["Tuple", "ColLabels", "'a,b,c'"],
        ["Tuple", "RowLabels", "'x,y'"],
      ],
      markup:
        '<BarChart3D col-labels="a,b,c" row-labels="x,y">\n  <List>\n    <List>4, 2, 3</List>\n    <List>1, 5, 2</List>\n  </List>\n</BarChart3D>',
    },
    {
      id: "tighter-packing-steeper-view",
      caption: "Tighter packing, steeper view",
      category: "Bars",
      notes: "gap is the space between neighbouring bars as a fraction of a cell; at 0 the bars touch.",
      expr: [
        "BarChart3D",
        ["List", ["List", 1, 2, 3, 4], ["List", 2, 3, 4, 5], ["List", 3, 4, 5, 6], ["List", 4, 5, 6, 7]],
        ["Tuple", "Gap", 0.05],
        ["Tuple", "Elevation", 45],
        ["Tuple", "Azimuth", 40],
      ],
      markup:
        '<BarChart3D gap="0.05" elevation="45" azimuth="40">\n  <List>\n    <List>1, 2, 3, 4</List>\n    <List>2, 3, 4, 5</List>\n    <List>3, 4, 5, 6</List>\n    <List>4, 5, 6, 7</List>\n  </List>\n</BarChart3D>',
    },
    {
      id: "negative-values",
      caption: "Negative values",
      category: "Bars",
      notes: "When the data straddles zero, the zero plane sits inside the cube and negative bars hang beneath it.",
      expr: ["BarChart3D", ["List", ["List", -2, 1, 3], ["List", 2, -1, 1]]],
      markup: "<BarChart3D>\n  <List>\n    <List>-2, 1, 3</List>\n    <List>2, -1, 1</List>\n  </List>\n</BarChart3D>",
    },
    {
      id: "a-pinned-height-scale",
      caption: "A pinned height scale",
      category: "Bars",
      notes:
        'zrange pins the height scale so several charts can be compared; axes="false" drops the projected axis box.',
      expr: [
        "BarChart3D",
        ["List", ["List", 1, 2], ["List", 2, 3]],
        ["Tuple", "ZRange", "'0,10'"],
        ["Tuple", "Axes", "'false'"],
      ],
      markup:
        '<BarChart3D zrange="0,10" axes="false">\n  <List>\n    <List>1, 2</List>\n    <List>2, 3</List>\n  </List>\n</BarChart3D>',
    },
  ],
};
