// Assemble the manifest (https://github.com/enumeratio/enumeratio/wiki/Manifest) into src/generated/, which `vp pack` then
// builds into dist/: each package's index from its records (scripts/package-index.ts), and
// compute-engine's own heads from a bare engine, put together by src/assemble.ts. Loads no
// package's code, so it sits at the bottom of the build graph.
//
//   node packages/manifest/scripts/build.ts

import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { ComputeEngine } from "@cortex-js/compute-engine";
import { canonicalOf } from "./declares-of.ts";
import { packageDirs, recordDirs } from "@enumeratio/entry/node";
import { assembleManifest, type PackageIndex } from "../src/assemble.ts";
import type { Placement } from "../src/hierarchy.ts";
import { notationSpecifier, type PackageField } from "../src/package-field.ts";
import { packageIndexOf } from "./package-index.ts";

const PACKAGES = fileURLToPath(new URL("../../", import.meta.url));
const OUT = fileURLToPath(new URL("../src/generated/", import.meta.url));

const cmp = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0);

// --- each package's index ---------------------------------------------------------------

/** Each package's notation entry, from its `package.json`'s `enumeratio.notation`. */
const notations = new Map<string, string>();
/** Each package's place in the hierarchy, from its `enumeratio.layer`, `area` and `extends`. */
const placements: Record<string, Placement> = {};
// The tree's packages, then the libraries installed beside them (a name in the tree wins).
const workspaceDirs = packageDirs(PACKAGES).map((p) => p.dir);
for (const dir of workspaceDirs) {
  const file = join(dir, "package.json");
  if (!existsSync(file)) continue;
  const pkg = JSON.parse(readFileSync(file, "utf8")) as { name?: string; enumeratio?: PackageField };
  const specifier = pkg.name === undefined ? undefined : notationSpecifier(pkg.name, pkg.enumeratio);
  if (specifier !== undefined) notations.set(pkg.name!.replace(/^@enumeratio\//, ""), specifier);
  const field = pkg.enumeratio;
  if (pkg.name === undefined || field?.layer === undefined) continue;
  const name = pkg.name.replace(/^@enumeratio\//, "");
  placements[name] = {
    layer: field.layer,
    ...(field.area === undefined ? {} : { area: field.area }),
    extends: field.extends ?? [],
  };
  for (const [subpath, placement] of Object.entries(field.entries ?? {}))
    placements[`${name}/${subpath.replace(/^\.\//, "")}`] = placement;
}

// One per package with records, in the order the records are read, then those with only a notation.
const withRecords = recordDirs(PACKAGES);
const indexes: PackageIndex[] = [
  ...withRecords.map(({ package: pkg, dir }) => packageIndexOf(pkg, dir, notations.get(pkg))),
  ...[...notations]
    .filter(([pkg]) => !withRecords.some((r) => r.package === pkg))
    .map(([pkg, notation]) => packageIndexOf(pkg, undefined, notation)),
];

// --- the engine's own heads -------------------------------------------------------------

interface Scope {
  readonly bindings: Map<string, unknown>;
  readonly parent?: Scope;
}

const bare = new ComputeEngine();
const engineNames = new Set<string>();
for (
  let scope: Scope | undefined = (bare as unknown as { context: { lexicalScope: Scope } }).context.lexicalScope;
  scope !== undefined;
  scope = scope.parent
)
  for (const name of scope.bindings.keys()) engineNames.add(name);

function engineTypes(): Map<string, string> {
  const ce = bare;
  const names = engineNames;
  const types = new Map<string, string>();
  for (const name of names) {
    if (!/^[A-Z]/.test(name)) continue;
    const found = ce.lookupDefinition(name) as
      | { operator?: { signature?: unknown }; value?: { type?: unknown } }
      | undefined;
    const type = found?.operator?.signature ?? found?.value?.type;
    if (type !== undefined) types.set(name, `${type as string}`);
  }
  return types;
}

const {
  symbols,
  declared: perPackage,
  examples: examplesOf,
  notations: notationTable,
} = assembleManifest(indexes, {
  types: engineTypes(),
  typing: new ComputeEngine(),
});

// --- writing ----------------------------------------------------------------------------

const HEADER = "// GENERATED by packages/manifest/scripts/build.ts at build time; never committed.\n\n";
const sorted = <T>(table: Record<string, T>): Record<string, T> =>
  Object.fromEntries(
    Object.keys(table)
      .toSorted(cmp)
      .map((k) => [k, table[k]]),
  );

rmSync(OUT, { recursive: true, force: true });
mkdirSync(join(OUT, "package"), { recursive: true });
writeFileSync(
  join(OUT, "symbols.ts"),
  `${HEADER}import type { SymbolInfo } from "../types.ts";\n\nexport const SYMBOLS: Readonly<Record<string, SymbolInfo>> = ${JSON.stringify(symbols)};\n`,
);
writeFileSync(
  join(OUT, "notations.ts"),
  `${HEADER}/** Each package with a notation entry, by manifest name: the specifier a host imports it by. */\nexport const NOTATIONS: Readonly<Record<string, string>> = ${JSON.stringify(sorted(notationTable))};\n`,
);
for (const [pkg, table] of [...perPackage].toSorted(([a], [b]) => cmp(a, b))) {
  const declared = sorted(table);
  const summaries = Object.fromEntries(Object.entries(declared).map(([k, v]) => [k, v.summary]));
  writeFileSync(
    join(OUT, "package", `${pkg}.ts`),
    `${HEADER}import type { DeclaredSymbol } from "../../types.ts";

/** What \`${pkg}\`'s declare reads for each head it documents. */
export const SYMBOLS: Readonly<Record<string, DeclaredSymbol>> = ${JSON.stringify(declared)};

/** Each head's record \`summary\`, for its \`description\`. */
export const SUMMARIES: Readonly<Record<string, string>> = ${JSON.stringify(summaries)};

/** How many examples each head's record shows and holds it to, where it has any. */
export const EXAMPLES: Readonly<Record<string, number>> = ${JSON.stringify(sorted(examplesOf.get(pkg) ?? {}))};
`,
  );
}

writeFileSync(
  join(OUT, "hierarchy.ts"),
  `${HEADER}import type { Placement } from "../hierarchy.ts";\n\nexport const HIERARCHY_DATA: Readonly<Record<string, Placement>> = ${JSON.stringify(sorted(placements))};\n`,
);
writeFileSync(
  join(OUT, "canonical.ts"),
  `${HEADER}/** compute-engine's own heads that canonicalise to others (\`Lb(x)\` is \`Log(x, 2)\`), with the heads. */\nexport const ENGINE_CANONICAL: Readonly<Record<string, readonly string[]>> = ${JSON.stringify(canonicalOf(new ComputeEngine(), engineNames))};\n`,
);

// A literal import per package, so a bundler keeps each one its own chunk, loaded by `describe`.
const loaders = [...perPackage.keys()]
  .toSorted(cmp)
  .map((pkg) => `  ${JSON.stringify(pkg)}: () => import("./package/${pkg}.ts"),`);
writeFileSync(
  join(OUT, "package-modules.ts"),
  `${HEADER}/** What \`describe\` reads of a package's module. */
export interface PackageModule {
  readonly SUMMARIES: Readonly<Record<string, string>>;
  readonly EXAMPLES?: Readonly<Record<string, number>>;
}

/** Each package's module, imported on first use. */
export const PACKAGE_MODULES: Readonly<Record<string, () => Promise<PackageModule>>> = {
${loaders.join("\n")}
};
`,
);

console.log(`manifest:${Object.keys(symbols).length} heads, ${perPackage.size} packages -> ${OUT}`);
