// Rebuild `@enumeratio/oracle`'s `mappings-data.ts` from every head's `origin: mapped`
// `bindings:` rows (symbol-metadata step 5, design/speculative/symbol-metadata.md). The oracle
// emitters need this as plain, synchronous data -- `emit.ts` runs in the site build and in the
// browser, so it cannot parse YAML at runtime.
//
// Lives in reference's scripts/ (the only place that can cheaply read every package's YAML)
// but writes into the ORACLE package's src/ -- a relative file write, not a new runtime
// dependency from oracle onto reference (reference already depends on oracle, not the other
// way around).
//
//   vp node packages/reference/scripts/collect-mappings.ts

import { writeFormatted } from "@enumeratio/entry/node";
import { referenceData } from "../src/node.ts";

const { entries } = referenceData();

interface MappingRow {
  head: string;
  arity?: number;
  emit: Record<string, string>;
  threadArg?: number;
  note?: string;
}

const key = (head: string, arity: number | undefined): string => `${head}\0${arity ?? ""}`;
const byKey = new Map<string, MappingRow>();

for (const entry of entries) {
  for (const b of entry.bindings ?? []) {
    // A `mapped` binding with no `template` is a hand-written aside about a head MAPPINGS
    // never covered (e.g. BarnesG's "wolfram / mpmath, same normalisation" note) -- prose,
    // not one of this table's rows.
    if (b.origin !== "mapped" || b.template === undefined) continue;
    const k = key(entry.name, b.arity);
    const row = byKey.get(k) ?? { head: entry.name, arity: b.arity, emit: {} };
    row.emit[b.form] = b.template;
    if (b.threadArg !== undefined) row.threadArg = b.threadArg;
    if (b.note !== undefined) row.note = b.note;
    byKey.set(k, row);
  }
}

const rows = [...byKey.values()].sort((a, b) => a.head.localeCompare(b.head) || (a.arity ?? -1) - (b.arity ?? -1));

await writeFormatted(
  new URL("../../oracle/src/mappings-data.ts", import.meta.url),
  `// GENERATED by packages/reference/scripts/collect-mappings.ts — do not edit by hand.
//
// Head → external-system source, rebuilt from every head's \`origin: mapped\` \`bindings:\` rows
// (design/speculative/symbol-metadata.md step 5). Regenerate with:
//
//   vp node packages/reference/scripts/collect-mappings.ts

import type { Mapping } from "./mappings.ts";

export const MAPPINGS_DATA: readonly Mapping[] = ${JSON.stringify(rows, null, 2)};
`,
);

console.log(`${rows.length} mapping rows collected across ${new Set(rows.map((r) => r.head)).size} heads`);
