// Collect what the engine and our own tables already know about where each symbol lives
// elsewhere, and rewrite the two generated files:
//
//   src/engine-symbols-data.ts   every symbol a bare compute-engine binds -- its description,
//                                signature and Wikidata id, as the engine declares them
//   src/crosswalk-data.ts        per head: the Fungrim identities whose rules mention it, the
//                                Wolfram symbol the transpiler vouches for, and the equivalent
//                                call in each oracle kernel
//
// Everything here is offline and mechanical; the hand-kept half of the crosswalk lives in
// `src/crosswalk/curated.ts` and the catalog's half in `@enumeratio/catalog`. Regenerate:
//
//   vp node packages/reference/scripts/collect-crosswalk.ts

import { writeFileSync } from "node:fs";
import { ComputeEngine } from "@cortex-js/compute-engine";
import { FUNGRIM_CORE } from "@cortex-js/compute-engine/identities";
import { MAPPINGS } from "@enumeratio/oracle/src";
import { HEADS, SYMBOLS } from "@enumeratio/wolfram/src";
import { entries } from "../src/entries.ts";
import { crosswalk, engineSymbols } from "./crosswalk.ts";

const symbols = engineSymbols(new ComputeEngine());
const records = crosswalk(
  [...new Set([...symbols.map((s) => s.name), ...entries.map((e) => e.name)])].sort(),
  FUNGRIM_CORE.rules,
  { ...SYMBOLS, ...HEADS },
  MAPPINGS,
);

const header = (
  what: string,
): string => `// GENERATED by scripts/collect-crosswalk.ts — do not edit by hand.
//
// ${what}
//
//   vp node packages/reference/scripts/collect-crosswalk.ts
`;

writeFileSync(
  new URL("../src/engine-symbols-data.ts", import.meta.url),
  `${header(
    "Every symbol a bare compute-engine binds, as the engine itself describes it. Regenerate with:",
  )}
/** One symbol of the engine's own namespace. */
export interface EngineSymbol {
  readonly name: string;
  readonly kind: "operator" | "constant";
  readonly description?: string;
  /** The declared function signature, or a constant's type. */
  readonly signature?: string;
  /** The Wikidata Q-id the engine's definition carries. */
  readonly wikidata?: string;
  readonly keywords?: readonly string[];
}

export const engineSymbols: readonly EngineSymbol[] = ${JSON.stringify(symbols, null, 2)};
`,
);

writeFileSync(
  new URL("../src/crosswalk-data.ts", import.meta.url),
  `${header(
    "What the engine's identities, the transpiler and the oracle table say about each head. Regenerate with:",
  )}
/** One head's mechanically derived references. Only heads with at least one are listed. */
export interface CrosswalkRecord {
  readonly name: string;
  /** Fungrim entry ids whose compiled rule mentions this head. */
  readonly fungrimEntries?: readonly string[];
  /** The Wolfram symbol the transpiler emits for this head. */
  readonly wolfram?: string;
  /** The equivalent call in each oracle kernel, per arity, as its emit template. */
  readonly oracle?: readonly { system: string; call: string; arity?: number }[];
}

export const crosswalk: readonly CrosswalkRecord[] = ${JSON.stringify(records, null, 2)};
`,
);

const withFungrim = records.filter((r) => r.fungrimEntries?.length).length;
const withWolfram = records.filter((r) => r.wolfram).length;
const withOracle = records.filter((r) => r.oracle?.length).length;
process.stdout.write(
  `${symbols.length} engine symbols (${symbols.filter((s) => s.wikidata).length} with wikidata); ` +
    `${records.length} heads cross-referenced — fungrim ${withFungrim}, wolfram ${withWolfram}, oracle ${withOracle}\n`,
);
