// Collect the provenance data the library ships, and rewrite `src/provenance-data.ts`.
//
// The classification logic lives in `provenance.ts` next door; this is the runner. Nothing
// here is exported by the package — the package exports the DATA, and a test re-derives it
// to make sure the committed copy has not gone stale.
//
// Everything collected here is offline: two compute-engine instances, plus a reflection of
// the head map in `@enumeratio/wolfram`. No external kernel, so it can run in CI. The
// oracle lanes that DO need a kernel (wolframscript, mpmath, sympy, sage) report separately
// and are never a gate.
//
//   vp node packages/reference/scripts/collect-provenance.ts

import { writeFileSync } from "node:fs";
import { ComputeEngine } from "@cortex-js/compute-engine";
import { HEADS } from "@enumeratio/wolfram/src";
import { referenceEntries } from "../src/node.ts";
import { declaredEngine } from "./engines.ts";
import { type HeadRecord, collect } from "./provenance.ts";

const entries = referenceEntries();

// Coverage answers come from an external kernel (collect-coverage.ts); this pass is
// offline, so carry whatever the last run found rather than blanking it.
let previous: readonly HeadRecord[] = [];
try {
  previous = ((await import("../src/provenance-data.ts")) as { provenance: HeadRecord[] })
    .provenance;
} catch {
  previous = [];
}
const records = collect(new ComputeEngine(), declaredEngine(), entries, HEADS, previous);

const source = `// GENERATED by scripts/collect-provenance.ts — do not edit by hand.
//
// Where each documented head comes from, and whether an external system has a function of
// the same meaning. Regenerate with:
//
//   vp node packages/reference/scripts/collect-provenance.ts
//
// \`provenance\` is:
//   compute-engine  a bare engine resolves it and we change nothing
//   extension       a bare engine has never heard of it
//   override        native, and declaring our libraries changes some result
//   unknown         the entry's examples never call its own head

/** One head's provenance, and its known equivalents elsewhere. */
export interface HeadRecord {
  readonly name: string;
  readonly provenance: "compute-engine" | "extension" | "override" | "unknown";
  /** The library the entry claims, or null for "compute-engine's own". */
  readonly declared: string | null;
  /** The Wolfram symbol this head is RENAMED to, or null when the name passes through. */
  readonly wolframAlias: string | null;
  /** External systems that have a function of this name — "wolfram", "sympy", "mpmath". */
  readonly elsewhere: readonly string[];
}

export const provenance: readonly HeadRecord[] = ${JSON.stringify(records, null, 2)};
`;

writeFileSync(new URL("../src/provenance-data.ts", import.meta.url), source);

const counts = new Map<string, number>();
for (const record of records) {
  counts.set(record.provenance, (counts.get(record.provenance) ?? 0) + 1);
}
const mapped = records.filter((record) => record.elsewhere.length > 0).length;
process.stdout.write(
  `${records.length} heads — ${[...counts]
    .map(([kind, n]) => `${kind} ${n}`)
    .join(", ")}; ${mapped} known elsewhere\n`,
);
