// Rebuild `src/crosswalk/curated-data.ts` from every head's `references:`/`names:` fields
// (symbol-metadata step 2, design/speculative/symbol-metadata.md). The crosswalk consumer
// needs these as plain, synchronous, browser-safe lookups -- it runs in the site build and in
// the browser -- so this is the "generated *-data.ts per consumer" option the design doc
// prefers over reading YAML at runtime.
//
//   vp node packages/reference/scripts/collect-curated.ts

import { writeFormatted } from "@enumeratio/entry/node";
import { referenceData } from "../src/node.ts";

const { entries } = referenceData();

const CURATED: Record<string, unknown> = {};
const FUNGRIM_NAMES: Record<string, string> = {};
const DLMF_NAMES: Record<string, string> = {};
const WIKIDATA_FIXES: Record<string, string> = {};
const WIKIDATA_CONFIRMED: string[] = [];
const CATALOG_ALIASES: Record<string, string> = {};

for (const entry of entries) {
  if (entry.references?.length) CURATED[entry.name] = entry.references;
  const names = entry.names;
  if (!names) continue;
  if (names.fungrim !== undefined) FUNGRIM_NAMES[entry.name] = names.fungrim;
  if (names.dlmf !== undefined) DLMF_NAMES[entry.name] = names.dlmf;
  if (names.wikidata !== undefined) WIKIDATA_FIXES[entry.name] = names.wikidata;
  if (names.wikidataConfirmed) WIKIDATA_CONFIRMED.push(entry.name);
  if (names.catalog !== undefined) CATALOG_ALIASES[entry.name] = names.catalog;
}

WIKIDATA_CONFIRMED.sort();

await writeFormatted(
  new URL("../src/crosswalk/curated-data.ts", import.meta.url),
  `// GENERATED by scripts/collect-curated.ts — do not edit by hand.
//
// The hand-kept half of the crosswalk, rebuilt from every head's \`references:\`/\`names:\`
// fields (design/speculative/symbol-metadata.md). Regenerate with:
//
//   vp node packages/reference/scripts/collect-curated.ts

import type { Reference } from "./types.ts";

/** Curated references, keyed by head -- design/speculative/symbol-metadata.md's \`references:\`. */
export const CURATED: Readonly<Record<string, readonly Reference[]>> = ${JSON.stringify(CURATED, null, 2)};

/** Fungrim's own spelling, where a head's page doesn't use ours verbatim -- \`names.fungrim\`. */
export const FUNGRIM_NAMES: Readonly<Record<string, string>> = ${JSON.stringify(FUNGRIM_NAMES, null, 2)};

/** The catalog's subject name, where it differs from the head's -- \`names.catalog\`. */
export const CATALOG_ALIASES: Readonly<Record<string, string>> = ${JSON.stringify(CATALOG_ALIASES, null, 2)};

/** The DLMF index's own wording -- \`names.dlmf\`. */
export const DLMF_NAMES: Readonly<Record<string, string>> = ${JSON.stringify(DLMF_NAMES, null, 2)};

/** Replaces the engine's own Wikidata id, which is wrong -- \`names.wikidata\`. */
export const WIKIDATA_FIXES: Readonly<Record<string, string>> = ${JSON.stringify(WIKIDATA_FIXES, null, 2)};

/** The engine's own Wikidata id, checked by hand and confirmed right -- \`names.wikidataConfirmed\`. */
export const WIKIDATA_CONFIRMED: ReadonlySet<string> = new Set(${JSON.stringify(WIKIDATA_CONFIRMED)});
`,
);

console.log(
  `${Object.keys(CURATED).length} curated rows, ${Object.keys(FUNGRIM_NAMES).length} fungrim, ` +
    `${Object.keys(DLMF_NAMES).length} dlmf, ${Object.keys(WIKIDATA_FIXES).length} wikidata fixes, ` +
    `${WIKIDATA_CONFIRMED.length} wikidata confirmed, ${Object.keys(CATALOG_ALIASES).length} catalog aliases`,
);
