// Build `@enumeratio/oracle`'s `carrier-names-data.ts` (gitignored; oracle's `build` runs this
// after every library is built): every carrier constructor name
// registered anywhere on the fully-declared reference engine (engines.ts's `declaredEngine`) —
// `allCarrierNames` reads `@enumeratio/structures`' registry, filled in by every package that
// calls `declareCarriers` (combinatorics' areas, number-theory, residues, numerals, …).
//
// oracle's `emit`/`structural` modules have to stay synchronous and browser-safe, so they
// cannot hold a live engine — this bakes the answer into a plain generated array, the same
// pattern as `collect-defined-names.ts`. It is what lets `emit()` unwrap a carrier
// CONSTRUCTOR call (`Permutation([2, 1, 3])`) to its contents (`[2, 1, 3]`) for an external
// system whose own encoding is the bare structure — https://github.com/enumeratio/enumeratio/wiki/Speculative-Combinatorics-Layering-and-Plausible
// §4 step 5.
//
//   vp node packages/reference/scripts/collect-carrier-names.ts

import { writeFormatted } from "@enumeratio/entry/node";
import { allCarrierNames, allCarrierParams } from "@enumeratio/structures";
import { declaredEngine } from "./engines.ts";

const ce = declaredEngine();
const names = [...allCarrierNames(ce)].toSorted();
const params = [...allCarrierParams(ce)].toSorted(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));

await writeFormatted(
  new URL("../../oracle/src/carrier-names-data.ts", import.meta.url),
  `// GENERATED by packages/reference/scripts/collect-carrier-names.ts — do not edit by hand.
//
// Every carrier constructor name registered on the fully-declared engine (reference/scripts/
// engines.ts's declaredEngine), via @enumeratio/structures' \`allCarrierNames\`. emit.ts and
// structural.ts use this to unwrap a carrier constructor call to its contents for an external
// system, and to compare our own carrier-typed expected values against another system's raw
// answer. Rebuild with:
//
//   vp node packages/reference/scripts/collect-carrier-names.ts

export const CARRIER_NAMES: ReadonlySet<string> = new Set(${JSON.stringify(names, null, 2)});

// How many of a packed multi-arg operand's LEADING slots are params, not the element(s) --
// \`@enumeratio/structures\`' \`allCarrierParams\`, from each carrier's own declared
// \`carrierParams\` (TQ-5: replaces the old "every slot is a carrier call" heuristic). A carrier
// absent here packs no leading params (0): its operand's slots, when there is more than one,
// are all elements (e.g. StandardTableauPair's carrierElements).
export const CARRIER_PARAMS: ReadonlyMap<string, number> = new Map(${JSON.stringify(params, null, 2)});
`,
);

console.log(`${names.length} carrier constructor names registered on the reference engine`);
