// Rebuild `src/crosswalk/catalog-references-data.ts` from every head's `catalog:` field
// (design/speculative/symbol-metadata.md; the one-time codemod that wrote it, and the dump it
// read, are both gone now that every consumer reads this instead). The crosswalk consumer needs these
// as a plain, synchronous, browser-safe lookup by the catalog's own subject name -- it runs in
// the site build and in the browser -- so this is the "generated *-data.ts per consumer"
// option design/speculative/symbol-metadata.md prefers over reading YAML at runtime.
//
//   vp node packages/reference/scripts/collect-catalog-references.ts

import { writeFormatted } from "@enumeratio/entry/node";
import { referenceData } from "../src/node.ts";

const { entries } = referenceData();

interface CatalogCrosswalkRow {
  readonly subject: string;
  readonly on?: string;
  readonly system: string;
  readonly identity: string;
  readonly url?: string;
  readonly note?: string;
  readonly relation?: "partial" | "aggregate" | "conceptual";
}

const rows: CatalogCrosswalkRow[] = [];
for (const entry of entries) {
  if (!entry.catalog?.length) continue;
  // The catalog's own name for this head -- `names.catalog` when it differs (the four
  // existing aliases), else the head's own name.
  const subject = entry.names?.catalog ?? entry.name;
  for (const reference of entry.catalog) {
    rows.push({
      subject,
      ...(reference.on ? { on: reference.on } : {}),
      system: reference.system,
      identity: reference.identity,
      ...(reference.url ? { url: reference.url } : {}),
      ...(reference.note ? { note: reference.note } : {}),
      ...(reference.relation ? { relation: reference.relation } : {}),
    });
  }
}

// By code unit, so a regeneration diffs clean regardless of locale, keyed the same way the
// old dump was scanned: subject, then system, then identity.
const cmp = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0);
rows.sort(
  (a, b) =>
    cmp(a.subject, b.subject) || cmp(a.on ?? "", b.on ?? "") || cmp(a.system, b.system) || cmp(a.identity, b.identity),
);

await writeFormatted(
  new URL("../src/crosswalk/catalog-references-data.ts", import.meta.url),
  `// GENERATED by scripts/collect-catalog-references.ts — do not edit by hand.
//
// The catalog's own crosswalk, rebuilt from every head's \`catalog:\` field
// (design/speculative/symbol-metadata.md). Regenerate with:
//
//   vp node packages/reference/scripts/collect-catalog-references.ts

/** One pointer the enumeratio database's own crosswalk recorded, rekeyed to our names. */
export interface CatalogCrosswalkRow {
  /** Our spelling of the subject -- a collection, statistic, map or carrier name, exactly as
   * the catalog knew it (\`names.catalog\` when a head's own name differs). */
  readonly subject: string;
  /** The carrier a statistic or map row is on. */
  readonly on?: string;
  readonly system: string;
  readonly identity: string;
  readonly url?: string;
  readonly note?: string;
  readonly relation?: "partial" | "aggregate" | "conceptual";
}

export const CATALOG_REFERENCES: readonly CatalogCrosswalkRow[] = ${JSON.stringify(rows, null, 2)};
`,
);

console.log(`${rows.length} catalog crosswalk rows`);
