// Rebuild `@enumeratio/oracle`'s `mappings-data.ts` from every head's `origin: mapped`
// `bindings:` rows (symbol-metadata step 5, https://github.com/enumeratio/enumeratio/wiki/Speculative-Symbol-Metadata). The oracle
// emitters need this as plain, synchronous data -- `emit.ts` runs in the site build and in the
// browser, so it cannot parse YAML at runtime.
//
// Lives in reference's scripts/ (the only place that can cheaply read every package's YAML)
// but writes into the ORACLE package's src/ -- a relative file write, not a new runtime
// dependency from oracle onto reference (reference already depends on oracle, not the other
// way around).
//
//   vp node packages/reference/scripts/collect-mappings.ts

import { writeFormatted } from "@enumeratio/entry/node";
// From the source: oracle's build runs this before oracle itself is built.
import { mappingsFromBindings } from "../../oracle/src/mappings.ts";
import { referenceData } from "../src/node.ts";

const { entries } = referenceData();

const rows = mappingsFromBindings(entries);

await writeFormatted(
  new URL("../../oracle/src/mappings-data.ts", import.meta.url),
  `// GENERATED by packages/reference/scripts/collect-mappings.ts — do not edit by hand.
//
// Head → external-system source, rebuilt from every head's \`origin: mapped\` \`bindings:\` rows
// (https://github.com/enumeratio/enumeratio/wiki/Speculative-Symbol-Metadata step 5). Regenerate with:
//
//   vp node packages/reference/scripts/collect-mappings.ts

import type { Mapping } from "./mappings.ts";

export const MAPPINGS_DATA: readonly Mapping[] = ${JSON.stringify(rows, null, 2)};
`,
);

console.log(`${rows.length} mapping rows collected across ${new Set(rows.map((r) => r.head)).size} heads`);
