// Ask a Wolfram kernel which `System`` names are vocabulary rather than functions or values:
// the attributes `SetAttributes` takes, the option names System functions accept, and the
// format symbols (`TeXForm`). Rewrites `wolfram/src/vocabulary.ts`.
//
// Committed for the same reason as `system-names.ts`: the oracle's emitter needs to tell a
// free variable that happens to share a name with Wolfram (`E`, `K`) from a name that means
// Wolfram's own thing in an argument position (`Orderless`, `FontWeight`), in CI, with no kernel.
//
// Rerun when the baseline kernel version moves:
//
//   node packages/reference/scripts/collect-wolfram-vocabulary.ts

import { writeFileSync } from "node:fs";
import { runKernel } from "@enumeratio/utils/bounded";

const code = [
  'names = Names["System`*"];',
  'names = Select[names, StringMatchQ[#, RegularExpression["[A-Za-z][A-Za-z0-9]*"]] &];',
  'Print["ATTRIBUTES=", StringRiffle[SymbolName /@ Union @@ (Attributes /@ names), ","]];',
  // What `Options` lists, and what the documentation lists for the symbols (a box has none in `Options`).
  "kernelOptions = Union @@ (Cases[Quiet[Options[Symbol[#]]], (Rule | RuleDelayed)[k_Symbol, _] :> SymbolName[k]] & /@ names);",
  'docOptions = Union[Flatten[Replace[Replace[EntityValue[Entity["WolframLanguageSymbol", #] & /@ names, "OptionNames"], _Missing -> {}, {1}], {Entity["WolframLanguageSymbol", n_] :> ToString[n], s_Symbol :> SymbolName[s]}, {2}]]];',
  'Print["OPTIONS=", StringRiffle[Union[kernelOptions, docOptions], ","]];',
  'Print["FORMS=", StringRiffle[Select[names, StringEndsQ[#, "Form"] &], ","]];',
  'Print["$Version=", $Version]',
].join(" ");
const out = await runKernel("wolframscript", ["-code", code], { timeoutMs: 900_000 });

const field = (key: string): string[] => {
  const line = out.split("\n").find((l) => l.startsWith(`${key}=`));
  if (line === undefined) throw new Error(`no ${key} line — did the kernel run?`);
  return line
    .slice(key.length + 1)
    .split(",")
    .map((name) => name.trim())
    .filter((name) => /^[A-Za-z][A-Za-z0-9]*$/.test(name))
    .toSorted();
};
const version = out
  .split("\n")
  .find((l) => l.startsWith("$Version="))
  ?.slice("$Version=".length);

const attributes = field("ATTRIBUTES");
const options = field("OPTIONS");
const forms = field("FORMS");
if (attributes.length < 10 || options.length < 500 || forms.length < 20)
  throw new Error(
    `implausibly small: ${attributes.length} attributes, ${options.length} options, ${forms.length} forms`,
  );

const source = `// GENERATED by reference/scripts/collect-wolfram-vocabulary.ts — do not edit by hand.
//
// The \`System\`\` names that are vocabulary, from ${version ?? "an unrecorded kernel"}: what \`SetAttributes\`
// takes, what System functions take as option keys, and the format symbols. A name here, when ours
// does not define it, is Wolfram's own in an argument position, never a free variable.

/** ${attributes.length} attribute names (\`Orderless\`). */
export const ATTRIBUTE_NAMES: readonly string[] = ${JSON.stringify(attributes)};

/** ${options.length} option keys of System functions (\`FontWeight\`). */
export const OPTION_NAMES: readonly string[] = ${JSON.stringify(options)};

/** ${forms.length} symbols named \`…Form\` (\`TeXForm\`). */
export const FORM_NAMES: readonly string[] = ${JSON.stringify(forms)};
`;

writeFileSync(new URL("../../wolfram/src/vocabulary.ts", import.meta.url), source);
process.stdout.write(
  `vocabulary.ts — ${attributes.length} attributes, ${options.length} options, ${forms.length} forms from ${version ?? "?"}\n`,
);
