// Rebuild `@enumeratio/catalog`'s `catalog-records-data.ts` from every head's catalog-role
// fields -- `grades`/`carrier`/`unbounded` (a collection), `catalogCarrier` (a bare carrier),
// `statOn`/`mapOn` (a statistic or map's overload set). `declareCatalog` needs these as plain,
// synchronous data; it runs wherever compute-engine does, so it cannot parse YAML at runtime.
// The one-time codemod that wrote these fields, and the database dump it read them from, are
// both gone now that every consumer reads this instead.
//
// Lives in reference's scripts/ (the only place that can cheaply read every package's YAML)
// but writes into the CATALOG package's src/ -- a relative file write, not a new runtime
// dependency from catalog onto reference (reference already depends on catalog, not the other
// way around; same reasoning as collect-mappings.ts / collect-wolfram-names.ts).
//
//   vp node packages/reference/scripts/collect-catalog-records.ts

import { writeFormatted } from "@enumeratio/entry/node";
import { referenceData } from "../src/node.ts";

const { entries } = referenceData();

interface CatalogCollectionRow {
  readonly name: string;
  readonly carrier?: string;
  readonly grades: { readonly name: string; readonly role: "axis" | "param" }[];
  readonly description?: string;
  readonly unbounded?: boolean;
}
interface CatalogCarrierRow {
  readonly name: string;
}
interface CatalogOverloadRow {
  readonly name: string;
  readonly on: readonly string[];
  readonly description?: string;
}

const carriers: CatalogCarrierRow[] = [];
const collections: CatalogCollectionRow[] = [];
const stats: CatalogOverloadRow[] = [];
const maps: CatalogOverloadRow[] = [];

for (const entry of entries) {
  if (entry.catalogCarrier) carriers.push({ name: entry.name });
  if (entry.grades !== undefined) {
    collections.push({
      name: entry.name,
      ...(entry.carrier ? { carrier: entry.carrier } : {}),
      grades: [...entry.grades],
      description: entry.summary,
      ...(entry.unbounded ? { unbounded: true } : {}),
    });
  }
  if (entry.statOn !== undefined) stats.push({ name: entry.name, on: [...entry.statOn], description: entry.summary });
  if (entry.mapOn !== undefined) maps.push({ name: entry.name, on: [...entry.mapOn], description: entry.summary });
}

const cmp = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0);
carriers.sort((a, b) => cmp(a.name, b.name));
collections.sort((a, b) => cmp(a.name, b.name));
stats.sort((a, b) => cmp(a.name, b.name));
maps.sort((a, b) => cmp(a.name, b.name));

await writeFormatted(
  new URL("../../catalog/src/catalog-records-data.ts", import.meta.url),
  `// GENERATED by packages/reference/scripts/collect-catalog-records.ts — do not edit by hand.
//
// What \`declareCatalog\` needs, rebuilt from every head's catalog-role fields
// (design/speculative/symbol-metadata.md). Regenerate with:
//
//   vp node packages/reference/scripts/collect-catalog-records.ts

import type { CatalogCarrier, CatalogCollection, CatalogOverload } from "./types.ts";

export const CARRIERS: readonly CatalogCarrier[] = ${JSON.stringify(carriers, null, 2)};

export const COLLECTIONS: readonly CatalogCollection[] = ${JSON.stringify(collections, null, 2)};

export const STATS: readonly CatalogOverload[] = ${JSON.stringify(stats, null, 2)};

export const MAPS: readonly CatalogOverload[] = ${JSON.stringify(maps, null, 2)};
`,
);

console.log(
  `${carriers.length} carriers, ${collections.length} collections, ${stats.length} stats, ${maps.length} maps`,
);
