// Ask a Wolfram kernel for its named characters (`\[Alpha]`, `\[Limit]`), and rewrite
// `wolfram/src/named-characters.ts`.
//
// A kernel prints a character outside ASCII as `\[Name]` where it has a name, so a string it
// answers can only be read back with the table. Committed (like `system-names.ts`) so that
// reading an answer needs no kernel.
//
// Rerun when the baseline kernel version moves:
//
//   node packages/reference/scripts/collect-named-characters.ts

import { writeFileSync } from "node:fs";
import { runKernel } from "@enumeratio/utils/bounded";

const code = [
  'Do[With[{f = StringTake[ToString[FromCharacterCode[c], InputForm, CharacterEncoding -> "ASCII"], {2, -2}]},',
  'If[StringStartsQ[f, "\\\\["], Print[c, " ", StringTake[f, {3, -2}]]]], {c, 128, 65535}];',
  'Print["$Version=", $Version]',
].join(" ");
const out = await runKernel("wolframscript", ["-code", code], { timeoutMs: 900_000 });

const names: [string, number][] = [];
let version: string | undefined;
for (const line of out.split("\n")) {
  const named = /^(\d+) ([A-Za-z][A-Za-z0-9]*)$/.exec(line.trim());
  if (named !== null) names.push([named[2] as string, Number(named[1])]);
  else if (line.startsWith("$Version=")) version = line.slice("$Version=".length).trim();
}
if (names.length < 500) throw new Error(`only ${names.length} named characters — did the kernel run?`);
names.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));

const source = `// GENERATED by reference/scripts/collect-named-characters.ts — do not edit by hand.
//
// Wolfram's named characters, from ${version ?? "an unrecorded kernel"}: the \`\\[Name]\` a kernel prints
// for a character outside ASCII, as its code point. ${names.length} names.

export const NAMED_CHARACTERS: Readonly<Record<string, number>> = ${JSON.stringify(Object.fromEntries(names), null, 1)};
`;

writeFileSync(new URL("../../wolfram/src/named-characters.ts", import.meta.url), source);
process.stdout.write(`named-characters.ts — ${names.length} names from ${version ?? "?"}\n`);
