// Rebuild `@enumeratio/oracle`'s `defined-names-data.ts`: every bare MathJSON symbol that
// appears anywhere in a reference example, for which the fully-declared reference engine
// (engines.ts's `declaredEngine`) counts as defined (`defined-names.ts`'s `isDefinedName` —
// more than a bare `ce.lookupDefinition(name) !== undefined`, see its own doc).
//
// This is what `emit.ts` (oracle) uses to decide whether a bare symbol is a free variable
// (no definition — carry it through symbolically) or a known name it shouldn't guess a value
// for (a domain like `Primes`, a constant, a pattern head passed as a value). oracle has to
// stay synchronous and browser-safe, so it can't hold a live ComputeEngine (every symbol
// package, on every call) — this bakes the answer, for every name this codebase's own data
// actually uses, into a plain generated Set. A name introduced by future reference data that
// isn't in this set yet is exactly what the currency test (defined-names.test.ts) catches.
//
//   vp node packages/reference/scripts/collect-defined-names.ts

import type { MathJSON } from "@enumeratio/oracle";
import { writeFormatted } from "@enumeratio/entry/node";
import { declaredEngine } from "./engines.ts";
import { isDefinedName, symbolsIn } from "./defined-names.ts";
import { referenceData, referenceEntries } from "../src/node.ts";

const data = referenceData();
const names = new Set<string>();
for (const entry of referenceEntries(data)) {
  for (const example of entry.examples) {
    symbolsIn(example.expr as MathJSON, names);
    symbolsIn(example.expected as MathJSON, names);
  }
}

const ce = declaredEngine();
const defined = [...names].filter((name) => isDefinedName(ce, name)).toSorted();

await writeFormatted(
  new URL("../../oracle/src/defined-names-data.ts", import.meta.url),
  `// GENERATED by packages/reference/scripts/collect-defined-names.ts — do not edit by hand.
//
// Every bare symbol used anywhere in a reference example for which the fully-declared engine
// (reference/scripts/engines.ts's declaredEngine) counts as defined — reference/scripts/
// defined-names.ts's isDefinedName. A name NOT in this set (and not this codebase's own
// arithmetic/pattern convention) is a free variable to emit.ts. Regenerate with:
//
//   vp node packages/reference/scripts/collect-defined-names.ts

export const DEFINED_NAMES: ReadonlySet<string> = new Set(${JSON.stringify(defined, null, 2)});
`,
);

console.log(`${defined.length} of ${names.size} symbols seen across the reference data are compute-engine-defined`);
