// Rebuild `@enumeratio/wolfram`'s `wolfram-names-data.ts` from every head's `names.wolfram` /
// `names.wolframIdentity` field (symbol-metadata step 4, design/speculative/symbol-metadata.md).
// `to-wolfram.ts` needs this as plain, synchronous, browser-safe data -- it runs in the site
// build and in the browser, so it cannot parse YAML at runtime.
//
// Lives in reference's scripts/ (the only place that can cheaply read every package's YAML)
// but writes into the WOLFRAM package's src/, which is where the consumer is -- a relative
// file write, not a new runtime dependency from wolfram onto reference (reference already
// depends on wolfram, not the other way around).
//
//   vp node packages/reference/scripts/collect-wolfram-names.ts

import { writeFormatted } from "@enumeratio/entry/node";
import { referenceData } from "../src/node.ts";

const { entries } = referenceData();

const WOLFRAM_NAMES: Record<string, string> = {};
for (const entry of entries) {
  const names = entry.names;
  if (!names) continue;
  if (names.wolfram !== undefined) WOLFRAM_NAMES[entry.name] = names.wolfram;
  else if (names.wolframIdentity) WOLFRAM_NAMES[entry.name] = entry.name;
}

const sorted = Object.fromEntries(Object.entries(WOLFRAM_NAMES).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)));

await writeFormatted(
  new URL("../../wolfram/src/wolfram-names-data.ts", import.meta.url),
  `// GENERATED by packages/reference/scripts/collect-wolfram-names.ts — do not edit by hand.
//
// compute-engine head → Wolfram spelling, rebuilt from every head's \`names.wolfram\` /
// \`names.wolframIdentity\` field (design/speculative/symbol-metadata.md step 4). Regenerate with:
//
//   vp node packages/reference/scripts/collect-wolfram-names.ts

export const WOLFRAM_NAMES: Readonly<Record<string, string>> = ${JSON.stringify(sorted, null, 2)};
`,
);

console.log(`${Object.keys(sorted).length} wolfram names collected`);
