// Rebuild each symbol package's `summaries-data.ts` from its heads' record `summary` field
// (symbol-metadata step 6, design/speculative/symbol-metadata.md). `ce.declare`'s
// `description` needs a single, synchronous source; the symbol packages can't parse YAML at
// runtime and can't depend on `@enumeratio/reference` (that would be a cycle back onto
// themselves through the packages reference already reads), so each package gets its own
// tiny name -> summary map instead.
//
// Lives in reference's scripts/ (the only place that can cheaply read every package's YAML)
// but writes into each SYMBOL package's src/ -- a relative file write, not a new runtime
// dependency, same reasoning as collect-mappings.ts / collect-catalog-records.ts.
//
// Unlike bindings/grades/names.wolfram, "declared with a description" isn't a flag the
// record schema tracks -- there's no record-side property to filter a package's entries by.
// So the head list below is this script's own manifest, not derived from the records: adding
// a `ce.declare(..., { description: … })` call means adding its head here too, then
// rerunning the script. Keeping the list here (rather than scanning `declare()` calls in
// each package's source for a `description:` literal) also survives the day every call reads
// this very map instead of passing one by hand.
//
//   vp node packages/reference/scripts/collect-summaries.ts

import { writeFormatted } from "@enumeratio/entry/node";
import { packageEntries, referenceData } from "../src/node.ts";

interface PackageSummaries {
  readonly heads: readonly string[];
  readonly outPath: string;
}

const PACKAGES: Record<string, PackageSummaries> = {
  collections: {
    heads: [
      "DifferenceDelta",
      "DiscreteRatio",
      "ExponentialGeneratingFunction",
      "FindSequenceFunction",
      "GeneratingFunction",
    ],
    outPath: "../../symbols/combinatorics/collections/src/summaries-data.ts",
  },
  residues: {
    heads: ["IntegerMod", "IntegerModRing", "MultiplicativeOrder", "PowerMod", "PowerModList", "PrimitiveRootList"],
    outPath: "../../symbols/arithmetic/residues/src/summaries-data.ts",
  },
  "number-theory": {
    heads: [
      "DivisorSum",
      "EulerE",
      "FrobeniusNumber",
      "FrobeniusSolve",
      "HermiteDecomposition",
      "IntegerExponent",
      "IsCoprime",
      "IsPrimePower",
      "LiouvilleLambda",
      "MangoldtLambda",
      "MersennePrimeExponent",
      "PartitionsQ",
      "PerfectNumber",
      "PowersRepresentations",
      "Quotient",
      "RamanujanTau",
      "RationalReconstruction",
      "SquaresR",
    ],
    outPath: "../../symbols/arithmetic/number-theory/src/summaries-data.ts",
  },
  adeles: {
    heads: ["Adele", "Idele", "ProfiniteDecomposition", "ProfiniteNumber", "ProfinitePlot"],
    outPath: "../../symbols/arithmetic/adeles/src/summaries-data.ts",
  },
  aestimatio: {
    heads: ["MemoryConstrained", "TimeConstrained", "VerificationTest"],
    outPath: "../../symbols/evaluation/aestimatio/src/summaries-data.ts",
  },
};

const data = referenceData();

const cmp = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0);

for (const [pkg, { heads, outPath }] of Object.entries(PACKAGES)) {
  const byName = new Map(packageEntries(pkg, data).map((e) => [e.name, e]));
  const summaries: Record<string, string> = {};
  for (const head of [...heads].sort(cmp)) {
    const entry = byName.get(head);
    if (entry === undefined) throw new Error(`collect-summaries: ${pkg} has no record for ${head}`);
    summaries[head] = entry.summary;
  }

  await writeFormatted(
    new URL(outPath, import.meta.url),
    `// GENERATED by packages/reference/scripts/collect-summaries.ts — do not edit by hand.
//
// What this package's \`ce.declare\` calls read for \`description\` (symbol-metadata step 6,
// design/speculative/symbol-metadata.md): each head's record \`summary\`, one source instead
// of two. Regenerate with:
//
//   vp node packages/reference/scripts/collect-summaries.ts

export const SUMMARIES: Readonly<Record<string, string>> = ${JSON.stringify(summaries, null, 2)};
`,
  );

  console.log(`${pkg}: ${Object.keys(summaries).length} summaries -> ${outPath}`);
}
