// Fetch the DLMF's index of notations, and rewrite `src/dlmf-data.ts`.
//
// The NIST Digital Library of Mathematical Functions has no machine index, but its
// Notations pages (dlmf.nist.gov/not/A … Z) list every notation in the handbook with the
// name of the function and the equation or section that defines it. That is the whole
// table -- seven hundred rows -- so all of it is kept, and the crosswalk matches names
// against it (`crosswalk/dlmf.ts`).
//
//   vp node packages/reference/scripts/fetch-dlmf.ts

import { writeFileSync } from "node:fs";
import type { DlmfNotation } from "../src/dlmf-data.ts";

const ROOT = "https://dlmf.nist.gov/";
const LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");

const unescape = (text: string): string =>
  text
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#(\d+);/g, (_m, code: string) => String.fromCodePoint(Number(code)));
// MathML leaves invisible operators (function application, invisible times) in the text.
const strip = (markup: string): string =>
  unescape(markup.replace(/<[^>]+>/g, ""))
    .replace(/[\u2061-\u2064]/g, "")
    .replace(/\s+/g, " ")
    .trim();

/** Each `<dt>` is one notation: its LaTeX `alttext`; the `<dd>` names it and links its home. */
function parse(page: string): DlmfNotation[] {
  const out: DlmfNotation[] = [];
  const entry =
    /<dt id="[^"]+" class="ltx_glossaryentry[^"]*">([\s\S]*?)<\/dt>\s*<dd>([\s\S]*?)<\/dd>/g;
  for (const [, dt, dd] of page.matchAll(entry)) {
    const notation = unescape(/alttext="([^"]*)"/.exec(dt!)?.[1] ?? "");
    const description = strip(dd!);
    const ref = /href="\.\.\/\.\/([^"]+)"/.exec(dd!)?.[1];
    // Bibliography-only rows ("notation used by …") point at a citation, not a definition.
    if (!ref || ref.startsWith("bib/")) continue;
    const name = description.split(";")[0]!.trim();
    if (!name) continue;
    out.push({ name, notation, ref });
  }
  return out;
}

const rows: DlmfNotation[] = [];
for (const letter of LETTERS) {
  const response = await fetch(`${ROOT}not/${letter}`);
  if (!response.ok) throw new Error(`${response.status} for not/${letter}`);
  rows.push(...parse(await response.text()));
}
if (rows.length < 500) throw new Error(`only ${rows.length} notations — page shape changed?`);

writeFileSync(
  new URL("../src/dlmf-data.ts", import.meta.url),
  `// GENERATED by scripts/fetch-dlmf.ts — do not edit by hand.
//
// Every notation in the DLMF's index (dlmf.nist.gov/not/), with the function it names and
// where the handbook defines it. Regenerate with:
//
//   vp node packages/reference/scripts/fetch-dlmf.ts

/** One notation: the handbook's name for it, its LaTeX, and the defining location. */
export interface DlmfNotation {
  readonly name: string;
  /** The notation as the DLMF writes it, with \\NVar{…} marking the variables. */
  readonly notation: string;
  /** Section and anchor, as the site addresses it: \`5.2#E1\`, \`24.2#i\`. */
  readonly ref: string;
}

export const dlmf: readonly DlmfNotation[] = ${JSON.stringify(rows, null, 2)};
`,
);
process.stdout.write(`${rows.length} DLMF notations\n`);
