// Fetch what Wikidata knows about the items the crosswalk touches, and rewrite
// `src/wikidata-data.ts`.
//
// Wikidata is itself a crosswalk: an item carries its English Wikipedia title and external
// identifiers for MathWorld (P2812), the OEIS (P829), nLab (P4215), the Encyclopedia of
// Mathematics (P7554), Britannica (P1417) and the DLMF (P11497). Starting from the Q-ids compute-engine puts on
// its definitions and the Wikipedia titles our curated and catalog rows name, one pass
// resolves the rest -- and the same item reached from two directions is one item.
//
//   vp node packages/reference/scripts/fetch-wikidata.ts

import { writeFileSync } from "node:fs";
import { REFERENCES } from "@enumeratio/catalog/src";
import { CURATED, WIKIDATA_FIXES } from "../src/crosswalk/curated.ts";
import { wikipediaTitle } from "../src/crosswalk/wikidata.ts";
import type { WikidataItem } from "../src/wikidata-data.ts";
import { engineSymbols } from "../src/engine-symbols-data.ts";
import { referenceEntries } from "../src/node.ts";

const entries = referenceEntries();

const API = "https://www.wikidata.org/w/api.php";
const headers = { "User-Agent": "notatio-crosswalk/0.1 (https://github.com/enumeratio)" };

/** The external-id properties we read, and the key each lands on. */
const PROPERTIES: Readonly<Record<string, keyof Omit<WikidataItem, "id" | "title">>> = {
  P2812: "mathworld",
  P829: "oeis",
  P4215: "nlab",
  P7554: "encyclopediaofmath",
  P1417: "britannica",
  P11497: "dlmf",
};

interface Entity {
  readonly id: string;
  readonly missing?: string;
  readonly sitelinks?: { readonly enwiki?: { readonly title: string } };
  readonly claims?: Readonly<
    Record<string, readonly { readonly mainsnak: { readonly datavalue?: { readonly value: unknown } } }[]>
  >;
}

const toItem = (entity: Entity): WikidataItem => {
  const item: { -readonly [K in keyof WikidataItem]: WikidataItem[K] } = { id: entity.id };
  const title = entity.sitelinks?.enwiki?.title;
  if (title) item.title = title;
  for (const [property, key] of Object.entries(PROPERTIES)) {
    const value = entity.claims?.[property]?.[0]?.mainsnak.datavalue?.value;
    if (typeof value === "string") item[key] = value;
  }
  return item;
};

async function fetchEntities(query: string): Promise<Entity[]> {
  const url = `${API}?action=wbgetentities&${query}&props=sitelinks|claims&sitefilter=enwiki&format=json`;
  const response = await fetch(url, { headers });
  if (!response.ok) throw new Error(`${response.status} for ${url}`);
  const body = (await response.json()) as { entities?: Record<string, Entity> };
  return Object.values(body.entities ?? {}).filter((entity) => !("missing" in entity));
}

const chunks = <T>(list: readonly T[], size: number): T[][] => {
  const out: T[][] = [];
  for (let i = 0; i < list.length; i += size) out.push(list.slice(i, i + size));
  return out;
};

// Where to start: every Q-id the engine declares, every Wikipedia title we name.
const ids = [
  ...new Set(
    engineSymbols.flatMap((s) => {
      const id = WIKIDATA_FIXES[s.name] ?? s.wikidata;
      return id ? [id] : [];
    }),
  ),
].sort();
const titles = [
  ...new Set(
    [
      ...Object.values(CURATED).flat(),
      ...entries.flatMap((e) => [...(e.references ?? []), ...(e.signatures ?? []).flatMap((s) => s.references ?? [])]),
      ...REFERENCES.map((r) => ({ system: r.system, identity: r.identity })),
    ]
      .filter((r) => r.system === "wikipedia")
      .map((r) => wikipediaTitle(r.identity)),
  ),
].sort();

const items = new Map<string, WikidataItem>();
for (const chunk of chunks(ids, 50)) {
  for (const entity of await fetchEntities(`ids=${chunk.join("|")}`)) {
    items.set(entity.id, toItem(entity));
  }
}
for (const chunk of chunks(titles, 50)) {
  const query = `sites=enwiki&titles=${chunk.map(encodeURIComponent).join("|")}`;
  for (const entity of await fetchEntities(query)) items.set(entity.id, toItem(entity));
}
const sorted = [...items.values()].sort((a, b) => Number(a.id.slice(1)) - Number(b.id.slice(1)));

writeFileSync(
  new URL("../src/wikidata-data.ts", import.meta.url),
  `// GENERATED by scripts/fetch-wikidata.ts — do not edit by hand.
//
// The Wikidata items the crosswalk reaches -- from the engine's Q-ids and from every
// Wikipedia title we name -- with their English Wikipedia title and external identifiers.
// Regenerate with:
//
//   vp node packages/reference/scripts/fetch-wikidata.ts

/** One item: its Q-id, English Wikipedia title, and the identifiers it carries. */
export interface WikidataItem {
  readonly id: string;
  readonly title?: string;
  readonly mathworld?: string;
  readonly oeis?: string;
  readonly nlab?: string;
  readonly encyclopediaofmath?: string;
  readonly britannica?: string;
  readonly dlmf?: string;
}

export const wikidata: readonly WikidataItem[] = ${JSON.stringify(sorted, null, 2)};
`,
);
const found = (key: keyof WikidataItem): number => sorted.filter((i) => i[key]).length;
process.stdout.write(
  `${sorted.length} items from ${ids.length} ids and ${titles.length} titles — ` +
    `${found("title")} wikipedia, ${found("mathworld")} mathworld, ${found("oeis")} oeis, ` +
    `${found("nlab")} nlab, ${found("encyclopediaofmath")} eom, ${found("britannica")} britannica, ` +
    `${found("dlmf")} dlmf\n`,
);
