// Fetch the Sphinx inventories of the Python systems we reference, and rewrite
// `src/inventory-data.ts` with the entries the crosswalk can use.
//
// SymPy, mpmath, Sage, NumPy and SciPy all publish `objects.inv` -- the intersphinx index of
// every documented object and its page anchor. That is the authoritative answer to "where is
// `hurwitz_zeta` documented", and it turns a name-only reference (`zeta($1, $2)` from the
// oracle table, `Permutations(n)` from the catalog) into a link to the right anchor without
// anyone guessing a URL. Only the names the crosswalk actually mentions are kept, so the
// data file stays small; rerun after adding oracle rows or refreshing the catalog.
//
//   vp node packages/reference/scripts/fetch-inventories.ts

import { writeFileSync } from "node:fs";
import { inflateSync } from "node:zlib";
import { REFERENCES } from "@enumeratio/catalog/src";
import { MAPPINGS } from "@enumeratio/oracle/src";
import { bareName, documents, INVENTORIES, type InventorySystem } from "../src/crosswalk/inventory.ts";
import { CURATED } from "../src/crosswalk/curated-data.ts";
import { referenceEntries } from "../src/node.ts";

const entries = referenceEntries();

interface Entry {
  readonly system: InventorySystem;
  readonly name: string;
  readonly role: string;
  readonly url: string;
}

/** Parse a v2 inventory: four header lines, then zlib-compressed `name role prio location disp`. */
function parse(system: InventorySystem, base: string, bytes: Buffer): Entry[] {
  let offset = 0;
  for (let line = 0; line < 4; line++) offset = bytes.indexOf(0x0a, offset) + 1;
  if (!bytes.subarray(0, offset).includes("version 2")) throw new Error(`${system}: not a v2 inventory`);
  const text = inflateSync(bytes.subarray(offset)).toString("utf8");
  const out: Entry[] = [];
  for (const row of text.split("\n")) {
    const match = /^(\S+)\s+(\S+)\s+(-?\d+)\s+(\S+)\s+(.*)$/.exec(row);
    if (!match) continue;
    const [, name, role, , location] = match;
    if (!role!.startsWith("py:")) continue;
    // `$` at the end of a location stands for the object's own name as the anchor.
    const path = location!.endsWith("$") ? `${location!.slice(0, -1)}${name}` : location!;
    out.push({ system, name: name!, role: role!, url: `${base}${path}` });
  }
  return out;
}

// Every name the crosswalk mentions in an inventoried system, dotted or bare.
const wanted = new Map<InventorySystem, Set<string>>();
const want = (system: string, identity: string): void => {
  if (!(system in INVENTORIES)) return;
  const set = wanted.get(system as InventorySystem) ?? new Set<string>();
  set.add(bareName(identity));
  set.add(identity.replace(/\(.*$/, "").replace(/\s.*$/, ""));
  wanted.set(system as InventorySystem, set);
};
for (const mapping of MAPPINGS) {
  for (const [system, call] of Object.entries(mapping.emit)) if (call) want(system, call);
}
for (const row of REFERENCES) want(row.system, row.identity);
const written = [
  ...Object.values(CURATED).flat(),
  ...entries.flatMap((e) => [...(e.references ?? []), ...(e.signatures ?? []).flatMap((s) => s.references ?? [])]),
];
for (const reference of written) want(reference.system, reference.identity);

const kept: Entry[] = [];
for (const [system, { inventories }] of Object.entries(INVENTORIES) as [
  InventorySystem,
  (typeof INVENTORIES)[InventorySystem],
][]) {
  const names = wanted.get(system) ?? new Set<string>();
  let total = 0;
  for (const base of inventories) {
    const response = await fetch(`${base}objects.inv`);
    if (!response.ok) throw new Error(`${response.status} for ${base}objects.inv`);
    const all = parse(system, base, Buffer.from(await response.arrayBuffer()));
    total += all.length;
    for (const entry of all) {
      if (names.has(entry.name) || [...names].some((bare) => documents(entry.name, bare))) {
        kept.push(entry);
      }
    }
  }
  process.stdout.write(`${system}: ${total} objects, ${kept.filter((e) => e.system === system).length} kept\n`);
}
kept.sort((a, b) => a.system.localeCompare(b.system) || a.name.localeCompare(b.name));

writeFileSync(
  new URL("../src/inventory-data.ts", import.meta.url),
  `// GENERATED by scripts/fetch-inventories.ts — do not edit by hand.
//
// Where the Python systems document the objects the crosswalk names, from each system's
// Sphinx inventory (objects.inv). Only names the crosswalk mentions are kept. Regenerate with:
//
//   vp node packages/reference/scripts/fetch-inventories.ts

import type { InventorySystem } from "./crosswalk/inventory.ts";


/** One documented object: its dotted name, Sphinx role and page anchor. */
export interface InventoryEntry {
  readonly system: InventorySystem;
  readonly name: string;
  readonly role: string;
  readonly url: string;
}

export const inventory: readonly InventoryEntry[] = ${JSON.stringify(kept, null, 2)};
`,
);
