// Fetch the list of symbols Fungrim has a page for, and rewrite `src/fungrim-symbols-data.ts`.
//
// The one online step in the crosswalk. Fungrim's symbol names are the key to its per-symbol
// pages (`fungrim.org/symbol/RiemannZeta/`); the compiled identities the engine ships name
// heads OUR way, so the correspondence has to come from Fungrim itself. A head whose name is
// in this list links straight through; the ones Fungrim spells differently are on the head's
// own record (`names.fungrim` in `<Head>.yaml`, rebuilt into `crosswalk/curated-data.ts`'s
// FUNGRIM_NAMES).
//
// Fungrim declares every builtin in pygrim's `expr.py`, but only publishes a page for a
// symbol some entry uses -- so each candidate is checked against the site.
//
//   vp node packages/reference/scripts/fetch-fungrim-symbols.ts

import { writeFileSync } from "node:fs";

const SOURCE = "https://raw.githubusercontent.com/fredrik-johansson/fungrim/master/pygrim/expr.py";
const page = (name: string): string => `https://fungrim.org/symbol/${name}/`;

const source = await (await fetch(SOURCE)).text();
const candidates = [
  ...new Set(
    [...source.matchAll(/inject_builtin\("""([\s\S]*?)"""\)/g)].flatMap((m) => m[1]!.split(/\s+/).filter(Boolean)),
  ),
].sort();
if (candidates.length < 300) throw new Error(`only ${candidates.length} builtins in ${SOURCE}`);

// A few at a time, with a retry: the host answers HEADs fine but resolver hiccups under
// a burst, and one missed name would silently drop a link.
const exists = async (name: string, attempt = 0): Promise<boolean> => {
  try {
    const response = await fetch(page(name), { method: "HEAD" });
    if (response.status === 404) return false;
    if (response.ok) return true;
    throw new Error(`${response.status} for ${name}`);
  } catch (error) {
    if (attempt >= 3) throw error;
    await new Promise((resolve) => setTimeout(resolve, 500 * (attempt + 1)));
    return exists(name, attempt + 1);
  }
};
const published: string[] = [];
const BATCH = 6;
for (let i = 0; i < candidates.length; i += BATCH) {
  const slice = candidates.slice(i, i + BATCH);
  const ok = await Promise.all(slice.map((name) => exists(name)));
  for (let j = 0; j < slice.length; j++) if (ok[j]) published.push(slice[j]!);
}

writeFileSync(
  new URL("../src/fungrim-symbols-data.ts", import.meta.url),
  `// GENERATED by scripts/fetch-fungrim-symbols.ts — do not edit by hand.
//
// Every Fungrim builtin (from pygrim's expr.py) that has a published symbol page.
// Regenerate with:
//
//   vp node packages/reference/scripts/fetch-fungrim-symbols.ts

/** ${published.length} symbols, of ${candidates.length} builtins. */
export const fungrimSymbols: ReadonlySet<string> = new Set(${JSON.stringify(published, null, 2)});
`,
);
process.stdout.write(`${published.length} of ${candidates.length} fungrim builtins have a page\n`);
