// Which FindStat maps each of ours IS, decided by VALUE: for each of our maps between carriers
// whose text FindStat's we read (`findstat/src/objects.ts`), every row of FindStat's own table
// for a map between the same collections (from the snapshot's crawl, `collect-findstat-data.ts`)
// is read, our map applied to its object, and the result compared with FindStat's image. A map
// whose every row agrees is that map. Rewrites `findstat/src/findstat-maps-data.ts`.
//
//   node packages/reference/scripts/find-findstat-maps.ts [--crawl DIR]

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { parseArgs } from "node:util";
import { CARRIERS, MAPS } from "@enumeratio/combinatorics";
import { readObject } from "../../symbols/combinatorics/combinatorics/findstat/src/objects.ts";
import { declaredEngine } from "./engines.ts";

const { values } = parseArgs({
  options: { crawl: { type: "string", default: join(homedir(), "Playground/@enumeratio/findstat-crawl") } },
});

/** FindStat's collections whose objects we read. */
const COLLECTION: Readonly<Record<string, string>> = {
  Permutations: "Permutation",
  "Dyck paths": "DyckPath",
  "Integer partitions": "IntegerPartition",
  "Set partitions": "SetPartition",
};
/** Rows tried per map, past the smallest objects (which are conventions more than checks). */
const ROWS = 40;
/** Fewer agreeing rows than this is no evidence. */
const MIN_ROWS = 5;

const carrierName = (type: string): string => CARRIERS.find((c) => c.type === type)?.name ?? type;
const folder = join(values.crawl!, "MapsDatabase");
const theirs = readdirSync(folder)
  .filter((f) => f.endsWith(".json"))
  .map((f) => ({ id: f.replace(/\.json$/, ""), ...JSON.parse(readFileSync(join(folder, f), "utf8")) }))
  .filter((m) => COLLECTION[m.MapDomain] && COLLECTION[m.MapCodomain]);

const ce = declaredEngine();
const matches: { name: string; from: string; to: string; findstat: string[]; values: number }[] = [];
for (const ours of MAPS) {
  const from = carrierName(ours.from);
  const to = carrierName(ours.to);
  const ids: string[] = [];
  let rows = 0;
  for (const m of theirs) {
    if (COLLECTION[m.MapDomain] !== from || COLLECTION[m.MapCodomain] !== to) continue;
    const table = Object.entries(m.MapData as Record<string, string>)
      .filter(([object]) => object.length >= 3)
      .slice(0, ROWS);
    let agree = 0;
    let tried = 0;
    for (const [object, image] of table) {
      const x = readObject(from, object);
      const y = readObject(to, image);
      if (x === undefined || y === undefined) continue;
      tried++;
      try {
        const ours_ = ce.box(["CombinatorialMap", x, `'${ours.name}'`] as never).evaluate().json;
        if (JSON.stringify(ours_) === JSON.stringify(y)) agree++;
      } catch {
        // A map that throws on an object doesn't agree on it.
      }
    }
    if (tried >= MIN_ROWS && agree === tried) {
      ids.push(m.id);
      rows = Math.max(rows, tried);
    }
  }
  if (ids.length > 0) matches.push({ name: ours.name, from, to, findstat: ids, values: rows });
}

const body = matches
  .map(
    (m) =>
      `  { name: ${JSON.stringify(m.name)}, from: ${JSON.stringify(m.from)}, to: ${JSON.stringify(m.to)}, findstat: ${JSON.stringify(m.findstat)}, values: ${m.values} },`,
  )
  .join("\n");
writeFileSync(
  new URL("../../symbols/combinatorics/combinatorics/findstat/src/findstat-maps-data.ts", import.meta.url),
  `// GENERATED by packages/reference/scripts/find-findstat-maps.ts — do not edit by hand.
//
// Which FindStat maps each of ours is, decided by VALUE: our map applied to each object of
// FindStat's own table, compared with its image. Regenerate with:
//
//   node packages/reference/scripts/find-findstat-maps.ts

/** One map of ours and the FindStat maps that agree with it on every row tried. */
export interface FindStatMapMatch {
  readonly name: string;
  readonly from: string;
  readonly to: string;
  /** More than one means they agree on every row tried. */
  readonly findstat: readonly string[];
  /** How many (object, image) rows the match rests on. */
  readonly values: number;
}

export const findstatMaps: readonly FindStatMapMatch[] = [
${body}
];
`,
);
console.log(`${matches.length} of ${MAPS.length} maps matched`);
for (const m of matches) console.log(`  ${m.name} (${m.from} → ${m.to}) = ${m.findstat.join(", ")} [${m.values}]`);
