// Check every Fungrim identity compute-engine ships, numerically, and rewrite
// `src/fungrim-verified-data.ts`.
//
// The crosswalk points a head at the Fungrim entries whose rules mention it -- 2116 chips,
// none of them checked by anything. A compiled rule is `match -> replace` over guarded
// wildcards, so each one is a claim we can put numbers into and test. This is that run.
//
// It drives a worker process (`check-fungrim-rule.ts`) rather than doing the work here,
// because a single evaluation can hang for minutes with no way back: the worker streams one
// result per line, and when the deadline passes the parent records the rule it died on as
// unevaluable and restarts after it.
//
//   vp node packages/reference/scripts/verify-fungrim.ts [--budget 20000] [--heap 1024]

import { spawn } from "node:child_process";
import { writeFileSync } from "node:fs";
import { ComputeEngine } from "@cortex-js/compute-engine";
import { FUNGRIM_CORE } from "@cortex-js/compute-engine/identities";
import { declareAnalytic } from "@enumeratio/analytic/src";
import type { FungrimVerdict } from "../src/fungrim-verified-data.ts";
import type { FungrimRule, Outcome } from "./fungrim.ts";

const option = (flag: string, fallback: number): number => {
  const i = process.argv.indexOf(flag);
  return i >= 0 ? Number(process.argv[i + 1]) : fallback;
};
/** How long a worker may go without producing a line before we assume it is stuck. */
const BUDGET = option("--budget", 20_000);
/** Worker heap cap in MB: a runaway evaluation dies here instead of starving the machine. */
const HEAP = option("--heap", 1024);

const rules = FUNGRIM_CORE.rules as unknown as readonly FungrimRule[];
const results = new Map<number, Outcome>();

/** Run the worker from `from`, returning the index it stopped before. */
function sweepFrom(from: number): Promise<number> {
  return new Promise((resolve) => {
    const child = spawn(
      process.execPath,
      [`--max-old-space-size=${HEAP}`, new URL("check-fungrim-rule.ts", import.meta.url).pathname, String(from)],
      { stdio: ["ignore", "pipe", "inherit"] },
    );
    let last = from - 1;
    let buffer = "";
    let timer: NodeJS.Timeout;
    const arm = (): void => {
      clearTimeout(timer);
      timer = setTimeout(() => child.kill("SIGKILL"), BUDGET);
    };
    arm();
    child.stdout.setEncoding("utf8");
    child.stdout.on("data", (chunk: string) => {
      buffer += chunk;
      const lines = buffer.split("\n");
      buffer = lines.pop() ?? "";
      for (const line of lines) {
        if (!line) continue;
        const { i, ...outcome } = JSON.parse(line) as { i: number } & Outcome;
        results.set(i, outcome as Outcome);
        last = i;
        arm();
      }
    });
    child.on("close", () => {
      clearTimeout(timer);
      resolve(last + 1);
    });
  });
}

let next = 0;
while (next < rules.length) {
  const stopped = await sweepFrom(next);
  if (stopped >= rules.length) break;
  if (stopped === next) {
    // The worker died before finishing this one: it is the rule that cannot be evaluated.
    results.set(next, { verdict: "inconclusive" });
    process.stderr.write(`too slow to evaluate: ${rules[next]!.id}\n`);
    next += 1;
  } else {
    next = stopped;
  }
}

// Which frontier heads the engine (with our analytic library) declares at all.
const engine = new ComputeEngine();
declareAnalytic(engine);
const declared = new Set(
  [...new Set(rules.flatMap((rule) => rule.heads))].filter((head) => Boolean(engine.lookupDefinition(head))),
);

const tally: Record<string, number> = {};
const verdicts: FungrimVerdict[] = [];
// The identities we could NOT check, by the head that stopped us: the frontier. An
// inconclusive rule is one our engine would not evaluate at a sample; every head it
// mentions gets the count, since any of them may be the reason.
const frontier = new Map<string, number>();
for (const [i, outcome] of [...results].sort((a, b) => a[0] - b[0])) {
  const rule = rules[i]!;
  tally[outcome.verdict] = (tally[outcome.verdict] ?? 0) + 1;
  if (outcome.verdict === "inconclusive") {
    for (const head of rule.heads) frontier.set(head, (frontier.get(head) ?? 0) + 1);
  }
  // Only what a page shows is stored: an entry that was checked, and how it came out.
  if (outcome.verdict === "agree" || outcome.verdict === "disagree") {
    verdicts.push({
      entry: rule.id.replace(/^fungrim:/, ""),
      heads: [...rule.heads].sort(),
      verdict: outcome.verdict,
      ...(outcome.verdict === "agree" ? { samples: outcome.samples } : { detail: outcome.detail }),
    });
  }
}

writeFileSync(
  new URL("../src/fungrim-verified-data.ts", import.meta.url),
  `// GENERATED by scripts/verify-fungrim.ts — do not edit by hand.
//
// Every Fungrim identity compute-engine ships, checked numerically: values put into the
// wildcards its guards allow, both sides evaluated, compared. Only the entries that were
// actually checked are here — an identity our engine cannot evaluate says nothing about
// Fungrim and is left out. Regenerate with:
//
//   vp node packages/reference/scripts/verify-fungrim.ts

/** One checked identity. */
export interface FungrimVerdict {
  /** The Fungrim entry id, as its page is addressed. */
  readonly entry: string;
  /** The heads its rule mentions. */
  readonly heads: readonly string[];
  readonly verdict: "agree" | "disagree";
  /** How many instantiations agreed. */
  readonly samples?: number;
  /** Where they parted, for one that did not. */
  readonly detail?: string;
}

export const fungrimVerified: readonly FungrimVerdict[] = ${JSON.stringify(verdicts, null, 2)};

/**
 * The Fungrim frontier: heads mentioned by identities our engine could not evaluate, ranked
 * by how many identities each one holds up. A head the engine does not declare at all
 * (\`declared: false\`) is the surest culprit and leads; a declared one appears because it
 * shares identities with an undeclared one, or does not evaluate at a complex argument.
 * Making a head evaluable unlocks its count -- that is the work queue, generated not written.
 */
export const fungrimFrontier: readonly {
  readonly head: string;
  readonly identities: number;
  readonly declared: boolean;
}[] = ${JSON.stringify(
    [...frontier]
      .map(([head, identities]) => ({ head, identities, declared: declared.has(head) }))
      .sort(
        (a, b) =>
          Number(a.declared) - Number(b.declared) || b.identities - a.identities || a.head.localeCompare(b.head),
      ),
    null,
    2,
  )};
`,
);
process.stdout.write(
  `${results.size} rules — ${Object.entries(tally)
    .map(([verdict, n]) => `${verdict} ${n}`)
    .join(", ")}\n`,
);
