// GENERATED by packages/reference/scripts/collect-summaries.ts — do not edit by hand.
//
// What this package's `ce.declare` calls read for `description` (symbol-metadata step 6,
// design/speculative/symbol-metadata.md): each head's record `summary`, one source instead
// of two. Regenerate with:
//
//   vp node packages/reference/scripts/collect-summaries.ts

export const SUMMARIES: Readonly<Record<string, string>> = {
  DisplayForm: "Boxes shown as what they draw, rather than as the expression that describes them.",
  ErrorBox: "Boxes marked as an error.",
  FractionBox: "A numerator over a denominator.",
  FrameBox: "A box drawn with a frame around it.",
  GridBox: "A two-dimensional array of boxes: a matrix's body, a piecewise definition's cases.",
  InterpretationBox: "Boxes that display one way and stand for exactly the expression they carry.",
  MakeBoxes: "The boxes of an expression's traditional notation, without evaluating it.",
  OverscriptBox: "A box set above a base: $\\overline{3}$, $\\hat{x}$.",
  RadicalBox: "An $n$th-root sign over a box, the index in its crook.",
  RawBoxes: "Boxes to be drawn in place, inside a larger expression.",
  RowBox: "A row of boxes, juxtaposed left to right: the box a sequence of tokens makes.",
  SqrtBox: "A square-root sign over a box.",
  StyleBox: "A box drawn in a style: `FontColor`, `FontWeight`, `FontSlant`, `FontSize`, `Background`.",
  SubscriptBox: "A base with a subscript: $x_1$.",
  SubsuperscriptBox: "A base with a subscript and a superscript: $\\int_0^1$.",
  SuperscriptBox: "A base with a superscript: $x^2$.",
  TagBox: "Boxes labelled with a tag saying how to read them back as an expression.",
  TextBox: "Literal text inside boxes, set as text rather than read as tokens.",
  ToBoxes: "The boxes an expression's traditional notation is made of, after evaluating it.",
  UnderoverscriptBox: "A base with boxes below and above it: $\\sum_{n=1}^{10}$.",
  UnderscriptBox: "A box set below a base: the limit under $\\lim$.",
};
