// Rebuild `src/naming-data.ts` from every head's `formerly:` field (symbol-metadata step 3,
// design/speculative/symbol-metadata.md). `blessedName` needs this reversed -- old catalog
// name to the head we actually declare -- and needs it as plain data: `naming.ts` runs in the
// browser too, so it cannot parse YAML at runtime the way a Node script can.
//
//   vp node packages/symbols/combinatorics/statistics/scripts/collect-naming.ts
//
// Read-only over reference/: unlike collect-entries.ts, this never calls writeEntries, so it
// cannot delete a hand-written record.

import { readEntries, writeFormatted } from "@enumeratio/entry/node";

const entries = readEntries(new URL("../reference/", import.meta.url));

// One catalog stat has no head of its own to carry `formerly:` -- StandardTableauCount is a
// cardinality answered by Count over a collection, not a definition (see cardinalities.ts) --
// so its rename is carried here by hand instead.
const NO_HEAD: Readonly<Record<string, string>> = { NumberOfStandardTableaux: "StandardTableauCount" };

const renamed: Record<string, string> = { ...NO_HEAD };
for (const entry of entries) {
  for (const oldName of entry.formerly ?? []) renamed[oldName] = entry.name;
}

const sorted = Object.fromEntries(Object.entries(renamed).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)));

await writeFormatted(
  new URL("../src/naming-data.ts", import.meta.url),
  `// GENERATED by scripts/collect-naming.ts — do not edit by hand.
//
// Catalog stat name → the head we actually declare, rebuilt from every head's \`formerly:\`
// field. Regenerate with:
//
//   vp node packages/symbols/combinatorics/statistics/scripts/collect-naming.ts

export const RENAMED_DATA: Readonly<Record<string, string>> = ${JSON.stringify(sorted, null, 2)};
`,
);

console.log(`${Object.keys(sorted).length} renames collected`);
