// Compile every statistic's Epsil definition to JavaScript ahead of time, with compute-engine's
// own compiler, into src/compiled.generated.js. Each entry carries the hash of the Epsil it came
// from: at run time an entry is used only while its hash matches, so an edited definition is
// interpreted until this is rerun. Definitions the compiler can't take yet are left out.
//
//   vp node packages/symbols/combinatorics/statistics/scripts/compile-definitions.ts

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { ComputeEngine } from "@cortex-js/compute-engine";
import { compileTyped, definitionHash } from "@enumeratio/engine/compiled";
import { ALL_STATISTICS } from "../src/all.ts";
import { signatureOf } from "../src/types.ts";
import { CARRIER_TYPES, SHAPES } from "./carriers.ts";

/** Each compilable definition's signature, hash and generated code. */
export function compiledDefinitions(): { signature: string; hash: string; code: string }[] {
  const ce = new ComputeEngine();
  const out: { signature: string; hash: string; code: string }[] = [];
  for (const definition of ALL_STATISTICS) {
    const type = CARRIER_TYPES[definition.on];
    const shape = type === undefined ? undefined : SHAPES[type];
    if (shape === undefined) continue;
    const compiled = compileTyped(ce, definition.expr, { _x: shape });
    if (compiled === undefined) continue;
    out.push({ signature: signatureOf(definition), hash: definitionHash(definition.expr), code: compiled.code });
  }
  return out.toSorted((a, b) => (a.signature < b.signature ? -1 : a.signature > b.signature ? 1 : 0));
}

function render(entries: ReturnType<typeof compiledDefinitions>): string {
  const body = entries
    .map(
      (e) =>
        `  ${JSON.stringify(e.signature)}: {\n    hash: ${JSON.stringify(e.hash)},\n    run: (_SYS, _) => ${e.code},\n  },`,
    )
    .join("\n");
  return `// GENERATED by scripts/compile-definitions.ts from the statistics' Epsil definitions, by
// compute-engine's JavaScript compiler. Do not edit: rerun the script. Each entry is used only
// while \`hash\` matches its definition; see src/compiled.ts.

export const COMPILED = {
${body}
};
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const entries = compiledDefinitions();
  const target = fileURLToPath(new URL("../src/compiled.generated.js", import.meta.url));
  writeFileSync(target, render(entries));
  // Laid out as `vp fmt` lays it out, so a rerun with nothing changed changes nothing.
  execFileSync("vp", ["fmt", target], { stdio: "ignore" });
  console.log(`${entries.length} of ${ALL_STATISTICS.length} definitions compiled`);
}
