// AUTO-GENERATED by gen-pack-entries.mts — do not hand-edit.
// Subpath: @enumeratio/data/packs/trees-graphs (#321, wiki Core-And-Packs §7). Regenerate
// (`pnpm --filter @enumeratio/data gen-pack-entries`) whenever EXTRACTED_PACKS (pack-map.ts) changes.
import { packEntry } from '../pack-entry.ts'

export const { name, requiresPack, files, manifest, fragment } = packEntry('trees-graphs')
