// Every head that gets a tag: the symbols a bare compute-engine binds, our own reference
// entries, and the heads that draw or control. Rewrites `src/heads-data.ts`, which the
// components package reads to register a generic `notatio-<head>` element for each head
// that has no hand-written one (design/vdom.md). Regenerate:
//
//   node --experimental-strip-types packages/notatio/scripts/collect-heads.ts

import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { GRAPHICS_HEADS } from "@enumeratio/formats";
import { engineSymbols, entries } from "@enumeratio/reference";

const names = new Set<string>();
for (const s of engineSymbols) names.add(s.name);
for (const e of entries) names.add(e.name);
for (const h of GRAPHICS_HEADS) names.add(h);
// The leaf tags the structural tree uses (design/vdom.md §1).
for (const atom of ["Integer", "Real", "Rational", "Complex", "String", "Symbol"]) names.add(atom);

// A tag needs a name that survives kebab-casing: letters and digits, starting with a letter.
const heads = [...names].filter((n) => /^[A-Za-z][A-Za-z0-9]*$/.test(n)).sort();

const out = resolve(dirname(fileURLToPath(import.meta.url)), "../src/heads-data.ts");
writeFileSync(
  out,
  `// GENERATED by scripts/collect-heads.ts — do not edit by hand.
//
// Every head that gets a \`notatio-<head>\` tag: the engine's own symbols, our reference
// entries, the heads that draw. Regenerate with:
//
//   node --experimental-strip-types packages/notatio/scripts/collect-heads.ts

export const HEADS: readonly string[] = ${JSON.stringify(heads, null, 2)};
`,
);
console.log(`${heads.length} heads -> ${out}`);
