// Indefinite binary quadratic forms, and their cycles.
//
// A binary quadratic form is ax² + bxy + cy², carried by the triple (a, b, c), with
// discriminant D = b² − 4ac. The modular group acts on forms by substituting
// (x, y) ↦ (px + qy, rx + sy), and the orbits of that action are the CLASSES — the objects
// Gauss's theory is about, and the reason class numbers exist.
//
// When D > 0 and is not a perfect square the form is INDEFINITE: it takes both signs, its
// roots are real quadratic irrationals, and — the fact that makes it belong in this package
// — a class does not contain a single distinguished reduced form but a CYCLE of them. Walk
// the cycle with ρ and you are running the continued-fraction expansion of the root; the
// cycle closes because that expansion is eventually periodic; and the period is the same
// periodic word that names a closed geodesic in psl2z.ts.
//
// So the three things are one thing:
//
//     a class of indefinite forms  =  a cycle of reduced forms
//                                  =  a periodic continued fraction
//                                  =  a closed geodesic on the modular surface.
//
// The stabiliser of a form is generated by its AUTOMORPH, a hyperbolic matrix built from the
// fundamental solution of Pell's equation t² − Du² = 4. That is the hyperbolic element whose
// conjugacy class is the geodesic, which is what ties this file back to the rest.

import { type Matrix, isModular } from "./psl2z.ts";

/** A binary quadratic form ax² + bxy + cy², as its coefficient triple. */
export interface Form {
  readonly a: number;
  readonly b: number;
  readonly c: number;
}

const isInt = (x: number): boolean => Number.isSafeInteger(x);

export const form = (a: number, b: number, c: number): Form | undefined =>
  isInt(a) && isInt(b) && isInt(c) ? { a, b, c } : undefined;

export const discriminant = ({ a, b, c }: Form): number => b * b - 4 * a * c;

/** The integer square root, and whether the argument was a perfect square. */
function integerSqrt(n: number): { root: number; exact: boolean } | undefined {
  if (!isInt(n) || n < 0) return undefined;
  let root = Math.floor(Math.sqrt(n));
  // Math.sqrt is a float; nudge until the integer bracket is right.
  while (root * root > n) root--;
  while ((root + 1) * (root + 1) <= n) root++;
  return { root, exact: root * root === n };
}

/**
 * Indefinite means D > 0 and D is not a perfect square. A square discriminant gives a form
 * that factors over the rationals, with no cycle and no geodesic — a different subject.
 */
export function isIndefinite(f: Form): boolean {
  const d = discriminant(f);
  const root = integerSqrt(d);
  return d > 0 && root !== undefined && !root.exact;
}

/** Evaluate the form at a point. */
export const evaluateForm = ({ a, b, c }: Form, x: number, y: number): number =>
  a * x * x + b * x * y + c * y * y;

/**
 * The action of SL(2,Z): substitute (x, y) ↦ (px + qy, rx + sy). The discriminant is
 * invariant, which is why classes live inside a fixed discriminant.
 */
export function actOn(f: Form, m: Matrix): Form | undefined {
  if (!isModular(m)) return undefined;
  const [p, q, r, s] = m;
  const { a, b, c } = f;
  return {
    a: a * p * p + b * p * r + c * r * r,
    b: 2 * a * p * q + b * (p * s + q * r) + 2 * c * r * s,
    c: a * q * q + b * q * s + c * s * s,
  };
}

/**
 * Gauss's reduction condition for an indefinite form: |√D − 2|a|| < b < √D.
 *
 * There are finitely many such forms per discriminant, and every class contains at least
 * one — but usually several, which is the difference from the definite case.
 */
export function isReduced(f: Form): boolean {
  if (!isIndefinite(f)) return false;
  const d = discriminant(f);
  const { root } = integerSqrt(d) as { root: number; exact: boolean };
  // D is not a square, so √D is irrational and the strict inequalities are integer ones:
  // b < √D means b ≤ root, and |√D − 2|a|| < b means the same for the two bracketing cases.
  const twiceA = 2 * Math.abs(f.a);
  return f.b > 0 && f.b <= root && Math.abs(root - twiceA) < f.b && twiceA < root + f.b;
}

/**
 * One step round the cycle. b' is the unique representative of −b modulo 2|c| inside a
 * window of width exactly 2|c|, so there is nothing to choose; which window depends on
 * whether |c| has passed √D, and that is the whole content of the definition.
 */
export function rho(f: Form): Form | undefined {
  const d = discriminant(f);
  const sqrt = integerSqrt(d);
  if (sqrt === undefined || d <= 0 || sqrt.exact || f.c === 0) return undefined;
  const { root } = sqrt;
  const magnitude = Math.abs(f.c);
  const modulus = 2 * magnitude;
  // The window is (low, low + 2|c|], and holds exactly one residue.
  const low = magnitude >= root + 1 ? -magnitude : root - modulus;
  let next = ((((-f.b - low - 1) % modulus) + modulus) % modulus) + low + 1;
  if (next > low + modulus) next -= modulus;
  const third = (next * next - d) / (4 * f.c);
  return isInt(third) ? { a: f.c, b: next, c: third } : undefined;
}

/** Reduce a form by walking ρ until the reduction condition holds. */
export function reduceForm(f: Form): Form | undefined {
  if (!isIndefinite(f)) return undefined;
  let current: Form | undefined = f;
  for (let guard = 0; guard < 10_000; guard++) {
    if (current === undefined) return undefined;
    if (isReduced(current)) return current;
    current = rho(current);
  }
  return undefined;
}

export const sameForm = (f: Form, g: Form): boolean => f.a === g.a && f.b === g.b && f.c === g.c;

/**
 * The cycle of reduced forms containing this one — the class, listed. Its length is always
 * even for an indefinite form, because ρ swaps the sign of the leading coefficient.
 */
export function cycleOf(f: Form): Form[] | undefined {
  const start = reduceForm(f);
  if (start === undefined) return undefined;
  const cycle: Form[] = [start];
  for (let guard = 0; guard < 10_000; guard++) {
    const next = rho(cycle[cycle.length - 1] as Form);
    if (next === undefined) return undefined;
    if (sameForm(next, start)) return cycle;
    cycle.push(next);
  }
  return undefined;
}

/** Every reduced form of a given indefinite discriminant. */
export function reducedForms(d: number): Form[] | undefined {
  const sqrt = integerSqrt(d);
  if (sqrt === undefined || d <= 0 || sqrt.exact || d > 100_000) return undefined;
  const { root } = sqrt;
  const out: Form[] = [];
  for (let b = 1; b <= root; b++) {
    if ((b - d) % 2 !== 0) continue; // b ≡ D (mod 2), since b² − D = 4ac
    const product = (b * b - d) / 4; // = ac, and negative because b² < D
    for (let a = -Math.abs(product); a <= Math.abs(product); a++) {
      if (a === 0 || product % a !== 0) continue;
      const candidate: Form = { a, b, c: product / a };
      if (isReduced(candidate)) out.push(candidate);
    }
  }
  return out;
}

/** The classes of a discriminant: the reduced forms, partitioned into ρ-cycles. */
export function formClasses(d: number): Form[][] | undefined {
  const reduced = reducedForms(d);
  if (reduced === undefined) return undefined;
  const key = ({ a, b, c }: Form): string => `${a},${b},${c}`;
  const seen = new Set<string>();
  const classes: Form[][] = [];
  for (const f of reduced) {
    if (seen.has(key(f))) continue;
    const cycle = cycleOf(f);
    if (cycle === undefined) return undefined;
    for (const member of cycle) seen.add(key(member));
    classes.push(cycle);
  }
  return classes;
}

/** The class number: how many classes of forms this discriminant has. */
export const classNumber = (d: number): number | undefined => formClasses(d)?.length;

// ── Pell, and the automorph ─────────────────────────────────────────────────────

/**
 * The fundamental solution of t² − Du² = 4 with u > 0, found by search. It is the smallest
 * unit of the order of discriminant D, and every form of that discriminant is stabilised by
 * a matrix built from it.
 */
export function pellSolution(d: number): { t: number; u: number } | undefined {
  const sqrt = integerSqrt(d);
  if (sqrt === undefined || d <= 0 || sqrt.exact) return undefined;
  for (let u = 1; u < 2_000_000; u++) {
    const square = d * u * u + 4;
    if (!isInt(square)) return undefined;
    const root = integerSqrt(square);
    if (root !== undefined && root.exact) return { t: root.root, u };
  }
  return undefined;
}

/**
 * The automorph: the generator of the form's stabiliser in SL(2,Z),
 *
 *     [ (t − bu)/2      −cu      ]
 *     [    au        (t + bu)/2  ]
 *
 * for (t, u) the fundamental Pell solution. Its determinant is (t² − Du²)/4 = 1, and its
 * trace is t — which exceeds 2, so it is HYPERBOLIC, and its conjugacy class is the closed
 * geodesic this form's cycle describes.
 */
export function automorph(f: Form): Matrix | undefined {
  if (!isIndefinite(f)) return undefined;
  const pell = pellSolution(discriminant(f));
  if (pell === undefined) return undefined;
  const { t, u } = pell;
  const topLeft = (t - f.b * u) / 2;
  const bottomRight = (t + f.b * u) / 2;
  if (!isInt(topLeft) || !isInt(bottomRight)) return undefined;
  const m: Matrix = [topLeft, -f.c * u, f.a * u, bottomRight];
  return isModular(m) ? m : undefined;
}
