// A GOLDEN CORPUS of the SQL the row half generates — the guard that makes rows.ts safe to refactor (#288).
//
// selfcert-rows.mts already proves `planRows` == `rowSql` on real data, and that is the differential that matters
// for CORRECTNESS. But both sides are generated by the same code, so a change that alters what both emit — a
// clause composed from `Pred[]` instead of spliced as text, say — moves the two together and the differential
// stays green while the SQL quietly changes underneath. That is exactly the refactor #288 step 2 proposes.
//
// So this pins the OTHER axis: the literal statement, byte for byte, for a corpus spanning every archetype and
// every clause shape. A diff here is not automatically a failure — it is a change to generated SQL that someone
// must look at and re-bless deliberately, which is the whole point of a golden file.
//
// It needs a live core because the statement depends on the collection's registered stats, reprs and accels.
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { close, makeDb, provideDb, rowSql, type RowQuery, type RowSelect, type RowWindow } from '../src/index.ts'

type Case = { id: string; q: RowQuery; w?: RowWindow; sel?: RowSelect }

/** Spanning set, not an exhaustive one: every archetype (elements, fibers, distribution, rollup, rowgroup), every
 *  clause (WHERE, GROUP BY, HAVING, ORDER BY), the open/bounded split, the SELECT half, and the two element
 *  relations that rewrite clause text (a kernel token and a graded cover) — which are precisely the paths a
 *  structured-clause refactor would touch. */
const CASES: Case[] = [
  { id: 'elements · bare', q: { from: 'permutations(size=4)' } },
  { id: 'elements · restriction', q: { from: 'permutations(size=4)', where: 'descents >= 2' } },
  { id: 'elements · between + in', q: { from: 'permutations(size=4)', where: 'descents BETWEEN 1 AND 2 AND inversions IN (1, 2, 3)' } },
  { id: 'elements · stat sort', q: { from: 'permutations(4)', orderBy: 'inversions DESC, rank' }, w: { count: 6 } },
  { id: 'elements · window', q: { from: 'permutations(size=0..4)' }, w: { first: 5, count: 7 } },
  { id: 'elements · open frontier', q: { from: 'permutations' }, w: { first: 8, count: 4 } },
  { id: 'elements · stat id collision', q: { from: 'subsets(3)', where: 'rank_stat = 2' } },
  { id: 'elements · select list', q: { from: 'permutations(size=4)' }, sel: { select: 'element,descents,map:inverse' } },
  { id: 'elements · glyph deferred', q: { from: 'permutations(size=4)' }, sel: { select: 'element,glyph' } },
  { id: 'elements · eager glyph', q: { from: 'permutations(size=4)' }, sel: { select: 'element,glyph', eager: true } },
  { id: 'fibers · band', q: { from: 'permutations(size=0..6)', groupBy: 'size' } },
  { id: 'fibers · prefix of two axes', q: { from: 'k_subsets(n=0..4)', groupBy: 'n' } },
  { id: 'fibers · key lens', q: { from: 'k_subsets(n=0..7)', groupBy: 'n, k', having: 'k = 2' } },
  { id: 'fibers · measure lens', q: { from: 'permutations(size=0..7)', groupBy: 'size', having: 'count(*) > 5' } },
  { id: 'fibers · symbol column', q: { from: 'permutations(size=0..5)', groupBy: 'size' }, sel: { select: 'size,count,symbol' } },
  { id: 'distribution · q-analog', q: { from: 'permutations(4)', groupBy: 'inversions' } },
  { id: 'distribution · triangle', q: { from: 'permutations(size=0..4)', groupBy: 'size, descents' } },
  { id: 'distribution · dist cell', q: { from: 'permutations(size=0..4)', groupBy: 'size' }, sel: { select: 'size,count,dist:descents' } },
  { id: 'distribution · pivot', q: { from: 'permutations(size=0..4)', groupBy: 'size' }, sel: { select: 'size,count,pivot:descents' } },
  { id: 'distribution · meta', q: { from: 'collections', groupBy: 'carrier', having: 'count(*) >= 8', orderBy: 'count DESC' } },
  { id: 'rollup', q: { from: 'k_subsets(n=0..3)', groupBy: 'ROLLUP (n, k)' } },
  { id: 'rollup · registered + measure lens', q: { from: 'permutations(size=0..5)', groupBy: 'ROLLUP (size, cycles)', having: 'count(*) > 1' } },
  { id: 'grouping sets · with footer', q: { from: 'permutations(size=0..4)', groupBy: 'GROUPING SETS ((size, descents), ())' } },
  { id: 'rowgroup', q: { from: 'permutations(size=0..3)', groupBy: 'GROUPING SETS ((size, rank, element), (size))' } },
  { id: 'rowgroup · key lens', q: { from: 'k_subsets(n=0..3)', groupBy: 'GROUPING SETS ((n, k, rank, element), (n))', having: 'n >= 2' } },
  { id: 'over · count lifted onto elements', q: { from: 'permutations(size=0..4)' }, sel: { select: 'element,over:count' } },
  { id: 'kernel · GROUP BY orbit', q: { from: 'words(4, 2)', groupBy: 'orbit:rotation' } },
  { id: 'kernel · GROUP BY map', q: { from: 'permutations(4)', groupBy: 'map:inverse' } },
  { id: 'order · graded cover relation', q: { from: 'permutations(4)', orderBy: 'weak_order' } },
  { id: 'facet · meta collection', q: { from: 'collections', where: `carrier = 'permutation'` } },
]

describe('generated SQL is pinned, so a refactor of the row half has to re-bless it', () => {
  beforeAll(() => { provideDb(() => makeDb()) })
  afterAll(async () => { await close() })

  it('every statement in the corpus matches its golden form', async () => {
    // plain text with real newlines, not JSON — the whole value of this file is that a human can READ the diff,
    // and JSON escapes every statement onto one unreadable line
    const parts: string[] = []
    for (const c of CASES) parts.push(`── ${c.id} ${'─'.repeat(Math.max(0, 96 - c.id.length))}\n${await rowSql(c.q, c.w ?? {}, c.sel ?? {})}`)
    await expect(parts.join('\n\n') + '\n').toMatchFileSnapshot('./__snapshots__/rowsql.golden.sql')
  })
})
