// GENERATED by scripts/collect-naming.ts — do not edit by hand.
//
// Catalog stat name → the head we actually declare, rebuilt from every head's `formerly:`
// field. Regenerate with:
//
//   vp node packages/symbols/combinatorics/statistics/scripts/collect-naming.ts

export const RENAMED_DATA: Readonly<Record<string, string>> = {
  Cycles: "CycleCount",
  NumberOfCyclesOfLength2: "TwoCycleCount",
  NumberOfCyclesOfLength3: "ThreeCycleCount",
  NumberOfOccurrencesOf213: "OccurrencesOf213",
  NumberOfStandardTableaux: "StandardTableauCount",
  NumberOfTouchPoints: "TouchPointCount",
};
