// GENERATED by packages/reference/scripts/find-findstat-maps.ts — do not edit by hand.
//
// Which FindStat maps each of ours is, decided by VALUE: our map applied to each row of FindStat's
// own table whose object has size at most 6 (rows beyond that are not compared), compared with its
// image. A table matches when no compared row disagrees and every row of size at most 5 is read on
// both sides. Regenerate with:
//
//   node packages/reference/scripts/find-findstat-maps.ts

/** FindStat's map, and how its table was read against ours. */
export interface FindStatAgreement {
  /** FindStat's id, e.g. `Mp00064`. */
  readonly id: string;
  /** Rows in FindStat's table. */
  readonly rows: number;
  /** Rows of size at most 6 read on both sides; every one agrees with ours. */
  readonly compared: number;
  /** Rows of size at most 6 that can't be read, so not compared. */
  readonly skipped: number;
}

/** One map of ours and the FindStat maps that agree with it on every compared row. */
export interface FindStatMapMatch {
  readonly name: string;
  readonly from: string;
  readonly to: string;
  /** More than one means they agree on every row of each. */
  readonly findstat: readonly FindStatAgreement[];
}

export const findstatMaps: readonly FindStatMapMatch[] = [
  {
    name: "Reverse",
    from: "Permutation",
    to: "Permutation",
    findstat: [{ id: "Mp00064", rows: 1200, compared: 873, skipped: 0 }],
  },
  {
    name: "Complement",
    from: "Permutation",
    to: "Permutation",
    findstat: [{ id: "Mp00069", rows: 1200, compared: 873, skipped: 0 }],
  },
  {
    name: "Inverse",
    from: "Permutation",
    to: "Permutation",
    findstat: [{ id: "Mp00066", rows: 1200, compared: 873, skipped: 0 }],
  },
  {
    name: "CycleType",
    from: "Permutation",
    to: "IntegerPartition",
    findstat: [{ id: "Mp00108", rows: 1200, compared: 873, skipped: 0 }],
  },
  {
    name: "CyclicShift",
    from: "Permutation",
    to: "Permutation",
    findstat: [{ id: "Mp00279", rows: 1200, compared: 873, skipped: 0 }],
  },
  {
    name: "RskInsertion",
    from: "Permutation",
    to: "StandardTableau",
    findstat: [{ id: "Mp00059", rows: 1200, compared: 873, skipped: 0 }],
  },
  {
    name: "RskShape",
    from: "Permutation",
    to: "IntegerPartition",
    findstat: [{ id: "Mp00060", rows: 1200, compared: 873, skipped: 0 }],
  },
  {
    name: "RskRecording",
    from: "Permutation",
    to: "StandardTableau",
    findstat: [{ id: "Mp00070", rows: 1200, compared: 873, skipped: 0 }],
  },
  {
    name: "CyclePartition",
    from: "Permutation",
    to: "SetPartition",
    findstat: [{ id: "Mp00151", rows: 1200, compared: 873, skipped: 0 }],
  },
  {
    name: "DescentComposition",
    from: "Permutation",
    to: "Composition",
    findstat: [{ id: "Mp00071", rows: 1200, compared: 873, skipped: 0 }],
  },
  {
    name: "BinarySearchTree",
    from: "Permutation",
    to: "BinaryTree",
    findstat: [{ id: "Mp00072", rows: 1200, compared: 873, skipped: 0 }],
  },
  {
    name: "Foata",
    from: "Permutation",
    to: "Permutation",
    findstat: [{ id: "Mp00087", rows: 1200, compared: 873, skipped: 0 }],
  },
  {
    name: "DyckPath",
    from: "BinaryTree",
    to: "DyckPath",
    findstat: [{ id: "Mp00012", rows: 1200, compared: 196, skipped: 0 }],
  },
  {
    name: "BinaryTree",
    from: "DyckPath",
    to: "BinaryTree",
    findstat: [{ id: "Mp00034", rows: 1200, compared: 196, skipped: 0 }],
  },
];
