// @enumeratio/frontend/core: the front end that runs without an engine -- the control
// contract, scrubbing and playback, the environments, highlighting, and the renderers
// that turn data into SVG. A page loads this at once; what parses or evaluates is the
// main entry's, and loads with compute-engine. `@enumeratio/components`' `tests/lazy.test.ts`
// holds the line.

export * from "./assert.ts";
export * from "./barchart3d.ts";
export * from "./chart.ts";
export * from "./clock.ts";
export * from "./collection-table.ts";
export * from "./row-spec.ts";
export * from "./table-view.ts";
export * from "./contour.ts";
export * from "./debug.ts";
export * from "./densityplot.ts";
export * from "./glyphs.ts";
export * from "./graph.ts";
export * from "./ipynb.ts";
export * from "./heads.ts";
export * from "./highlight.ts";
export * from "./listplot3d.ts";
export * from "./manipulate.ts";
export * from "./orbit.ts";
export * from "./gestures.ts";
export * from "./graphics-rules.ts";
export * from "./tiles-canvas.ts";
export * from "./graphics-box.ts";
export * from "./show-spec.ts";
export * from "./lattice-layers.ts";
export * from "./show-box.ts";
export * from "./svg-draw.ts";
export * from "./strand-frame.ts";
export * from "./cell-frame.ts";
export * from "./tree-frame.ts";
export * from "./path-frame.ts";
export * from "./polytope-frame.ts";
export * from "./camera-frame.ts";
export * from "./figure-frames.ts";
export * from "./variables.ts";
export * from "./lattice.ts";
export * from "./palettes.ts";
export * from "./plot-color.ts";
export * from "./plot.ts";
export * from "./plot-box.ts";
export * from "./plot-lowering.ts";
export * from "./plot3d.ts";
export * from "./polarplot.ts";
export * from "./project3d.ts";
export * from "./prose.ts";
export * from "./reactive.ts";
export * from "./scales.ts";
export * from "./space.ts";
export * from "./scrub.ts";
export * from "./torussquare.ts";
export * from "./transcript.ts";
export * from "./vectorplot.ts";
export * from "./playback.ts";
export * from "./controls.ts";
export * from "./primitives.ts";
export * from "./engine.ts";
export * from "./latex.ts";
export * from "./environment.ts";
export * from "./complex-plot.ts";
export * from "./gpu-eval.ts";
export * from "./complex-plot-3d.ts";
