// Rebuild `src/stories-data.ts` from every `reference/<Name>.stories.yaml` -- the component
// reference pages read this file, not the YAML, the same way the crosswalk reads
// `curated-data.ts` instead of parsing records at runtime (they run in the browser and the
// site build, and cannot parse YAML there). Each story's markup is derived from its vdom and
// pinned here too: a storybook card renders the vdom live and prints this text as its source,
// so what's shown can never drift from what renders.
//
//   vp node packages/components/scripts/collect-stories.ts

import { readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { COMPONENT_STORIES_SCHEMA, validateSchema } from "@enumeratio/entry/schema";
import { readStories, STORIES_SUFFIX, writeFormatted } from "@enumeratio/entry/node";
import { markupOf, type Rendering } from "@enumeratio/frontend";
import type { ComponentStory, StoryVdom } from "@enumeratio/entry";

// `StoryVdom` leaves `attributes` optional (nicer to author a text leaf without it);
// `Rendering` always carries it. Stories.vue normalizes the same way to render one live.
const asRendering = (vdom: StoryVdom): Rendering => ({
  tag: vdom.tag,
  attributes: vdom.attributes ?? {},
  children: vdom.children?.map(asRendering),
  text: vdom.text,
});

const referenceDir = new URL("../reference/", import.meta.url);
const referencePath = fileURLToPath(referenceDir);

const names = readdirSync(referencePath)
  .filter((f) => f.endsWith(STORIES_SUFFIX))
  .map((f) => f.slice(0, -STORIES_SUFFIX.length))
  .sort();

export interface StoryData extends ComponentStory {
  /** `markupOf(story.vdom)`, pinned so a page shows it without re-deriving it. */
  readonly markup: string;
}

const data: Record<string, StoryData[]> = {};
const issues: string[] = [];
for (const name of names) {
  const stories = readStories(referenceDir, name);
  for (const message of validateSchema(COMPONENT_STORIES_SCHEMA, stories))
    issues.push(`${name}${STORIES_SUFFIX}: ${message}`);
  data[name] = stories.map((story) => ({ ...story, markup: markupOf(asRendering(story.vdom)) }));
}
if (issues.length > 0) throw new Error(`collect-stories: ${issues.map((i) => `\n  ${i}`).join("")}`);

await writeFormatted(
  new URL("../src/stories-data.ts", import.meta.url),
  `// GENERATED by scripts/collect-stories.ts — do not edit by hand.
//
// Every component's stories (reference/<Name>.stories.yaml), keyed by component name, each
// with its markup derived from its vdom and pinned. Regenerate with:
//
//   vp node packages/components/scripts/collect-stories.ts

export interface StoryVdom {
  readonly tag: string;
  readonly attributes?: Readonly<Record<string, string>>;
  readonly children?: readonly StoryVdom[];
  readonly text?: string;
}

export interface StoryData {
  readonly id: string;
  readonly caption: string;
  readonly category?: string;
  readonly notes?: string;
  readonly vdom: StoryVdom;
  readonly markup: string;
}

export const STORIES_DATA: Readonly<Record<string, readonly StoryData[]>> = ${JSON.stringify(data, null, 2)};
`,
);

console.log(`${names.length} component(s), ${Object.values(data).flat().length} stories collected`);
