// Rebuild `src/stories-data.ts` from every `reference/<Name>.stories.yaml` -- the component
// reference pages read this file, not the YAML, the same way the crosswalk reads
// `curated-data.ts` instead of parsing records at runtime (they run in the browser and the
// site build, and cannot parse YAML there). A story's `expr` is the source of truth (design/
// vdom.md: a MathJSON node and a vdom node are the same tree under a renaming); its source
// panel shows it in several equivalent written forms, each derived here and pinned so the page
// never re-derives one. Today there are two: `head`, the structural tree (`structuralOf`)
// printed as a person would write it by hand, PascalCase heads and all; and `html`, the
// lit-tag markup a plain-HTML host would write (`renderingOf`/`vdomOf` -- the same lowering
// that draws the live render -- plus `markupOf`). More forms (Vue template, JSX, …) land the
// same way. The live render on the page still goes through `vdomOf`/`toVNode` at runtime:
// that lowering is cheap, pure and can only get more correct as the engine does, so pinning it
// would just be something else to regenerate.
//
//   vp node packages/components/scripts/collect-stories.ts

import { readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { COMPONENT_STORIES_SCHEMA, validateSchema } from "@enumeratio/entry/schema";
import { readStories, STORIES_SUFFIX, writeFormatted } from "@enumeratio/entry/node";
import { markupOf, renderingOf } from "@enumeratio/frontend/symbols";
import { structuralMarkupOf } from "@enumeratio/frontend/reflect";
import { structuralOf, vdomOf } from "@enumeratio/frontend/vdom";
import type { ComponentStory } from "@enumeratio/entry";

const referenceDir = new URL("../reference/", import.meta.url);
const referencePath = fileURLToPath(referenceDir);

const names = readdirSync(referencePath)
  .filter((f) => f.endsWith(STORIES_SUFFIX))
  .map((f) => f.slice(0, -STORIES_SUFFIX.length))
  .sort();

/** One written form of a story's source, shown as a tab in the source panel. */
export interface StoryForm {
  /** Which tab; stable across regeneration -- `head` and `html` today. */
  readonly id: string;
  /** The tab's label. */
  readonly label: string;
  /** The markup itself. */
  readonly text: string;
}

export interface StoryData extends ComponentStory {
  /** The story's source, one entry per written form -- see the forms named above. */
  readonly forms: readonly StoryForm[];
}

/** Every written form of `expr`, in tab order. */
function formsOf(expr: ComponentStory["expr"]): StoryForm[] {
  const json = expr as never;
  return [
    { id: "head", label: "<Head>", text: structuralMarkupOf(structuralOf(json)) },
    // `renderingOf` falls back to `vdomOf`'s `notatio-out` only for an expression with no
    // component of its own -- not a story's, which is always over its component's head.
    { id: "html", label: "Web component", text: markupOf(renderingOf(json) ?? vdomOf(json)) },
  ];
}

const data: Record<string, StoryData[]> = {};
const issues: string[] = [];
for (const name of names) {
  const stories = readStories(referenceDir, name);
  for (const message of validateSchema(COMPONENT_STORIES_SCHEMA, stories))
    issues.push(`${name}${STORIES_SUFFIX}: ${message}`);
  const seen = new Set<string>();
  for (const story of stories) {
    if (seen.has(story.id)) issues.push(`${name}${STORIES_SUFFIX}: duplicate story id "${story.id}"`);
    seen.add(story.id);
  }
  data[name] = stories.map((story) => ({
    ...story,
    forms: formsOf(story.expr),
  }));
}
if (issues.length > 0) throw new Error(`collect-stories: ${issues.map((i) => `\n  ${i}`).join("")}`);

await writeFormatted(
  new URL("../src/stories-data.ts", import.meta.url),
  `// GENERATED by scripts/collect-stories.ts — do not edit by hand.
//
// Every component's stories (reference/<Name>.stories.yaml), keyed by component name, each
// with its source forms derived from its expr and pinned. Regenerate with:
//
//   vp node packages/components/scripts/collect-stories.ts

export type MathJSON = number | string | boolean | readonly MathJSON[] | { readonly [key: string]: unknown };

export interface StoryForm {
  readonly id: string;
  readonly label: string;
  readonly text: string;
}

export interface StoryData {
  readonly id: string;
  readonly caption: string;
  readonly category?: string;
  readonly notes?: string;
  readonly expr: MathJSON;
  readonly forms: readonly StoryForm[];
}

export const STORIES_DATA: Readonly<Record<string, readonly StoryData[]>> = ${JSON.stringify(data, null, 2)};
`,
);

console.log(`${names.length} component(s), ${Object.values(data).flat().length} stories collected`);
