import type { ReferenceEntry } from "../types.ts";

// Every `expected` was produced by evaluating `expr` with compute-engine 0.128.0
// (the reference tests re-evaluate and pin it). See sibling domain files.
export const elementary: readonly ReferenceEntry[] = [
  {
    name: "Sin",
    domain: "Elementary functions",
    signature: "Sin(x)",
    summary: "The sine of x, in radians.",
    signatures: [{ call: "Sin(x)", description: "the sine of x, in radians." }],
    details: [
      "Odd function: $\\sin(-x) = -\\sin(x)$.",
      "Period $2\\pi$: $\\sin(x + 2\\pi) = \\sin(x)$.",
      "Reciprocal of [[Csc]]: $\\sin(x) = \\frac{1}{\\csc(x)}$.",
      "compute-engine evaluates exactly at rational multiples of $\\pi$ that have a closed radical form -- well past the usual $\\pi/6, \\pi/4, \\pi/3$ set, e.g. $\\pi/5$.",
      "A numeric argument that isn't a recognized special angle, and isn't already floating-point, is left symbolic; pass a float or wrap in N(...) for a numeric approximation.",
    ],
    examples: [
      { expr: ["Sin", 0], expected: 0 },
      {
        expr: ["Sin", ["Divide", "Pi", 6]],
        expected: ["Rational", 1, 2],
        caption: "Exact value at a special angle",
      },
      { expr: ["Sin", ["Divide", "Pi", 4]], expected: ["Divide", ["Sqrt", 2], 2] },
      { expr: ["Sin", ["Divide", "Pi", 3]], expected: ["Divide", ["Sqrt", 3], 2] },
      { expr: ["Sin", ["Divide", "Pi", 2]], expected: 1 },
      { expr: ["Sin", "Pi"], expected: 0 },
      {
        expr: [
          "Add",
          ["Power", ["Sin", ["Divide", "Pi", 6]], 2],
          ["Power", ["Cos", ["Divide", "Pi", 6]], 2],
        ],
        expected: 1,
        category: "Properties",
        caption: "Pythagorean identity $\\sin^2 x + \\cos^2 x = 1$, here at $x = \\pi/6$",
      },
      {
        expr: [
          "Equal",
          ["Sin", ["Negate", ["Divide", "Pi", 6]]],
          ["Negate", ["Sin", ["Divide", "Pi", 6]]],
        ],
        expected: "True",
        category: "Properties",
        caption: "Odd function: $\\sin(-x) = -\\sin(x)$",
      },
      {
        expr: ["Sin", ["Add", ["Divide", "Pi", 6], ["Multiply", 2, "Pi"]]],
        expected: ["Rational", 1, 2],
        category: "Properties",
        caption: "Period $2\\pi$: adding a full turn doesn't change the value",
      },
      {
        expr: ["Sin", ["List", 0, ["Divide", "Pi", 2], "Pi"]],
        expected: ["List", 0, 1, 0],
        category: "Applications",
        caption: "Threads element-wise over a list",
      },
      {
        expr: ["Sin", ["Degrees", 30]],
        expected: ["Rational", 1, 2],
        category: "Applications",
        caption:
          "Degrees(d) converts a degree measure to radians, so familiar degree angles still evaluate exactly",
      },
      {
        expr: ["Sin", 1],
        expected: ["Sin", 1],
        category: "Possible issues",
        caption:
          "1 radian isn't a recognized special angle, so this stays symbolic; wrap in N(...) or pass 1.0 for \u2248 0.841",
      },
      {
        expr: ["Sin", ["Divide", "Pi", 5]],
        expected: [
          "Multiply",
          ["Divide", ["Sqrt", 2], 4],
          ["Sqrt", ["Add", 5, ["Negate", ["Sqrt", 5]]]],
        ],
        category: "Neat examples",
        caption:
          "The special-angle table reaches past 30-45-60: $\\sin(\\pi/5)$ comes out as a nested radical",
      },
    ],
    seeAlso: ["Cos", "Tan", "Csc", "Arcsin"],
  },
  {
    name: "Cos",
    domain: "Elementary functions",
    signature: "Cos(x)",
    summary: "The cosine of x, in radians.",
    signatures: [{ call: "Cos(x)", description: "the cosine of x, in radians." }],
    details: [
      "Even function: $\\cos(-x) = \\cos(x)$.",
      "Period $2\\pi$.",
      "Reciprocal of [[Sec]]: $\\cos(x) = \\frac{1}{\\sec(x)}$.",
      "Co-function with [[Sin]]: $\\cos(x) = \\sin(\\pi/2 - x)$.",
    ],
    examples: [
      { expr: ["Cos", 0], expected: 1 },
      { expr: ["Cos", ["Divide", "Pi", 6]], expected: ["Divide", ["Sqrt", 3], 2] },
      { expr: ["Cos", ["Divide", "Pi", 4]], expected: ["Divide", ["Sqrt", 2], 2] },
      { expr: ["Cos", ["Divide", "Pi", 3]], expected: ["Rational", 1, 2] },
      { expr: ["Cos", ["Divide", "Pi", 2]], expected: 0 },
      { expr: ["Cos", "Pi"], expected: -1 },
      {
        expr: ["Equal", ["Cos", ["Negate", ["Divide", "Pi", 3]]], ["Cos", ["Divide", "Pi", 3]]],
        expected: "True",
        category: "Properties",
        caption: "Even function: $\\cos(-x) = \\cos(x)$",
      },
      {
        expr: [
          "Equal",
          ["Cos", ["Divide", "Pi", 6]],
          ["Sin", ["Subtract", ["Divide", "Pi", 2], ["Divide", "Pi", 6]]],
        ],
        expected: "True",
        category: "Properties",
        caption: "Co-function identity: $\\cos x = \\sin(\\pi/2 - x)$",
      },
      {
        expr: ["Cos", ["List", 0, ["Divide", "Pi", 2], "Pi"]],
        expected: ["List", 1, 0, -1],
        category: "Applications",
        caption: "Threads element-wise over a list",
      },
      {
        expr: ["Cos", 2],
        expected: ["Cos", 2],
        category: "Possible issues",
        caption:
          "As with [[Sin]], a non-special numeric argument stays symbolic unless it's already a float",
      },
      {
        expr: ["Cos", ["Divide", "Pi", 5]],
        expected: ["Add", ["Rational", 1, 4], ["Divide", ["Sqrt", 5], 4]],
        category: "Neat examples",
        caption: "$\\cos(\\pi/5) = \\frac{1+\\sqrt5}{4}$, related to the golden ratio",
      },
    ],
    seeAlso: ["Sin", "Tan", "Sec", "Arccos"],
  },
  {
    name: "Tan",
    domain: "Elementary functions",
    signature: "Tan(x)",
    summary: "The tangent of x, in radians.",
    signatures: [{ call: "Tan(x)", description: "the tangent of x, in radians." }],
    details: [
      "$\\tan(x) = \\frac{\\sin(x)}{\\cos(x)}$.",
      "Odd function: $\\tan(-x) = -\\tan(x)$.",
      "Period $\\pi$ -- half the period of [[Sin]] and [[Cos]].",
      "Undefined wherever $\\cos(x) = 0$, i.e. at odd multiples of $\\pi/2$; compute-engine returns ComplexInfinity there rather than an error.",
    ],
    examples: [
      { expr: ["Tan", 0], expected: 0 },
      { expr: ["Tan", ["Divide", "Pi", 6]], expected: ["Divide", ["Sqrt", 3], 3] },
      { expr: ["Tan", ["Divide", "Pi", 4]], expected: 1 },
      { expr: ["Tan", ["Divide", "Pi", 3]], expected: ["Sqrt", 3] },
      {
        expr: [
          "Equal",
          ["Tan", ["Divide", "Pi", 4]],
          ["Divide", ["Sin", ["Divide", "Pi", 4]], ["Cos", ["Divide", "Pi", 4]]],
        ],
        expected: "True",
        category: "Properties",
        caption: "$\\tan(x) = \\frac{\\sin(x)}{\\cos(x)}$",
      },
      {
        expr: ["Tan", ["Negate", ["Divide", "Pi", 4]]],
        expected: -1,
        category: "Properties",
        caption: "Odd function: $\\tan(-x) = -\\tan(x)$",
      },
      {
        expr: ["Tan", ["Add", ["Divide", "Pi", 4], "Pi"]],
        expected: 1,
        category: "Properties",
        caption: "Period $\\pi$, not $2\\pi$: adding a half turn doesn't change the value",
      },
      {
        expr: ["Tan", ["List", 0, ["Divide", "Pi", 4]]],
        expected: ["List", 0, 1],
        category: "Applications",
        caption: "Threads element-wise over a list",
      },
      {
        expr: ["Tan", ["Divide", "Pi", 2]],
        expected: "ComplexInfinity",
        category: "Possible issues",
        caption: "A pole: $\\cos(\\pi/2) = 0$, so the ratio blows up",
      },
      {
        expr: ["Tan", 1],
        expected: ["Tan", 1],
        category: "Possible issues",
        caption: "Same rule as [[Sin]] and [[Cos]]: a non-special numeric argument stays symbolic",
      },
    ],
    seeAlso: ["Sin", "Cos", "Cot", "Arctan"],
  },
  {
    name: "Cot",
    domain: "Elementary functions",
    signature: "Cot(x)",
    summary: "Cotangent, the reciprocal of [[Tan]].",
    signatures: [{ call: "Cot(x)", description: "the cotangent of x, $\\frac{1}{\\tan(x)}$." }],
    details: [
      "$\\cot(x) = \\frac{\\cos(x)}{\\sin(x)} = \\frac{1}{\\tan(x)}$.",
      "Period $\\pi$, same as [[Tan]].",
      "Undefined wherever $\\sin(x) = 0$, i.e. at multiples of $\\pi$ -- not the same poles as [[Tan]].",
    ],
    examples: [
      { expr: ["Cot", ["Divide", "Pi", 6]], expected: ["Sqrt", 3] },
      { expr: ["Cot", ["Divide", "Pi", 4]], expected: 1 },
      { expr: ["Cot", ["Divide", "Pi", 3]], expected: ["Divide", ["Sqrt", 3], 3] },
      {
        expr: ["Equal", ["Cot", ["Divide", "Pi", 4]], ["Divide", 1, ["Tan", ["Divide", "Pi", 4]]]],
        expected: "True",
        category: "Properties",
        caption: "Reciprocal of [[Tan]]: $\\cot(x) = \\frac{1}{\\tan(x)}$",
      },
      {
        expr: [
          "Equal",
          ["Add", 1, ["Power", ["Cot", ["Divide", "Pi", 6]], 2]],
          ["Power", ["Csc", ["Divide", "Pi", 6]], 2],
        ],
        expected: "True",
        category: "Properties",
        caption: "Pythagorean identity: $1 + \\cot^2 x = \\csc^2 x$",
      },
      {
        expr: ["Cot", 0],
        expected: "ComplexInfinity",
        category: "Possible issues",
        caption: "A pole: $\\sin(0) = 0$",
      },
      {
        expr: ["Cot", ["Divide", "Pi", 2]],
        expected: 0,
        category: "Possible issues",
        caption: "Not a pole here -- [[Tan]]'s pole at $\\pi/2$ is [[Cot]]'s zero instead",
      },
    ],
    seeAlso: ["Tan", "Sin", "Cos"],
  },
  {
    name: "Sec",
    domain: "Elementary functions",
    signature: "Sec(x)",
    summary: "Secant, the reciprocal of [[Cos]].",
    signatures: [{ call: "Sec(x)", description: "the secant of x, $\\frac{1}{\\cos(x)}$." }],
    details: [
      "$\\sec(x) = \\frac{1}{\\cos(x)}$.",
      "Even function, period $2\\pi$, same as [[Cos]].",
      "Undefined wherever $\\cos(x) = 0$, the same poles as [[Tan]].",
    ],
    examples: [
      { expr: ["Sec", 0], expected: 1 },
      { expr: ["Sec", ["Divide", "Pi", 4]], expected: ["Sqrt", 2] },
      { expr: ["Sec", ["Divide", "Pi", 3]], expected: 2 },
      { expr: ["Sec", "Pi"], expected: -1 },
      {
        expr: ["Equal", ["Sec", ["Divide", "Pi", 3]], ["Divide", 1, ["Cos", ["Divide", "Pi", 3]]]],
        expected: "True",
        category: "Properties",
        caption: "Reciprocal of [[Cos]]: $\\sec(x) = \\frac{1}{\\cos(x)}$",
      },
      {
        expr: [
          "Equal",
          ["Add", 1, ["Power", ["Tan", ["Divide", "Pi", 6]], 2]],
          ["Power", ["Sec", ["Divide", "Pi", 6]], 2],
        ],
        expected: "True",
        category: "Properties",
        caption: "Pythagorean identity: $1 + \\tan^2 x = \\sec^2 x$",
      },
      {
        expr: ["Sec", ["Divide", "Pi", 2]],
        expected: "ComplexInfinity",
        category: "Possible issues",
        caption: "A pole: $\\cos(\\pi/2) = 0$",
      },
    ],
    seeAlso: ["Cos", "Csc", "Cot"],
  },
  {
    name: "Csc",
    domain: "Elementary functions",
    signature: "Csc(x)",
    summary: "Cosecant, the reciprocal of [[Sin]].",
    signatures: [{ call: "Csc(x)", description: "the cosecant of x, $\\frac{1}{\\sin(x)}$." }],
    details: [
      "$\\csc(x) = \\frac{1}{\\sin(x)}$.",
      "Odd function, period $2\\pi$, same as [[Sin]].",
      "Undefined wherever $\\sin(x) = 0$, the same poles as [[Cot]].",
    ],
    examples: [
      { expr: ["Csc", ["Divide", "Pi", 6]], expected: 2 },
      { expr: ["Csc", ["Divide", "Pi", 4]], expected: ["Sqrt", 2] },
      { expr: ["Csc", ["Divide", "Pi", 2]], expected: 1 },
      {
        expr: ["Equal", ["Csc", ["Divide", "Pi", 6]], ["Divide", 1, ["Sin", ["Divide", "Pi", 6]]]],
        expected: "True",
        category: "Properties",
        caption: "Reciprocal of [[Sin]]: $\\csc(x) = \\frac{1}{\\sin(x)}$",
      },
      {
        expr: ["Csc", 0],
        expected: "ComplexInfinity",
        category: "Possible issues",
        caption: "A pole: $\\sin(0) = 0$",
      },
    ],
    seeAlso: ["Sin", "Sec", "Cot"],
  },
  {
    name: "Arcsin",
    domain: "Elementary functions",
    signature: "Arcsin(x)",
    summary: "Arcsine, the inverse of [[Sin]] restricted to $[-\\pi/2, \\pi/2]$.",
    signatures: [
      {
        call: "Arcsin(x)",
        description: "the principal value $y \\in [-\\pi/2, \\pi/2]$ with $\\sin(y) = x$.",
      },
    ],
    details: [
      "Real-valued only for $x \\in [-1, 1]$; outside that range the result is complex.",
      "Odd function: $\\arcsin(-x) = -\\arcsin(x)$.",
      "Co-function with [[Arccos]]: $\\arcsin(x) + \\arccos(x) = \\pi/2$.",
      "Undoes [[Sin]] on its principal branch: $\\sin(\\arcsin(x)) = x$ for $x \\in [-1, 1]$.",
    ],
    examples: [
      { expr: ["Arcsin", 0], expected: 0 },
      { expr: ["Arcsin", ["Rational", 1, 2]], expected: ["Multiply", ["Rational", 1, 6], "Pi"] },
      {
        expr: ["Arcsin", 1],
        expected: ["Multiply", ["Rational", 1, 2], "Pi"],
        caption: "The top of the principal range",
      },
      { expr: ["Arcsin", -1], expected: ["Multiply", ["Rational", -1, 2], "Pi"] },
      {
        expr: ["Equal", ["Sin", ["Arcsin", ["Rational", 1, 2]]], ["Rational", 1, 2]],
        expected: "True",
        category: "Properties",
        caption: "$\\sin(\\arcsin(x)) = x$ on the principal branch",
      },
      {
        expr: [
          "Equal",
          ["Add", ["Arcsin", ["Rational", 1, 2]], ["Arccos", ["Rational", 1, 2]]],
          ["Divide", "Pi", 2],
        ],
        expected: "True",
        category: "Properties",
        caption: "Co-function identity: $\\arcsin(x) + \\arccos(x) = \\pi/2$",
      },
      {
        expr: ["Arcsin", 2],
        expected: ["Arcsin", 2],
        category: "Possible issues",
        caption:
          "Outside $[-1, 1]$ the real domain is exceeded, so this stays symbolic; N(...) gives a complex approximation",
      },
      {
        expr: ["Arcsin", 2],
        expected: [
          "Subtract",
          ["Divide", "Pi", 2],
          ["Multiply", "ImaginaryUnit", ["Ln", ["Add", 2, ["Sqrt", 3]]]],
        ],
        aspirational: true,
        category: "Scope",
        caption:
          "Should evaluate to the exact closed form $\\frac{\\pi}{2} - i\\ln(2+\\sqrt3)$; currently left symbolic, and even $N(\\dots)$ gives only a numeric approximation, not this exact form",
      },
    ],
    seeAlso: ["Sin", "Arccos", "Arctan"],
  },
  {
    name: "Arccos",
    domain: "Elementary functions",
    signature: "Arccos(x)",
    summary: "Arccosine, the inverse of [[Cos]] restricted to $[0, \\pi]$.",
    signatures: [
      {
        call: "Arccos(x)",
        description: "the principal value $y \\in [0, \\pi]$ with $\\cos(y) = x$.",
      },
    ],
    details: [
      "Real-valued only for $x \\in [-1, 1]$; outside that range the result is complex.",
      "Co-function with [[Arcsin]]: $\\arccos(x) = \\pi/2 - \\arcsin(x)$.",
      "Undoes [[Cos]] on its principal branch: $\\cos(\\arccos(x)) = x$ for $x \\in [-1, 1]$.",
    ],
    examples: [
      { expr: ["Arccos", 1], expected: 0 },
      { expr: ["Arccos", ["Rational", 1, 2]], expected: ["Multiply", ["Rational", 1, 3], "Pi"] },
      { expr: ["Arccos", 0], expected: ["Multiply", ["Rational", 1, 2], "Pi"] },
      { expr: ["Arccos", -1], expected: "Pi", caption: "The top of the principal range" },
      {
        expr: ["Equal", ["Cos", ["Arccos", ["Rational", 1, 2]]], ["Rational", 1, 2]],
        expected: "True",
        category: "Properties",
        caption: "$\\cos(\\arccos(x)) = x$ on the principal branch",
      },
      {
        expr: ["Arccos", 2],
        expected: ["Arccos", 2],
        category: "Possible issues",
        caption:
          "Outside $[-1, 1]$ this stays symbolic, same as [[Arcsin]]; N(...) gives a complex approximation",
      },
    ],
    seeAlso: ["Cos", "Arcsin", "Arctan"],
  },
  {
    name: "Arctan",
    domain: "Elementary functions",
    signature: "Arctan(x)",
    summary: "Arctangent, the inverse of [[Tan]] restricted to $(-\\pi/2, \\pi/2)$.",
    signatures: [
      {
        call: "Arctan(x)",
        description: "the principal value $y \\in (-\\pi/2, \\pi/2)$ with $\\tan(y) = x$.",
      },
    ],
    details: [
      "Defined for every real x, unlike [[Arcsin]] and [[Arccos]].",
      "Odd function: $\\arctan(-x) = -\\arctan(x)$.",
      "Horizontal asymptotes at $\\pm\\pi/2$ as $x \\to \\pm\\infty$.",
      "The two-argument atan2 form is a separate compute-engine function, $\\mathrm{Arctan2}(x, y)$, rather than an overload of Arctan.",
    ],
    examples: [
      { expr: ["Arctan", 0], expected: 0 },
      { expr: ["Arctan", 1], expected: ["Multiply", ["Rational", 1, 4], "Pi"] },
      { expr: ["Arctan", ["Sqrt", 3]], expected: ["Multiply", ["Rational", 1, 3], "Pi"] },
      {
        expr: ["Equal", ["Tan", ["Arctan", 1]], 1],
        expected: "True",
        category: "Properties",
        caption: "$\\tan(\\arctan(x)) = x$",
      },
      {
        expr: ["Arctan", "PositiveInfinity"],
        expected: ["Multiply", ["Rational", 1, 2], "Pi"],
        category: "Neat examples",
        caption: "The horizontal asymptote as $x \\to +\\infty$",
      },
      {
        expr: ["Arctan", "NegativeInfinity"],
        expected: ["Multiply", ["Rational", -1, 2], "Pi"],
        category: "Neat examples",
        caption: "And as $x \\to -\\infty$",
      },
      {
        expr: ["Arctan", 1, 1],
        expected: [
          "Error",
          "'unexpected-argument'",
          "'1'",
          ["ErrorTrace", ["ErrorFrame", "'Arctan'", 2]],
        ],
        category: "Possible issues",
        caption:
          "compute-engine's Arctan takes only one argument and errors on a second; the two-argument atan2 form is the separate $\\mathrm{Arctan2}(x, y)$ function",
        divergence: {
          wolfram:
            "compute-engine's Arctan takes one argument and rejects a second; Wolfram's ArcTan[x, y] is the two-argument arctangent (atan2), here π/4.",
        },
      },
    ],
    seeAlso: ["Tan", "Arcsin", "Arccos"],
  },
  {
    name: "Arccot",
    domain: "Elementary functions",
    signature: "Arccot(x)",
    summary: "Arccotangent, the inverse of [[Cot]].",
    signatures: [{ call: "Arccot(x)", description: "the value $y$ with $\\cot(y) = x$." }],
    details: [
      "Stays symbolic even at values where the reciprocal circular functions fold exactly (e.g. $x = 1$) -- wrap in N(...) for a numeric result.",
    ],
    examples: [
      {
        expr: ["N", ["Arccot", 1]],
        expected: { num: "0.785398163397448309616" },
        caption: "$\\pi/4$, numerically -- N(...) forces the fold plain evaluation withholds",
      },
      {
        expr: ["Equal", ["Cot", ["Arccot", 1]], 1],
        expected: "True",
        category: "Properties",
        caption: "Undoes [[Cot]]: $\\cot(\\text{arccot}(x)) = x$",
      },
    ],
    seeAlso: ["Cot", "Arctan"],
  },
  {
    name: "Arccsc",
    domain: "Elementary functions",
    signature: "Arccsc(x)",
    summary: "Arccosecant, the inverse of [[Csc]].",
    signatures: [{ call: "Arccsc(x)", description: "the value $y$ with $\\csc(y) = x$." }],
    examples: [
      { expr: ["Arccsc", 1], expected: ["Multiply", ["Rational", 1, 2], "Pi"] },
      { expr: ["Arccsc", 2], expected: ["Multiply", ["Rational", 1, 6], "Pi"] },
      {
        expr: ["Equal", ["Csc", ["Arccsc", 2]], 2],
        expected: "True",
        category: "Properties",
        caption: "Undoes [[Csc]]: $\\csc(\\text{arccsc}(x)) = x$",
      },
    ],
    seeAlso: ["Csc", "Arcsin"],
  },
  {
    name: "Arcsec",
    domain: "Elementary functions",
    signature: "Arcsec(x)",
    summary: "Arcsecant, the inverse of [[Sec]].",
    signatures: [{ call: "Arcsec(x)", description: "the value $y$ with $\\sec(y) = x$." }],
    examples: [
      { expr: ["Arcsec", 1], expected: 0 },
      { expr: ["Arcsec", 2], expected: ["Multiply", ["Rational", 1, 3], "Pi"] },
      {
        expr: ["Equal", ["Sec", ["Arcsec", 2]], 2],
        expected: "True",
        category: "Properties",
        caption: "Undoes [[Sec]]: $\\sec(\\text{arcsec}(x)) = x$",
      },
    ],
    seeAlso: ["Sec", "Arccos"],
  },
  {
    name: "Sinh",
    domain: "Elementary functions",
    signature: "Sinh(x)",
    summary: "Hyperbolic sine: $\\sinh(x) = \\frac{e^x - e^{-x}}{2}$.",
    signatures: [{ call: "Sinh(x)", description: "the hyperbolic sine of x." }],
    details: [
      "Defined in terms of [[Exp]]: $\\sinh(x) = \\frac{e^x - e^{-x}}{2}$.",
      "Odd function: $\\sinh(-x) = -\\sinh(x)$.",
      "Unlike [[Sin]] and [[Cos]], compute-engine has no table of exact hyperbolic special values -- plain evaluation leaves Sinh symbolic even at $x = 0$; a floating-point argument, or N(...), still produces a numeric result.",
    ],
    examples: [
      {
        expr: ["N", ["Sinh", 0]],
        expected: 0,
        caption: "N(...) forces the numeric result that plain evaluation withholds",
      },
      { expr: ["N", ["Sinh", 1]], expected: { num: "1.17520119364380145688" } },
      {
        expr: ["Equal", ["Sinh", ["Negate", 1]], ["Negate", ["Sinh", 1]]],
        expected: "True",
        category: "Properties",
        caption: "Odd function: $\\sinh(-x) = -\\sinh(x)$",
      },
      {
        expr: [
          "Equal",
          ["Sinh", 1],
          ["Divide", ["Subtract", ["Exp", 1], ["Exp", ["Negate", 1]]], 2],
        ],
        expected: "True",
        category: "Properties",
        caption: "Definition in terms of [[Exp]]: $\\sinh(x) = \\frac{e^x - e^{-x}}{2}$",
      },
      {
        expr: ["Sinh", 0],
        expected: ["Sinh", 0],
        category: "Possible issues",
        caption:
          "Stays symbolic even at 0 -- compute-engine doesn't fold hyperbolic functions to exact values the way it does [[Sin]]/[[Cos]]; wrap in N(...) as above",
      },
    ],
    seeAlso: ["Cosh", "Tanh", "Exp"],
  },
  {
    name: "Cosh",
    domain: "Elementary functions",
    signature: "Cosh(x)",
    summary: "Hyperbolic cosine: $\\cosh(x) = \\frac{e^x + e^{-x}}{2}$.",
    signatures: [{ call: "Cosh(x)", description: "the hyperbolic cosine of x." }],
    details: [
      "Defined in terms of [[Exp]]: $\\cosh(x) = \\frac{e^x + e^{-x}}{2}$.",
      "Even function: $\\cosh(-x) = \\cosh(x)$.",
      "Same fold-only-with-N(...) behavior as [[Sinh]]: plain evaluation leaves Cosh symbolic even at $x = 0$.",
    ],
    examples: [
      {
        expr: ["N", ["Cosh", 0]],
        expected: 1,
        caption: "N(...) forces the numeric result that plain evaluation withholds",
      },
      { expr: ["N", ["Cosh", 1]], expected: { num: "1.54308063481524377848" } },
      {
        expr: ["Equal", ["Cosh", ["Negate", 1]], ["Cosh", 1]],
        expected: "True",
        category: "Properties",
        caption: "Even function: $\\cosh(-x) = \\cosh(x)$",
      },
      {
        expr: ["Equal", ["Subtract", ["Power", ["Cosh", 1], 2], ["Power", ["Sinh", 1], 2]], 1],
        expected: "True",
        category: "Properties",
        caption: "Hyperbolic Pythagorean identity: $\\cosh^2 x - \\sinh^2 x = 1$",
      },
      {
        expr: ["Cosh", 0],
        expected: ["Cosh", 0],
        category: "Possible issues",
        caption: "Stays symbolic even at 0, same as [[Sinh]]; wrap in N(...) as above",
      },
    ],
    seeAlso: ["Sinh", "Tanh", "Exp"],
  },
  {
    name: "Tanh",
    domain: "Elementary functions",
    signature: "Tanh(x)",
    summary: "Hyperbolic tangent: $\\tanh(x) = \\frac{\\sinh(x)}{\\cosh(x)}$.",
    signatures: [{ call: "Tanh(x)", description: "the hyperbolic tangent of x." }],
    details: [
      "$\\tanh(x) = \\frac{\\sinh(x)}{\\cosh(x)}$, ranging over $(-1, 1)$.",
      "Odd function: $\\tanh(-x) = -\\tanh(x)$.",
      "Same fold-only-with-N(...) behavior as [[Sinh]] and [[Cosh]].",
    ],
    examples: [
      {
        expr: ["N", ["Tanh", 0]],
        expected: 0,
        caption: "N(...) forces the numeric result that plain evaluation withholds",
      },
      { expr: ["N", ["Tanh", 1]], expected: { num: "0.761594155955764888119" } },
      {
        expr: ["Equal", ["Tanh", 1], ["Divide", ["Sinh", 1], ["Cosh", 1]]],
        expected: "True",
        category: "Properties",
        caption: "$\\tanh(x) = \\frac{\\sinh(x)}{\\cosh(x)}$",
      },
      {
        expr: ["Tanh", 0],
        expected: ["Tanh", 0],
        category: "Possible issues",
        caption: "Stays symbolic even at 0, same as [[Sinh]] and [[Cosh]]; wrap in N(...) as above",
      },
    ],
    seeAlso: ["Sinh", "Cosh"],
  },
  {
    name: "Arcoth",
    domain: "Elementary functions",
    signature: "Arcoth(x)",
    summary: "Inverse hyperbolic cotangent, the inverse of Coth.",
    signatures: [{ call: "Arcoth(x)", description: "the value $y$ with $\\coth(y) = x$." }],
    details: [
      "Stays symbolic at plain evaluation, same as [[Arsinh]]-family functions; wrap in N(...).",
    ],
    examples: [
      {
        expr: ["N", ["Arcoth", 2]],
        expected: { num: "0.5493061443340548457" },
      },
    ],
    seeAlso: ["Artanh"],
  },
  {
    name: "Arcsch",
    domain: "Elementary functions",
    signature: "Arcsch(x)",
    summary: "Inverse hyperbolic cosecant, the inverse of Csch.",
    signatures: [
      { call: "Arcsch(x)", description: "the value $y$ with $\\operatorname{csch}(y) = x$." },
    ],
    examples: [
      {
        expr: ["N", ["Arcsch", 2]],
        expected: { num: "0.481211825059603447495" },
      },
    ],
    seeAlso: ["Arsinh"],
  },
  {
    name: "Arsech",
    domain: "Elementary functions",
    signature: "Arsech(x)",
    summary: "Inverse hyperbolic secant, the inverse of Sech.",
    signatures: [
      { call: "Arsech(x)", description: "the value $y$ with $\\operatorname{sech}(y) = x$." },
    ],
    examples: [
      {
        expr: ["N", ["Arsech", ["Rational", 1, 2]]],
        expected: { num: "1.31695789692481670863" },
      },
    ],
    seeAlso: ["Arcosh"],
  },
  {
    name: "Exp",
    domain: "Elementary functions",
    signature: "Exp(x)",
    summary: "The natural exponential function $e^x$.",
    signatures: [{ call: "Exp(x)", description: "$e^x$, the natural exponential of x." }],
    details: [
      "Inverse of [[Ln]]: $\\ln(e^x) = x$ and $e^{\\ln x} = x$ for $x > 0$.",
      "Once the argument is symbolic, compute-engine represents Exp(x) as Power(ExponentialE, x) -- the same object as $e^x$ written with [[Power]].",
      "Applied to a matrix (or any nested list) it broadcasts element-wise -- this is NOT the matrix exponential.",
    ],
    examples: [
      { expr: ["Exp", 0], expected: 1 },
      {
        expr: ["Exp", 1],
        expected: "ExponentialE",
        caption: "Stays the exact constant rather than decimalizing",
      },
      {
        expr: ["Exp", "x"],
        expected: ["Power", "ExponentialE", "x"],
        caption: "compute-engine represents Exp(x) as $e^x$ once the argument is symbolic",
      },
      {
        expr: ["Equal", ["Exp", ["Ln", 5]], 5],
        expected: "True",
        category: "Properties",
        caption: "Inverse of [[Ln]]: $e^{\\ln x} = x$",
      },
      {
        expr: ["Equal", ["Multiply", ["Exp", 2], ["Exp", 3]], ["Exp", 5]],
        expected: "True",
        category: "Properties",
        caption: "$e^a \\, e^b = e^{a+b}$",
      },
      {
        expr: ["Exp", ["List", 0, 1]],
        expected: ["List", 1, "ExponentialE"],
        category: "Applications",
        caption: "Threads element-wise over a list",
      },
      {
        expr: ["Exp", ["List", ["List", 0, 1], ["List", 1, 0]]],
        expected: ["List", ["List", ["Cosh", 1], ["Sinh", 1]], ["List", ["Sinh", 1], ["Cosh", 1]]],
        aspirational: true,
        category: "Scope",
        caption:
          "The true matrix exponential -- here $\\begin{pmatrix}\\cosh 1 & \\sinh 1\\\\ \\sinh 1 & \\cosh 1\\end{pmatrix}$ -- is not yet computed; $\\mathrm{Exp}$ always broadcasts element-wise, giving $\\begin{pmatrix}1 & e\\\\ e & 1\\end{pmatrix}$ instead",
      },
    ],
    seeAlso: ["Ln", "Log", "Sinh"],
  },
  {
    name: "Ln",
    domain: "Elementary functions",
    signature: "Ln(x)",
    summary: "The natural logarithm, the inverse of [[Exp]].",
    signatures: [{ call: "Ln(x)", description: "the natural logarithm of x, base $e$." }],
    details: [
      "Inverse of [[Exp]]: $\\ln(e^x) = x$.",
      "The natural logarithm. Note compute-engine's own [[Log]] is not a synonym: it defaults to base 10 (see that entry).",
      "$\\ln(0) = -\\infty$; a negative real argument leaves the plain evaluation symbolic rather than jumping to a complex value.",
    ],
    examples: [
      { expr: ["Ln", 1], expected: 0 },
      { expr: ["Ln", "ExponentialE"], expected: 1 },
      { expr: ["Ln", 0], expected: "NegativeInfinity" },
      {
        expr: ["Equal", ["Ln", ["Exp", 5]], 5],
        expected: "True",
        category: "Properties",
        caption: "Inverse of [[Exp]]: $\\ln(e^x) = x$",
      },
      {
        expr: ["Equal", ["Add", ["Ln", 2], ["Ln", 3]], ["Ln", 6]],
        expected: "True",
        category: "Properties",
        caption: "Product rule: $\\ln(ab) = \\ln a + \\ln b$",
      },
      {
        expr: ["Ln", -1],
        expected: ["Ln", -1],
        category: "Possible issues",
        caption:
          "A negative real stays symbolic under plain evaluation; N(Ln(-1)) gives the complex value $i\\pi$",
      },
      {
        expr: ["Ln", -1],
        expected: ["Multiply", "ImaginaryUnit", "Pi"],
        aspirational: true,
        category: "Scope",
        caption:
          "$\\mathrm{Ln}(-1)$ should evaluate to the exact principal value $i\\pi$; currently left symbolic, and $N(\\dots)$ gives only a numeric approximation of it",
      },
    ],
    seeAlso: ["Exp", "Log", "Log2"],
  },
  {
    name: "Log",
    domain: "Elementary functions",
    signature: "Log(z, b = 10)",
    summary: "The logarithm of z in base b, defaulting to base 10.",
    signatures: [
      { call: "Log(z)", description: "the base-10 logarithm of z." },
      { call: "Log(z, b)", description: "the logarithm of z in base b." },
    ],
    details: [
      "compute-engine's default base is 10, not $e$: Log(z) means $\\log_{10}(z)$, and [[Ln]] is the natural logarithm.",
      "compute-engine's $\\mathrm{Log}(z, b)$ takes the value first (value, then base) and defaults to base 10 in the one-argument form; for the natural logarithm use [[Ln]].",
      "Product rule: $\\log_b(xy) = \\log_b(x) + \\log_b(y)$. Power rule: $\\log_b(x^k) = k \\log_b(x)$.",
    ],
    examples: [
      { expr: ["Log", 100], expected: 2, caption: "Default base is 10" },
      { expr: ["Log", 100, 10], expected: 2, caption: "Same result written with an explicit base" },
      { expr: ["Log", 8, 2], expected: 3, caption: "Base 2 via the explicit second argument" },
      {
        expr: ["Equal", ["Log", 100], ["Log", 100, 10]],
        expected: "True",
        category: "Properties",
        caption: "Confirms the default base is 10",
      },
      {
        expr: ["Equal", ["Log", ["Multiply", 8, 4], 2], ["Add", ["Log", 8, 2], ["Log", 4, 2]]],
        expected: "True",
        category: "Properties",
        caption: "Product rule: $\\log_b(xy) = \\log_b(x) + \\log_b(y)$",
      },
      {
        expr: ["Equal", ["Log", ["Power", 2, 5], 2], ["Multiply", 5, ["Log", 2, 2]]],
        expected: "True",
        category: "Properties",
        caption: "Power rule: $\\log_b(x^k) = k \\log_b(x)$",
      },
      {
        expr: ["Log", 0],
        expected: "NegativeInfinity",
        category: "Possible issues",
        caption: "$\\log_{10}(0) = -\\infty$",
      },
      {
        expr: ["Log", -5],
        expected: ["Log", -5, 10],
        category: "Possible issues",
        caption:
          "A negative argument stays symbolic, with the default base filled in; wrap in N(...) for the complex value",
      },
    ],
    seeAlso: ["Ln", "Log2", "Log10", "Lb"],
  },
  {
    name: "Log2",
    domain: "Elementary functions",
    signature: "Log2(z)",
    summary: "The base-2 (binary) logarithm of z.",
    signatures: [{ call: "Log2(z)", description: "the base-2 logarithm of z, $\\log_2(z)$." }],
    details: [
      "Equivalent to Log(z, 2), and identical to [[Lb]].",
      "Folds exactly for positive integer powers of 2, but not for exact rational powers less than 1 (e.g. $1/8$) -- only a floating-point argument reduces there.",
    ],
    examples: [
      { expr: ["Log2", 8], expected: 3 },
      { expr: ["Log2", 1], expected: 0 },
      { expr: ["Log2", 1024], expected: 10 },
      {
        expr: ["Equal", ["Log2", 8], ["Log", 8, 2]],
        expected: "True",
        category: "Properties",
        caption: "Same as Log(z, 2)",
      },
      {
        expr: ["Log2", 0.5],
        expected: -1,
        category: "Applications",
        caption: "A float argument folds even for a fractional power of 2",
      },
      {
        expr: ["Log2", ["Rational", 1, 8]],
        expected: ["Log", ["Rational", 1, 8], 2],
        category: "Possible issues",
        caption:
          "The exact rational $1/8 = 2^{-3}$ doesn't reduce; pass 0.125 instead (see Applications)",
      },
    ],
    seeAlso: ["Log", "Log10", "Lb"],
  },
  {
    name: "Log10",
    domain: "Elementary functions",
    signature: "Log10(z)",
    summary: "The base-10 (common) logarithm of z.",
    signatures: [{ call: "Log10(z)", description: "the base-10 logarithm of z, $\\log_{10}(z)$." }],
    details: [
      "Equivalent to Log(z, 10) and to compute-engine's default-base [[Log]](z).",
      "Same fold-only-for-floats limit on fractional exact powers as [[Log2]].",
    ],
    examples: [
      { expr: ["Log10", 1000], expected: 3 },
      { expr: ["Log10", 1], expected: 0 },
      { expr: ["Log10", 100000], expected: 5 },
      {
        expr: ["Equal", ["Log10", 1000], ["Log", 1000]],
        expected: "True",
        category: "Properties",
        caption: "Same as compute-engine's default-base [[Log]]",
      },
      {
        expr: ["Log10", 0.001],
        expected: -3,
        category: "Applications",
        caption: "A float argument folds even for a fractional power of 10",
      },
      {
        expr: ["Log10", ["Rational", 1, 100]],
        expected: ["Log", ["Rational", 1, 100], 10],
        category: "Possible issues",
        caption: "The exact rational $1/100$ doesn't reduce; pass 0.01 instead (see Applications)",
      },
    ],
    seeAlso: ["Log", "Log2", "Lb"],
  },
  {
    name: "Lb",
    domain: "Elementary functions",
    signature: "Lb(z)",
    summary: "The binary logarithm of z, identical to [[Log2]].",
    signatures: [{ call: "Lb(z)", description: "the base-2 logarithm of z, $\\log_2(z)$." }],
    details: [
      'An alias for [[Log2]] -- the "lb" notation is borrowed from information theory and computer science, as opposed to "lg" for base 10.',
      "$\\mathrm{Lb}$ is the binary logarithm, identical to [[Log2]].",
    ],
    examples: [
      { expr: ["Lb", 8], expected: 3 },
      { expr: ["Lb", 1], expected: 0 },
      { expr: ["Lb", 1024], expected: 10 },
      {
        expr: ["Equal", ["Lb", 64], ["Log2", 64]],
        expected: "True",
        category: "Properties",
        caption: "Identical to [[Log2]]",
      },
      {
        expr: ["Lb", ["Rational", 1, 8]],
        expected: ["Log", ["Rational", 1, 8], 2],
        category: "Possible issues",
        caption: "Same exact-rational limit as [[Log2]]: $1/8$ doesn't reduce; pass 0.125 instead",
      },
    ],
    seeAlso: ["Log2", "Log", "Log10"],
  },
];
