-- requires: element_relations, realizer
-- poset_mobius — the zeta/Möbius pair of any registered COVER relation, generated per (collection, rel_id).
--
-- base_element_relation already holds the covers of every poset in the catalog (Π_n refinement, Young's lattice,
-- Tamari, strong/weak Bruhat, dominance, subset inclusion). What it does not give is the ORDER those covers
-- generate, or its Möbius function — and μ is the engine under every inclusion–exclusion the catalog wants to
-- state: the diagram↔orbit change of basis on Π_2k (#331), the characteristic polynomial of a lattice, any
-- "exactly" reconstructed from an "at least".
--
-- Generated per relation rather than written once, because a carrier is a NOMINAL pg composite and forward_fn is
-- typed on it — there is no `anyelement` spelling that dispatches over carriers (the same nominal-typing fact that
-- decided #268). So this file is a codegen finalizer, exactly like the realizer: one typed trio per cover relation.
--
--     <collection>_<rel_id>_le(x, y)        -- x ≤ y in the order the covers generate
--     <collection>_<rel_id>_interval(x, y)  -- SETOF carrier: every z with x ≤ z ≤ y
--     <collection>_<rel_id>_mobius(x, y)    -- μ(x, y), with μ(x,x) = 1 and Σ_{x≤z≤y} μ(x,z) = [x = y]
--
-- GRADED ONLY. The search walks UP from x along covers and stops at the first level containing y, which collects
-- exactly the nodes of depth ≤ depth(y) — correct when every maximal chain in [x,y] has the same length. Every
-- cover relation registered today is graded. A non-graded poset would need a down-cover function to bound the
-- interval from above, which base_element_relation does not carry; such a relation simply must not opt in here.
--
-- Cost is honest rather than clever: the interval is materialized. Fine at the fiber sizes these posets are
-- browsed at (Π_5 is 52, S_4's Bruhat order 24), and `max_nodes` is a hard stop that RAISES rather than silently
-- returning a wrong answer on truncation — a quiet 0 would read as "not comparable", which is a different claim.
--
-- One asymmetry worth knowing, and the reason μ does not call `le`: proving x ≤ y takes a bounded search (y turns
-- up, or the levels run out), but DISPROVING it means exhausting the up-set of x, and that set is infinite when
-- covers cross fibers — every partition of every n sits above ∅ in Young's lattice. So `le` and `interval` can hit
-- max_nodes and raise on such a poset when the answer is "no". `mobius` never does: it closes the interval's own
-- cover edges transitively, and the interval is finite by construction. Bounding `le` in general needs a rank
-- function to stop the walk at rank(y), which base_element_relation does not carry today.

CREATE TABLE base_poset_order (
  collection text NOT NULL,
  rel_id     text NOT NULL,
  le_fn      text NOT NULL,
  interval_fn text NOT NULL,
  mobius_fn  text NOT NULL,
  PRIMARY KEY (collection, rel_id),
  FOREIGN KEY (collection, rel_id) REFERENCES base_element_relation (collection, rel_id));
COMMENT ON TABLE base_poset_order IS
  'The order generated by a cover relation: its ≤ test, its intervals, and its Möbius function. Rows are written '
  'by the base_poset_order_finalize codegen, one per graded cover relation, not by hand.';

-- ── the codegen ───────────────────────────────────────────────────────────────────────────────────────────────
-- PACK-scoped, and it deliberately ignores which pack it was called for: each pass sweeps every cover relation
-- that does not yet have a trio. A collection-scoped finalizer would miss the case that actually bites — a PACK
-- registering a relation on a CORE collection. `permutations` is core, so it finalizes at core's tail, but
-- `permutations-plus` adds strong_bruhat afterwards, and the per-pack pass only revisits collections that pack
-- OWNS. Sweeping the ungenerated remainder is idempotent (the to_regprocedure guard below), cheap (the registry
-- is a handful of rows), and correct whenever a relation lands, whoever owns the collection it hangs off.
-- Relations carrying only a related_fn are skipped: a pair predicate names no successors, so there is nothing to
-- walk (integer_partitions' dominance order is the live example).
CREATE FUNCTION base_poset_order_finalize(p_pack text) RETURNS void LANGUAGE plpgsql AS $fin$
DECLARE
  r        record;
  carrier  text;
  le_fn    text;
  ival_fn  text;
  mob_fn   text;
BEGIN
  FOR r IN SELECT er.*, c.carrier AS carrier FROM base_element_relation er
             JOIN base_collection c ON c.id = er.collection
            WHERE er.kind = 'cover' AND er.forward_fn IS NOT NULL
              AND NOT EXISTS (SELECT 1 FROM base_poset_order po
                               WHERE po.collection = er.collection AND po.rel_id = er.rel_id)
            ORDER BY er.collection, er.rel_id LOOP
    carrier := r.carrier;
    le_fn   := format('%s_%s_le',       r.collection, r.rel_id);
    ival_fn := format('%s_%s_interval', r.collection, r.rel_id);
    mob_fn  := format('%s_%s_mobius',   r.collection, r.rel_id);
    CONTINUE WHEN to_regprocedure(format('%I(%s,%s,integer)', mob_fn, carrier, carrier)) IS NOT NULL;

    -- ── the interval [x,y] ──────────────────────────────────────────────────────────────────────────────────
    -- Level-by-level up-walk from x, stopping at the first level that contains y: for a graded poset that is
    -- every node of depth ≤ depth(y), a superset of [x,y]. Then keep only the nodes from which y is still
    -- reachable along the collected cover edges — that intersection IS the interval.
    EXECUTE format($gen$
      CREATE FUNCTION %I(x %2$s, y %2$s, max_nodes int DEFAULT 20000) RETURNS SETOF %2$s
      LANGUAGE plpgsql IMMUTABLE AS $body$
      DECLARE
        seen %2$s[] := ARRAY[x]; frontier %2$s[] := ARRAY[x]; nextf %2$s[];
        lo %2$s[] := ARRAY[]::%2$s[]; hi %2$s[] := ARRAY[]::%2$s[];   -- cover edges, as parallel arrays
        z %2$s; c %2$s; keep boolean[]; changed boolean; i int; n int;
      BEGIN
        IF x = y THEN RETURN NEXT x; RETURN; END IF;
        WHILE array_length(frontier, 1) > 0 LOOP
          nextf := ARRAY[]::%2$s[];
          FOREACH z IN ARRAY frontier LOOP
            FOR c IN SELECT * FROM %3$I(z) LOOP
              lo := lo || z; hi := hi || c;
              IF NOT (c = ANY(seen)) THEN seen := seen || c; nextf := nextf || c; END IF;
            END LOOP;
          END LOOP;
          IF array_length(seen, 1) > max_nodes THEN
            RAISE EXCEPTION '%1$s: interval search exceeded max_nodes=%% walking up from the lower bound '
                            '(raise max_nodes, or the poset is not graded)', max_nodes;
          END IF;
          EXIT WHEN y = ANY(seen);         -- graded: this level is depth(y), so every node of [x,y] is now seen
          frontier := nextf;
        END LOOP;
        IF NOT (y = ANY(seen)) THEN RETURN; END IF;    -- y is not above x: the interval is empty

        -- reverse-reachability from y along the collected edges (small; iterate to fixpoint)
        n := array_length(seen, 1);
        keep := array_fill(false, ARRAY[n]);
        FOR i IN 1 .. n LOOP IF seen[i] = y THEN keep[i] := true; END IF; END LOOP;
        LOOP
          changed := false;
          FOR i IN 1 .. coalesce(array_length(lo, 1), 0) LOOP
            IF keep[array_position(seen, hi[i])] AND NOT keep[array_position(seen, lo[i])] THEN
              keep[array_position(seen, lo[i])] := true; changed := true;
            END IF;
          END LOOP;
          EXIT WHEN NOT changed;
        END LOOP;
        FOR i IN 1 .. n LOOP IF keep[i] THEN RETURN NEXT seen[i]; END IF; END LOOP;
      END $body$$gen$, ival_fn, carrier, r.forward_fn);

    -- ── x ≤ y ───────────────────────────────────────────────────────────────────────────────────────────────
    EXECUTE format($gen$
      CREATE FUNCTION %I(x %2$s, y %2$s, max_nodes int DEFAULT 20000) RETURNS boolean
      LANGUAGE sql IMMUTABLE AS $body$ SELECT EXISTS (SELECT 1 FROM %3$I(x, y, max_nodes)) $body$$gen$,
      le_fn, carrier, ival_fn);

    -- ── μ(x, y) ─────────────────────────────────────────────────────────────────────────────────────────────
    -- Defined by μ(x,x) = 1 and Σ_{x ≤ z ≤ y} μ(x,z) = 0 for x < y, i.e. μ(x,y) = −Σ_{x ≤ z < y} μ(x,z).
    -- The strict order needed for that sum is built from the cover edges INSIDE the interval and closed
    -- transitively — deliberately not from the generated `le`, whose search is unbounded when its target is not
    -- above its source. On a poset with an infinite up-set (Young's lattice: every partition of every n sits
    -- above ∅) such a call cannot terminate short of the node cap, so μ would raise on perfectly ordinary pairs.
    -- The interval is finite by construction, so closing it is both cheap and total.
    EXECUTE format($gen$
      CREATE FUNCTION %I(x %2$s, y %2$s, max_nodes int DEFAULT 20000) RETURNS numeric
      LANGUAGE plpgsql IMMUTABLE AS $body$
      DECLARE
        zs %2$s[]; mu numeric[]; n int; i int; j int; k int; s numeric; progressed boolean; c %2$s;
        below boolean[];    -- flattened n×n: below[(i-1)*n + j] is "zs[i] < zs[j]" (strictly)
      BEGIN
        IF x = y THEN RETURN 1; END IF;
        zs := ARRAY(SELECT t FROM %3$I(x, y, max_nodes) AS t);   -- `SELECT *` would expand the composite's fields
        n := coalesce(array_length(zs, 1), 0);
        IF n = 0 THEN RETURN 0; END IF;                       -- y is not above x
        below := array_fill(false, ARRAY[n * n]);
        FOR i IN 1 .. n LOOP                                  -- cover edges with both ends inside the interval
          FOR c IN SELECT * FROM %4$I(zs[i]) LOOP
            j := array_position(zs, c);
            IF j IS NOT NULL THEN below[(i - 1) * n + j] := true; END IF;
          END LOOP;
        END LOOP;
        FOR k IN 1 .. n LOOP                                  -- transitive closure; n is an interval, so small
          FOR i IN 1 .. n LOOP
            CONTINUE WHEN NOT below[(i - 1) * n + k];
            FOR j IN 1 .. n LOOP
              IF below[(k - 1) * n + j] THEN below[(i - 1) * n + j] := true; END IF;
            END LOOP;
          END LOOP;
        END LOOP;
        mu := array_fill(NULL::numeric, ARRAY[n]);
        FOR i IN 1 .. n LOOP IF zs[i] = x THEN mu[i] := 1; END IF; END LOOP;
        LOOP
          progressed := false;
          FOR j IN 1 .. n LOOP
            CONTINUE WHEN mu[j] IS NOT NULL;
            s := 0;
            FOR i IN 1 .. n LOOP
              IF below[(i - 1) * n + j] THEN
                IF mu[i] IS NULL THEN s := NULL; EXIT; END IF;
                s := s + mu[i];
              END IF;
            END LOOP;
            IF s IS NOT NULL THEN mu[j] := - s; progressed := true; END IF;
          END LOOP;
          EXIT WHEN NOT progressed;
        END LOOP;
        FOR i IN 1 .. n LOOP IF zs[i] = y THEN RETURN mu[i]; END IF; END LOOP;
        RETURN 0;
      END $body$$gen$, mob_fn, carrier, ival_fn, r.forward_fn);

    INSERT INTO base_poset_order (collection, rel_id, le_fn, interval_fn, mobius_fn)
      VALUES (r.collection, r.rel_id, le_fn, ival_fn, mob_fn)
      ON CONFLICT (collection, rel_id) DO NOTHING;
  END LOOP;
END $fin$;

INSERT INTO base_finalizer (id, fn, description, scope) VALUES
  ('poset_order', 'base_poset_order_finalize',
   'generates the ≤ / interval / Möbius trio for every graded cover relation not yet carrying one', 'pack');

-- ── examples ──────────────────────────────────────────────────────────────────────────────────────────────────
-- Expected values are the classical closed forms, NOT readings taken off this implementation:
--   Boolean lattice 2^[n]:  μ(∅, S) = (−1)^|S|
--   partition lattice Π_n:  μ(0̂, 1̂) = (−1)^(n−1) (n−1)!
-- plus the defining identity Σ_{x ≤ z ≤ y} μ(x,z) = [x = y], which is what makes μ invert ζ at all.
INSERT INTO base_example (suite, title, kind, expected, description, sql) VALUES
  ('poset_mobius','every walkable cover relation gets a trio, whoever owns the collection','eq','true',
   'a floor, not a list — but it must cover the pack-adds-to-a-core-collection case, which a collection-scoped '
   'finalizer silently missed: permutations is core, strong_bruhat arrives later with permutations-plus',$q$
    SELECT (NOT EXISTS (SELECT 1 FROM base_element_relation er
                         WHERE er.kind = 'cover' AND er.forward_fn IS NOT NULL
                           AND NOT EXISTS (SELECT 1 FROM base_poset_order po
                                            WHERE po.collection = er.collection AND po.rel_id = er.rel_id)))::text $q$),

  ('poset_mobius','a relation with no forward_fn is skipped, not failed','eq','true',
   'integer_partitions'' dominance order names only a pair predicate — no successors to walk',$q$
    SELECT (EXISTS (SELECT 1 FROM base_element_relation
                     WHERE collection = 'integer_partitions' AND rel_id = 'dominance' AND forward_fn IS NULL)
        AND NOT EXISTS (SELECT 1 FROM base_poset_order
                         WHERE collection = 'integer_partitions' AND rel_id = 'dominance'))::text $q$),

  ('poset_mobius','strong Bruhat on S_3 is Eulerian: μ(u,w) = (−1)^(ℓ(w)−ℓ(u)), so μ(id,w₀) = −1 and μ(id,231) = +1','eq','-1|1',
   'the order a pack hangs off a core collection — reachable only because the sweep is pack-scoped',$q$
    SELECT permutations_strong_bruhat_mobius(ROW(ARRAY[1,2,3])::permutation, ROW(ARRAY[3,2,1])::permutation)::text
      || '|' || permutations_strong_bruhat_mobius(ROW(ARRAY[1,2,3])::permutation, ROW(ARRAY[2,3,1])::permutation)::text $q$),

  ('poset_mobius','Young''s lattice, across fibers: μ(∅,(1)) = −1, and μ(∅,(1,1)) = 0 because that interval is a chain','eq','-1|0',
   'covers here CROSS fibers, and the up-set of ∅ is INFINITE — μ stays total because it closes the interval''s own '
   'edges rather than asking the unbounded ≤',$q$
    SELECT integer_partitions_young_mobius(ROW(ARRAY[]::int[])::integer_partition, ROW(ARRAY[1])::integer_partition)::text
      || '|' || integer_partitions_young_mobius(ROW(ARRAY[]::int[])::integer_partition, ROW(ARRAY[1,1])::integer_partition)::text $q$),

  ('poset_mobius','Boolean lattice: μ(∅, S) = (−1)^|S| for |S| = 0..3','eq','1,-1,1,-1',
   'the inclusion-exclusion signs, which is what μ on 2^[n] IS',$q$
    SELECT string_agg(subsets_inclusion_mobius(ROW(ARRAY[]::int[], 3)::finset,
                                               ROW(ARRAY(SELECT generate_series(1, k)), 3)::finset)::text, ',' ORDER BY k)
      FROM generate_series(0, 3) k $q$),

  ('poset_mobius','partition lattice Π_n: μ(0̂, 1̂) = (−1)^(n−1)(n−1)! for n = 2,3,4','eq','-1,2,-6',
   'all-singletons up to the one-block partition; the covers merge two blocks',$q$
    SELECT string_agg(set_partitions_refinement_mobius(
             ROW(ARRAY(SELECT generate_series(0, n - 1)))::set_partition,
             ROW(array_fill(0, ARRAY[n]))::set_partition)::text, ',' ORDER BY n)
      FROM generate_series(2, 4) n $q$),

  ('poset_mobius','the defining identity: Σ_{0̂ ≤ z ≤ 1̂} μ(0̂, z) = 0 over Π_4','eq','0',
   'μ inverts ζ exactly when this vanishes off the diagonal',$q$
    SELECT sum(set_partitions_refinement_mobius(ROW(ARRAY[0,1,2,3])::set_partition, z))::text
      FROM set_partitions_refinement_interval(ROW(ARRAY[0,1,2,3])::set_partition,
                                              ROW(ARRAY[0,0,0,0])::set_partition) z $q$),

  ('poset_mobius','μ(x,x) = 1 on the diagonal','eq','1',NULL,$q$
    SELECT set_partitions_refinement_mobius(ROW(ARRAY[0,1,0])::set_partition,
                                            ROW(ARRAY[0,1,0])::set_partition)::text $q$),

  ('poset_mobius','the interval [0̂,1̂] of Π_3 is all 5 of it; [0̂,0̂] is a single point','eq','5|1',
   'Π_3 = B(3) = 5, and a degenerate interval is not empty',$q$
    SELECT (SELECT count(*) FROM set_partitions_refinement_interval(
              ROW(ARRAY[0,1,2])::set_partition, ROW(ARRAY[0,0,0])::set_partition))::text || '|' ||
           (SELECT count(*) FROM set_partitions_refinement_interval(
              ROW(ARRAY[0,1,2])::set_partition, ROW(ARRAY[0,1,2])::set_partition))::text $q$),

  ('poset_mobius','an incomparable pair: μ = 0 and the interval is empty','eq','0|0',
   '{1,2}/{3} and {1,3}/{2} are both one merge above 0̂ — neither is above the other',$q$
    SELECT set_partitions_refinement_mobius(ROW(ARRAY[0,0,1])::set_partition, ROW(ARRAY[0,1,0])::set_partition)::text
        || '|' || (SELECT count(*) FROM set_partitions_refinement_interval(
                     ROW(ARRAY[0,0,1])::set_partition, ROW(ARRAY[0,1,0])::set_partition))::text $q$),

  ('poset_mobius','≤ agrees with the hand-written refinement predicate across all of Π_4 (5² = 225 pairs)','eq','true',
   'the generated order is the order the covers were meant to generate — an independent oracle',$q$
    SELECT bool_and(set_partitions_refinement_le((a).value, (b).value) = set_partition_refines((a).value, (b).value))::text
      FROM elements(set_partitions(4)) a, elements(set_partitions(4)) b $q$),

  ('poset_mobius','μ over the Boolean lattice matches (−1)^|T\S| on every nested pair in 2^[3]','eq','true',
   'not just from ∅ — every interval of 2^[n] is itself a Boolean lattice',$q$
    SELECT bool_and(subsets_inclusion_mobius((a).value, (b).value)
                    = (-1) ^ (cardinality(((b).value).members) - cardinality(((a).value).members)))::text
      FROM elements(subsets(3)) a, elements(subsets(3)) b
     WHERE subsets_inclusion_le((a).value, (b).value) $q$);

