// Hand-maintained (design/speculative/combinatorics-layering-and-plausible.md §4 step 4).
// Carriers with their own combinatorics area live there now — see the imports below — and
// this file keeps only the LEFTOVER carriers: arithmetic values (`GaussianInteger`,
// `ModularResidue`, `RationalNumber`, `Fraction`, the factorizations, `ContinuedFraction`,
// `EgyptianFraction`, `Multicomplex`, `CollatzTrajectory`, `PythagoreanTriple`,
// `SquareDecomposition`, `GoldbachPartition`), tooling records (`FindStatHit`,
// `DistributionMatchHit`) and a notatio type (`GlyphKind`) — step 8 carves these out to the
// arithmetic packages, `statistics`' FindStat tooling, and the notatio side respectively.
//
// This was generated by the now-retired `scripts/extract.ts` from enumeratio's SQL composite
// types (carrier-shapes.txt, no longer checked in). Two quirks worth keeping in mind while
// hand-editing: `binary_tree`'s shape (`integer | list<any>`) and `set_partition` /
// `set_composition`'s (`list<list<integer>>`) are overrides of the SQL storage, not the SQL
// shape itself — see the trees and set-partitions areas for why.

import { COMPOSITIONS_DOMAINS } from "../../compositions/src/domain-data.ts";
import { GRAPHS_DOMAINS } from "../../graphs/src/domain-data.ts";
import { LATTICE_PATHS_DOMAINS } from "../../lattice-paths/src/domain-data.ts";
import { PARTITIONS_DOMAINS } from "../../partitions/src/domain-data.ts";
import { PERMUTATIONS_DOMAINS } from "../../permutations/src/domain-data.ts";
import { SET_PARTITIONS_DOMAINS } from "../../set-partitions/src/domain-data.ts";
import { TABLEAUX_DOMAINS } from "../../tableaux/src/domain-data.ts";
import { TREES_DOMAINS } from "../../trees/src/domain-data.ts";
import { WORDS_DOMAINS } from "../../words/src/domain-data.ts";
import type { Domain } from "./types.ts";

/** Carriers with no combinatorics area of their own (yet) — see the file comment. */
export const LEFTOVER_DOMAINS: readonly Domain[] = [
  {
    name: "CollatzTrajectory",
    type: "collatz_trajectory",
    shape: "list<integer>",
    id: "collatz_trajectory",
    plural: "CollatzTrajectories",
  },
  {
    name: "ContinuedFraction",
    type: "continued_fraction",
    shape: "list<integer>",
    id: "continued_fraction",
  },
  {
    name: "DistributionMatchHit",
    type: "distribution_match_hit",
    shape: "tuple<string, string, list<string>, number, number>",
    id: "distribution_match_hit",
    plural: "DistributionMatchHits",
  },
  {
    name: "EgyptianFraction",
    type: "egyptian_fraction",
    shape: "list<integer>",
    id: "egyptian_fraction",
    plural: "EgyptianFractions",
  },
  {
    name: "Factorization",
    type: "factorization",
    shape: "tuple<list<number>, list<integer>>",
    id: "factorization",
    plural: "Factorizations",
  },
  {
    name: "FindStatHit",
    type: "find_stat_hit",
    shape: "tuple<string, string, list<string>, number, number>",
    id: "find_stat_hit",
    plural: "FindStatHits",
  },
  {
    name: "Fraction",
    type: "fraction",
    shape: "tuple<number, number>",
    id: "fraction",
    plural: "Fractions",
  },
  {
    name: "FractionalNumber",
    type: "fractional_number",
    shape: "tuple<integer, integer>",
    id: "fractional_number",
    plural: "FractionalNumbers",
  },
  {
    name: "GaussianFractional",
    type: "gaussian_fractional",
    shape: "tuple<fractional_number, fractional_number>",
    id: "gaussian_fractional",
    plural: "GaussianFractionals",
  },
  {
    name: "GaussianInteger",
    type: "gaussian_integer",
    shape: "tuple<integer, integer>",
    id: "gaussian_integer",
    plural: "GaussianIntegers",
  },
  {
    name: "GaussianRational",
    type: "gaussian_rational",
    shape: "tuple<rational_number, rational_number>",
    id: "gaussian_rational",
    plural: "GaussianRationals",
  },
  {
    name: "GlyphKind",
    type: "glyph_kind",
    shape: "tuple<string, string>",
    id: "glyph_kind",
    plural: "GlyphKinds",
  },
  {
    name: "GoldbachPartition",
    type: "goldbach_partition",
    shape: "tuple<integer, integer>",
    id: "goldbach_partition",
    plural: "GoldbachPartitions",
  },
  {
    name: "IntegerFactorization",
    type: "integer_factorization",
    shape: "tuple<boolean, list<number>, list<integer>>",
    id: "integer_factorization",
    plural: "IntegerFactorizations",
  },
  {
    name: "ModularResidue",
    type: "modular_residue",
    shape: "tuple<integer, integer>",
    id: "modular_residue",
    plural: "ModularResidues",
  },
  {
    name: "Multicomplex",
    type: "multicomplex",
    shape: "tuple<list<integer>, integer>",
    id: "multicomplex",
    plural: "Multicomplexes",
  },
  {
    name: "PythagoreanTriple",
    type: "pythagorean_triple",
    shape: "tuple<integer, integer, integer>",
    id: "pythagorean_triple",
    plural: "PythagoreanTriples",
  },
  {
    name: "RationalNumber",
    type: "rational_number",
    shape: "tuple<integer, integer>",
    id: "rational_number",
    plural: "RationalNumbers",
  },
  {
    name: "SquareDecomposition",
    type: "square_decomposition",
    shape: "tuple<number, number>",
    id: "square_decomposition",
    plural: "SquareDecompositions",
  },
];

/** Every carrier domain: the areas' own data, plus the leftover carriers above. */
export const DOMAINS: readonly Domain[] = [
  ...PERMUTATIONS_DOMAINS,
  ...PARTITIONS_DOMAINS,
  ...COMPOSITIONS_DOMAINS,
  ...WORDS_DOMAINS,
  ...LATTICE_PATHS_DOMAINS,
  ...TREES_DOMAINS,
  ...SET_PARTITIONS_DOMAINS,
  ...TABLEAUX_DOMAINS,
  ...GRAPHS_DOMAINS,
  ...LEFTOVER_DOMAINS,
];
