// GENERATED by packages/reference/scripts/collect-summaries.ts — do not edit by hand.
//
// What this package's `ce.declare` calls read for `description` (symbol-metadata step 6,
// design/speculative/symbol-metadata.md): each head's record `summary`, one source instead
// of two. Regenerate with:
//
//   vp node packages/reference/scripts/collect-summaries.ts

export const SUMMARIES: Readonly<Record<string, string>> = {
  DivisorSum:
    "The sum of $f(d)$ over the positive divisors $d$ of $n$, optionally only those where $\\mathrm{cond}(d)$ holds.",
  EulerE: "The Euler numbers $E_n$ and Euler polynomials $E_n(x)$.",
  FrobeniusNumber: "The largest integer that is not a non-negative integer combination of the given positive integers.",
  FrobeniusSolve: "All non-negative integer solutions $x$ of $a\\cdot x = b$, lexicographically.",
  HermiteDecomposition:
    "$\\{u, h\\}$ with $u$ unimodular and $u \\cdot m = h$ upper triangular in Hermite normal form.",
  IntegerExponent: "The largest $k$ with $b^k \\mid n$ — the $b$-adic valuation of $n$ as an integer.",
  IsCoprime: "Tests whether the arguments are pairwise relatively prime.",
  IsPrimePower: "Tests whether $n$ is a positive integer power of a single prime.",
  LiouvilleLambda: "The Liouville function $\\lambda(n)=(-1)^{\\Omega(n)}$.",
  MangoldtLambda: "The von Mangoldt function: $\\ln p$ if $n$ is a power of the prime $p$, else 0.",
  MersennePrimeExponent: "The exponent $p$ of the $n$th Mersenne prime $2^p-1$.",
  PartitionsQ: "The number $q(n)$ of partitions of $n$ into distinct parts.",
  PerfectNumber: "The $n$th perfect number.",
  PowersRepresentations: "The ways to write $n$ as a sum of $k$ non-negative $p$th powers, as non-decreasing lists.",
  Quotient: "The integer quotient of $m$ by $n$ — for Gaussian integers, $m/n$ rounded to the nearest lattice point.",
  RamanujanTau:
    "Ramanujan's tau function: the coefficients of the discriminant modular form $\\Delta(q) = q\\prod_{k\\ge1}(1-q^k)^{24}$.",
  RationalReconstruction:
    "The small fraction $n/d$ whose image in $\\mathbb{Z}/m$ is $a$ — the inverse of reading $n/d$ as $n \\cdot d^{-1} \\bmod m$.",
  SquaresR: "The number of ways to write $n$ as a sum of $d$ squares, counting signs and order.",
};
