// Ask a Wolfram kernel for its entire `System`` symbol table, and rewrite
// `src/system-names.ts`.
//
// Committed because the interesting question is not "what does Wolfram call this" — that is
// a lookup — but "does Wolfram already use this name, and for what". That question has to be
// answerable in CI, on a machine with no kernel, every time a head is added. Without the
// table a collision is found by a person reading the docs; with it, a test finds it.
//
// Rerun when the baseline kernel version moves:
//
//   vp node packages/wolfram/scripts/collect-system-names.ts

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";

const code = 'Print[StringRiffle[Names["System`*"], "\\n"]]; Print["$Version=", $Version]';
const out = execFileSync("wolframscript", ["-code", code], {
  encoding: "utf8",
  timeout: 600_000,
  maxBuffer: 64 * 1024 * 1024,
});

const lines = out.split("\n").map((line) => line.trim());
const version = lines.find((line) => line.startsWith("$Version="))?.slice("$Version=".length);
const names = lines.filter((line) => /^[A-Za-z$][A-Za-z0-9$]*$/.test(line)).sort();
if (names.length < 5000) throw new Error(`only ${names.length} names — did the kernel run?`);

const source = `// GENERATED by scripts/collect-system-names.ts — do not edit by hand.
//
// Every symbol in Wolfram's \`System\`\` context, from ${version ?? "an unrecorded kernel"}.
//
// This is here to be asked "is this name taken, and by what" without a kernel. A head of
// ours that shares a name with one of these is either the SAME function — in which case it
// belongs in \`HEADS\` and the transpiler vouches for it — or a different one, in which case
// it belongs in \`FOREIGN\` and emits into our own context. Falling through by name is the
// third option and it is always wrong; \`tests/alignment.test.ts\` is what says so.

/** ${names.length} symbols. */
export const SYSTEM_NAMES: readonly string[] = ${JSON.stringify(names, null, 2)};

/** Whether Wolfram's \`System\`\` context already defines \`name\`. */
export const isSystemName = (name: string): boolean => SYSTEM_NAME_SET.has(name);

const SYSTEM_NAME_SET = new Set(SYSTEM_NAMES);
`;

writeFileSync(new URL("../src/system-names.ts", import.meta.url), source);
process.stdout.write(`system-names.ts — ${names.length} symbols from ${version ?? "?"}\n`);
