// GENERATED by scripts/audit-head-map.ts — do not edit by hand.
//
// The warning in design/roadmap.md §1 generalized: every head in the wolfram head map
// (packages/wolfram/src/to-wolfram.ts `HEADS`) that the transpiler will happily emit, but
// that the engine either does not declare at all (`undeclared`) or does not actually
// produce an answer for a representative sample on any of its overload arms
// (`unevaluated`). Regenerate with:
//
//   vp node packages/census/scripts/audit-head-map.ts
//
// An `unevaluated` entry with no `sample` means no arm of the signature gave anything
// concrete to check — unverified, not cleared, so its absence from this list is not a claim
// the head works. Only `undeclared` is guarded by a test (tests/head-map-audit.test.ts);
// `unevaluated` is read-only for now — a passing sample is not proof a head is right for
// every shape it takes, and a failing one deserves a human look before it blocks anything.

export type AuditCategory = "undeclared" | "unevaluated";

export interface AuditEntry {
  readonly head: string;
  readonly category: AuditCategory;
  readonly sample?: string;
  readonly reason: string;
}

export const HEAD_MAP_AUDIT: readonly AuditEntry[] = [
  {
    head: "VerificationTest",
    category: "unevaluated",
    reason:
      'signature "(any*) -> any" gives no arm with a derivable sample — unverified, not cleared',
  },
];
