// Compile every map's Epsil definition (its body, and its guard where it has one) to JavaScript
// ahead of time, with compute-engine's own compiler, into src/compiled-maps.generated.js. Each
// entry carries the hash of the definition it came from: at run time an entry is used only while
// its hash matches, so an edited map is compiled on first use (or interpreted) until this is
// rerun. Maps the compiler can't take yet are left out.
//
//   vp node packages/symbols/combinatorics/combinatorics/scripts/compile-maps.ts

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { ComputeEngine } from "@cortex-js/compute-engine";
import { compileTyped, definitionHash } from "@enumeratio/engine/compiled";
import { CARRIERS } from "../src/carriers.ts";
import { MAPS } from "../src/maps.ts";

interface Entry {
  readonly key: string;
  readonly hash: string;
  readonly body: string;
  readonly guard?: string;
}

/** Each compilable map's key (`Name@from`), hash and generated code. */
export function compiledMaps(): Entry[] {
  const ce = new ComputeEngine();
  const shapeOf = new Map(CARRIERS.map((carrier) => [carrier.type, carrier.shape]));
  const out: Entry[] = [];
  for (const map of MAPS) {
    if (map.body === undefined) continue;
    const from = shapeOf.get(map.from);
    const to = shapeOf.get(map.to);
    if (from === undefined || to === undefined) continue;
    const body = compileTyped(ce, map.body, { _raw: from });
    if (body === undefined) continue;
    const guard = map.guard === undefined ? undefined : compileTyped(ce, map.guard, { _raw: from, _image: to });
    if (map.guard !== undefined && guard === undefined) continue;
    out.push({
      key: `${map.name}@${map.from}`,
      hash: definitionHash({ body: map.body, guard: map.guard }),
      body: body.code,
      ...(guard === undefined ? {} : { guard: guard.code }),
    });
  }
  return out.toSorted((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));
}

function render(entries: readonly Entry[]): string {
  const body = entries
    .map((e) =>
      [
        `  ${JSON.stringify(e.key)}: {`,
        `    hash: ${JSON.stringify(e.hash)},`,
        `    run: (_SYS, _) => ${e.body},`,
        ...(e.guard === undefined ? [] : [`    guard: (_SYS, _) => ${e.guard},`]),
        "  },",
      ].join("\n"),
    )
    .join("\n");
  return `// GENERATED by scripts/compile-maps.ts from the maps' Epsil definitions, by compute-engine's
// JavaScript compiler. Do not edit: rerun the script. Each entry is used only while \`hash\`
// matches its definition; see src/compiled.ts.
// A definition that ignores its argument compiles to code that never reads it.
/* eslint-disable no-unused-vars */

export const COMPILED_MAPS = {
${body}
};
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const entries = compiledMaps();
  const target = fileURLToPath(new URL("../src/compiled-maps.generated.js", import.meta.url));
  writeFileSync(target, render(entries));
  // Laid out as `vp fmt` lays it out, so a rerun with nothing changed changes nothing.
  execFileSync("vp", ["fmt", target], { stdio: "ignore" });
  console.log(`${entries.length} of ${MAPS.filter((m) => m.body !== undefined).length} map definitions compiled`);
}
