// Compile every Epsil family's definitions (count, unrank, rank, valid) to JavaScript ahead of
// time, with compute-engine's own compiler, into
// collections/src/families/compiled-families.generated.js. Each entry carries the hash of the
// definitions it came from: at run time it is used only while the hash matches, so an edited
// family is compiled on first use until this is rerun. Operations the compiler can't take yet
// are left out, and interpreted.
//
//   vp node packages/symbols/combinatorics/combinatorics/scripts/compile-families.ts

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { ComputeEngine } from "@cortex-js/compute-engine";
import { compileTyped } from "@enumeratio/engine/compiled";
import {
  type EpsilFamily,
  familyHash,
  isEpsilFamily,
  OPERATIONS,
  type Operation,
  operationTypes,
} from "../collections/src/families/epsil.ts";
import { allFamilies } from "../collections/src/families/index.ts";

interface Entry {
  readonly head: string;
  readonly hash: string;
  readonly code: Partial<Record<Operation, string>>;
}

/** Each Epsil family's head, hash and the generated code of the operations that compile. */
export function compiledFamilies(): Entry[] {
  const ce = new ComputeEngine();
  const out: Entry[] = [];
  for (const family of allFamilies.filter(isEpsilFamily) as EpsilFamily[]) {
    const code: Partial<Record<Operation, string>> = {};
    for (const operation of OPERATIONS) {
      const types = operationTypes(family, operation);
      const compiled = types === undefined ? undefined : compileTyped(ce, family.epsil[operation], types);
      if (compiled !== undefined) code[operation] = compiled.code;
    }
    out.push({ head: family.head, hash: familyHash(family), code });
  }
  return out.toSorted((a, b) => (a.head < b.head ? -1 : a.head > b.head ? 1 : 0));
}

function render(entries: readonly Entry[]): string {
  const body = entries
    .map((e) =>
      [
        `  ${e.head}: {`,
        `    hash: ${JSON.stringify(e.hash)},`,
        ...OPERATIONS.flatMap((operation) =>
          e.code[operation] === undefined ? [] : [`    ${operation}: (_SYS, _) => ${e.code[operation]},`],
        ),
        "  },",
      ].join("\n"),
    )
    .join("\n");
  return `// GENERATED by scripts/compile-families.ts from the families' Epsil definitions, by
// compute-engine's JavaScript compiler. Do not edit: rerun the script. Each entry is used only
// while \`hash\` matches its definitions; see ./epsil.ts.
// A definition that ignores one of its inputs compiles to code that never reads it.
/* eslint-disable no-unused-vars */

export const COMPILED_FAMILIES = {
${body}
};
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const entries = compiledFamilies();
  const target = fileURLToPath(new URL("../collections/src/families/compiled-families.generated.js", import.meta.url));
  writeFileSync(target, render(entries));
  // Laid out as `vp fmt` lays it out, so a rerun with nothing changed changes nothing.
  execFileSync("vp", ["fmt", target], { stdio: "ignore" });
  const operations = entries.reduce((sum, e) => sum + Object.keys(e.code).length, 0);
  console.log(`${operations} of ${entries.length * OPERATIONS.length} family operations compiled`);
}
