// Compile every map's Epsil definition (its body, and its guard where it has one) to JavaScript
// ahead of time, with compute-engine's own compiler, into src/compiled-maps.generated.js. Each
// entry carries the hash of the definition it came from: at run time an entry is used only while
// its hash matches, so an edited map is compiled on first use (or interpreted) until this is
// rerun. Maps the compiler can't take yet are left out; a map whose compiled code answers
// differently from the interpreter on small elements of its source carrier is listed as
// `interpreted`, so it isn't compiled on first use either.
//
//   vp node packages/symbols/combinatorics/combinatorics/scripts/compile-maps.ts

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import type { Engine } from "@enumeratio/engine";
import { bareEngine } from "@enumeratio/engine/testing";
import { compileTyped, definitionHash, fromJs, toJs } from "@enumeratio/engine/compiled";
import { CARRIERS } from "../src/carriers.ts";
import { evaluateDefinition, MAPS } from "../src/maps.ts";
import { smallElements } from "./samples.ts";

interface Entry {
  readonly key: string;
  readonly hash: string;
  readonly body?: string;
  readonly guard?: string;
}

type Run = (vars: Record<string, unknown>) => unknown;

/** Whether the compiled body (and guard) give the interpreter's answer on every subject the
 *  compiled code answers at all: the same image, or a decline where the guard declines. */
function agrees(
  ce: Engine,
  map: (typeof MAPS)[number],
  body: Run,
  guard: Run | undefined,
  subjects: readonly unknown[],
): boolean {
  for (const subject of subjects) {
    const raw = toJs(subject);
    if (raw === undefined) continue;
    let answer;
    try {
      const image = body({ _raw: raw });
      answer = fromJs(image);
      if (answer !== undefined && guard !== undefined && guard({ _raw: raw, _image: image }) !== true) answer = null;
    } catch {
      continue;
    }
    if (answer === undefined) continue;
    const expected = evaluateDefinition(ce, map, subject) ?? null;
    if (JSON.stringify(answer) !== JSON.stringify(expected)) return false;
  }
  return true;
}

/** Each compilable map's key (`Name@from`), hash and generated code; no code for a map whose
 *  compiled code disagreed with the interpreter. */
export function compiledMaps(): Entry[] {
  const ce = bareEngine();
  const carrierOf = new Map(CARRIERS.map((carrier) => [carrier.type, carrier]));
  const out: Entry[] = [];
  for (const map of MAPS) {
    if (map.body === undefined) continue;
    const from = carrierOf.get(map.from);
    const to = carrierOf.get(map.to);
    if (from === undefined || to === undefined) continue;
    const body = compileTyped(ce, map.body, { _raw: from.shape });
    if (body === undefined) continue;
    const guard =
      map.guard === undefined ? undefined : compileTyped(ce, map.guard, { _raw: from.shape, _image: to.shape });
    if (map.guard !== undefined && guard === undefined) continue;
    const key = `${map.name}@${map.from}`;
    const hash = definitionHash({ body: map.body, guard: map.guard });
    if (!agrees(ce, map, body.run, guard?.run, smallElements(ce, from.name))) {
      out.push({ key, hash });
      continue;
    }
    out.push({ key, hash, body: body.code, ...(guard === undefined ? {} : { guard: guard.code }) });
  }
  return out.toSorted((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));
}

function render(entries: readonly Entry[]): string {
  const body = entries
    .map((e) =>
      [
        `  ${JSON.stringify(e.key)}: {`,
        `    hash: ${JSON.stringify(e.hash)},`,
        e.body === undefined ? "    interpreted: true," : `    run: (_SYS, _) => ${e.body},`,
        ...(e.guard === undefined ? [] : [`    guard: (_SYS, _) => ${e.guard},`]),
        "  },",
      ].join("\n"),
    )
    .join("\n");
  return `// GENERATED by scripts/compile-maps.ts from the maps' Epsil definitions, by compute-engine's
// JavaScript compiler. Do not edit: rerun the script. Each entry is used only while \`hash\`
// matches its definition; see src/compiled.ts.
// A definition that ignores its argument compiles to code that never reads it.
/* eslint-disable no-unused-vars, unicorn/no-useless-spread */

export const COMPILED_MAPS = {
${body}
};
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const entries = compiledMaps();
  const target = fileURLToPath(new URL("../src/compiled-maps.generated.js", import.meta.url));
  writeFileSync(target, render(entries));
  // Laid out as `vp fmt` lays it out, so a rerun with nothing changed changes nothing.
  execFileSync("vp", ["fmt", target], { stdio: "ignore" });
  const compiled = entries.filter((e) => e.body !== undefined);
  console.log(`${compiled.length} of ${MAPS.filter((m) => m.body !== undefined).length} map definitions compiled`);
  for (const e of entries.filter((entry) => entry.body === undefined))
    console.log(`${e.key}: compiled code disagreed with the interpreter; left interpreted`);
}
