// Every map's laws, read off its record's `laws:` front matter (@enumeratio/entry/node's
// strict reader) and written to src/maps-laws.generated.ts (step 6c part 2, design §6): the
// record is the source of truth, this is only how the runtime gets it without parsing YAML.
// `src/maps.ts` merges this onto each area's own map data by `${name}@${from}` when it builds
// `MAPS` — see that file.
//
// `Permutation` (cycle_decomposition -> permutation) has no `reference/Permutation/` record (a
// pre-existing gap this migration didn't fill), so it keeps its one law inline in
// `permutations/src/maps.ts` instead of going through here — skipped below for that reason,
// not carelessly.
//
//   vp node packages/symbols/combinatorics/combinatorics/scripts/generate-map-laws.ts

import { fileURLToPath } from "node:url";
import { type EntryLaw, lawsFor } from "@enumeratio/entry";
import { readEntry, writeFormatted } from "@enumeratio/entry/node";
import type { Law } from "@enumeratio/structures";
import { COMPOSITIONS_MAPS } from "../compositions/src/maps.ts";
import { LATTICE_PATHS_MAPS } from "../lattice-paths/src/maps.ts";
import { PERMUTATIONS_MAPS } from "../permutations/src/maps.ts";
import { SET_PARTITIONS_MAPS } from "../set-partitions/src/maps.ts";
import { TREES_MAPS } from "../trees/src/maps.ts";
import { WORDS_MAPS } from "../words/src/maps.ts";

const MAPS = [
  ...PERMUTATIONS_MAPS,
  ...TREES_MAPS,
  ...LATTICE_PATHS_MAPS,
  ...SET_PARTITIONS_MAPS,
  ...COMPOSITIONS_MAPS,
  ...WORDS_MAPS,
];

const REFERENCE_DIR = fileURLToPath(new URL("../reference/", import.meta.url));

export interface MapLaws {
  readonly laws?: readonly Law[];
  readonly orderIsomorphism?: { readonly from: string; readonly to: string; readonly sizeOffset?: number };
}

/** `entry`'s laws, in structures' `Law` shape (`on` stripped, `orderIsomorphism` split out). */
function toMapLaws(entryLaws: readonly EntryLaw[]): MapLaws {
  const laws: Law[] = [];
  let orderIsomorphism: MapLaws["orderIsomorphism"];
  for (const law of entryLaws) {
    if (typeof law === "string") laws.push(law);
    else if ("inverse" in law) laws.push({ inverse: law.inverse });
    else orderIsomorphism = law.orderIsomorphism;
  }
  return { ...(laws.length > 0 ? { laws } : {}), ...(orderIsomorphism === undefined ? {} : { orderIsomorphism }) };
}

/** Every map's laws by `${name}@${from}`, for the maps whose record has a `laws:` list. */
export function mapLaws(): Map<string, MapLaws> {
  const out = new Map<string, MapLaws>();
  for (const map of MAPS) {
    if (map.name === "Permutation") continue; // no record -- see file comment.
    const entry = readEntry(REFERENCE_DIR, map.name);
    const forThisOverload = lawsFor(entry.laws, map.from);
    if (forThisOverload.length === 0) continue;
    out.set(`${map.name}@${map.from}`, toMapLaws(forThisOverload));
  }
  return out;
}

function render(entries: ReadonlyMap<string, MapLaws>): string {
  const body = [...entries]
    .toSorted(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([key, value]) => `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`)
    .join("\n");
  return `// GENERATED by scripts/generate-map-laws.ts from each map's own record (reference/<Name>/
// index.md's \`laws:\`). Do not edit: rerun the script after changing a record's laws.
import type { Law } from "@enumeratio/structures";

export interface MapLaws {
  readonly laws?: readonly Law[];
  readonly orderIsomorphism?: { readonly from: string; readonly to: string; readonly sizeOffset?: number };
}

export const MAP_LAWS: Readonly<Record<string, MapLaws>> = {
${body}
};
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const entries = mapLaws();
  const target = new URL("../src/maps-laws.generated.ts", import.meta.url);
  await writeFormatted(target, render(entries));
  console.log(`${entries.size} maps' laws written`);
}
