// GENERATED by packages/reference/scripts/collect-summaries.ts — do not edit by hand.
//
// What this package's `ce.declare` calls read for `description` (symbol-metadata step 6,
// design/speculative/symbol-metadata.md): each head's record `summary`, one source instead
// of two. Regenerate with:
//
//   vp node packages/reference/scripts/collect-summaries.ts

export const SUMMARIES: Readonly<Record<string, string>> = {
  DifferenceDelta: "f(n+1) - f(n), simplified -- the forward difference of a sequence.",
  DiscreteRatio: "The ratio $f(n+1)/f(n)$ between consecutive terms of a sequence, simplified.",
  ExponentialGeneratingFunction:
    "The exponential generating function $\\sum_n \\mathrm{expr}(n)\\,x^n/n!$ of a sequence, in closed form, when one exists.",
  FindSequenceFunction:
    "A closed form $a(n)$ for a sequence given as a list $a(0), a(1), \\dots$, when one can be found.",
  GeneratingFunction:
    "The ordinary generating function $\\sum_n \\mathrm{expr}(n)\\,x^n$ of a sequence, in closed form, when one exists.",
};
