// GENERATED by @enumeratio/notatio/generate from the element sources -- do not edit.
import { defineComponent, h } from "vue";

/** Only what the page set, and a boolean only when true: the element keeps its own defaults. */
function bound(props: Record<string, unknown>, fixed: Record<string, string>): Record<string, unknown> {
  const out: Record<string, unknown> = { ...fixed };
  for (const [k, v] of Object.entries(props)) {
    if (v === undefined || v === null || v === false) continue;
    out[k] = v;
  }
  return out;
}

/** `<Animator>` is `<notatio-animator>`: props are the element's attributes, typed. */
export const Animator = defineComponent({
  name: "Animator",
  props: {
    /** The binding this slider drives: `name="a"` fills the wildcard `_a`. */
    name: { type: String, required: false },
    /** The starting value. */
    value: { type: String, required: false },
    /** Lowest value. Defaults to a symmetric range around the start. */
    min: { type: Number, required: false },
    /** Highest value. */
    max: { type: Number, required: false },
    /** How much one step moves the value; also fixes the printed places. */
    step: { type: Number, required: false },
    /** `x` (default) lies flat; `y` stands the slider up. */
    axis: { type: String, required: false },
    /** Show the value beside the track. */
    readout: { type: Boolean, required: false },
    /** Show a play/pause button. Space on the focused thumb toggles playback regardless. */
    play: { type: Boolean, required: false },
    /** Sweep while scrolled into view; pause when scrolled out. */
    autoplay: { type: Boolean, required: false },
    /** Milliseconds per playback step. Defaults to a whole sweep in a few seconds. */
    interval: { type: Number, required: false },
    /** Playback speed as a multiplier on `interval`. */
    rate: { type: Number, required: false },
    /** What an iteration does at the ends: `cycle`, `reflect` or `none` (default). */
    loop: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-animator", bound(props, {}), slots.default?.());
  },
});

/** `<BarChart3D>` is `<notatio-bar-chart-3d>`: props are the element's attributes, typed. */
export const BarChart3D = defineComponent({
  name: "BarChart3D",
  props: {
    data: { type: String, required: false },
    azimuth: { type: Number, required: false },
    elevation: { type: Number, required: false },
    zoom: { type: Number, required: false },
    gap: { type: Number, required: false },
    axes: { type: String, required: false },
    zrange: { type: String, required: false },
    rowLabels: { type: String, required: false },
    colLabels: { type: String, required: false },
    label: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-bar-chart-3d", bound(props, {}), slots.default?.());
  },
});

/** `<Cell>` is `<notatio-cell>`: props are the element's attributes, typed. */
export const Cell = defineComponent({
  name: "Cell",
  props: {
    /** The initial input, in the syntax `format` names. */
    value: { type: String, required: false },
    /** The syntax `value` is written in. */
    format: { type: String, required: false },
    /** Which editor shows the In row; its menu can switch this live. */
    inForm: { type: String, required: false },
    /** The representation the Out shows; its own menu changes this live. */
    outForm: { type: String, required: false },
    /** Evaluate the input rather than only boxing it. On by default. */
    evaluate: { type: Boolean, required: false },
    /** Box the input without evaluating, so a source Out form shows the expression itself. */
    box: { type: Boolean, required: false },
    /** A MathJSON value to assert the Out against, while the cell is clean. */
    expect: { type: String, required: false },
    /** Mark an `expect` mismatch as a known gap, while the cell is clean. */
    planned: { type: Boolean, required: false },
    /** Forwarded to the Out: a preset its picture reduces for, else the page's own. */
    env: { type: String, required: false },
    /** Forwarded to the Out: describe a long `List` result rather than typeset it. */
    elideAbove: { type: Number, required: false },
    /** Forwarded to the Out: also report the substituted-but-unevaluated input. */
    plot: { type: Boolean, required: false },
    /** Pin the `standard` editor to a binding, forwarded to `<notatio-in>`: the symbol name and its `\coloneq` become fixed chrome, and only the value can be edited. A page *about* p keeps a p bound to something, whatever the reader types into it. */
    bind: { type: String, required: false },
    /** The domain asserted for `bind` (`integer`, `real`, `complex`, ...); see `notatio-in`. */
    domain: { type: String, required: false },
    /** Set once the reader has made an edit; reflected so a stylesheet can key on it. */
    dirty: { type: Boolean, required: false },
    /** Set while an edit is held back waiting for commit (inside a transcript, the `standard` editor between a keystroke and the next Enter/blur); reflected so a stylesheet can dim the now-stale Out. */
    pending: { type: Boolean, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-cell", bound(props, {}), slots.default?.());
  },
});

/** `<Chart>` is `<notatio-chart>`: props are the element's attributes, typed. */
export const Chart = defineComponent({
  name: "Chart",
  props: {
    /** Which chart: `bar`, `histogram`, `pie`, `box`, `array`, `discrete`, `list` or `listline` -- or `auto` (the default), chosen from the data's shape (`chooseChartType`). */
    type: { type: String, required: false },
    /** The values, as JSON — a number list, or `[x,y]` pairs where the chart takes points. */
    data: { type: String, required: false },
    /** A JSON list of category labels, where the chart shows them. */
    labels: { type: String, required: false },
    /** Histogram bin count; empty chooses one from the data. */
    bins: { type: Number, required: false },
    /** Caption drawn above the chart. */
    label: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-chart", bound(props, {}), slots.default?.());
  },
});

/** `<Checkbox>` is `<notatio-checkbox>`: props are the element's attributes, typed. */
export const Checkbox = defineComponent({
  name: "Checkbox",
  props: {
    /** The binding this box drives: `name="a"` fills the wildcard `_a`. */
    name: { type: String, required: false },
    /** `True` or `False` at first. */
    value: { type: String, required: false },
    /** A label drawn beside the box. */
    label: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-checkbox", bound(props, {}), slots.default?.());
  },
});

/** `<Clock>` is `<notatio-clock>`: props are the element's attributes, typed. */
export const Clock = defineComponent({
  name: "Clock",
  props: {
    /** Seconds per cycle. */
    period: { type: Number, required: false },
    /** Hide the scrubber, leaving just the play button. */
    compact: { type: String, required: false },
    label: { type: String, required: false },
    /** What the end of a cycle does: `cycle` (default), `reflect` or `none`. */
    loop: { type: String, required: false },
    /** Speed, as a multiplier on real time. */
    rate: { type: Number, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-clock", bound(props, {}), slots.default?.());
  },
});

/** `<Code>` is `<notatio-code>`: props are the element's attributes, typed. */
export const Code = defineComponent({
  name: "Code",
  props: {
    /** Syntax highlighting to apply, e.g. `wolfram`, `python`, `javascript`, `glsl`, `wgsl`. */
    language: { type: String, required: false },
    /** The source text. Editable unless `readonly`. */
    value: { type: String, required: false },
    /** Show the code without allowing edits. */
    readonly: { type: Boolean, required: false },
    /** Visible height, in lines. */
    rows: { type: Number, required: false },
    /** Hide the corner language tag, when the form is already indicated elsewhere. */
    hideLang: { type: Boolean, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-code", bound(props, {}), slots.default?.());
  },
});

/** `<CollectionTable>` is `<notatio-collection-table>`: props are the element's attributes, typed. */
export const CollectionTable = defineComponent({
  name: "CollectionTable",
  props: {
    /** The collection to enumerate, in Epsil: `Subsets(4)`, `SymmetricGroup(5)`. */
    expr: { type: String, required: false },
    /** Statistic columns, comma-separated. A bare head applies to the row (`Descents` means `Descents(_)`); anything else is an expression over `_`. */
    columns: { type: String, required: false },
    /** A predicate over the row `_`, e.g. `FixedPoints(_) == 0`. Empty for no filter. */
    filter: { type: String, required: false },
    /** The column (as written in `columns`) the rows are ordered by. Empty for index order. */
    sort: { type: String, required: false },
    /** Sort descending rather than ascending. */
    descending: { type: Boolean, required: false },
    /** Rows per page. */
    pageSize: { type: Number, required: false },
    /** The current page, 1-based. */
    page: { type: Number, required: false },
    /** The carrier its rows inhabit -- the constructor head from `@enumeratio/domains`, e.g. `Permutation`. Set it and each row is handed to the columns and the filter AS that carrier, so a statistic of a permutation (`Cycles`, `FixedPoints`) can be asked for at all: those heads take the carrier, not a bare list. Leave it unset and rows stay bare lists, which only the list-function statistics accept. */
    carrier: { type: String, required: false },
    /** Draw each row as a glyph too: `permutation`, `subset`, `partition`, `dyck`, … */
    glyph: { type: String, required: false },
    /** Ground-set size for the `subset` glyph; taken from the collection's first argument when 0. */
    n: { type: Number, required: false },
    /** How many source rows a filter scan covers before it pauses and offers to go on. */
    scanLimit: { type: Number, required: false },
    /** How many rows a sort materialises; past this the order covers only a prefix. */
    sortLimit: { type: Number, required: false },
    /** Hide the editors (expression, columns, filter) and show only the table and pager. */
    readonly: { type: Boolean, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-collection-table", bound(props, {}), slots.default?.());
  },
});

/** `<ColorSlider>` is `<notatio-color-slider>`: props are the element's attributes, typed. */
export const ColorSlider = defineComponent({
  name: "ColorSlider",
  props: {
    /** The binding this swatch drives: `name="c"` fills the wildcard `_c`. */
    name: { type: String, required: false },
    /** The starting colour, `#rrggbb`. */
    value: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-color-slider", bound(props, {}), slots.default?.());
  },
});

/** `<Column>` is `<notatio-column>`: props are the element's attributes, typed. */
export const Column = defineComponent({
  name: "Column",
  props: {},
  setup(props, { slots }) {
    return () => h("notatio-column", bound(props, {}), slots.default?.());
  },
});

/** `<ComplexPlot>` is `<notatio-complex-plot>`: props are the element's attributes, typed. */
export const ComplexPlot = defineComponent({
  name: "ComplexPlot",
  props: {
    /** The complex-valued expression to colour, in Epsil. */
    value: { type: String, required: false },
    /** The complex variable; defaults to `z`. */
    var: { type: String, required: false },
    /** Centre of the view in the complex plane, as `re,im`. Dragging pans it. */
    center: { type: String, required: false },
    /** Half-width of the view. Scrolling zooms it. */
    extent: { type: Number, required: false },
    /** Dim everything outside this radius; 0 masks nothing. */
    mask: { type: Number, required: false },
    /** Canvas height in pixels. */
    height: { type: Number, required: false },
    /** Show a frame-rate readout. */
    fps: { type: Boolean, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-complex-plot", bound(props, {}), slots.default?.());
  },
});

/** `<ComplexPlot3D>` is `<notatio-complex-plot-3d>`: props are the element's attributes, typed. */
export const ComplexPlot3D = defineComponent({
  name: "ComplexPlot3D",
  props: {
    /** The complex-valued expression to draw, in Epsil. */
    value: { type: String, required: false },
    /** The complex variable; defaults to `z`. */
    var: { type: String, required: false },
    /** The rectangle to sample, as `re0,re1,im0,im1`. */
    domain: { type: String, required: false },
    /** Samples per side, clamped to 2..400. */
    samples: { type: Number, required: false },
    /** `"false"` samples on the CPU even where WebGPU is available. A number sets `samples` for the GPU. */
    gpu: { type: String, required: false },
    /** Height ceiling for |f|, since a pole goes to infinity. */
    maxHeight: { type: Number, required: false },
    /** `"false"` hides the axes frame and its range labels. */
    axes: { type: String, required: false },
    /** Rotation about the vertical, in degrees. Dragging changes this. */
    azimuth: { type: Number, required: false },
    /** Viewing angle above the plane, in degrees. Dragging changes this. */
    elevation: { type: Number, required: false },
    /** View scale; ctrl/cmd + wheel or a pinch changes this. Double-click resets. */
    zoom: { type: Number, required: false },
    /** Caption drawn above the surface. */
    label: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-complex-plot-3d", bound(props, {}), slots.default?.());
  },
});

/** `<ContourPlot>` is `<notatio-contour-plot>`: props are the element's attributes, typed. */
export const ContourPlot = defineComponent({
  name: "ContourPlot",
  props: {
    /** The bivariate expression, in Epsil. */
    expr: { type: String, required: false },
    /** The variable on the x axis; defaults to the expression's first unknown. */
    xvar: { type: String, required: false },
    /** The variable on the y axis; defaults to the next unknown after `xvar`. */
    yvar: { type: String, required: false },
    /** The x sampling range, as `lo,hi`. */
    xrange: { type: String, required: false },
    /** The y sampling range, as `lo,hi`. */
    yrange: { type: String, required: false },
    /** Grid resolution per side. */
    n: { type: Number, required: false },
    /** A contour count, or an explicit JSON list of level values. */
    levels: { type: String, required: false },
    /** Anything but `"false"` shades the bands between contours. */
    filled: { type: String, required: false },
    /** `"false"` hides the axes. */
    axes: { type: String, required: false },
    /** Axis label for x. */
    xLabel: { type: String, required: false },
    /** Axis label for y. */
    yLabel: { type: String, required: false },
    /** Caption drawn above the figure. */
    label: { type: String, required: false },
    /** A pre-sampled grid as a JSON matrix, plotted instead of `expr`. */
    data: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-contour-plot", bound(props, {}), slots.default?.());
  },
});

/** `<Curve3D>` is `<notatio-curve-3d>`: props are the element's attributes, typed. */
export const Curve3D = defineComponent({
  name: "Curve3D",
  props: {
    /** An Epsil expression evaluating to a list of 3-D points. */
    value: { type: String, required: false },
    /** Rotation about the vertical, in degrees. Dragging changes this. */
    azimuth: { type: Number, required: false },
    /** Viewing angle above the plane, in degrees. Dragging changes this. */
    elevation: { type: Number, required: false },
    /** View scale; ctrl/cmd + wheel or a pinch changes this. */
    zoom: { type: Number, required: false },
    /** Leave the curve open, for a trajectory that is not a loop. */
    open: { type: Boolean, required: false },
    /** Draw the torus the curve lies on, faintly, behind it: "major,minor". */
    torus: { type: String, required: false },
    /** Caption drawn above the curve. */
    label: { type: String, required: false },
    at: { type: Number, required: false },
    clock: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-curve-3d", bound(props, {}), slots.default?.());
  },
});

/** `<DensityPlot>` is `<notatio-density-plot>`: props are the element's attributes, typed. */
export const DensityPlot = defineComponent({
  name: "DensityPlot",
  props: {
    /** The bivariate expression, in Epsil. */
    expr: { type: String, required: false },
    /** The variable on the x axis; defaults to the expression's first unknown. */
    xvar: { type: String, required: false },
    /** The variable on the y axis; defaults to the next unknown after `xvar`. */
    yvar: { type: String, required: false },
    /** The x sampling range, as `lo,hi`. */
    xrange: { type: String, required: false },
    /** The y sampling range, as `lo,hi`. */
    yrange: { type: String, required: false },
    /** Clamp the colour ramp, as `lo,hi`; empty fits the sampled values. */
    zrange: { type: String, required: false },
    /** Grid resolution per side. */
    n: { type: Number, required: false },
    /** Anything but `"false"` draws the colour ramp beside the plot. */
    legend: { type: String, required: false },
    /** `"false"` hides the axes. */
    axes: { type: String, required: false },
    /** Axis label for x. */
    xLabel: { type: String, required: false },
    /** Axis label for y. */
    yLabel: { type: String, required: false },
    /** Caption drawn above the figure. */
    label: { type: String, required: false },
    /** A pre-sampled grid as a JSON matrix, plotted instead of `expr`. */
    data: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-density-plot", bound(props, {}), slots.default?.());
  },
});

/** `<Dynamic>` is `<notatio-dynamic>`: props are the element's attributes, typed. */
export const Dynamic = defineComponent({
  name: "Dynamic",
  props: {
    /** The Epsil expression to evaluate and typeset. */
    value: { type: String, required: false },
    /** Typeset as a centred display equation rather than inline. */
    display: { type: Boolean, required: false },
    /** Significant figures to keep of an approximate result; `0` prints all of them. */
    digits: { type: Number, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-dynamic", bound(props, {}), slots.default?.());
  },
});

/** `<DynamicModule>` is `<notatio-dynamic-module>`: props are the element's attributes, typed. */
export const DynamicModule = defineComponent({
  name: "DynamicModule",
  props: {},
  setup(props, { slots }) {
    return () => h("notatio-dynamic-module", bound(props, {}), slots.default?.());
  },
});

/** `<Figure>` is `<notatio-figure>`: props are the element's attributes, typed. */
export const Figure = defineComponent({
  name: "Figure",
  props: {
    /** Which glyph to draw: `permutation`, `partition`, `composition`, `subset` or `dyck`. */
    kind: { type: String, required: false },
    /** The element as an integer list, `[3,1,2]` or `3,1,2`. */
    value: { type: String, required: false },
    /** Ground-set size, where the glyph needs one beyond the element itself. */
    n: { type: Number, required: false },
    /** Raw SVG to render instead of a generated glyph. */
    svg: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-figure", bound(props, {}), slots.default?.());
  },
});

/** `<GraphPlot>` is `<notatio-graph-plot>`: props are the element's attributes, typed. */
export const GraphPlot = defineComponent({
  name: "GraphPlot",
  props: {
    /** Which layout: `tree`, `dendrogram`, `graph` or `layered`. */
    type: { type: String, required: false },
    /** The structure, as JSON — `{nodes, edges}` for a graph, a nested node for a tree. */
    data: { type: String, required: false },
    /** Draw edges as arrows. */
    directed: { type: Boolean, required: false },
    /** Caption drawn above the figure. */
    label: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-graph-plot", bound(props, {}), slots.default?.());
  },
});

/** `<Grid>` is `<notatio-grid>`: props are the element's attributes, typed. */
export const Grid = defineComponent({
  name: "Grid",
  props: {
    /** How many children make a row. */
    columns: { type: Number, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-grid", bound(props, {}), slots.default?.());
  },
});

/** `<In>` is `<notatio-in>`: props are the element's attributes, typed. */
export const In = defineComponent({
  name: "In",
  props: {
    /** The LaTeX in the editor; changes emit `notatio-change`. */
    value: { type: String, required: false },
    /** Typeset the value without allowing edits. */
    readonly: { type: Boolean, required: false },
    /** Read-only: `value` as InputForm, kept in sync and reflected so a copy can read it off a cloned selection fragment. Set `value`, not this. */
    inputForm: { type: String, required: false },
    /** The wrapper head asked for -- `N`, `FullForm`, `TraditionalForm`, ... (see `WRAPPER_HEADS`), or `""` for none. The emitted value is wrapped in it while the editor keeps showing the expression as written. */
    head: { type: String, required: false },
    /** Pin this field to a binding: the symbol name and its `\coloneq` become fixed chrome, and only the value can be edited. */
    bind: { type: String, required: false },
    /** The domain asserted for `bind`, spelled as a compute-engine type (`integer`, `real`, `complex`, ...). Shown as a membership beside the name. Not `type`: that attribute already means "which symbol this component is" elsewhere. */
    domain: { type: String, required: false },
    /** Show a play button that sweeps a pinned numeric value through its range. */
    play: { type: Boolean, required: false },
    /** What a sweep does at the ends: `cycle`, `reflect` or `none` (default). */
    loop: { type: String, required: false },
    /** Playback speed as a multiplier on `interval`. */
    rate: { type: Number, required: false },
    /** Milliseconds per step; defaults to a whole sweep in a few seconds. */
    interval: { type: Number, required: false },
    /** The sweep's range and step; inferred from the value when not given. */
    min: { type: Number, required: false },
    max: { type: Number, required: false },
    step: { type: Number, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-in", bound(props, {}), slots.default?.());
  },
});

/** `<InputField>` is `<notatio-input-field>`: props are the element's attributes, typed. */
export const InputField = defineComponent({
  name: "InputField",
  props: {
    /** The binding this field drives: `name="x"` fills the wildcard `_x`. */
    name: { type: String, required: false },
    /** The starting text, as Epsil. */
    value: { type: String, required: false },
    /** `expression` (default) or `number`. */
    type: { type: String, required: false },
    /** Width in characters. */
    size: { type: Number, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-input-field", bound(props, {}), slots.default?.());
  },
});

/** `<IntervalSlider>` is `<notatio-interval-slider>`: props are the element's attributes, typed. */
export const IntervalSlider = defineComponent({
  name: "IntervalSlider",
  props: {
    /** The binding this slider drives: `name="r"` fills the wildcard `_r`. */
    name: { type: String, required: false },
    /** The starting interval, `lo,hi`. */
    value: { type: String, required: false },
    min: { type: Number, required: false },
    max: { type: Number, required: false },
    step: { type: Number, required: false },
    /** Show the interval beside the track. */
    readout: { type: Boolean, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-interval-slider", bound(props, {}), slots.default?.());
  },
});

/** `<Knob>` is `<notatio-knob>`: props are the element's attributes, typed. */
export const Knob = defineComponent({
  name: "Knob",
  props: {
    /** The binding this knob drives: `name="a"` fills the wildcard `_a`. */
    name: { type: String, required: false },
    /** The starting value: `3`, `-1.5`, `3+2i`, or an entry of `choices`. */
    value: { type: String, required: false },
    /** Lowest value a drag can reach. Defaults to a symmetric range around the start. */
    min: { type: Number, required: false },
    /** Highest value a drag can reach. */
    max: { type: Number, required: false },
    /** How much one step of the drag moves the value; also fixes the printed places. */
    step: { type: Number, required: false },
    /** Add the imaginary axis: dragging up/down moves the imaginary part. */
    complex: { type: Boolean, required: false },
    /** A `|`-separated list to scrub through instead of a numeric range. */
    choices: { type: String, required: false },
    /** Pixels of travel per step — lower drags faster. */
    sensitivity: { type: Number, required: false },
    /** The drag direction of a one-axis knob: `x` (default, right raises) or `y` (up raises). */
    axis: { type: String, required: false },
    /** Show a play/pause button beside the value. Space toggles playback regardless. */
    play: { type: Boolean, required: false },
    /** Start sweeping when scrolled into view; pause when scrolled out. */
    autoplay: { type: Boolean, required: false },
    /** Milliseconds per playback step. Defaults to a whole sweep in a few seconds. */
    interval: { type: Number, required: false },
    /** Playback speed as a multiplier on `interval`: `2` is twice as fast. */
    rate: { type: Number, required: false },
    /** What an iteration does at the ends: `cycle`, `reflect` or `none`. */
    loop: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-knob", bound(props, {}), slots.default?.());
  },
});

/** `<Labeled>` is `<notatio-labeled>`: props are the element's attributes, typed. */
export const Labeled = defineComponent({
  name: "Labeled",
  props: {
    /** The label's text. */
    label: { type: String, required: false },
    /** Where the label goes: `after` (default), `before`, `above` or `below`. */
    position: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-labeled", bound(props, {}), slots.default?.());
  },
});

/** `<ListPicker>` is `<notatio-list-picker>`: props are the element's attributes, typed. */
export const ListPicker = defineComponent({
  name: "ListPicker",
  props: {
    /** The binding this control drives: `name="a"` fills the wildcard `_a`. */
    name: { type: String, required: false },
    /** The entries, `|`-separated, each optionally `value -> label`. */
    values: { type: String, required: false },
    /** The entry (or, for a multiple selection, the `|`-separated entries) selected at first. */
    value: { type: String, required: false },
    /** Allow one selection only; the binding is then the value, not a list of one. */
    single: { type: Boolean, required: false },
    /** Entries visible before the list scrolls. */
    rows: { type: Number, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-list-picker", bound(props, {}), slots.default?.());
  },
});

/** `<ListPlot3D>` is `<notatio-list-plot-3d>`: props are the element's attributes, typed. */
export const ListPlot3D = defineComponent({
  name: "ListPlot3D",
  props: {
    data: { type: String, required: false },
    type: { type: String, required: false },
    azimuth: { type: Number, required: false },
    elevation: { type: Number, required: false },
    zoom: { type: Number, required: false },
    n: { type: Number, required: false },
    size: { type: Number, required: false },
    depthCue: { type: Number, required: false },
    wireframe: { type: String, required: false },
    axes: { type: String, required: false },
    zrange: { type: String, required: false },
    label: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-list-plot-3d", bound(props, {}), slots.default?.());
  },
});

/** `<Locator>` is `<notatio-locator>`: props are the element's attributes, typed. */
export const Locator = defineComponent({
  name: "Locator",
  props: {
    /** The binding this point drives: `name="p"` fills the wildcard `_p`. */
    name: { type: String, required: false },
    /** The starting point, `x,y` -- or `a+bi` with `complex`. */
    value: { type: String, required: false },
    /** Bind a complex number `x + y i` rather than a list. */
    complex: { type: Boolean, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-locator", bound(props, {}), slots.default?.());
  },
});

/** `<Manipulate>` is `<notatio-manipulate>`: props are the element's attributes, typed. */
export const Manipulate = defineComponent({
  name: "Manipulate",
  props: {
    /** Control tuples: `{a, min, max}`, `{a, min, max, step}`, `{ {a, init}, min, max}` or a discrete `{k, {1, 2, 3}}`; separate several with `;` or `,`. */
    params: { type: String, required: false },
    /** `below` puts the control panel under the content instead of above it. */
    controls: { type: String, required: false },
    /** A sentence to render as the control panel, with `{k}` holes for the parameters. */
    prose: { type: String, required: false },
    /** What playback does at the ends: `cycle` (default), `reflect` or `none`. */
    loop: { type: String, required: false },
    /** Show a frame-rate readout while a slider is playing. */
    fps: { type: Boolean, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-manipulate", bound(props, {}), slots.default?.());
  },
});

/** `<Notebook>` is `<notatio-notebook>`: props are the element's attributes, typed. */
export const Notebook = defineComponent({
  name: "Notebook",
  props: {
    /** A JSON array of cell sources, used as the notebook's initial cells. */
    seed: { type: String, required: false },
    /** The seed's syntax: `epsil` (default) or `latex`, the syntax `notatio-cell` reads. */
    inForm: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-notebook", bound(props, {}), slots.default?.());
  },
});

/** `<Out>` is `<notatio-out>`: props are the element's attributes, typed. */
export const Out = defineComponent({
  name: "Out",
  props: {
    /** The expression to render, in the encoding `format` names. */
    value: { type: String, required: false },
    /** How to read `value`: `latex`, `mathjson` or `epsil`. */
    format: { type: String, required: false },
    /** Sit inline in a sentence: the rendering alone, no label, no menu, no status. */
    inline: { type: Boolean, required: false },
    /** Set as a centred display equation (`\displaystyle`), for `$$…$$`. */
    display: { type: Boolean, required: false },
    /** Evaluate before rendering, rather than rendering the input as given. */
    evaluate: { type: Boolean, required: false },
    /** Box without evaluating, so the source and AST forms populate. */
    box: { type: Boolean, required: false },
    /** Box without canonicalising, so the expression shows as authored -- `a - b` stays a `Subtract`, `a > b` is not flipped into a `Less`. For a definition, whose spelling is the point. Ignored when `evaluate` is set. */
    raw: { type: Boolean, required: false },
    /** A MathJSON value to assert the result against; a mismatch is reported inline. */
    expect: { type: String, required: false },
    /** Mark an `expect` mismatch as a known gap — shown as a note rather than a failure. */
    planned: { type: Boolean, required: false },
    /** The representation to show, e.g. `standard`, `traditional`, `fullform`, `numpy`. */
    form: { type: String, required: false },
    /** Row label, e.g. `In` or `Out`. */
    label: { type: String, required: false },
    /** A preset to reduce the picture for (`print`, `pipe`, …); by default the page's own, as it changes. */
    env: { type: String, required: false },
    /** Above this many operands, describe a `List` result rather than typeset it (`0`, the default, never elides). A long numeric result costs real time to serialize and typeset for an output line that exists to be *drawn*, not read -- see `elideResult`. General: any cell over a control that can grow a long result can set this, not only a worksheet's. */
    elideAbove: { type: Number, required: false },
    /** Also report the substituted-but-unevaluated form of the input, in the `notatio-result` event's `plot` detail, for a consumer that draws the INPUT rather than the fully-evaluated output -- so a complex portrait or plot doesn't collapse at a pole a bound parameter crosses (`substitutedForm`). Only meaningful for a cell inside a `<notatio-dynamic-module>` (`evaluate` and a shared scope); ignored otherwise. */
    plot: { type: Boolean, required: false },
    /** Read-only: set while the value is being evaluated or typeset (the engine loads lazily, so the first one can take a moment). Styled as a pending state; a script can wait for `:not([busy])`. */
    busy: { type: Boolean, required: false },
    /** Put the form menu on the label instead of a selector at the right: click `In`/`Out` to open it. Leaves the right of the row free. */
    labelMenu: { type: Boolean, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-out", bound(props, {}), slots.default?.());
  },
});

/** `<Panel>` is `<notatio-panel>`: props are the element's attributes, typed. */
export const Panel = defineComponent({
  name: "Panel",
  props: {},
  setup(props, { slots }) {
    return () => h("notatio-panel", bound(props, {}), slots.default?.());
  },
});

/** `<Plot>` is `<notatio-plot>`: props are the element's attributes, typed. */
export const Plot = defineComponent({
  name: "Plot",
  props: {
    /** The curve, in Epsil. A list (`{f, g}`) overlays a series each; a list of pairs is data. */
    value: { type: String, required: false },
    /** The plot variable; defaults to the sole free symbol left after the slots are filled. */
    var: { type: String, required: false },
    /** The sampling range, as `lo,hi`. */
    domain: { type: String, required: false },
    /** Sample count across the domain. Adaptive refinement adds more where the curve bends. */
    samples: { type: Number, required: false },
    /** `"false"` hides the axes. */
    axes: { type: String, required: false },
    /** Scaling function for x: `linear`, `log`, `log10`, `log2` or `sqrt`. */
    xScale: { type: String, required: false },
    /** Scaling function for y. */
    yScale: { type: String, required: false },
    /** Anything but `"false"` reads `value` as a pair `(x(t), y(t))` traced over `domain`. */
    parametric: { type: String, required: false },
    /** `line` or `points`; data defaults to points and functions to lines. */
    mode: { type: String, required: false },
    /** `"false"` samples on a uniform grid instead of refining where the curve bends. */
    adaptive: { type: String, required: false },
    /** Clamp the y range, as `lo,hi`; empty fits the samples. */
    plotRange: { type: String, required: false },
    /** Marks drawn over the curve, as Epsil graphics primitives: `Point((1, 0.5))`, `Line([...])`, `Circle(c, r)`, `Text("t", p)`. Wolfram's `Epilog`. */
    epilog: { type: String, required: false },
    /** Marks drawn under the curve; Wolfram's `Prolog`. */
    prolog: { type: String, required: false },
    /** Anything but `"false"` draws grid lines. */
    grid: { type: String, required: false },
    /** Anything but `"false"` fills between the curve and the axis. */
    fill: { type: String, required: false },
    /** Anything but `"false"` draws a series legend. */
    legend: { type: String, required: false },
    /** Axis label for x. */
    xLabel: { type: String, required: false },
    /** Axis label for y. */
    yLabel: { type: String, required: false },
    /** Caption drawn above the plot. */
    label: { type: String, required: false },
    /** `x` or `y` colours the curve along that coordinate rather than by series. */
    colorBy: { type: String, required: false },
    /** Manipulate-style controls, e.g. `{a, 1, 5}`, filling the `_a` wildcards in `value`. */
    params: { type: String, required: false },
    /** What a playing slider does at the ends: `cycle` (default), `reflect` or `none`. */
    loop: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-plot", bound(props, {}), slots.default?.());
  },
});

/** `<Plot3D>` is `<notatio-plot-3d>`: props are the element's attributes, typed. */
export const Plot3D = defineComponent({
  name: "Plot3D",
  props: {
    /** The surface, in Epsil. A list (`{f, g}`) overlays several on one scale. */
    value: { type: String, required: false },
    /** The variable on the x axis; defaults to the expression's first unknown. */
    xvar: { type: String, required: false },
    /** The variable on the y axis; defaults to the next unknown after `xvar`. */
    yvar: { type: String, required: false },
    /** The x sampling range, as `lo,hi`. */
    xDomain: { type: String, required: false },
    /** The y sampling range, as `lo,hi`. */
    yDomain: { type: String, required: false },
    /** Grid resolution per side, clamped to 2..60. `gpu` raises this. */
    n: { type: Number, required: false },
    /** `"false"` hides the axes frame and its range labels. */
    axes: { type: String, required: false },
    /** Scaling function for x: `linear`, `log`, `log10`, `log2` or `sqrt`. */
    xScale: { type: String, required: false },
    /** Scaling function for y. */
    yScale: { type: String, required: false },
    /** Scaling function for the height. */
    zScale: { type: String, required: false },
    /** Rotation about the vertical, in degrees. Dragging changes this. */
    azimuth: { type: Number, required: false },
    /** Viewing angle above the plane, in degrees. Dragging changes this. */
    elevation: { type: Number, required: false },
    /** View scale; ctrl/cmd + wheel or a pinch changes this. Double-click resets. */
    zoom: { type: Number, required: false },
    /** Caption drawn above the surface. */
    label: { type: String, required: false },
    /** Anything but `"false"` draws the height-colour ramp beside the surface. */
    colorLegend: { type: String, required: false },
    /** Anything but `"false"` auto-rotates the view; the ⟳ button toggles it. */
    spin: { type: String, required: false },
    /** Evaluate the grid in a WebGPU shader. A number also sets `n`; falls back to the CPU. */
    gpu: { type: String, required: false },
    /** Manipulate-style controls, e.g. `{k, 1, 4}`, filling the `_k` wildcards in `value`. */
    params: { type: String, required: false },
    /** What a playing slider does at the ends: `cycle` (default), `reflect` or `none`. */
    loop: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-plot-3d", bound(props, {}), slots.default?.());
  },
});

/** `<PolarPlot>` is `<notatio-polar-plot>`: props are the element's attributes, typed. */
export const PolarPlot = defineComponent({
  name: "PolarPlot",
  props: {
    /** The radius r(θ), in Epsil. */
    expr: { type: String, required: false },
    /** The angle variable; defaults to the expression's first unknown, else `theta`. */
    tvar: { type: String, required: false },
    /** The angular sweep, as `lo,hi` in radians. */
    trange: { type: String, required: false },
    /** Sample count across the sweep. */
    n: { type: Number, required: false },
    /** Clamp the radial axis; 0 fits the samples. */
    max: { type: Number, required: false },
    /** `"false"` hides the polar grid. */
    axes: { type: String, required: false },
    /** Anything but `"false"` joins the last point back to the first. */
    closed: { type: String, required: false },
    /** Anything but `"false"` shades the region the curve encloses. */
    filled: { type: String, required: false },
    /** `"false"` hides the point markers on an explicit data list. */
    markers: { type: String, required: false },
    /** Caption drawn above the figure. */
    label: { type: String, required: false },
    /** An explicit point list — `[[θ,r],…]` or bare radii — plotted instead of `expr`. */
    data: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-polar-plot", bound(props, {}), slots.default?.());
  },
});

/** `<Polytope>` is `<notatio-polytope>`: props are the element's attributes, typed. */
export const Polytope = defineComponent({
  name: "Polytope",
  props: {
    which: { type: String, required: false },
    n: { type: Number, required: false },
    selected: { type: String, required: false },
    dimension: { type: Number, required: false },
    labels: { type: String, required: false },
    labelForm: { type: String, required: false },
    recentre: { type: String, required: false },
    reorient: { type: String, required: false },
    shade: { type: String, required: false },
    azimuth: { type: Number, required: false },
    elevation: { type: Number, required: false },
    zoom: { type: Number, required: false },
    label: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-polytope", bound(props, {}), slots.default?.());
  },
});

/** `<PopupMenu>` is `<notatio-popup-menu>`: props are the element's attributes, typed. */
export const PopupMenu = defineComponent({
  name: "PopupMenu",
  props: {
    /** The binding this control drives: `name="a"` fills the wildcard `_a`. */
    name: { type: String, required: false },
    /** The entries, `|`-separated, each optionally `value -> label`. */
    values: { type: String, required: false },
    /** The entry (or, for a multiple selection, the `|`-separated entries) selected at first. */
    value: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-popup-menu", bound(props, {}), slots.default?.());
  },
});

/** `<RadioButtonBar>` is `<notatio-radio-button-bar>`: props are the element's attributes, typed. */
export const RadioButtonBar = defineComponent({
  name: "RadioButtonBar",
  props: {
    /** The binding this control drives: `name="a"` fills the wildcard `_a`. */
    name: { type: String, required: false },
    /** The entries, `|`-separated, each optionally `value -> label`. */
    values: { type: String, required: false },
    /** The entry (or, for a multiple selection, the `|`-separated entries) selected at first. */
    value: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-radio-button-bar", bound(props, {}), slots.default?.());
  },
});

/** `<Row>` is `<notatio-row>`: props are the element's attributes, typed. */
export const Row = defineComponent({
  name: "Row",
  props: {},
  setup(props, { slots }) {
    return () => h("notatio-row", bound(props, {}), slots.default?.());
  },
});

/** `<SetterBar>` is `<notatio-setter-bar>`: props are the element's attributes, typed. */
export const SetterBar = defineComponent({
  name: "SetterBar",
  props: {
    /** The binding this control drives: `name="a"` fills the wildcard `_a`. */
    name: { type: String, required: false },
    /** The entries, `|`-separated, each optionally `value -> label`. */
    values: { type: String, required: false },
    /** The entry (or, for a multiple selection, the `|`-separated entries) selected at first. */
    value: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-setter-bar", bound(props, {}), slots.default?.());
  },
});

/** `<Slider>` is `<notatio-slider>`: props are the element's attributes, typed. */
export const Slider = defineComponent({
  name: "Slider",
  props: {
    /** The binding this slider drives: `name="a"` fills the wildcard `_a`. */
    name: { type: String, required: false },
    /** The starting value. */
    value: { type: String, required: false },
    /** Lowest value. Defaults to a symmetric range around the start. */
    min: { type: Number, required: false },
    /** Highest value. */
    max: { type: Number, required: false },
    /** How much one step moves the value; also fixes the printed places. */
    step: { type: Number, required: false },
    /** `x` (default) lies flat; `y` stands the slider up. */
    axis: { type: String, required: false },
    /** Show the value beside the track. */
    readout: { type: Boolean, required: false },
    /** Show a play/pause button. Space on the focused thumb toggles playback regardless. */
    play: { type: Boolean, required: false },
    /** Sweep while scrolled into view; pause when scrolled out. */
    autoplay: { type: Boolean, required: false },
    /** Milliseconds per playback step. Defaults to a whole sweep in a few seconds. */
    interval: { type: Number, required: false },
    /** Playback speed as a multiplier on `interval`. */
    rate: { type: Number, required: false },
    /** What an iteration does at the ends: `cycle`, `reflect` or `none` (default). */
    loop: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-slider", bound(props, {}), slots.default?.());
  },
});

/** `<Slider2D>` is `<notatio-slider-2d>`: props are the element's attributes, typed. */
export const Slider2D = defineComponent({
  name: "Slider2D",
  props: {
    /** The binding this pad drives: `name="p"` fills the wildcard `_p`. */
    name: { type: String, required: false },
    /** The starting point, `x,y` -- or `a+bi` with `complex`. */
    value: { type: String, required: false },
    /** The lower-left corner, `x,y`. */
    min: { type: String, required: false },
    /** The upper-right corner, `x,y`. */
    max: { type: String, required: false },
    /** One step for both axes, or `dx,dy`. */
    step: { type: String, required: false },
    /** Bind a complex number `x + y i` rather than a list. */
    complex: { type: Boolean, required: false },
    /** Show the point's coordinates beside the pad. */
    readout: { type: Boolean, required: false },
    /** The pad's side, in CSS pixels. */
    size: { type: Number, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-slider-2d", bound(props, {}), slots.default?.());
  },
});

/** `<Terminal>` is `<notatio-terminal>`: props are the element's attributes, typed. */
export const Terminal = defineComponent({
  name: "Terminal",
  props: {
    /** `repl` for the interactive session, `cli` for the command-line transcript, `show` for one expression. */
    mode: { type: String, required: false },
    /** In `show` mode, the expression, in Epsil. */
    value: { type: String, required: false },
    /** In `show` mode, the environment it is shown for: `tty` or `pipe`. */
    env: { type: String, required: false },
    /** A JSON array of input lines to run on load. */
    seed: { type: String, required: false },
    /** Show the example picker beside the terminal. */
    examples: { type: Boolean, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-terminal", bound(props, {}), slots.default?.());
  },
});

/** `<TestResultObject>` is `<notatio-test-result-object>`: props are the element's attributes, typed. */
export const TestResultObject = defineComponent({
  name: "TestResultObject",
  props: {
    /** The held input, as Epsil source. */
    input: { type: String, required: false },
    /** The evaluated result, as Epsil source; absent on Error/Aborted. */
    actual: { type: String, required: false },
    /** What it was compared against, as Epsil source; absent when there was none. */
    expected: { type: String, required: false },
    /** `Success`, `Failure`, `Error` or `Aborted`. */
    outcome: { type: String, required: false },
    /** `AbsoluteTimeUsed`, in seconds. */
    time: { type: Number, required: false },
    /** `TestID`, when the test named one. */
    testId: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-test-result-object", bound(props, {}), slots.default?.());
  },
});

/** `<Toggler>` is `<notatio-toggler>`: props are the element's attributes, typed. */
export const Toggler = defineComponent({
  name: "Toggler",
  props: {
    /** The binding this toggler drives: `name="a"` fills the wildcard `_a`. */
    name: { type: String, required: false },
    /** The entries to cycle through, `|`-separated, each optionally `value -> label`. None: a True/False switch. */
    values: { type: String, required: false },
    /** The entry to start on: one of `values` (by value or label), or its index. */
    value: { type: String, required: false },
    /** Show a play/pause button beside the word. Space toggles playback regardless. */
    play: { type: Boolean, required: false },
    /** Cycle while scrolled into view; pause when scrolled out. */
    autoplay: { type: Boolean, required: false },
    /** Milliseconds per entry while playing. */
    interval: { type: Number, required: false },
    /** Playback speed as a multiplier on `interval`. */
    rate: { type: Number, required: false },
    /** What reaching an end does: `cycle` (default), `reflect` or `none`. */
    loop: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-toggler", bound(props, {}), slots.default?.());
  },
});

/** `<TogglerBar>` is `<notatio-toggler-bar>`: props are the element's attributes, typed. */
export const TogglerBar = defineComponent({
  name: "TogglerBar",
  props: {
    /** The binding this control drives: `name="a"` fills the wildcard `_a`. */
    name: { type: String, required: false },
    /** The entries, `|`-separated, each optionally `value -> label`. */
    values: { type: String, required: false },
    /** The entry (or, for a multiple selection, the `|`-separated entries) selected at first. */
    value: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-toggler-bar", bound(props, {}), slots.default?.());
  },
});

/** `<TorusSquare>` is `<notatio-torus-square>`: props are the element's attributes, typed. */
export const TorusSquare = defineComponent({
  name: "TorusSquare",
  props: {
    p: { type: Number, required: false },
    q: { type: Number, required: false },
    /** A fixed phase in `[0, 1)`. Given, the figure ignores the clock. */
    at: { type: Number, required: false },
    /** Follow the page's clock. `clock`, not `animate`: every element inherits  `Element.animate()` from the DOM, and a reactive property of that name shadows it. */
    clock: { type: String, required: false },
    dials: { type: String, required: false },
    label: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-torus-square", bound(props, {}), slots.default?.());
  },
});

/** `<VectorPlot>` is `<notatio-vector-plot>`: props are the element's attributes, typed. */
export const VectorPlot = defineComponent({
  name: "VectorPlot",
  props: {
    /** The x component of the field, in Epsil. */
    u: { type: String, required: false },
    /** The y component of the field, in Epsil. */
    v: { type: String, required: false },
    /** Both components at once, comma-separated — `"-y, x"`. */
    field: { type: String, required: false },
    /** The variable on the x axis; defaults to the expression's first unknown. */
    xvar: { type: String, required: false },
    /** The variable on the y axis; defaults to the next unknown after `xvar`. */
    yvar: { type: String, required: false },
    /** The x sampling range, as `lo,hi`. */
    xrange: { type: String, required: false },
    /** The y sampling range, as `lo,hi`. */
    yrange: { type: String, required: false },
    /** Arrows (or streamline seeds) per side. */
    n: { type: Number, required: false },
    /** `vector` for arrows, `stream` for RK4 streamlines. */
    type: { type: String, required: false },
    /** Streamline integration steps taken in each direction from a seed. */
    steps: { type: Number, required: false },
    /** `"false"` hides the axes. */
    axes: { type: String, required: false },
    /** Axis label for x. */
    xLabel: { type: String, required: false },
    /** Axis label for y. */
    yLabel: { type: String, required: false },
    /** Caption drawn above the figure. */
    label: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-vector-plot", bound(props, {}), slots.default?.());
  },
});

/** `<VerticalSlider>` is `<notatio-vertical-slider>`: props are the element's attributes, typed. */
export const VerticalSlider = defineComponent({
  name: "VerticalSlider",
  props: {
    /** The binding this slider drives: `name="a"` fills the wildcard `_a`. */
    name: { type: String, required: false },
    /** The starting value. */
    value: { type: String, required: false },
    /** Lowest value. Defaults to a symmetric range around the start. */
    min: { type: Number, required: false },
    /** Highest value. */
    max: { type: Number, required: false },
    /** How much one step moves the value; also fixes the printed places. */
    step: { type: Number, required: false },
    /** `x` (default) lies flat; `y` stands the slider up. */
    axis: { type: String, required: false },
    /** Show the value beside the track. */
    readout: { type: Boolean, required: false },
    /** Show a play/pause button. Space on the focused thumb toggles playback regardless. */
    play: { type: Boolean, required: false },
    /** Sweep while scrolled into view; pause when scrolled out. */
    autoplay: { type: Boolean, required: false },
    /** Milliseconds per playback step. Defaults to a whole sweep in a few seconds. */
    interval: { type: Number, required: false },
    /** Playback speed as a multiplier on `interval`. */
    rate: { type: Number, required: false },
    /** What an iteration does at the ends: `cycle`, `reflect` or `none` (default). */
    loop: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-vertical-slider", bound(props, {}), slots.default?.());
  },
});

/** `<When>` is `<notatio-when>`: props are the element's attributes, typed. */
export const When = defineComponent({
  name: "When",
  props: {
    /** The Epsil predicate, over the dynamic module's knob wildcards. */
    test: { type: String, required: false },
    /** Show the children when the test is false instead of true. */
    invert: { type: Boolean, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-when", bound(props, {}), slots.default?.());
  },
});

/** `<Worksheet>` is `<notatio-worksheet>`: props are the element's attributes, typed. */
export const Worksheet = defineComponent({
  name: "Worksheet",
  props: {
    /** A JSON array of the worksheet's initial cells. An entry is a source string, or an object `{value, locked, bind, domain, integer}` -- `bind`/`domain` pin the declaration so only the value can be edited. Sources are in the syntax `in-form` names; a binding is `s := 2`. */
    seed: { type: String, required: false },
    /** The seed's syntax: `epsil` (default) or `latex`. Cells are Epsil internally. */
    inForm: { type: String, required: false },
    /** Where the shared view sits: `auto`, `side` or `below`. */
    screen: { type: String, required: false },
    /** Show the cells without allowing edits. Implies a fixed structure. */
    readonly: { type: Boolean, required: false },
    /** `fixed` keeps the reader from adding or removing cells; `open` (default) allows it. */
    structure: { type: String, required: false },
    /** What a sweeping binding does at the ends: `cycle` (default), `reflect` or `none`. */
    loop: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-worksheet", bound(props, {}), slots.default?.());
  },
});

/** `<StreamPlot>` is `<notatio-vector-plot>`: props are the element's attributes, typed. */
export const StreamPlot = defineComponent({
  name: "StreamPlot",
  props: {
    /** The x component of the field, in Epsil. */
    u: { type: String, required: false },
    /** The y component of the field, in Epsil. */
    v: { type: String, required: false },
    /** Both components at once, comma-separated — `"-y, x"`. */
    field: { type: String, required: false },
    /** The variable on the x axis; defaults to the expression's first unknown. */
    xvar: { type: String, required: false },
    /** The variable on the y axis; defaults to the next unknown after `xvar`. */
    yvar: { type: String, required: false },
    /** The x sampling range, as `lo,hi`. */
    xrange: { type: String, required: false },
    /** The y sampling range, as `lo,hi`. */
    yrange: { type: String, required: false },
    /** Arrows (or streamline seeds) per side. */
    n: { type: Number, required: false },
    /** Streamline integration steps taken in each direction from a seed. */
    steps: { type: Number, required: false },
    /** `"false"` hides the axes. */
    axes: { type: String, required: false },
    /** Axis label for x. */
    xLabel: { type: String, required: false },
    /** Axis label for y. */
    yLabel: { type: String, required: false },
    /** Caption drawn above the figure. */
    label: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-vector-plot", bound(props, { type: "stream" }), slots.default?.());
  },
});

/** `<ListPlot>` is `<notatio-chart>`: props are the element's attributes, typed. */
export const ListPlot = defineComponent({
  name: "ListPlot",
  props: {
    /** The values, as JSON — a number list, or `[x,y]` pairs where the chart takes points. */
    data: { type: String, required: false },
    /** A JSON list of category labels, where the chart shows them. */
    labels: { type: String, required: false },
    /** Histogram bin count; empty chooses one from the data. */
    bins: { type: Number, required: false },
    /** Caption drawn above the chart. */
    label: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-chart", bound(props, { type: "list" }), slots.default?.());
  },
});

/** `<ListLinePlot>` is `<notatio-chart>`: props are the element's attributes, typed. */
export const ListLinePlot = defineComponent({
  name: "ListLinePlot",
  props: {
    /** The values, as JSON — a number list, or `[x,y]` pairs where the chart takes points. */
    data: { type: String, required: false },
    /** A JSON list of category labels, where the chart shows them. */
    labels: { type: String, required: false },
    /** Histogram bin count; empty chooses one from the data. */
    bins: { type: Number, required: false },
    /** Caption drawn above the chart. */
    label: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-chart", bound(props, { type: "listline" }), slots.default?.());
  },
});

/** `<BarChart>` is `<notatio-chart>`: props are the element's attributes, typed. */
export const BarChart = defineComponent({
  name: "BarChart",
  props: {
    /** The values, as JSON — a number list, or `[x,y]` pairs where the chart takes points. */
    data: { type: String, required: false },
    /** A JSON list of category labels, where the chart shows them. */
    labels: { type: String, required: false },
    /** Histogram bin count; empty chooses one from the data. */
    bins: { type: Number, required: false },
    /** Caption drawn above the chart. */
    label: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-chart", bound(props, { type: "bar" }), slots.default?.());
  },
});

/** `<Histogram>` is `<notatio-chart>`: props are the element's attributes, typed. */
export const Histogram = defineComponent({
  name: "Histogram",
  props: {
    /** The values, as JSON — a number list, or `[x,y]` pairs where the chart takes points. */
    data: { type: String, required: false },
    /** A JSON list of category labels, where the chart shows them. */
    labels: { type: String, required: false },
    /** Histogram bin count; empty chooses one from the data. */
    bins: { type: Number, required: false },
    /** Caption drawn above the chart. */
    label: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-chart", bound(props, { type: "histogram" }), slots.default?.());
  },
});

/** `<PieChart>` is `<notatio-chart>`: props are the element's attributes, typed. */
export const PieChart = defineComponent({
  name: "PieChart",
  props: {
    /** The values, as JSON — a number list, or `[x,y]` pairs where the chart takes points. */
    data: { type: String, required: false },
    /** A JSON list of category labels, where the chart shows them. */
    labels: { type: String, required: false },
    /** Histogram bin count; empty chooses one from the data. */
    bins: { type: Number, required: false },
    /** Caption drawn above the chart. */
    label: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-chart", bound(props, { type: "pie" }), slots.default?.());
  },
});

/** `<BoxWhiskerChart>` is `<notatio-chart>`: props are the element's attributes, typed. */
export const BoxWhiskerChart = defineComponent({
  name: "BoxWhiskerChart",
  props: {
    /** The values, as JSON — a number list, or `[x,y]` pairs where the chart takes points. */
    data: { type: String, required: false },
    /** A JSON list of category labels, where the chart shows them. */
    labels: { type: String, required: false },
    /** Histogram bin count; empty chooses one from the data. */
    bins: { type: Number, required: false },
    /** Caption drawn above the chart. */
    label: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-chart", bound(props, { type: "box" }), slots.default?.());
  },
});

/** `<ArrayPlot>` is `<notatio-chart>`: props are the element's attributes, typed. */
export const ArrayPlot = defineComponent({
  name: "ArrayPlot",
  props: {
    /** The values, as JSON — a number list, or `[x,y]` pairs where the chart takes points. */
    data: { type: String, required: false },
    /** A JSON list of category labels, where the chart shows them. */
    labels: { type: String, required: false },
    /** Histogram bin count; empty chooses one from the data. */
    bins: { type: Number, required: false },
    /** Caption drawn above the chart. */
    label: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-chart", bound(props, { type: "array" }), slots.default?.());
  },
});

/** `<DiscretePlot>` is `<notatio-chart>`: props are the element's attributes, typed. */
export const DiscretePlot = defineComponent({
  name: "DiscretePlot",
  props: {
    /** The values, as JSON — a number list, or `[x,y]` pairs where the chart takes points. */
    data: { type: String, required: false },
    /** A JSON list of category labels, where the chart shows them. */
    labels: { type: String, required: false },
    /** Histogram bin count; empty chooses one from the data. */
    bins: { type: Number, required: false },
    /** Caption drawn above the chart. */
    label: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-chart", bound(props, { type: "discrete" }), slots.default?.());
  },
});

/** `<TreeGraph>` is `<notatio-graph-plot>`: props are the element's attributes, typed. */
export const TreeGraph = defineComponent({
  name: "TreeGraph",
  props: {
    /** The structure, as JSON — `{nodes, edges}` for a graph, a nested node for a tree. */
    data: { type: String, required: false },
    /** Draw edges as arrows. */
    directed: { type: Boolean, required: false },
    /** Caption drawn above the figure. */
    label: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-graph-plot", bound(props, { type: "tree" }), slots.default?.());
  },
});

/** `<LayeredGraphPlot>` is `<notatio-graph-plot>`: props are the element's attributes, typed. */
export const LayeredGraphPlot = defineComponent({
  name: "LayeredGraphPlot",
  props: {
    /** The structure, as JSON — `{nodes, edges}` for a graph, a nested node for a tree. */
    data: { type: String, required: false },
    /** Draw edges as arrows. */
    directed: { type: Boolean, required: false },
    /** Caption drawn above the figure. */
    label: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-graph-plot", bound(props, { type: "layered" }), slots.default?.());
  },
});

/** `<Dendrogram>` is `<notatio-graph-plot>`: props are the element's attributes, typed. */
export const Dendrogram = defineComponent({
  name: "Dendrogram",
  props: {
    /** The structure, as JSON — `{nodes, edges}` for a graph, a nested node for a tree. */
    data: { type: String, required: false },
    /** Draw edges as arrows. */
    directed: { type: Boolean, required: false },
    /** Caption drawn above the figure. */
    label: { type: String, required: false },
  },
  setup(props, { slots }) {
    return () => h("notatio-graph-plot", bound(props, { type: "dendrogram" }), slots.default?.());
  },
});

/** Every generated component by name, for a loop that registers them. */
export const components = {
  Animator,
  BarChart3D,
  Cell,
  Chart,
  Checkbox,
  Clock,
  Code,
  CollectionTable,
  ColorSlider,
  Column,
  ComplexPlot,
  ComplexPlot3D,
  ContourPlot,
  Curve3D,
  DensityPlot,
  Dynamic,
  DynamicModule,
  Figure,
  GraphPlot,
  Grid,
  In,
  InputField,
  IntervalSlider,
  Knob,
  Labeled,
  ListPicker,
  ListPlot3D,
  Locator,
  Manipulate,
  Notebook,
  Out,
  Panel,
  Plot,
  Plot3D,
  PolarPlot,
  Polytope,
  PopupMenu,
  RadioButtonBar,
  Row,
  SetterBar,
  Slider,
  Slider2D,
  Terminal,
  TestResultObject,
  Toggler,
  TogglerBar,
  TorusSquare,
  VectorPlot,
  VerticalSlider,
  When,
  Worksheet,
  StreamPlot,
  ListPlot,
  ListLinePlot,
  BarChart,
  Histogram,
  PieChart,
  BoxWhiskerChart,
  ArrayPlot,
  DiscretePlot,
  TreeGraph,
  LayeredGraphPlot,
  Dendrogram,
};
